### ISSUE TITLE
Slow code when using whatever star in index to return full-length object (who'da thunk?)

### ISSUE THREAD

**Issue by jubilatious1** [rakudo/rakudo#3865] opened 2020-08-22 05:00 UTC
## TMTOWDI in action

I've noticed a new behavior with rakudo-2020.06 and I really like it. In true TMTOWTDI fashion, you can leave off an indexing postfix to return a full length object, you can add a 'zen-slice' (empty) postfix to to return a full length object, and (now as of rakudo-2020.06) you can just use a plain whatever star (thunk). All three lines below give the same return:

```
user@mbook:~$ raku -e 'put ("a" .. "zz")'
user@mbook:~$ raku -e 'put ("a" .. "zz")[ ]'
user@mbook:~$ raku -e 'put ("a" .. "zz")[*]'
```

I actually like this a whole lot. It will help people from other languages get up to speed quickly with whatever stars. And it makes sense too: calling a postfix index with a value of  [\*-1] returns the last element, so it's simple for people to remember that using a postfix [*] means "give me everything".

## The Problem (Actual Behavior)
```
user@mbook:~$ time(raku -e 'put ("a" .. "zz")[*]')
a b c d e f g h i j k l m n o p q r s t u v w x y z aa ab ac ad ae af ag ah ai aj ak al am an ao ap aq ar as at au av aw ax ay az ba bb bc bd be bf bg bh bi bj bk bl bm bn bo bp bq br bs bt bu bv bw bx by bz ca cb cc cd ce cf cg ch ci cj ck cl cm cn co cp cq cr cs ct cu cv cw cx cy cz da db dc dd de df dg dh di dj dk dl dm dn do dp dq dr ds dt du dv dw dx dy dz ea eb ec ed ee ef eg eh ei ej ek el em en eo ep eq er es et eu ev ew ex ey ez fa fb fc fd fe ff fg fh fi fj fk fl fm fn fo fp fq fr fs ft fu fv fw fx fy fz ga gb gc gd ge gf gg gh gi gj gk gl gm gn go gp gq gr gs gt gu gv gw gx gy gz ha hb hc hd he hf hg hh hi hj hk hl hm hn ho hp hq hr hs ht hu hv hw hx hy hz ia ib ic id ie if ig ih ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nb nc nd ne nf ng nh ni nj nk nl nm nn no np nq nr ns nt nu nv nw nx ny nz oa ob oc od oe of og oh oi oj ok ol om on oo op oq or os ot ou ov ow ox oy oz pa pb pc pd pe pf pg ph pi pj pk pl pm pn po pp pq pr ps pt pu pv pw px py pz qa qb qc qd qe qf qg qh qi qj qk ql qm qn qo qp qq qr qs qt qu qv qw qx qy qz ra rb rc rd re rf rg rh ri rj rk rl rm rn ro rp rq rr rs rt ru rv rw rx ry rz sa sb sc sd se sf sg sh si sj sk sl sm sn so sp sq sr ss st su sv sw sx sy sz ta tb tc td te tf tg th ti tj tk tl tm tn to tp tq tr ts tt tu tv tw tx ty tz ua ub uc ud ue uf ug uh ui uj uk ul um un uo up uq ur us ut uu uv uw ux uy uz va vb vc vd ve vf vg vh vi vj vk vl vm vn vo vp vq vr vs vt vu vv vw vx vy vz wa wb wc wd we wf wg wh wi wj wk wl wm wn wo wp wq wr ws wt wu wv ww wx wy wz xa xb xc xd xe xf xg xh xi xj xk xl xm xn xo xp xq xr xs xt xu xv xw xx xy xz ya yb yc yd ye yf yg yh yi yj yk yl ym yn yo yp yq yr ys yt yu yv yw yx yy yz za zb zc zd ze zf zg zh zi zj zk zl zm zn zo zp zq zr zs zt zu zv zw zx zy zz

real	0m4.897s
user	0m4.931s
sys	0m0.079s
```

##  Expected Behavior

Make it faster!

## Environment
* Operating system: MacOS_X (fairly old)
```
user@mbook:~$ perl6 -v
This is Rakudo version 2020.06 built on MoarVM version 2020.06
implementing Raku 6.d.
```

**Comment by MasterDuke17** [comment] 2020-08-25 10:00
09:55 | MasterDuke | m: my @a = ("a" .. "za")[]; say @a[(^@a).pick]; say @a.elems; say now - INIT now
-- | -- | --
09:55 | camelia | rakudo-moar c1784bda1: OUTPUT: «qj␤677␤0.0325126␤»
09:55 | MasterDuke | m: my @a = ("a" ... "za")[]; say @a[(^@a).pick]; say @a.elems; say now - INIT now
09:55 | camelia | rakudo-moar c1784bda1: OUTPUT: «tz␤677␤0.036371␤»
09:56 | MasterDuke | m: my @a = ("a" .. "za")[*]; say @a[(^@a).pick]; say @a.elems; say now - INIT now
09:56 | camelia | rakudo-moar c1784bda1: OUTPUT: «og␤677␤5.46495354␤»
09:56 | MasterDuke | m: my @a = ("a" ... "za")[*]; say @a[(^@a).pick]; say @a.elems; say now - INIT now
09:56 | camelia | rakudo-moar c1784bda1: OUTPUT: «jn␤677␤0.048007␤»

**Comment by lizmat** [comment] 2020-12-27 17:13
Appears fixed by https://github.com/rakudo/rakudo/commit/9ad80af215

**Comment by melezhik** [comment] 2021-06-25 20:28
test_needed:

if this test too naive ( just an assumption that in average it should not take longer then 0.1 sec )

```
[root@10f560a7a630 r3tool]# tomty --env=2020_06 3865
load configuration from /root/projects/r3tool/.tomty/env/config.2020_06.pl6
[repository] :: index updated from file:///root/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/3865]
==================================================
[3865] :: cat $root_dir/task.bash
[3865] ::
[3865] :: $RAKUBIN -v
[3865] ::
[3865] :: $RAKUBIN -e 'put ("a" .. "zz")[*]; say "time: ", now - INIT now';
[3865] :: This is Rakudo version 2020.06 built on MoarVM version 2020.06
[3865] :: implementing Raku 6.d.
[3865] :: a b c d e f g h i j k l m n o p q r s t u v w x y z aa ab ac ad ae af ag ah ai aj ak al am an ao ap aq ar as at au av aw ax ay az ba bb bc bd be bf bg bh bi bj bk bl bm bn bo bp bq br bs bt bu bv bw bx by bz ca cb cc cd ce cf cg ch ci cj ck cl cm cn co cp cq cr cs ct cu cv cw cx cy cz da db dc dd de df dg dh di dj dk dl dm dn do dp dq dr ds dt du dv dw dx dy dz ea eb ec ed ee ef eg eh ei ej ek el em en eo ep eq er es et eu ev ew ex ey ez fa fb fc fd fe ff fg fh fi fj fk fl fm fn fo fp fq fr fs ft fu fv fw fx fy fz ga gb gc gd ge gf gg gh gi gj gk gl gm gn go gp gq gr gs gt gu gv gw gx gy gz ha hb hc hd he hf hg hh hi hj hk hl hm hn ho hp hq hr hs ht hu hv hw hx hy hz ia ib ic id ie if ig ih ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nb nc nd ne nf ng nh ni nj nk nl nm nn no np nq nr ns nt nu nv nw nx ny nz oa ob oc od oe of og oh oi oj ok ol om on oo op oq or os ot ou ov ow ox oy oz pa pb pc pd pe pf pg ph pi pj pk pl pm pn po pp pq pr ps pt pu pv pw px py pz qa qb qc qd qe qf qg qh qi qj qk ql qm qn qo qp qq qr qs qt qu qv qw qx qy qz ra rb rc rd re rf rg rh ri rj rk rl rm rn ro rp rq rr rs rt ru rv rw rx ry rz sa sb sc sd se sf sg sh si sj sk sl sm sn so sp sq sr ss st su sv sw sx sy sz ta tb tc td te tf tg th ti tj tk tl tm tn to tp tq tr ts tt tu tv tw tx ty tz ua ub uc ud ue uf ug uh ui uj uk ul um un uo up uq ur us ut uu uv uw ux uy uz va vb vc vd ve vf vg vh vi vj vk vl vm vn vo vp vq vr vs vt vu vv vw vx vy vz wa wb wc wd we wf wg wh wi wj wk wl wm wn wo wp wq wr ws wt wu wv ww wx wy wz xa xb xc xd xe xf xg xh xi xj xk xl xm xn xo xp xq xr xs xt xu xv xw xx xy xz ya yb yc yd ye yf yg yh yi yj yk yl ym yn yo yp yq yr ys yt yu yv yw yx yy yz za zb zc zd ze zf zg zh zi zj zk zl zm zn zo zp zq zr zs zt zu zv zw zx zy zz
[3865] :: time: 4.6581244
[task check] stdout match <^^ "time:" \s+ (\S+)> True
[task check] execution time found: 4.6581244
[task check] <execution time is less then 0.1> False
=================
TASK CHECK FAIL
```

**Comment by Altai-man** [comment] 2021-06-29 10:26
I think the policy is not to add performance-related tests, as they are unstable depending on the load.
As the issue is fixed, closing, please re-open if needed.

**Closed by Altai-man** 2021-06-29 10:26 UTC
Labels: performance, tests needed

**Comment by melezhik** [comment] 2021-06-29 14:27
@Altai-man  fair point, one can always skip performance tests by `--skip=performance`

**Comment by melezhik** [comment] 2022-06-08 03:45
FYI. those my test if flickering , the time is around `0.1 sec` for the given code:

02:29:09 06/08/2022 [bash: main.build.pre] :: ==================================================
02:29:09 06/08/2022 [bash: main.build.pre] :: [https://github.com/rakudo/rakudo/issues/3865]
02:29:09 06/08/2022 [bash: main.build.pre] :: ==================================================
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: cat $root_dir/task.bash
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: 
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: $RAKUBIN -v
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: 
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: $RAKUBIN -e 'put ("a" .. "zz")[*]; say "time: ", now - INIT now';
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: Welcome to Rakudo™ v2022.06-3-gd4e8b671a.
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: Implementing the Raku® Programming Language v6.d.
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:54 06/08/2022 [3865] :: Built on MoarVM version 2022.06.
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:55 06/08/2022 [3865] :: a b c d e f g h i j k l m n o p q r s t u v w x y z aa ab ac ad ae af ag ah ai aj ak al am an ao ap aq ar as at au av aw ax ay az ba bb bc bd be bf bg bh bi bj bk bl bm bn bo bp bq br bs bt bu bv bw bx by bz ca cb cc cd ce cf cg ch ci cj ck cl cm cn co cp cq cr cs ct cu cv cw cx cy cz da db dc dd de df dg dh di dj dk dl dm dn do dp dq dr ds dt du dv dw dx dy dz ea eb ec ed ee ef eg eh ei ej ek el em en eo ep eq er es et eu ev ew ex ey ez fa fb fc fd fe ff fg fh fi fj fk fl fm fn fo fp fq fr fs ft fu fv fw fx fy fz ga gb gc gd ge gf gg gh gi gj gk gl gm gn go gp gq gr gs gt gu gv gw gx gy gz ha hb hc hd he hf hg hh hi hj hk hl hm hn ho hp hq hr hs ht hu hv hw hx hy hz ia ib ic id ie if ig ih ii ij ik il im in io ip iq ir is it iu iv iw ix iy iz ja jb jc jd je jf jg jh ji jj jk jl jm jn jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx ly lz ma mb mc md me mf mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na nb nc nd ne nf ng nh ni nj nk nl nm nn no np nq nr ns nt nu nv nw nx ny nz oa ob oc od oe of og oh oi oj ok ol om on oo op oq or os ot ou ov ow ox oy oz pa pb pc pd pe pf pg ph pi pj pk pl pm pn po pp pq pr ps pt pu pv pw px py pz qa qb qc qd qe qf qg qh qi qj qk ql qm qn qo qp qq qr qs qt qu qv qw qx qy qz ra rb rc rd re rf rg rh ri rj rk rl rm rn ro rp rq rr rs rt ru rv rw rx ry rz sa sb sc sd se sf sg sh si sj sk sl sm sn so sp sq sr ss st su sv sw sx sy sz ta tb tc td te tf tg th ti tj tk tl tm tn to tp tq tr ts tt tu tv tw tx ty tz ua ub uc ud ue uf ug uh ui uj uk ul um un uo up uq ur us ut uu uv uw ux uy uz va vb vc vd ve vf vg vh vi vj vk vl vm vn vo vp vq vr vs vt vu vv vw vx vy vz wa wb wc wd we wf wg wh wi wj wk wl wm wn wo wp wq wr ws wt wu wv ww wx wy wz xa xb xc xd xe xf xg xh xi xj xk xl xm xn xo xp xq xr xs xt xu xv xw xx xy xz ya yb yc yd ye yf yg yh yi yj yk yl ym yn yo yp yq yr ys yt yu yv yw yx yy yz za zb zc zd ze zf zg zh zi zj zk zl zm zn zo zp zq zr zs zt zu zv zw zx zy zz
02:29:09 06/08/2022 [bash: main.build.pre] :: 02:27:55 06/08/2022 [3865] :: time: 0.1138552
02:29:09 06/08/2022 [bash: main.build.pre] :: [task check] stdout match <^^ "time:" \s+ (\S+)> True
02:29:09 06/08/2022 [bash: main.build.pre] :: [task check] execution time found: 0.1138552
02:29:09 06/08/2022 [bash: main.build.pre] :: [task check] <execution time is less then 0.1> False
02:29:09 06/08/2022 [bash: main.build.pre] :: =================
02:29:09 06/08/2022 [bash: main.build.pre] :: TASK CHECK FAIL
02:29:09 06/08/2022 [bash: main.build.pre] :: 
02:29:09 06/08/2022 [bash: main.build.pre] :: 
02:29:09 06/08/2022 [bash: main.build.pre] :: task exit status: 1

http://sparrowhub.io:2222/report/580
