### ISSUE TITLE
Twigil method return nothing for variable

### ISSUE THREAD

**Issue by araraloren** [rakudo/rakudo#2275] opened 2018-09-14 12:55 UTC
## The Problem

Twigil method of Parameter return nothing.

## Expected Behavior

Return the twigil of parameter.

## Actual Behavior

Return nothing.

## Steps to Reproduce

```
class Foo {
    has $!a;
    method f(:$!a) { }
}
print Foo.^find_method('f').signature.params.[0].twigil;
```
Above code print nothing.
## Environment
* Operating system: fedora 26
* Compiler version (`perl6 -v`): 2018.08

**Comment by lizmat** [comment] 2018-09-14 13:06
You're looking at the wrong parameter in the signature.  The first parameter is a representation of `self`, which indeed has no twigil.

    class Foo {
        has $!a;
        method f(:$!a) { }
    }
    print Foo.^find_method('f').signature.params[1]].twigil;  # !

**Comment by araraloren** [comment] 2018-09-14 13:12
@lizmat  
Oh, Thanks you point that 👍 
And I wonder is the twigil will avaiable when the parameter is dynamic variables ?
such as `sub f($*a) {}`

**Comment by araraloren** [comment] 2018-09-14 14:11
#2276 
So the problem change to 
```
say :(:$*a).params.[0].twigil;
```
is print nothing.

**Comment by lizmat** [comment] 2018-09-14 14:13
Turns out it is valid and used syntax.  TIL.

The problem is in the introspection only, as a `Parameter` doesn't get a `Scalar` container by default, and it's that container that contains all of the introspectable information.  However, it *is* possible to change the `twigil` method of the `Parameter` object.

**Comment by jnthn** [comment] 2018-09-14 14:14
Yes, I expect `*` from the twigil method for such a parameter.

**Comment by lizmat** [comment] 2018-09-14 14:34
Fixed with https://github.com/rakudo/rakudo/commit/39f2d68a11 , working on tests now

**Comment by lizmat** [comment] 2018-09-14 14:49
Added tests with https://github.com/perl6/roast/commit/c60405b224

**Closed by lizmat** 2018-09-14 14:49 UTC
