### ISSUE TITLE
"no compile time value" errors lack location of the problematic code

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#2052] opened 2018-07-11 22:42 UTC
At the very least, the error is missing a location.

```
m: sub class { }; my \point = %(a => 1); class point{"a"}.say
rakudo-moar 5682ee1f1: OUTPUT: «===SORRY!===␤No compile-time value for point␤»
```

**Comment by shishini** [comment] 2018-07-12 19:36
Hi

I was told this bug report is related to a point i raised in chat, that when defining a class ancestor, you need a space between the parent class and the opening curly bracket 

My testing code looked like this 

```
class Parent1{
    method Hello {
        say "Hello"
    }
}

class Parent2{
    method Bonjour {
        say "Bonjour"
    }
}
 

class Child is Parent1 is Parent2{
    method Aloha {
        say "Aloha"
    }
}
 
my Child $test;
$test.Hello;
$test.Bonjour;
$test.Aloha;
```

And the error message looked like this 

```
PS C:\dev\lang\perl6> perl6 .\hello2.p6
===SORRY!=== Error while compiling C:\dev\lang\perl6/.\hello2.p6
Cannot resolve caller trait_mod:<is>(Child, Parent2, Block); none of these signatures match:
    (Mu:U $child, Mu:U $parent)
    (Mu:U $child, :$DEPRECATED!)
    (Mu:U $type, :$rw!)
    (Mu:U $type, :$nativesize!)
    (Mu:U $type, :$ctype!)
    (Mu:U $type, :$unsigned!)
    (Mu:U $type, :$hidden!)
    (Mu:U $type, Mu :$array_type!)
    (Mu:U $type, *%fail)
    (Attribute:D $attr, |c is raw)
    (Attribute:D $attr, :$rw!)
    (Attribute:D $attr, :$readonly!)
    (Attribute $attr, :$required!)
    (Attribute $attr, Mu :$default!)
    (Attribute:D $attr, :$box_target!)
    (Attribute:D $attr, :$DEPRECATED!)
    (Attribute:D $attr, :$leading_docs!)
    (Attribute:D $attr, :$trailing_docs!)
    (Routine:D $r, |c is raw)
    (Routine:D $r, :$rw!)
    (Routine:D $r, :$raw!)
    (Routine:D $r, :$default!)
    (Routine:D $r, :$DEPRECATED!)
    (Routine:D $r, Mu :$inlinable!)
    (Routine:D $r, :$onlystar!)
    (Routine:D $r, :prec(%spec)!)
    (Routine $r, :&equiv!)
    (Routine $r, :&tighter!)
    (Routine $r, :&looser!)
    (Routine $r, :$assoc!)
    (Parameter:D $param, |c is raw)
    (Parameter:D $param, :$readonly!)
    (Parameter:D $param, :$rw!)
    (Parameter:D $param, :$copy!)
    (Parameter:D $param, :$required!)
    (Parameter:D $param, :$raw!)
    (Parameter:D $param, :$onearg!)
    (Parameter:D $param, :$leading_docs!)
    (Parameter:D $param, :$trailing_docs!)
    (Routine:D \r, :$export!, :$SYMBOL = { ... })
    (Mu:U \type, :$export!)
    (Mu \sym, :$export!, :$SYMBOL!)
    (Block:D $r, :$leading_docs!)
    (Block:D $r, :$trailing_docs!)
    (Routine:D $r, :$leading_docs!)
    (Routine:D $r, :$trailing_docs!)
    (Mu:U $docee, :$leading_docs!)
    (Mu:U $docee, :$trailing_docs!)
    (Routine:D $r, :$hidden-from-backtrace!)
    (Routine:D $r, :$hidden-from-USAGE!)
    (Routine:D $r, :$pure!)
    (Routine:D $r, :$nodal!)
    (Variable:D $v, |c is raw)
    (Variable:D $v, Mu :$default!)
    (Variable:D $v, :$dynamic!)
    (Variable:D $v, :$export!)
    (Routine $r, Str :$equiv!)
    (Routine $r, Str :$tighter!)
    (Routine $r, Str :$looser!)
at C:\dev\lang\perl6/.\hello2.p6:14
```

I found this error message to be a bit daunting
and it took me a while to figure out I just needed to add one space to fix this

**Comment by lizmat** [comment] 2018-07-12 21:19
Fixed the second case with 1956df2552

**Comment by lizmat** [comment] 2018-07-12 21:28
The first case feels a bit like DIHWIDT to me.

**Comment by zoffixznet** [comment] 2018-07-12 21:29
> The first case feels a bit like DIHWIDT to me.

Yeah, I think the error itself is fine, but it could use a location information for where the problematic code is at.

**Comment by zoffixznet** [comment] 2018-07-12 21:30
I see other "No compile time value" errors lack location as well:

```
<Zoffix__> m: sub ::(rand) {}
<camelia> rakudo-moar 8f090821a: OUTPUT: «===SORRY!===␤Name ::(rand) is not compile-time known, and can not serve as a sub declaration␤»
```

**Comment by lizmat** [comment] 2018-07-12 21:30
Hmmm... it does fix it for `class A {}; class C is A{}; dd C`.  Will add another candidate.

**Comment by lizmat** [comment] 2018-07-12 21:37
Another partial fix for the second case: 21eb168ca4

**Comment by shishini** [comment] 2018-07-13 20:09
> Fixed the second case with 1956df2

i am not a compiler expert or anything, but if the compiler knows exactly what the issue is, and in this case it cannot be anything else (i assume)

why is this an issue or an error in the first place 

why doesn't the compiler do the equivalent of adding the space .. and just compile it

**Comment by jnthn** [comment] 2018-07-13 20:48
> why is this an issue or an error in the first place

Because the `is` trait syntax allows any circumfix after the trait name, which is parsed in the same way that colonpair syntax would parse such a thing. For example, `is foo[1, 2]` applies the trait with an array, and `is foo{ bar => 42 }` applies it with a hash, and so forth. It's valid syntax...just for something else.

**Comment by lizmat** [comment] 2024-10-04 18:22
in RakuAST
```
% RAKUDO_RAKUAST=1 raku -e 'sub class { }; my \point = %(a => 1); class point{"a"}.say'
===SORRY!===
Symbol 'point' does not have a compile-time value
```
which still doesn't point at the location, but *is* a little clearer I'd say.

Closing because of general DIHWIDT

**Closed by lizmat** 2024-10-04 18:22 UTC
Labels: LTA
