### ISSUE TITLE
Ordering of attributes WRT to inheritance

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#3888] opened 2020-08-28 04:30 UTC
The Problem

Consider:
```
class A {
    has $.a;
    has $.b;
}

class B is A {
    has $.c;
}
```
## Expected Behavior

I would have expected the ordering of .^attributes to be `$!a $!b $!c`,

I.e attributes from the parent class first.

## Actual Behavior

`say B.^attributes>>.name.join(' ');` actually gives `$!c $!a $!b`

Prompted by a currently [open bug](https://github.com/pdf-raku/Native-Packing-raku/issues/2) in Native::Packing

**Comment by vrurg** [comment] 2020-08-28 14:00
You get the correct and expected output. Introspection of class inheritance is done with `.^mro` order. This makes full sense. Consider, for example, multiple inheritance case:

```raku
class C1 { has $.c1; }
class C2 { has $.c2; }
class C3 is C1 is C2 { has $.c3; }
class C4 { has $.c4 }
class C5 { has $.c5 }
class C6 is C4 is C5 { has $.c6; }
class C7 is C3 is C6 { has $.c7; }
```

Where would you start walking the tree? Apparently, from it's root, not from a leaf. But if for a second we try to consider the proposed logic then what leaf shall we start with? How do we choose the order of sorting of nodes?

The exact point of having attribute list returned in MRO order is because when you do `C7.new.c4` you actually invoke a method-accessor. Therefore it makes full sense to have introspection done in the same order the language lookups methods.

I think you need another solution for your problem.

Closing as reported behavior is not a bug.

**Closed by vrurg** 2020-08-28 14:00 UTC

**Comment by dwarring** [comment] 2020-08-28 18:39
OK, for the record what I'm after is not MRO, but CStruct like storage order.
```
class A is repr('CStruct') { has uint8 $.a; has uint16 $b; }
class B is A is repr('CStruct') { has uint32 $.c }
```
As being $!a $!b $!c
