### ISSUE TITLE
Gather issues

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#3380] opened 2019-12-25 10:44 UTC
## The Problem

A `Seq` produced by `gather` does not declare itself to be lazy. Invoking `.gist` on an infinite gather makes a subsequent  `.is-lazy` hang.

## Expected Behavior

 The following tests:

```raku
use Test;
plan 3;

my $seq = gather {
    my $i = 0;
    while 1 { take $i++ }
};

ok $seq.is-lazy, '.is-lazy returns True on infinite gather';

is $seq.gist, (0..100).list.gist, '.gist';

my $test = start { $seq.is-lazy };
await Promise.anyof($test, Promise.in(5));
ok $test, '.is-lazy does not hang after .gist';
```

Should output

```tap
1..3
ok 1 - .is-lazy returns True on infinite gather
ok 2 - .gist
ok 3 - .is-lazy does not hang after .gist
```

## Actual Behavior

The actual test output is

```tap
1..3
not ok 1 - .is-lazy returns True on infinite gather
# Failed test '.is-lazy returns True on infinite gather'
# at gather.is-lazy.pl6 line 9
ok 2 - .gist
not ok 3 - .is-lazy does not hang after .gist
# Failed test '.is-lazy does not hang after .gist'
# at gather.is-lazy.pl6 line 15
# Looks like you failed 2 tests of 3
```

## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`):
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by lizmat** [comment] 2019-12-25 13:38
An easy fix would be to just mark the `Rakudo::Iterator::Gather` iterator as lazy.  However, that breaks installation with:

    ===SORRY!===
    Cannot sort a lazy list

So that's not an option.  So I guess we need a syntactic  way to mark a `gather` block as lazy, so it can be passed to the iterator creation.

In preparation for that, I have added an "is-lazy" attribute to the underlying iterator in b6afa71277

**Comment by lizmat** [comment] 2019-12-25 14:16
After 07072f3803 the following test runs to completion:

    use Test;
    plan 3;

    my $seq = gather {
        my $i = 0;
        while 1 { take $i++ }
    } :is-lazy;

    ok $seq.is-lazy, '.is-lazy returns True on infinite gather';

    is $seq.gist, '(...)', '.gist';

    my $test = start { $seq.is-lazy };
    await Promise.anyof($test, Promise.in(5));
    ok $test, '.is-lazy does not hang after .gist';

Pinging @jnthn to see if he's ok with this change.

**Comment by jnthn** [comment] 2019-12-25 14:17
> So I guess we need a syntactic way to mark a gather block as lazy

We do; it's spelled `lazy gather`.

**Comment by jnthn** [comment] 2019-12-25 14:19
> Pinging @jnthn to see if he's ok with this change.

No, not when there's already a fine way that's shorter and more regular. :-)

Ah, and to add: that `gather` is not lazy by default, and requires such marking, is by design.

**Comment by lizmat** [comment] 2019-12-25 14:21
Ok, I'll revert the last one.  And look at making `lazy` smarter, so it can tell the `gather` iterator to be lazy, rather than embedding it in another iterator marking itself lazy.

**Comment by jnthn** [comment] 2019-12-25 14:35
Be very careful; it must only do that optimization if it is immediately receiving the `gather` block.

**Comment by lizmat** [comment] 2019-12-25 20:16
Yeah, that is becoming difficult.  The whole `Lazy` iterator is based on the fact that it will **not** call the `source.iterator` until the first `pull-one` is done.  So essentially we would need to know whether an iterator will be lazy **before** it gets instantiated.  Chicken and egg problem.  So closing this ticket now.

**Comment by dumarchie** [comment] 2019-12-27 08:59
@lizmat, I accept that the first `is-lazy` returns false by design. But still the second `is-lazy` should not hang and this ticket should not be closed until that is fixed.

Note that I used `.gist` to trigger the hang because that's what the REPL calls on the result of most statements. The hang is actually caused by the underlying `.cache` call, so I reduced the test to

```raku
use Test;
plan 2;

my $seq = gather {
    my $i = 0;
    while 1 { take $i++ }
};
ok !$seq.is-lazy, '.is-lazy on infinite gather';

$seq.cache;

my $test = start { $seq.is-lazy };
await Promise.anyof($test, Promise.in(5));
ok $test, '.is-lazy does not hang after .cache';
```
and on the latest Rakudo build the output is:

```tap
1..2
ok 1 - .is-lazy on infinite gather
not ok 2 - .is-lazy does not hang after .cache
# Failed test '.is-lazy does not hang after .cache'
# at gather.is-lazy.pl6 line 14
# You failed 1 test of 2
```

**Comment by lizmat** [comment] 2019-12-27 10:37
This behaviour is caused by `List.is-lazy` doing a `$!todo.reify-until-lazy`, because after the `$seq.cache` call, this is essentially lazy List semantics at work.

FWIW, I've never fully understood why the caching semantics of `Seq` would need to use the `List` semantics.  Perhaps @jnthn can enlighten.

**Comment by dumarchie** [comment] 2019-12-27 12:51
Maybe `Sequence` should have something like an `is-cacheable` predicate that defaults to `False` for `gather` sequences. If false, `.cache` should throw.

That way we'll have a clear distinction between the concepts of "supports lazy evaluation" and "possibly produces too many values to fit in memory"

**Comment by lizmat** [comment] 2020-06-04 13:07
I'm closing this issue now.  Please re-open if you disagree.

**Closed by lizmat** 2020-06-04 13:07 UTC

**Comment by 2colours** [comment] 2026-02-12 02:42
> This behaviour is caused by `List.is-lazy` doing a `$!todo.reify-until-lazy`, because after the `$seq.cache` call, this is essentially lazy List semantics at work.

I have a hard time following. Okay, `Seq.is-lazy` may call `List.is-lazy` but where does that do a `$!todo.reify-until-lazy`?

And anyway, why would that be a good thing? `is-lazy` arguably shouldn't retrieve a single value by design; it's pretty much tied to iterators anyway, and iterators rarely, if ever, change their own state. This should be a simple `True` or `False`.

I think this is still an issue.
