### ISSUE TITLE
$*KERNEL.bits on Windows

### ISSUE THREAD

**Issue by hankache** [rakudo/rakudo#2756] opened 2019-03-10 00:12 UTC
## The Problem
$*KERNEL.bits 
## Expected Behavior
Rakudo Star 2018.10
![2018 10](https://user-images.githubusercontent.com/15119547/54078886-32417d80-42d9-11e9-897d-51676fa3cd2f.PNG)

## Actual Behavior
Rakudo 2019.03
![2019 03](https://user-images.githubusercontent.com/15119547/54078887-34a3d780-42d9-11e9-9355-4e1b0ffc5ef4.PNG)
## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`):  This is Rakudo Star version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by ugexe** [comment] 2019-03-10 02:15
```
C:\Users\ugexe\.rakudobrew>perl6 --ll-exception -e "say $*KERNEL.bits"
Earlier failure:
 (HANDLED) Failed to find 'C:\usr\bin\uname' while trying to do '.x'
  in block <unit> at -e line 1

Final error:
 Type check failed in assignment to $!has_uname; expected Bool but got Failure (&CORE::infix:<orelse>...)
   at SETTING::src/core/Exception.pm6:62  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:throw)
 from SETTING::src/core/Exception.pm6:2757  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:)
 from gen/moar/BOOTSTRAP.nqp:1624  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/nqp/lib/Perl6/BOOTSTRAP.moarvm:)
 from SETTING::src/core/Kernel.pm6:14  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:uname)
 from SETTING::src/core/Kernel.pm6:81  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Kernel.pm6:80  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Kernel.pm6:79  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Kernel.pm6:78  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:hardware)
 from SETTING::src/core/Kernel.pm6:105  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share/perl6/runtime/CORE.setting.moarvm:bits)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen\moar\stage2\NQPHLL.nqp:1684  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\nqp\lib/NQPHLL.moarvm:eval)
 from gen\moar\stage2\NQPHLL.nqp:1793  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\nqp\lib/NQPHLL.moarvm:)
 from gen\moar\stage2\NQPHLL.nqp:1848  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\nqp\lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:38  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\nqp\lib/Perl6/Compiler.moarvm:command_eval)
 from gen\moar\stage2\NQPHLL.nqp:1773  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\nqp\lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:48  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\perl6\runtime\perl6.moarvm:MAIN)
 from gen/moar/main.nqp:1  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\perl6\runtime\perl6.moarvm:<mainline>)
 from <unknown>:1  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\perl6\runtime\perl6.moarvm:<main>)
 from <unknown>:1  (C:\Users\ugexe\.rakudobrew\moar-blead-master\install\share\perl6\runtime\perl6.moarvm:<entry>)
```

**Comment by ugexe** [comment] 2019-03-10 02:27
So this was caused by https://github.com/rakudo/rakudo/commit/a5b9fc2de5eac6734d700724fe46b2c3ab0d82fe but I cannot figure out why.

fwiw https://github.com/perl6/nqp/pull/517 would allow us to get rid of uname altogether (except for `uname -p`, aka `$*KERNEL.arch`)

**Comment by ugexe** [comment] 2019-03-11 00:59
I'm going to close this without tests since there are roast tests for `$*KERNEL.bits`. The problem here being that we do not yet have a good method of checking different roast runs on windows that is easily accessible to non-windows users (along with a method of showing a diff in output, since there are quite a few roast failures as to easily make anything new overlooked).

**Closed by ugexe** 2019-03-11 00:59 UTC
