### ISSUE TITLE
Fail to run regex repeatedly with --profile

### ISSUE THREAD

**Issue by lizmat** [rakudo/rakudo#2108] opened 2018-07-22 08:22 UTC
## The Problem

perl6 --profile -e 'my @alts = ^256; say "127.0.0.1" ~~ /^ @alts ** 4 % \. $/ for ^2'

## Expected Behavior

Run without problem, output:
｢127.0.0.1｣
｢127.0.0.1｣

## Actual Behavior

｢127.0.0.1｣
This type (NQPMu) does not support positional operations
  in any literal at /Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm line 1
  in block <unit> at -e line 1

## Steps to Reproduce

See also: http://colabti.org/irclogger/irclogger_log/moarvm?date=2018-07-22#l10

$ perl6 --ll-exception --profile -e 'my @alts = ^256; say "127.0.0.1" ~~ /^ @alts ** 4 % \. $/ for ^2'
｢127.0.0.1｣
This type (NQPMu) does not support positional operations
   at gen/moar/stage2/QRegex.nqp:92  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:addedge)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:literal)
 from gen/moar/stage2/QRegex.nqp:129  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:regex_nfa)
 from gen/moar/stage2/QRegex.nqp:119  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/QRegex.moarvm:addnode)
 from SETTING::src/core/Match.pm6:274  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Match.pm6:255  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Match.pm6:243  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Match.pm6:239  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Match.pm6:294  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:INTERPOLATE)
 from <unknown>:1  (<ephemeral file>:)
 from SETTING::src/core/Regex.pm6:27  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.setting.moarvm:ACCEPTS)
 from -e:1  (<ephemeral file>:)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1559  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:73  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:run_profiled)
 from gen/moar/stage2/NQPHLL.nqp:1559  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1673  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1728  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1654  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/perl6.moarvm:<entry>)

## Environment
* Operating system: 
* Compiler version (`perl6 -v`):

**Comment by zoffixznet** [comment] 2018-07-22 08:47
This probably can be merged with https://github.com/rakudo/rakudo/issues/2013 which has gdb output for very likely the same problem

**Comment by dogbert17** [comment] 2019-11-02 16:37
Seems to be working now:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-m -v
    This is Rakudo version 2019.07.1-452-g7cf73de built on MoarVM version 2019.07.1-311-g8caf9fd
implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-m --profile -e 'my @alts = ^256; say "127.0.0.1" ~~ /^ @alts ** 4 % . $/ for ^2'
    ｢127.0.0.1｣
    ｢127.0.0.1｣
    Writing profiler output to profile-1572712593.1506062.html

**Comment by jonathanstowe** [comment] 2019-12-25 17:35
Confirmed with `This is Rakudo version 2019.11-271-g0e2485a83 built on MoarVM version 2019.11-92-gd7b6855d3`

**Comment by vrurg** [comment] 2019-12-26 14:31
Thanks @dogbert17 and @jonathanstowe ! Closing as confirmed fixed.

**Closed by vrurg** 2019-12-26 14:31 UTC
Labels: regex
