### ISSUE TITLE
P5built-ins fails after a commit that attempts to fix P5* modules

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2637] opened 2019-01-24 02:54 UTC
```
===> Testing: P5built-ins:ver<0.0.21>:auth<cpan:ELIZABETH>
===SORRY!===
Cannot invoke this object (REPR: Null; VMNull)
t/01-basic.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/01-basic.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
Parse errors: No plan found in TAP output
```

Bisected: 88c46676c540eb39f741904eacab8b371776181e

:pancakes:

**Comment by lizmat** [comment] 2019-01-24 09:33
Golfed to:

    $ perl6 --ll-exception --doc=Markdown lib/P5built-ins.pm6
    Cannot invoke this object (REPR: Null; VMNull)
       at gen/moar/stage2/QRegex.nqp:1276  (.../install/share/nqp/lib/QRegex.moarvm:check_LANG_oopsies)
     from gen/moar/Perl6-Grammar.nqp:1298  (.../install/share/nqp/lib/Perl6/Grammar.moarvm:statement_control:sym<use>)
     from gen/moar/stage2/QRegex.nqp:1693  (.../install/share/nqp/lib/QRegex.moarvm:!protoregex)
     from <unknown>:1  (.../install/share/nqp/lib/Perl6/Grammar.moarvm:statement_control)
     from gen/moar/Perl6-Grammar.nqp:955  (.../install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
   ...

**Comment by lizmat** [comment] 2019-01-24 09:45
If I do **not** load any of the following modules in `P5builtins`, then it loads ok:

    P5print
    P5readlink
    P5seek
    P5-X

Looking into what makes these modules different.  FWIW, they all load correctly by themselves, it only happens when one of these modules is loaded inside P5builtins.

**Comment by jnthn** [comment] 2019-01-25 16:34
The direct cause of the error is that `check_LANG_oopsies` uses `note`, but NQP has a problem where setting subs are not visible inside of roles. Fixing that (I'm trying a patch) will let it output the message, which might give more of a clue (and also, modulo the note, get things to work, though I'd like to try and track down what's going on with the change too).

**Comment by jnthn** [comment] 2019-01-25 16:34
@lizmat Do any of those export operators?

**Comment by lizmat** [comment] 2019-01-25 16:59
P5print:  exports term:<>s
P5seek:  exports term:<>s
P5-X: exports prefix:<>s

**Comment by lizmat** [comment] 2019-01-25 16:59
P5readlink only exports a single proto

**Comment by jnthn** [comment] 2019-01-25 17:12
I fixed the immediate crash in https://github.com/perl6/nqp/commit/6e75b0476a, which doesn't fix the actual problem, but does at least mean we get some better indication of what is going on. I suspect it's related to the language tweaks done by the exports.

**Comment by lizmat** [comment] 2019-01-25 17:17
So, should I bump NQP to get these fixes in for the release ?

**Comment by lizmat** [comment] 2019-01-25 17:23
Does this ring a bell?

    Deprecated use of %*LANG<dynamic-scope> assignment detected in use; module should export syntax using $*LANG.define_slang("dynamic-scope",<grammar>,<actions>) instead
      (value in braid: BOOTCode, value in %*LANG: BOOTCode)

**Comment by jnthn** [comment] 2019-01-25 17:25
@lizmat I don't know if it's bogus or if I'm using `set_pragma` wrong yet. Either way, with the two commits referenced, the tests now pass again.

**Comment by jnthn** [comment] 2019-01-25 17:25
However, we should keep the issue open to look into the new warnings.

**Comment by lizmat** [comment] 2019-01-25 17:30
FWIW, turns out the failure of `P5readlink` was caused by it not being installed.  So it is indeed exporting `term:<>`s and `prefix:<>`s that causes issues.

**Comment by jnthn** [comment] 2019-01-25 17:32
> Running mi6 test on P5builtins now dies with:

You're missing the Rakudo commit which fixed that.

**Comment by jonathanstowe** [comment] 2019-01-25 19:05
> Running `mi6 test` on `P5builtins` now dies with:
> 
> ===SORRY!===
> Serialization Error: missing static code ref for closure '' (src/Perl6/World.nqp:1226)

Ooh I saw that one too,  almost impossible to golf but basically I removed the "no precompilation" from [Staticish](https://github.com/jonathanstowe/Staticish) which has always been problematic and then rolled back the changes in [Lumberjack](https://github.com/jonathanstowe/Lumberjack) ( https://github.com/jonathanstowe/Lumberjack/commit/3461e025500c12f1bfb8c9f5e31ffd96d7236947) that took that dependency out and the very first time it was compiled it got that error.  After it was compiled the first time it was happy.  

But hey that's an improvement over the way it used to fail before ;-)

**Comment by lizmat** [comment] 2019-01-26 11:16
@AlexDaniel I think the blocker label can be removed for now.   Although it spews some warnings during installation, it does install correctly with `zef`.

**Comment by lizmat** [comment] 2019-01-26 11:17
Perhaps a new ticket about the warnings should be created, as that appears to be related to a new pragma feature that isn't fully developed yet.

**Comment by AlexDaniel** [comment] 2019-01-26 11:34
I'm OK with that, please create a ticket and close this one.

**Comment by lizmat** [comment] 2019-01-26 11:51
Closing this to be continued in #2647

**Closed by lizmat** 2019-01-26 11:51 UTC
Labels: ⚠ blocker ⚠
