### ISSUE TITLE
IO::Notifications for changes to file contents (2019.03 vs 2019.07.1)

### ISSUE THREAD

**Issue by bduggan** [rakudo/rakudo#3100] opened 2019-08-05 15:49 UTC
## The Problem

`.IO.watch` and `watch-path` do not provide notifications when there is a change to the contents of a file -- this is a change between `2019.03` and `2019.07.1`.

## Expected Behavior

The supply `$file.IO.watch` will emit `IO::Notification` objects when the contents of the file changes.

## Actual Behavior

It doesn't

## Steps to Reproduce
Run this:
```
(while true; do date; sleep 1; done) > watchme &
```
Then run this:
```
react whenever 'watchme'.IO.watch -> $e {
  say "got an event: " ~ $e
}
```

Under `2019.03` we see:
```
got an event: IO::Notification::Change<140210566333952>
got an event: IO::Notification::Change<140210566334912>
got an event: IO::Notification::Change<140210566334960>
```

But under `2019.07.1`, we see
```
```
(i.e. nothing)

## Environment
* Operating system:  OS/X 10.14

* Compiler version (`perl6 -v`):  see above

**Comment by vrurg** [comment] 2019-09-10 01:12
Not reproducible on macOS 10.14.6, rakudo 2019.07.1 and HEAD work equally well:

```
got an event: IO::Notification::Change<140566742368256>
got an event: IO::Notification::Change<140566742369216>
got an event: IO::Notification::Change<140566742369264>
got an event: IO::Notification::Change<140566742369312>
```

I remove BLOCKER for now. Ticket could be closed if no additional information provided.

**Comment by bduggan** [comment] 2019-09-10 12:36
What information would be helpful?  I'm still seeing this issue. (`macOS 10.14 (18A391)`)
Also `tail -f watchme` works fine

**Comment by vrurg** [comment] 2019-09-10 14:25
Ok, I've reproduced the problem. Due to different shell (I use fish) I rewrote the command line to a slightly different variant and that was the difference. I.e. things work fine for:

```
while true; date >>watchme ; sleep 1; end
```

but fail if:

```
while true; date; sleep 1; end >watchme
```

The breaking change really happened somewhere between 2019.03 and 2019.07.

**Comment by bduggan** [comment] 2019-09-10 14:57
Yes -- I noticed this too -- adding one line at a time works.

**Comment by jonathanstowe** [comment] 2019-09-10 19:13
I've checked with FreeBSD (which has on occasion shown similar regressions,) and that is fine @ ```his is Rakudo version 2019.07.1-296-g66e0561f9 built on MoarVM version 2019.07.1-187-gcadf3a793```

Was there a libuv bump somewhere in there?  If there was I'd start there.

**Comment by jnthn** [comment] 2019-09-10 21:43
I think https://github.com/MoarVM/MoarVM/commit/a515819b6031f2 is the only one between `2019.03` and `2019.07.1`.

**Comment by vrurg** [comment] 2019-09-19 13:25
@bduggan I have opened a MoarVM ticket MoarVM/MoarVM#1178. To have better diagnosis @jnthn reasonably proposes trying a version of MoarVM prior to MoarVM/MoarVM@a515819. Unfortunately, I'm in the middle of a big task and won't have time for a while for this. Maybe you could give it a try and report back?

**Comment by bduggan** [comment] 2019-09-19 16:44
So -- I downgraded to the commit right before  that one, and rebuilt (also downgrading nqp and rakudo to versions such that the deps were satisfied) -- and can report that it did not fix the issue -- i.e. this version still failed :
```
This is Rakudo version 2019.03.1-410-ge0076423c built on MoarVM version 2019.05-26-gc63e7eb7a
implementing Perl 6.d.
```
The moarvm,nqp, and rakudo commits to which I downgraded were respectively -- MoarVM/Moarvm@c63e7eb7a33492b0ee6c8a8b161b3ff55016cb94 , perl6/nqp@6372077890a39f32dd4784be06e406e2560830b7 and rakudo/rakudo@e0076423c5906e732125736665d2f7222eed00c6 

Here's the output, of running 2019.03.1 (which works), and the above (which doesn't) --
```
$ cat runme.p6
react whenever 'watchme'.IO.watch -> $e {
  say "got an event: " ~ $e
}
$ perl6 -v
This is Rakudo version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
$ perl6 runme.p6
got an event: IO::Notification::Change<140480293651968>
got an event: IO::Notification::Change<140480293652928>
got an event: IO::Notification::Change<140480293652976>
^C
$ ~/p6-dev/rakudo/perl6 -v
This is Rakudo version 2019.03.1-410-ge0076423c built on MoarVM version 2019.05-26-gc63e7eb7a
implementing Perl 6.d.
$ ~/p6-dev/rakudo/perl6 ./runme.p6
^C
$

```

**Comment by vrurg** [comment] 2019-09-19 18:43
@bduggan Thank you!

May I also ask you to report on MoarVM ticket?

**Comment by bduggan** [comment] 2019-09-19 19:58
Sure -- done :-)

**Comment by vrurg** [comment] 2019-09-24 02:00
The problem is in unmistakably tracked down to MoarVM/MoarVM@62b58164a

**Comment by ugexe** [comment] 2019-09-24 02:23
Unmistakably? The issue is not present in 2019.03 released in June/July, and you’re linking to a commit made 7 months ago.

**Comment by vrurg** [comment] 2019-09-24 02:26
@ugexe I provided full methodology in MoarVM ticket. And yes, I'm 100% positive that it was the commit.

**Comment by vrurg** [comment] 2019-09-24 02:26
Ah, I see why: the NQP bump which brought in that commit happened on Mar 16.

**Comment by ugexe** [comment] 2019-09-24 02:29
Well, the op also provides full methodology showing it working in 2019.03.

**Comment by vrurg** [comment] 2019-09-24 02:33
@ugexe with `git checkout 2019.03`:

```
⇒ cd nqp/MoarVM/3rdparty/libuv/ && git log | head -10                                                     23-09-19 22:33:01
commit 7ebb26225f2eaae6db22f4ef34ce76fa16ff89ec
Author: cjihrig <cjihrig@gmail.com>
Date:   Thu Aug 16 22:05:34 2018 -0400

    2018.08.18, Version 1.23.0 (Stable)
```

**Comment by ugexe** [comment] 2019-09-24 02:36
Ah then indeed there is no reason to doubt it is libuv 1.26

**Comment by vrurg** [comment] 2019-09-25 23:18
Since the problem has been tracked down to libuv changes and resulted in libuv/libuv#2488, I remove blocker from this ticket because it's nothing to do with changes in Rakudo. Moreover, people from libuv concluded that the problem stems even deeper down the stack and it's a bug of Darwin's implementation of kernel events.

As long as it's out of our control there is no reason for the blocking status.

**Comment by jnthn** [comment] 2019-09-25 23:21
> As long as it's out of our control there is no reason for the blocking status.

Arguably, we could consider reverting the libuv version bump, however.

**Comment by vrurg** [comment] 2019-09-25 23:23
There're dependencies on later versions of libuv. uname, in particular. I'm afraid, revert would require a chain of other reverts.

**Comment by jnthn** [comment] 2019-09-25 23:24
@vrurg Ah, then than argues more for waiting, given it seems there's PRs already in libuv. Thanks for golfing it down to report, by the way.

**Comment by vrurg** [comment] 2019-09-26 14:24
libuv/libuv@97b85e8 workarounds the bug. Waiting for next libuv release to be included into MoarVM.

**Comment by vrurg** [comment] 2019-10-17 22:45
Closing via moarvm/moarvm@0f05efbb7bcc8add499207ae173f814ca3407cbb

Thanks @bduggan!

**Closed by vrurg** 2019-10-17 22:45 UTC
Labels: macOS

**Comment by bduggan** [comment] 2019-10-18 00:48
Great, thanks!
