### ISSUE TITLE
Misgenerated laziness-related exception messages

### ISSUE THREAD

**Issue by 2colours** [rakudo/rakudo#5093] opened 2022-11-04 15:49 UTC
## The Problem
At https://github.com/rakudo/rakudo/blame/14fb6a5c3d4e4a747acc8b80df6f3cbb6061b2a6/src/core.c/Exception.pm6#L2534, the generated message depends on the $.what value. However, the https://github.com/rakudo/rakudo/commit/71960b162d244cc077654f5abb3fd3aecc4e9c8c#diff-c7ec673bbe90e52336b2deab6848644b916ac3678b73a4fb4cda1a00e730f795 rework eliminated the difference in the calls, hence now everything shows up with the "onto" format.

## Expected Behavior
`my @test = 1..*; try dd @test; $!.message.say; #Cannot .elems a lazy list`
## Actual Behavior
`my @test = 1..*; try dd @test; $!.message.say; #Cannot .elems a lazy list onto a Array`

## Environment
* Operating system: `5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Compiler version (`perl6 -v` or `raku -v`): Rakudo v2022.07 on MoarVM

**Comment by lizmat** [comment] 2022-11-04 16:16
I think the issue is really that `Array.raku` throws an exception, when it shouldn't.

**Comment by 2colours** [comment] 2022-11-04 16:53
I think it's both: the error message used to be generated in a meaningful way prior to the marked commit. Whether .raku should through or not is another thing.

**Comment by lizmat** [comment] 2022-11-04 19:45
I'm pretty sure the issue existed before the mentioned commit.

Unless you can find another situation where the error message changed, I would like to close this issue.

**Comment by 2colours** [comment] 2022-11-04 22:24
Simple enough:

> my @demo = 1..*; say @demo.elems;

Generates the correct error message on 2020.12, incorrect error message on HEAD.

**Comment by 2colours** [comment] 2022-11-04 22:28
Or:
> my @demo = 1..*; say @demo.List;

Trust me, I have checked the bisected commit and the problem is indeed related to it. Look up occasions of throw-iterator-cannot-be-lazy with only one argument prior to the modification. They all got broken.

**Closed** 2022-11-05 11:31 UTC
