### ISSUE TITLE
REPL: Internal error: unhandled encoding (Readline)

### ISSUE THREAD

**Issue by cfa** [rakudo/rakudo#2759] opened 2019-03-10 19:17 UTC
## The Problem

Intermittent internal errors from `Readline`, e.g.

```
$ perl6
> $*ENV<RAKUDO_HIST> ?? $*ENV<RAKUDO_HIST>.IO !! ($*HOME || $*TMPDIR).add('.perl6/rakudo-history');
Internal error: unhandled encoding
  in method CALL-ME at /Users/cfa/.rakudup/2019.03/install/share/perl6/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 587
  in method readline at /Users/cfa/.rakudup/2019.03/install/share/perl6/site/sources/EBC1B2DDA59A9D91D483BD81DAA416714D2D1276 (Readline) line 1460
^D
$ perl6
$*ENV<RAKUDO_HIST> ?? $*ENV<RAKUDO_HIST>.IO !! ($*HOME || $*TMPDIR).add('.perl6/rakudo-history');
"/Users/cfa/.perl6/rakudo-history".IO
```

Note how the same input triggers the exception in one run but not the next. This has occurred with a variety of input and seemingly at random—though frequently enough to make the REPL nigh unusable.
Also note that errors usually occur midway through a REPL session; the above was cherrypicked for clarity.

## Expected Behavior

Handled encoding!

## Actual Behavior

See above.

Following a discussion in `#perl6`, I also tried with `MVM_SPESH_DISABLE=1` and `MVM_JIT_DISABLE=1`; neither helped:

```
$ MVM_SPESH_DISABLE=1 p6
To exit type 'exit' or '^D'
> %*ENV<MVM_SPESH_DISABLE>
Internal error: unhandled encoding
  in method CALL-ME at /Users/cfa/.rakudup/2019.03/install/share/perl6/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 587
  in method readline at /Users/cfa/.rakudup/2019.03/install/share/perl6/site/sources/EBC1B2DDA59A9D91D483BD81DAA416714D2D1276 (Readline) line 1460

> %*ENV<MVM_SPESH_DISABLE>
1
```

and

```
$ MVM_JIT_DISABLE=1 p6
To exit type 'exit' or '^D'
> %*ENV<MVM_SPESH_DISABLE>
Internal error: unhandled encoding
  in method CALL-ME at /Users/cfa/.rakudup/2019.03/install/share/perl6/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 587
  in method readline at /Users/cfa/.rakudup/2019.03/install/share/perl6/site/sources/EBC1B2DDA59A9D91D483BD81DAA416714D2D1276 (Readline) line 1460

> %*ENV<MVM_JIT_DISABLE>
1
> %*ENV<MVM_SPESH_DISABLE>
(Any)
```

(Again, quite a few runs were required to reproduce the error at the beginning of the session.)

## Environment
* Operating system: macOS.
* Compiler version (`perl6 -v`): 2019.03. Problem first noticed following upgrade from 2018.12.

**Comment by cfa** [comment] 2019-03-10 19:17
Potentially related: https://gist.github.com/0racle/c7e65b6946a30479cf8493fbafc04f53.

**Comment by cfa** [comment] 2019-03-10 19:52
Also, in case anyone else hits this error: My current workaround is the following wrapper script (`p6`):

```sh
#!/bin/sh

# workaround for https://github.com/rakudo/rakudo/issues/2759
RAKUDO_LINE_EDITOR='none' rlwrap perl6 "$@"
```

—no need to uninstall `Readline` or fall back on `Linenoise`.

**Comment by Kaiepi** [comment] 2019-06-08 10:04
I thought this was an OpenBSD exclusive thing since it uses its own version of Readline... huh.

**Comment by Kaiepi** [comment] 2019-06-22 08:31
Does this still happen? I can't get the error to appear on HEAD

**Comment by AlexDaniel** [comment] 2019-06-25 20:03
Ping @cfa :)

**Comment by AlexDaniel** [comment] 2019-06-27 10:53
I also can't reproduce. Blocker label removed.

If anybody stumbles upon this ticket in the future, just close it.

**Closed** 2024-10-09 13:33 UTC
Labels: REPL
