### ISSUE TITLE
try { Any.Str }; does not contain the exception

### ISSUE THREAD

**Issue by chrsteel** [rakudo/rakudo#3420] opened 2020-01-13 12:29 UTC
## The Problem
`raku -e 'try { Any.Str };'` returns the following exception for me:
```
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at -e line 1
```

## Expected Behavior
Of course the error is correct, but I expected the exception to be contained by the `try`-Block.
Just as in (for example) `raku -e 'try { Any.Num };`the exception is contained.

## Environment
* Operating system: gentoo
* Compiler version (`perl6 -v`):
```
$ raku --version
This is Rakudo version 2019.11 built on MoarVM version 2020.01
implementing Perl 6.d.
```

**Comment by lizmat** [comment] 2020-01-13 12:40
`Any.Str` does **not** throw an `Exception`, it merely warns, as shown in this code:

    $ raku -e 'dd Any.Str; say "still alive"'
    Use of uninitialized value of type Any in string context.
    Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
      in block <unit> at -e line 1
    ""
    still alive

On the other hand, `Any.Num` **does** throw an exception:

    $ raku -e 'say Any.Num'
    No such method 'Num' for invocant of type 'Any'. Did you mean 'sum'?
      in block <unit> at -e line 1

One could argue that `Any.Num` should also just warn and produce `0e0`.

But all in all, I'd say this is not a bug.

**Comment by chrsteel** [comment] 2020-01-13 12:49
Ah! You are right, i missed that.
This is definitely not a bug then -- Sorry for the noise!

Hmm.. However, I would think that `try`-Blocks should contain warnings too:
After all, if I use `try`, I expect something might go wrong there, but I know how to handle that -- So a warning about potential danger is not appreciated in this case.
Just my 2¢ though,
Thank you!

**Comment by jnthn** [comment] 2020-01-13 13:08
There's also `quietly` blocks for suppressing warnings, and one can `quietly try ...` too.

**Comment by jnthn** [comment] 2020-02-12 15:32
Closing, since `try` also catching warnings automatically feels like a bad idea in general; `quietly try` is short enough for that, and in this case `quietly` alone is enough.

**Closed by jnthn** 2020-02-12 15:32 UTC
