### ISSUE TITLE
Unable to trap SIGPIPE or resulting X::AdHoc exception

### ISSUE THREAD

**Issue by dmaestro** [rakudo/rakudo#2695] opened 2019-02-13 04:30 UTC
This could be related to #2014 
## The Problem

I have found that emitting output with say from a perl6 program and feeding the output to the unix `head` command results in unwanted diagnostics (see #2014). In addition, I have found no way to trap the error in the program itself to allow silent operation in this use case.

## Expected Behavior

```
doug$ perl6 -e'.say for 1..Inf' | head
1
2
3
4
5
6
7
8
9
10
doug$
```

## Actual Behavior
```
doug$ perl6 -e'.say for 1..Inf' | head
1
2
3
4
5
6
7
8
9
10
Failed to write bytes to filehandle: Broken pipe
  in block <unit> at -e line 1

Unhandled exception: Failed to write bytes to filehandle: Broken pipe
   at SETTING::src/core/Exception.pm6:470  (/var/local/test/share/perl6/runtime/CORE.setting.moarvm:<anon>)
 from gen/moar/stage2/NQPHLL.nqp:1855  (/var/local/test/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:48  (/var/local/test/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1777  (/var/local/test/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:54  (/var/local/test/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:42  (/var/local/test/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/var/local/test/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/var/local/test/share/perl6/runtime/perl6.moarvm:<entry>)
doug$
```
Note that an attempt to trap the error still emits an 'unhandled exception' message:
```
doug$ perl6 -e'CATCH { when X::AdHoc {} }; .say for 1..Inf' | head
1
2
3
4
5
6
7
8
9
10
Unhandled exception: Failed to write bytes to filehandle: Broken pipe
doug$
```
## Steps to Reproduce

Run the above one-liners from the command line.

## Environment
This was reproduced on the following OS versions:
### MacOS
* Operating system: macosx (10.13.6)
* Compiler version (`perl6 -v`): 
```
This is Rakudo Star version 2018.10 built on MoarVM version 2018.10
implementing Perl 6.c.
```
### Linux
* Operating system: slackware (14.2)
```
Linux ender 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz GenuineIntel GNU/Linux
```
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2018.12 built on MoarVM version 2018.12
implementing Perl 6.d.
```

**Comment by dmaestro** [comment] 2019-02-13 04:38
Attempts to intercept a sigpipe also had no effect.
```
doug$ perl6 -e'signal(SIGPIPE).tap({ $*ERR.say("Trapped a SIGPIPE"); exit 0; }); CATCH { .so; when X::AdHoc {} }; .say for 1..Inf' | head
1
2
3
4
5
6
7
8
9
10
Unhandled exception: Failed to write bytes to filehandle: Broken pipe
Trapped a SIGPIPE
doug$
```

**Comment by Leont** [comment] 2019-06-20 01:23
One workaround for this is the following sniplet:
~~~~
use NativeCall;
my sub signal(int32 $signal, long $func) is native { * }
signal(+SIGPIPE, 0);
~~~~

**Comment by treyharris** [comment] 2019-06-20 16:52
This issue is a bit overly-focused on a side effect, so rather than adding a comment to it which might leave it unnoticed and never acted upon, I opened a new issue #3004.

This one might be closed as a dupe as it would naturally be fixed by the other (though perhaps @dmaestro might disagree), but I don’t have access rights to this GitHub org as I do to perl6, so I’ll leave that to someone else.

**Comment by treyharris** [comment] 2019-06-20 17:53
Duplicate of #3004

**Closed** 2019-06-20 17:58 UTC
