### ISSUE TITLE
Would be nice to have an easy way to work with SetHashes and its kin

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1203] opened 2017-10-24 10:59 UTC
Based on discussion [on RT#132352](https://rt.perl.org/Ticket/Display.html?id=132352), it would be nice if you could have a `%-` sigiled var to worth with SetHash and its kin and so you could use meta-assign form of set ops, like `∖=`

```
[...] make the following variation of it work:

    my %days is SetHash = Date.today … Date.new: '2014-04-02';
    %days ∖= %days.grep: *.key.day-of-week > 5;
    %days{Date.today}:delete;

...and then promote %-sigiled SetHash variables as the recommended way to store SetHash'es.

It should be possible to make this last example work by implementing `method STORE` for type SetHash, right?

(That it currently doesn't, may well be an oversight rather than a design choice.)
```

**Comment by jnthn** [comment] 2017-10-25 13:01
Yes, I think `STORE` should be implemented on `SetHash`, `MixHash`, and `BagHash`; and it should work very much like `STORE` does in `Hash`, except with the setty/baggy/mixy semantics. I think the only reason it's not been done yet is that nobody got around to it; there's no design reason I can think of for this to be missing.

**Comment by lizmat** [comment] 2017-10-25 13:24
So should .STORE use .new or .new-from-pairs semantics?

**Comment by jnthn** [comment] 2017-10-25 16:02
Neither, it seems. If we look at what assignment to an ordinary hash does:

```
> my %h = a => 1, 'b', 2
{a => 1, b => 2}
```

Then we see it knows what to do with both pairs and lone elements. Ditto for object hash:

```
> my %h{Any} = a => 1, 'b', 2
{a => 1, b => 2}
```

So I'd expect:

```
my %h is BagHash = a => 2, 'b', 2;
```

To result in a `BagHash` the same as:

```
(my %h = a => 1, 'b', 2).BagHash
```

Currently does.

**Comment by lizmat** [comment] 2017-10-25 17:58
That’s the new-from-pairs semantics  :-)  I’ll try to get that in after the release.

**Comment by jnthn** [comment] 2017-10-25 18:46
Ah, cool, the docs left me thinking it really only worked on pairs. :-)

**Comment by AlexDaniel** [comment] 2017-11-18 16:58
So what's the status of this now?
FWIW: [RT#132352](https://rt.perl.org/Ticket/Display.html?id=132352) [RT#132353](https://rt.perl.org/Ticket/Display.html?id=132353)

**Comment by lizmat** [comment] 2017-11-18 21:04
It appears to me these can both be closed as there appear to be tests for it that pass.

**Comment by zoffixznet** [comment] 2017-12-11 17:09
With current HEAD, running the OP's code no longer errors out, but instead of DWIMMing, the code produces a SetHash with 1 element: a `set()`.

Is this by design or is it a bug?

```
Zoffix │ m: my %days := SetHash.new: Date.today … Date.new: '2030-04-02'; %days ∖= %days.grep: *.key.day-of-week > 5; say %days.elems 
+camelia │ rakudo-moar f1be29c0d: OUTPUT: «1␤»
```

**Comment by lizmat** [comment] 2019-06-22 11:23
FWIW, Zoffix's last code produces the right answer on HEAD, so closing this ticket for now

    $ perl6 -e 'my %days := SetHash.new: Date.today … Date.new: "2030-04-02"; %days ∖= %days.grep: *.key.day-of-week > 5; say %days.elems'
    2812

**Comment by lizmat** [comment] 2019-06-22 14:15
https://github.com/perl6/problem-solving/issues/47

**Comment by vrurg** [comment] 2019-09-12 01:51
Closing because this is intended behavior.

**Closed by vrurg** 2019-09-12 01:51 UTC
Labels: data types
