### ISSUE TITLE
Hypers in interpolation only work on first method

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1460] opened 2018-01-31 19:38 UTC
You can chain method calls when interpolating. You can also add hypered method calls—but that works only if the hyper is on the first method:

```
$ perl6 -e 'my %add = :42foo, :70bar, :10ber; say qq|%add».sort.map(*.fmt("%s %s"))|'
bar 70 ber 10 foo 42

$ perl6 -e 'my %add = :42foo, :70bar, :10ber; say qq|%add.sort».map(*.fmt("%s %s"))|'
%add.sort».map(*.fmt("%s %s"))

$ perl6 -v
This is Rakudo version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.
```

**Comment by b2gills** [comment] 2018-02-26 01:00
It works if you add `()` before `»`

```
$ perl6 -e 'my %add = :42foo, :70bar, :10ber; say qq|%add.sort()».map(*.fmt("%s %s"))|'
bar 70 ber 10 foo 42
```

**Comment by ab5tract** [comment] 2024-05-17 23:53
This is still happening:

```
> set-base;  r 'my %add = :42foo, :70bar, :10ber; say qq|%add».sort.map(*.fmt("%s %s"))|'
bar 70 foo 42 ber 10

> set-base; r 'my %add = :42foo, :70bar, :10ber; say qq|%add.sort».map(*.fmt("%s %s"))|'
%add.sort».map(*.fmt("%s %s"))

> set-rakuast; r 'my %add = :42foo, :70bar, :10ber; say qq|%add».sort.map(*.fmt("%s %s"))|'
ber 10 bar 70 foo 42

> set-rakuast; r 'my %add = :42foo, :70bar, :10ber; say qq|%add.sort».map(*.fmt("%s %s"))|'
%add.sort».map(*.fmt("%s %s"))

> ./rakudo-m -v
Welcome to Rakudo™ v2024.04-96-ge3ad75a69.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.04-6-g84121f0de.
```

**Comment by lizmat** [comment] 2024-10-02 09:51
I think this is by design.  In interpolation, methods are only recognized as method calls if the final method call is followed by parentheses, even if there are no arguments passed.

The reason for that is really email addresses:  "liz@raku.rocks".  You don't want it complain about `@raku` not being defined, or the `.rocks` method not existing.

This is different from hash interpolation.

So closing this as a WONTFIX

**Closed by lizmat** 2024-10-02 09:51 UTC
