### ISSUE TITLE
"make test" fails on Apple M1 hardware

### ISSUE THREAD

**Issue by mbamac** [rakudo/rakudo#4341] opened 2021-04-24 19:20 UTC
## The Problem
"make test" fails on Apple M1 hardware
## Actual Behavior
t/04-nativecall/02-simple-args.t ................................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/14 subtests 
	(less 1 skipped subtest: 12 okay)

(cut...)

Test Summary Report
-------------------
t/04-nativecall/02-simple-args.t                              (Wstat: 256 Tests: 14 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
Files=109, Tests=1835, 25 wallclock secs ( 0.42 usr  0.18 sys + 128.98 cusr 12.89 csys = 142.47 CPU)
Result: FAIL

## Steps to Reproduce

download and unpack rakudo-2021.03.tar.gz from rakudo.net

perl Configure.pl --backend=moar --gen-moar --prefix=/Applications/rakudo-2021.03
make
make test

## Environment
* Operating system: macOS 11.2.3 on Apple M1 hardware

**Comment by tony-o** [comment] 2021-04-27 02:48
Is this a duplicate of #4317  ?

**Comment by mbamac** [comment] 2021-04-27 19:40
not duplicate. I can build it, install and run simple programs.

**Comment by jonathanstowe** [comment] 2021-04-27 19:57
I seem to recall that test failing on arm previously without `ffi`.

Try configuring the MoarVM with `--has-ffi`:

    perl Configure.pl --gen-moar --moar-option='--has-ffi'  --gen-nqp --backends=moar

You may need to install the `libffi` if you don't already have it.

**Comment by mbamac** [comment] 2021-07-15 09:54
> I seem to recall that test failing on arm previously without `ffi`.
> 
> Try configuring the MoarVM with `--has-ffi`:
> 
> ```
> perl Configure.pl --gen-moar --moar-option='--has-ffi'  --gen-nqp --backends=moar
> ```
> 
> You may need to install the `libffi` if you don't already have it.

Configuring and building MoarVM ...
perl Configure.pl --has-ffi --optimize --prefix=/Applications/rakudo-2021.06 --make-install
Unknown option: has-ffi

**Comment by MasterDuke17** [comment] 2021-07-15 11:35
> Configuring and building MoarVM ...
> perl Configure.pl --has-ffi --optimize --prefix=/Applications/rakudo-2021.06 --make-install
> Unknown option: has-ffi

It's `--has-libffi`. `perl Configure.pl --help` shows all the different build options.

**Comment by mbamac** [comment] 2021-07-15 16:53
@MasterDuke17 thanks for the advice.

Now it can be compiled without errors in `make test` with libffi 3.4.1.

Libffi configured with:

`./configure --prefix=/Applications/rakudo-2021.06`

rakudo configured with:

`export CPATH=/Applications/rakudo-2021.06/include`
`perl Configure.pl --backend=moar --gen-moar --prefix=/Applications/rakudo-2021.06 --moar-option='--has-libffi'`

**Closed** 2021-08-09 21:09 UTC
