### ISSUE TITLE
Unknown QAST node type NQPMu with fake-infix adverbs on a construct inside args to another routine

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1500] opened 2018-02-08 00:02 UTC
Expected this test to pass, instead got a QAST error:

```
<Zoffix__> c: 2018.01 use Test; my Pair $p; is-deeply ($p .= new :key<foo> :value<bar>), :foo<bar>.Pair, 'fake-infix adverbs on a construct inside args to another routine'
<committable6> Zoffix__, ¦2018.01: «===SORRY!===␤Unknown QAST node type NQPMu␤ «exit code = 1»»
```

**Comment by skids** [comment] 2018-05-11 04:36
I've started to look at colonlists in https://github.com/skids/rakudo/tree/colonlists

The first commit fixes part of this: the NQPMu is caused by the angle quotes on the
fake-infix :value<bar>.  (The patch fixes RT#127267 RT#127023 but there are some
other areas where I need to make similar changes, like in <arglist>)

A second part of the problem is that the above test case seems to require a colon after
the new, and probably should not since the bare case does not, though the precedence
on these constructs is tricky. I don't think anything I am doing will fix that.

**Comment by zoffixznet** [comment] 2018-05-11 11:07
> to require a colon after the new, and probably should not 

Right, with colon after `.new` it wouldn't be "fakeinfix" adverbs anymore, but just named args.

**Comment by skids** [comment] 2018-05-21 03:38
Well, it appears I did manage to fix that after all.  I'll need to make a new branch to clean out some git garbage due to a few wrong turns, and the fix could use some review.  Tests in https://github.com/skids/roast/tree/colonlists for this and three RTs the above branch fixes as well as a bunch of previously untested stuff.

**Comment by AlexDaniel** [comment] 2019-06-26 14:24
That was fixed in https://github.com/rakudo/rakudo/commit/91359141fb7501636b073ccaf6fb6598dc273bec, right?

**Closed** 2019-10-19 15:29 UTC
Labels: tests needed
