### ISSUE TITLE
Making of == return in Callable

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#1876] opened 2018-05-27 18:38 UTC
## The Problem

[Those functions both return T](https://github.com/rakudo/rakudo/blob/master/src/core/Callable.pm6#L4-L5).

## Expected Behavior

It's unlikely that they will return anything else in the future, so having two functions with the same behavior is confusing. Maybe one is going to be obsoleted. Wouldn't it be better if one calls the other?

**Comment by ab5tract** [comment] 2024-05-22 22:44
Closing this because there isn't any buggy behavior or reproducible issue. It would be better suited as a problem-solving ticket, though the proposed solution is vague (which of the two methods is maybe going to be obsoleted? which should call which? maybe they should both call a common private method?).

Beyond that, there's nothing to really be gained here except for a small overhead for one of the two methods. The code is super-compact as it is, there's no lacking in clarity. This is the kind of DRY that ends up chafing.

**Closed by ab5tract** 2024-05-22 22:44 UTC

**Comment by niner** [comment] 2024-05-23 06:15
Well `of` is the more general name of the two while `returns` is very intuitive for callables. Additionally there's a tiny difference in behavior in Block, though whether that's intentional or not I don't know.
