### ISSUE TITLE
Raku HEAD problem with pairs method on Array Enum

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#4310] opened 2021-04-09 22:03 UTC
## The Problem

I'm getting  new error when running the following program latest Rakudo.

Golfed from PDF::Content t/page.t

```
my Array enum PageSizes «
        :Letter[0,0,612,792]
        :Tabloid[0,0,792,1224]
    »;

dd (PageSizes::Letter).value.pairs;
dd (PageSizes::Letter).pairs;
```

## Expected Behavior

output:
```
(0 => 0, 1 => 0, 2 => 612, 3 => 792).Seq
(0 => 0, 1 => 0, 2 => 612, 3 => 792).Seq
```

## Actual Behavior

```
(0 => 0, 1 => 0, 2 => 612, 3 => 792).Seq
Ambiguous call to 'pairs(PageSizes: )'; these signatures all match:
  (Enumeration: *%_)
  (List:D: *%_)
   at SETTING::src/core.c/Exception.pm6:62  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/Exception.pm6:3032  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from gen/moar/BOOTSTRAP/v6c.nqp:2612  (/home/david/git/rakudo/install/share/perl6/lib/Perl6/BOOTSTRAP/v6c.moarvm:)
 from SETTING::src/core.c/Any.pm6:112  (/home/david/git/rakudo/install/share/perl6/runtime/CORE.c.setting.moarvm:pairs)
 from /tmp/tst.raku:7  (<ephemeral file>:<unit>)
 from /tmp/tst.raku:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1946  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2151  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2111  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:109  (/home/david/git/rakudo/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2036  (/home/david/git/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/david/git/rakudo/install/share/perl6/runtime/perl6.moarvm:<entry>)
```

## Steps to Reproduce
     `raku --ll-exception  /tmp/tst.raku` 

## Environment
* Operating system: Linux toshiba 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`): Welcome to Rakudo(tm) v2021.03-142-gb4813bbdb.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.03-39-gba124ad12.

**Comment by Altai-man** [comment] 2021-04-10 10:21
It behaves normally on 2021.03, so it's a regression and thus a blocker.

**Comment by Altai-man** [comment] 2021-04-10 10:23
Bisected to https://github.com/rakudo/rakudo/commit/615030d279d9caba6bacb397107387cd6aaef410 log https://gist.github.com/Whateverable/223dba45e4b44e3d9a22ead7dc070b2a
ping @lizmat

**Comment by lizmat** [comment] 2021-04-11 22:03
FWIW, same kind of error for `.keys` and `.values`, but oddly enough **not** for `.kv`.

**Comment by lizmat** [comment] 2021-04-12 17:12
Tests added with https://github.com/Raku/roast/commit/4a0ab5968ac2ce99b1b09172ff2ed14d82a93f7f , fixed with https://github.com/rakudo/rakudo/commit/b1556cbadc34fa43df62179581ad1098a7af9b33

**Closed** 2021-04-12 17:12 UTC
Labels: BLOCKER, regression

**Comment by dwarring** [comment] 2021-04-13 22:41
@lizmat
Output from `dd (PageSizes::Letter).pairs;` is now:
`(:Tabloid([0, 0, 792, 1224]), :Letter([0, 0, 612, 792])).Seq`

Shouldn't it be: (0 => 0, 1 => 0, 2 => 612, 3 => 792).Seq
?

**Comment by lizmat** [comment] 2021-04-14 06:06
dd Letter.value;
    Array element = [0, 0, 612, 792]

The value of the enum is an Array.  An Array doesn't flatten itself?

**Comment by vrurg** [comment] 2021-04-14 14:29
@lizmat I think the confusion is caused by `PageSizes::Letter` falling back to the enum type itself whereas the element is expected. I'd say that `PageSizes::Letter.pairs` should be `(0 => :Letters[...])`, i.e. no `Tabloid` included into the output.

**Comment by dwarring** [comment] 2021-04-14 18:18
I was used to the 2020.05.1 behavior , where PageSizes::Letter.pairs was equivalent to PageSizes::Letter.value.pairs.

I see the conflict now, an enum item is normally augmented with methods pairs, values, keys etc.
