### ISSUE TITLE
Cro + Digest::SHA256::Native = segfault

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1660] opened 2018-03-27 20:40 UTC
Code:
```perl6
use Cro::HTTP::Client;
use Digest::SHA256::Native;

sub get($url) {
    say $url;
    await Cro::HTTP::Client.get: $url
}
await
    start {
        get ‘http://docs.perl6.org’ for ^10
    },
    start {
        sha256-hex await get(‘https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz’).body for ^10
    }
```

Output:
```
http://docs.perl6.org
https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
http://docs.perl6.org
http://docs.perl6.org
http://docs.perl6.org
https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
http://docs.perl6.org
http://docs.perl6.org
http://docs.perl6.org
http://docs.perl6.org
https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
http://docs.perl6.org
http://docs.perl6.org
https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
Segmentation fault
```

Sometimes it works, but typically it segfaults. Make sure to run a few times when trying to reproduce.

I *think* there's a way to make it fail even without start blocks, but I'm not sure. The same process done sequentially segfaults in [undersightable](https://github.com/perl6/whateverable/issues/273), but there are other things going on in the actual bot so maybe that's not related.

Also, I did try running it with `perl6-valgrind-m` but the segfault disappears. Segfault happens even with JIT or spesh disabled.

I also tried running that code in bisectable, but for some reason it never segfaults that way, so I can't tell if it's a regression or not.

**Comment by lizmat** [comment] 2018-03-27 20:47
Perhaps a stupid question, but is the underlying library of Digest::SHA256::Native threadsafe?

**Comment by AlexDaniel** [comment] 2018-03-27 20:52
@lizmat does it matter? It is being used from one thread only anyway.

**Comment by AlexDaniel** [comment] 2018-03-27 20:57
Well, there's a chance that something that is being used by Cro is not threadsafe, so indeed it could be a problem in some module, like in one of these:
```
all-modules/cpan/JNTHN/Cro-HTTP
all-modules/cpan/JNTHN/Cro-Core
all-modules/github/ugexe/Perl6-Base64
all-modules/github/jnthn/oo-monitors
all-modules/cpan/TIMOTIMO/JSON-Fast
all-modules/github/jnthn/p6-http-hpack
all-modules/cpan/JNTHN/Cro-TLS
all-modules/cpan/JNTHN/IO-Socket-Async-SSL
all-modules/github/sergot/openssl
```

**Comment by lizmat** [comment] 2018-03-27 21:28
Ah, yes… startled by starts  :-)


Shouldn’t:

  sha256-hex await get(‘https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz’).body for ^10

be:

  sha256-hex get(‘https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz’).body for ^10

because get() already does an await?

**Comment by AlexDaniel** [comment] 2018-03-27 21:52
@lizmat no, because .body returns a Promise. :)

**Comment by dogbert17** [comment] 2018-03-29 15:23
Had a hard time reproducing this, I had to make a change in MoarVM in order to make show up consistently:

    dilbert@Linux-Mint18 ~/.rakudobrew/moar-master/nqp/MoarVM $ git diff
    diff --git a/src/gc/collect.h b/src/gc/collect.h
    index 123d934..8281cac 100644
    --- a/src/gc/collect.h
    +++ b/src/gc/collect.h
    @@ -1,6 +1,6 @@
     /* The maximum size of the nursery area. Note that since it's semi-space
      * copying, we could actually have double this amount allocated per thread. */
    -#define MVM_NURSERY_SIZE 4194304
    +#define MVM_NURSERY_SIZE (32768 * 8)
     
     /* The nursery size threads other than the main thread start out with. If
      * they fill it and trigger a GC run, then it is doubled. If they are
    diff --git a/src/gc/debug.h b/src/gc/debug.h
    index 9c613ca..3c99f15 100644
    --- a/src/gc/debug.h
    +++ b/src/gc/debug.h
    @@ -3,7 +3,7 @@
      * 1 = Checks on reference assignments and other relatively cheap cases
      * 2 = Checks on every object register access (slow)
      */
    -#define MVM_GC_DEBUG 0
    +#define MVM_GC_DEBUG 2
     
     #if MVM_GC_DEBUG
     #define MVM_ASSERT_NOT_FROMSPACE(tc, c) do { \

here's what gdb had to say:

    dilbert@Linux-Mint18 ~ $ perl6-gdb-m scratch.pl6
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.03.126.gf.8.c.4416 built on MoarVM version 2018.03.35.gafdcad.4,
    running on linuxmint (18.3.Sylvia) / linux (4.10.0.38.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dilbert/.rakudobrew/moar-master/install/bin/moar...done.
    Starting program: /home/dilbert/.rakudobrew/moar-master/install/bin/moar --execname=/home/dilbert/.rakudobrew/bin/../moar-master/install/bin/perl6-gdb-m --libpath=/home/dilbert/.rakudobrew/moar-master/install/share/nqp/lib --libpath=/home/dilbert/.rakudobrew/moar-master/install/share/perl6/lib --libpath=/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime /home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm scratch.pl6
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff66ae700 (LWP 3654)]
    [New Thread 0x7fffef443700 (LWP 3655)]
    [New Thread 0x7fffeec42700 (LWP 3656)]
    http://docs.perl6.org
    [New Thread 0x7fffee439700 (LWP 3657)]
    https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
    [New Thread 0x7fffedc38700 (LWP 3658)]
    [New Thread 0x7fffecbe4700 (LWP 3659)]
    [New Thread 0x7fffd7fff700 (LWP 3660)]
    [New Thread 0x7fffd77fe700 (LWP 3661)]
    [New Thread 0x7fffd6ffd700 (LWP 3662)]
    [New Thread 0x7fffd67fc700 (LWP 3663)]
    [New Thread 0x7fffd5ffb700 (LWP 3664)]
    http://docs.perl6.org
    http://docs.perl6.org
    [New Thread 0x7fffd57fa700 (LWP 3665)]
    http://docs.perl6.org
    https://rakudo.perl6.org/downloads/rakudo/rakudo-2017.10.tar.gz
    http://docs.perl6.org
    
    Thread 13 "moar" received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffd57fa700 (LWP 3665)]
    0x00007ffff75f8c29 in MVM_gc_mark_collectable (tc=0x604a10, worklist=0x7fffb818cb70, new_addr=0x30dfcf0) at src/gc/collect.c:367
    367	        MVM_gc_worklist_add(tc, worklist, &(tc->instance->all_scs[sc_idx]->sc));
    (gdb) bt
    #0  0x00007ffff75f8c29 in MVM_gc_mark_collectable (tc=0x604a10, worklist=0x7fffb818cb70, new_addr=0x30dfcf0) at src/gc/collect.c:367
    #1  0x00007ffff75f8ae1 in process_worklist (tc=0x604a10, worklist=0x7fffb818cb70, wtp=0x7fffd57f8360, gen=1 '\001') at src/gc/collect.c:341
    #2  0x00007ffff75f802d in MVM_gc_collect (tc=0x604a10, what_to_do=2 '\002', gen=1 '\001') at src/gc/collect.c:66
    #3  0x00007ffff75ef57d in process_in_tray (tc=0x604a10, gen=1 '\001') at src/gc/orchestrate.c:110
    #4  0x00007ffff75ef662 in finish_gc (tc=0x7fffcc1f2e40, gen=1 '\001', is_coordinator=1 '\001') at src/gc/orchestrate.c:141
    #5  0x00007ffff75eff4c in run_gc (tc=0x7fffcc1f2e40, what_to_do=0 '\000') at src/gc/orchestrate.c:411
    #6  0x00007ffff75f0393 in MVM_gc_enter_from_allocator (tc=0x7fffcc1f2e40) at src/gc/orchestrate.c:524
    #7  0x00007ffff75f0a1e in MVM_gc_allocate_nursery (tc=0x7fffcc1f2e40, size=56) at src/gc/allocation.c:32
    #8  0x00007ffff75f0921 in MVM_gc_allocate (tc=0x7fffcc1f2e40, size=56) at src/gc/allocation.h:13
    #9  0x00007ffff75f0a9e in MVM_gc_allocate_zeroed (tc=0x7fffcc1f2e40, size=56) at src/gc/allocation.c:49
    #10 0x00007ffff75f0dc9 in MVM_gc_allocate_object (tc=0x7fffcc1f2e40, st=0x15fb948) at src/gc/allocation.c:86
    #11 0x00007ffff7627f8f in allocate (tc=0x7fffcc1f2e40, st=0x15fb948) at src/6model/reprs/P6opaque.c:60
    #12 0x00007ffff7616053 in MVM_repr_alloc_init (tc=0x7fffcc1f2e40, type=0xce1ee0) at src/6model/reprconv.c:17
    #13 0x00007ffff54cb51a in p6scalarfromdesc () from /home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/dynext/libperl6_ops_moar.so
    #14 0x00007fffec3ac4f5 in ?? ()
    #15 0x00007fffb818ce30 in ?? ()
    #16 0x00007ffff75dc532 in MVM_free (p=0x7fffb818cb20) at src/core/alloc.h:40
    #17 0x00007ffff7716d9e in MVM_jit_enter_code (tc=0x7fffcc1f2e40, cu=0x156eaf0, code=0x7ffff0138b90) at src/jit/compile.c:335
    #18 0x00007ffff75b21b8 in MVM_interp_run (tc=0x7fffcc1f2e40, initial_invoke=0x7ffff75c6fb1 <thread_initial_invoke>, invoke_data=0x7fffcc1e73e0) at src/core/interp.c:5769
    #19 0x00007ffff75c70fa in start_thread (data=0x7fffcc1e73e0) at src/core/threads.c:87
    #20 0x00007ffff6ac26ba in start_thread (arg=0x7fffd57fa700) at pthread_create.c:333
    #21 0x00007ffff70e841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
    (gdb) info threads
      Id   Target Id         Frame 
      1    Thread 0x7ffff7fd9700 (LWP 3650) "moar" 0x00007ffff6aca827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5268ea0)
        at ../sysdeps/unix/sysv/linux/futex-internal.h:205
      2    Thread 0x7ffff66ae700 (LWP 3654) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      3    Thread 0x7fffef443700 (LWP 3655) "moar" 0x00007ffff6aca827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fffe81d0480)
        at ../sysdeps/unix/sysv/linux/futex-internal.h:205
      4    Thread 0x7fffeec42700 (LWP 3656) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      5    Thread 0x7fffee439700 (LWP 3657) "moar" 0x00007ffff6aca827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fffe41e3950)
        at ../sysdeps/unix/sysv/linux/futex-internal.h:205
      6    Thread 0x7fffedc38700 (LWP 3658) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      7    Thread 0x7fffecbe4700 (LWP 3659) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      8    Thread 0x7fffd7fff700 (LWP 3660) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      9    Thread 0x7fffd77fe700 (LWP 3661) "moar" 0x00007ffff6aca827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fffc80d6950)
        at ../sysdeps/unix/sysv/linux/futex-internal.h:205
      10   Thread 0x7fffd6ffd700 (LWP 3662) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      11   Thread 0x7fffd67fc700 (LWP 3663) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
      12   Thread 0x7fffd5ffb700 (LWP 3664) "moar" 0x00007ffff6aca827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fffc400e050)
        at ../sysdeps/unix/sysv/linux/futex-internal.h:205
    * 13   Thread 0x7fffd57fa700 (LWP 3665) "moar" 0x00007ffff75f8c29 in MVM_gc_mark_collectable (tc=0x604a10, worklist=0x7fffb818cb70, new_addr=0x30dfcf0) at src/gc/collect.c:367
    (gdb) l
    362	
    363	    assert(!(new_addr->flags & MVM_CF_FORWARDER_VALID));
    364	    /*assert(REPR(new_addr));*/
    365	    sc_idx = MVM_sc_get_idx_of_sc(new_addr);
    366	    if (sc_idx > 0)
    367	        MVM_gc_worklist_add(tc, worklist, &(tc->instance->all_scs[sc_idx]->sc));
    368	
    369	    if (new_addr->flags & MVM_CF_TYPE_OBJECT) {
    370	        /* Add the STable to the worklist. */
    371	        MVM_gc_worklist_add(tc, worklist, &((MVMObject *)new_addr)->st);
    (gdb) p worklist
    $1 = (MVMGCWorklist *) 0x7fffb818cb70
    (gdb) p sc_idx
    $2 = 51250392
    (gdb) p MVM_dump_backtrace(tc)
       at SETTING::src/core/Semaphore.pm6:6  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:acquire)
     from SETTING::src/core/Awaiter.pm6:23  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/Awaiter.pm6:10  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:await)
     from SETTING::src/core/asyncops.pm6:33  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:await)
     from SETTING::src/core/asyncops.pm6:16  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:await)
     from SETTING::src/core/asyncops.pm6:54  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:)
     from SETTING::src/core/Any-iterable-methods.pm6:423  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:push-all)
     from SETTING::src/core/List.pm6:146  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:reify-all)
     from SETTING::src/core/List.pm6:896  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:eager)
     from SETTING::src/core/Sequence.pm6:71  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:eager)
     from SETTING::src/core/Any.pm6:59  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:eager)
     from SETTING::src/core/asyncops.pm6:54  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:await)
     from SETTING::src/core/asyncops.pm6:16  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:await)
     from scratch.pl6:9  (<ephemeral file>:<unit>)
     from scratch.pl6:1  (<ephemeral file>:<unit-outer>)
     from gen/moar/stage2/NQPHLL.nqp:1585  (/home/dilbert/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:1822  (/home/dilbert/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:1714  (/home/dilbert/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from src/Perl6/Compiler.nqp:42  (/home/dilbert/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:1673  (/home/dilbert/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/main.nqp:47  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:MAIN)
     from gen/moar/main.nqp:38  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<mainline>)
     from <unknown>:1  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<main>)
     from <unknown>:1  (/home/dilbert/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<entry>)
    $3 = void
    (gdb)

**Comment by jnthn** [comment] 2018-03-29 15:40
I can reproduce it also.

**Comment by jnthn** [comment] 2018-03-30 12:39
After some hours debugging, tracked it down to a long-standing bit of missing GC marking. Fixed in https://github.com/MoarVM/MoarVM/commit/ce38e35f27 (and an earlier commit also enhanced GC debugging support to be able to find similar mistakes like this more rapidly in the future).

**Comment by AlexDaniel** [comment] 2018-03-30 18:01
Wow @jnthn, thank you very much!

This resolved these whateverable issues:
* https://github.com/perl6/whateverable/issues/24#issuecomment-345484511
* https://github.com/perl6/whateverable/issues/24#issuecomment-347633560
* https://github.com/perl6/whateverable/issues/24#issuecomment-365359614
* https://github.com/perl6/whateverable/issues/24#issuecomment-376341612

As well as these two unmanageable rakudo tickets:
* https://github.com/rakudo/rakudo/issues/1259
* https://github.com/rakudo/rakudo/issues/1278

**Comment by AlexDaniel** [comment] 2018-03-30 18:05
But we still need tests I think. Any thoughts on how this can be done?

**Comment by jnthn** [comment] 2018-03-30 19:20
The bug could show up in some cases when a closure was lazily deserialized, but it almost certainly would have needed a separate closure with the same outer to have been deserialized long enough ago for a full (gen2) GC run to take place between the two, which means there needs to be a decent bit of memory use between them and the memory must stay allocated (since if it doesn't we never reach needing a gen2 collect). And I'm not entirely sure there isn't a third ingredient somehow involved.

**Closed** 2024-10-03 09:30 UTC
Labels: tests needed, SEGV, exotictest
