### ISSUE TITLE
Some variables set on sub MAIN have no value outside of it

### ISSUE THREAD

**Issue by getimiskon** [rakudo/rakudo#4731] opened 2022-01-22 16:52 UTC
## The Problem
A value set on `sub MAIN` which was declared outside of `sub MAIN` doesn't work outside of `sub MAIN`, while another doesn't seem to have that issue.
For example, in a script I'm working on, there's this line of code:
```sub MAIN ($mode = 'viewer', $resolution = 720)```
While the `$mode` variable works normally in another subroutine, `$resolution` doesn't.
## Expected Behavior
The output should be like this:
```
YouTube CLI Viewer - Raku version
DEBUG: Arguments: (no arguments)
DEBUG: Resolution: 720p
DEBUG: Mode: viewer
Paste the video link: foo.bar
DEBUG: Resolution: 720p
```
## Actual Behavior
```
YouTube CLI Viewer - Raku version
DEBUG: Arguments: (no arguments)
DEBUG: Resolution: 720p
DEBUG: Mode: viewer
Paste the video link: foo.bar
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in sub playVideo at ./youtube-script.raku line 15
DEBUG: Resolution: p
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in sub playVideo at ./youtube-script.raku line 17
```
## Steps to Reproduce
The issue can be reproduced by running that script.

```YouTube CLI Viewer - Raku version
DEBUG: Arguments: (no arguments)
DEBUG: Resolution: 720p
DEBUG: Mode: viewer
Paste the video link: foo.bar
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in sub playVideo at youtube-script.raku line 15
DEBUG: Resolution: p
Use of uninitialized value element of type Any in string context.
Methods .^name, .raku, .gist, or .say can be used to stringify it to something meaningful.
  in sub playVideo at youtube-script.raku line 17
[file] Cannot open file 'foo.bar': No such file or directory 
Failed to open foo.bar.

Exiting... (Errors when loading file)
The spawned command 'mpv 'foo.bar' --ytdl-format='bestvideo[height<=]+bestaudio/best'' exited unsuccessfully (exit code: 2, signal: 0)
   at SETTING::src/core.c/Exception.pm6:62  (/usr/lib/raku/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/Proc.pm6:239  (/usr/lib/raku/runtime/CORE.c.setting.moarvm:sink)
 from SETTING::src/core.c/Main.pm6:406  (/usr/lib/raku/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Main.pm6:402  (/usr/lib/raku/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Main.pm6:401  (/usr/lib/raku/runtime/CORE.c.setting.moarvm:RUN-MAIN)
 from youtube-script.raku:5  (<ephemeral file>:<unit>)
 from youtube-script.raku:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1949  (/usr/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2154  (/usr/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2114  (/usr/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:111  (/usr/lib/raku/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2039  (/usr/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/usr/lib/raku/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/usr/lib/raku/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/usr/lib/raku/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/usr/lib/raku/runtime/perl6.moarvm:<entry>)
```

## Environment
* Operating system: Void Linux x86_64 (kernel version:  5.15.9_1)
* Compiler version: 
```
Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.12.
```

**Comment by lizmat** [comment] 2022-01-22 17:43
It is unclear to me what the code is that shows the problem.  Without the code, we can not look at what the problem is.

**Comment by MasterDuke17** [comment] 2022-01-22 18:20
https://gist.github.com/Whateverable/f7bc96df4100834c741b3b3f0350cce2 has a link to a gist

**Comment by Leont** [comment] 2022-01-26 23:09
> It is unclear to me what the code is that shows the problem. Without the code, we can not look at what the problem is.

Same. The arguments to MAIN are different variables than the same-named ones in the outer scope. AFAICT it's all working as it should.

**Comment by lizmat** [comment] 2022-01-26 23:14
Closing as it appears to work as intended.  Please re-open with an example of the code showing the problem if you disagree.

**Closed by lizmat** 2022-01-26 23:14 UTC
