### ISSUE TITLE
Raku loads Perl modules first when Raku modules have the same base name

### ISSUE THREAD

**Issue by tbrowder** [rakudo/rakudo#3783] opened 2020-07-09 18:08 UTC
## The Problem

Given two modules in the same directory with the same base name:

1. `MyMod.pm`   - a Perl module:
~~~
$ cat MyMod.pm
package MyMod;
our $debug = 1;
1;
~~~

2. `MyMod.rakumod` - an equivalent Raku module:
~~~
$ cat MyMod.rakumod
unit module MyMod;
our $debug is export = 1;
~~~

## Expected Behavior

Raku should find and load the Raku module:

~~~
$ raku -I. -MMyMod -e 'say $MyMod::debug'
1
~~~

## Actual Behavior

As confirmed by @lizmat:

~~~
$ raku -I. -MMyMod -e 'say $MyMod::debug'
This appears to be Perl code. If you intended it to be Raku code, please use a Raku style declaration like "unit package Foo;" or "unit module Foo;", or use the block form instead of the semicolon form.
at /home/tbrowde/tmp/MyMod.pm (MyMod):1
------> package MyMod;⏏<EOL>

at -e:1
~~~

## Environment

* Operating system: Debian 10 (Buster) 
* Compiler version (`perl6 -v` or `raku -v`):

This is Rakudo version 2020.06 built on MoarVM version 2020.06
implementing Raku 6.d.

**Comment by lizmat** [comment] 2020-07-09 18:21
Turns out the problem is here: https://github.com/rakudo/rakudo/blob/master/src/core.c/CompUnit/Repository/FileSystem.pm6#L250

Multiple keys for a module, the last one wins.  We need to be smarter there  :-)

**Comment by ugexe** [comment] 2020-07-09 19:13
The simplest solution would be to sort the list of files.

**Comment by lizmat** [comment] 2020-07-09 20:01
Indeed.  But am working on a slightly different approach atm.

**Comment by ugexe** [comment] 2020-07-09 20:14
Ok, but note I’d prefer if any optimizations are left considered as premature unless they are justified.

**Comment by lizmat** [comment] 2020-07-09 21:25
Understood.  I've abstracted the inlined logic of `!distribution` into another private method `!dist-from-ls` and used more for loops rather than Inlining with `.Slip`.  I hope you'll find the result more readable.

**Comment by lizmat** [comment] 2020-07-09 21:30
Fixed with https://github.com/rakudo/rakudo/commit/f3b1c8dfd7

**Comment by melezhik** [comment] 2020-11-17 19:57
I've added rkp test - http://rakudist.raku.org/sparky/report/RakuPlay-1/1219 if it helps ...

**Comment by melezhik** [comment] 2021-06-25 20:41
I've tested this is r3 - https://gist.github.com/melezhik/3e691e202ff9843a0c563bf10c03829d

**Closed** 2024-05-27 22:13 UTC
Labels: tests needed
