### ISSUE TITLE
Simple literal-only regex fails

### ISSUE THREAD

**Issue by GrayJoKing** [rakudo/rakudo#5550] opened 2024-04-11 13:46 UTC
## The Problem

This code:

```
say ("_20__32022320" ~~ m/2022320/).so
```

outputs `False`. A quick visual inspection shows that the numbers in the regex appear at the end of the string, so it should definitely match.

### Expected Behaviour

This should act identical to the same code with `m:P5/2022320/` or even `/.022320/` which both output `True`.

## Steps to Reproduce
`raku -e 'say ("_20__32022320" ~~ m/2022320/).so'`

## Environment
* Operating system: Fedora
* Compiler version (`rakudo -v` or `raku -v`): 2023.05.

### Comments
This bug is also present on my old version of 2018.12, so it's been here for a while. This is actually the most minimal example I could find. The numbers don't actually matter (applying `tr/023/abc/` keeps the bug). The `_` represents places that can be any characters, and you can add anything at the end and/or start and preserve the bug. My suspicion is that the the section`20__320` is somehow creating a fake match that makes the second true match fail.

**Comment by niner** [comment] 2024-04-12 20:21
I did not anticipate this, but habit made me try:
```
nine@sphinx:~/rakudo (main >)> ./rakudo-m -e 'say ("_20__32022320" ~~ m/2022320/).so'
False
nine@sphinx:~/rakudo (main >)> RAKUDO_RAKUAST=1 ./rakudo-m -e 'say ("_20__32022320" ~~ m/2022320/).so'
True
```

**Comment by jonathanstowe** [comment] 2024-04-13 08:27
FWIW, it's the leading '_' in the LHS that seems to trigger this:

```
jonathan@menenius:~/working/NAP/hesabu$ raku -e 'my $a = "20__32022320"; say ($a ~~ m/2022320/).so'
True
jonathan@menenius:~/working/NAP/hesabu$ raku -e 'my $a = "_20__32022320"; say ($a ~~ m/2022320/).so'
False
```

**Comment by lizmat** [comment] 2024-04-13 09:25
I golfed this to: `say "Xabddcabaacab" ~~ m/abaacab/`

Observations:
- it's got nothing to do with the characters itself, just with the pattern apparently
- works ok in RakuAST (@niner++)
- works ok in the REPL (with or without RakuAST)
- does *not* work in `-e` or in code
- adding any characters before or after the haystack, doesn't make it match
- replacing the first character by any other character, doesn't make it match
- removing a character from start or end of needle, makes it match

**Comment by jnthn** [comment] 2024-04-13 12:37
Any different from disabling the static optimizer? I believe it does some regex rewrites that could be guilty.

**Comment by lizmat** [comment] 2024-04-13 12:40
```
% raku --optimize=0 -e 'say "Xabddcabaacab" ~~ m/abaacab/'
False
```

**Comment by ab5tract** [comment] 2024-04-15 13:14
@librasteve++ and @dr.shuppet++ raised this to my attention and I thought it should be documented here:

```
> ./nqp -e 'say("Xabddcabaacab" ~~ /abaacab/)'
abaacab
```

**Comment by ab5tract** [comment] 2024-04-15 13:38
This snippet probably explains the difference in behavior between `-e`/code files and the REPL:

```
> raku -e 'say qq| "Xabddcabaacab" ~~ /abaacab/;\n|.EVAL'
abaacab
```

**Comment by ab5tract** [comment] 2024-04-15 15:36
A (very) preliminary fix has been found but it will take a moment to concretize it into an appropriate solution.

Essentially it boils down to the difference between:

```
# QAST from RakuAST:
    │   │   │   - QAST::Regex(:rxtype(concat) :subtype()) <wanted>
    │   │   │     - QAST::Regex(:rxtype(scan) :subtype())
    │   │   │       - abaacab
    │   │   │     - QAST::Regex(:rxtype(concat) :subtype())  abaacab
    │   │   │       - QAST::Regex(:rxtype(literal) :subtype())  a
    │   │   │         - abaacab
    │   │   │     - QAST::Regex(:rxtype(pass) :subtype())
```

and:

```
# QAST from RakuAST:
    │     │ - QAST::Regex(:rxtype(concat) :subtype())
    │     │   - QAST::Regex(:rxtype(scan) :subtype())
    │     │   - QAST::Regex(:rxtype(concat) :subtype())
    │     │     - QAST::Regex(:rxtype(literal) :subtype())
    │     │       - abaacab
    │     │   - QAST::Regex(:rxtype(pass) :subtype())
```

The investigation into root causes will continue but this is a promising development.

**Comment by lenticularis39** [comment] 2024-04-15 18:04
Not sure what the source of the bug is, but the behavior is definitely amusing (for me at least, maybe not so much for you Rakudo developers). Without an EOL, `EVAL` does not work in `-e` (but does in REPL):
```bash
$ raku --version
Welcome to Rakudo™ v2024.03.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.03.
$ raku -e 'say qq| "Xabddcabaacab" ~~ /abaacab/;\n |.EVAL'
｢abaacab｣
$ raku -e 'say qq| "Xabddcabaacab" ~~ /abaacab/|.EVAL'
Nil
$ raku
[0] > qq| "Xabddcabaacab" ~~ /abaacab/|.EVAL
｢abaacab｣
```

Also, why does it matter whether single or double quotes are used _for the first occurence_ of the EVALed string (that is not even executed)?

```bash
$ raku test1.raku
｢abaacab｣
$ raku test2.raku
Nil
$ raku test3.raku
Nil
```

Code:

```perl
# test1.raku
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = "\"Xabddcabaacab\" ~~ \$regex";
}
say '"Xabddcabaacab" ~~ $regex'.EVAL;

# test2.raku
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = '"Xabddcabaacab" ~~ $regex';
}
say '"Xabddcabaacab" ~~ $regex'.EVAL;

# test3.raku
my $regex = /abaacab/;
say '"Xabddcabaacab" ~~ $regex'.EVAL;
```

**Comment by ab5tract** [comment] 2024-04-15 22:05
Interesting data points @lenticularis39, thanks for deriving these and sharing here.

Just to add some another confusion to the mix, using `qq` instead of escaped double quotes reverts the first example to the failure baseline.

```
# test1a.raku
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = qq| "Xabddcabaacab" ~~ \$regex |;
}
say '"Xabddcabaacab" ~~ $regex'.EVAL;
```

```
> raku test1a.raku
Nil
```

**Comment by lizmat** [comment] 2024-04-15 22:24
That's a different failure mode?  `Nil` vs `False` ?

**Comment by lenticularis39** [comment] 2024-04-16 06:03
@ab5tract Actually, qq behaves the same as escaped double quotes. The double-quoted string has to be equal to the single-quoted one (yours has added spaces at the beginning and end):
```perl
# test1b.raku
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = qq|"Xabddcabaacab" ~~ \$regex|;
}
say '"Xabddcabaacab" ~~ $regex'.EVAL;
# test1c.raku
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = " \"Xabddcabaacab\" ~~ \$regex ";
}
say '"Xabddcabaacab" ~~ $regex'.EVAL;
```

```
$ raku test1b.raku
｢abaacab｣
$ raku test1c.raku
Nil
```

**Comment by lenticularis39** [comment] 2024-04-16 06:05
> That's a different failure mode? `Nil` vs `False` ?

No, it's because the original example uses `.so` on the result, my examples don't.

**Comment by ab5tract** [comment] 2024-04-16 10:36
> That's a different failure mode?  `Nil` vs `False` ?

The match result versus Nil.

**Comment by ab5tract** [comment] 2024-04-16 10:40
@lenticularis39 Good catch. That's both reassuring and disturbing at the same time.

**Comment by lenticularis39** [comment] 2024-04-16 11:30
It's quite clear that the compiler only creates one string literal constant and re-uses it for the second use, that is expected (it happens even with `--optimize=0`, but I'd say it's a simple enough optimization to be always applied). There is "only" a bug in creating the constant. To illustrate this further, this code:
```perl
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = '"Xabddcabaacab" ~~ $regex';
}
say "\"Xabddcabaacab\" ~~ \$regex".EVAL;
```
(single quotes first, double quotes next) also does not work:
```
$ raku test2a.raku 
Nil
```
The QAST dumped by `--target=ast` is the same, except for the quotes, so I expect there to be some weird quirk not displayed when dumping the AST or entirely outside the AST.

Given that, I'm not entirely sure if investigating these examples with `EVAL` is the way to search for the cause, since the original issue also appears without `EVAL`. I feel like the weird eval behavior might not even be a bug per se, just some compile-time vs run-time quirk.

**Comment by ab5tract** [comment] 2024-04-19 22:44
I've locally confirmed that [this commit (e71ba738)](https://github.com/MoarVM/MoarVM/commit/e71ba7381506b2b39db9e376a8ee0f4e4e121602) from 2018 in MoarVM is responsible for the behavior.

Quoting the commit message:

> The only caveat is the table uses a modulus so it can only jump to the next
codepoint of the same modulus. So it can only jump forward to the next
codepoint of the same modulus.

This seems to explain the extreme pattern-ality of the bug.

As mentioned previously, it triggers for `rakudo-m` but not for `nqp-m` even though both go through [this line](https://github.com/Raku/nqp/blob/ec940c08c0d9437f248e281bc98c5727a8a5f03c/src/vm/moar/QAST/QASTRegexCompilerMAST.nqp#L1141) in `QASTRegexCompilerMAST.nqp` (too bored; didn't click: it's a call to MAST op `index_s`). Why? It seems almost certain that we aren't using the `MVM_string_memmem_grapheme32` function for `BOOTStr`, but I haven't nailed down the precise divergence point yet.

I don't want to simply revert `e71ba738` from MoarVM without further discussion because the commit message indicates a 4-15x speedup. It's worth noting that the only search results that return when I query for `memmem32` all seem to be MoarVM-related. Regarding generic `memmem`, it seems that FreeBSD (from which our `memmem32` is borrowed) has replaced their `memmem` implementation with one provided by `musl`.

**Comment by ab5tract** [comment] 2024-04-20 15:36
The reason why `nqp-m` is unaffected here is that its strings are stored, at least in this case, as `MVM_STRING_GRAPHEME_8`. Thus they never hit the `memmem_uint32` codepath. This was obvious enough, but now I've confirmed:

```
    frame #0: 0x0000000100dfa964 libmoar.dylib`MVM_string_index(tc=0x0000020000020180, Haystack=0x000002000102c4e0, needle=0x000002000102c660, start=1) at ops.c:592:13
   589 	    /* Fast paths when storage types are identical. Uses memmem function, which
   590 	     * uses Knuth-Morris-Pratt algorithm on Linux and on others
   591 	     * Crochemore+Perrin two-way string matching */
-> 592 	    switch (Haystack->body.storage_type) {
   593 	        case MVM_STRING_GRAPHEME_32:
   594 	            if (needle->body.storage_type == MVM_STRING_GRAPHEME_32 || n_graphs < 100) {
   595 	                return MVM_string_memmem_grapheme32str(tc, Haystack, needle, start, H_graphs, n_graphs);
Target 0: (nqp-m) stopped.
(lldb) n
Process 84545 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step over
    frame #0: 0x0000000100dfa9e8 libmoar.dylib`MVM_string_index(tc=0x0000020000020180, Haystack=0x000002000102c4e0, needle=0x000002000102c660, start=1) at ops.c:599:17
   596 	            }
   597 	            break;
   598 	        case MVM_STRING_GRAPHEME_8:
-> 599 	            if (needle->body.storage_type == MVM_STRING_GRAPHEME_8 || n_graphs < 100) {
   600 	                void         *mm_return_8 = NULL;
   601 	                MVMGrapheme8 *needle_buf  = NULL;
   602 	                if (needle->body.storage_type != MVM_STRING_GRAPHEME_8) {
Target 0: (nqp-m) stopped.
```

**Comment by ab5tract** [comment] 2024-04-21 16:50
Closed as of f56a39731cc15f0fd86712a9823707d5cbccb914

**Closed** 2024-04-21 16:51 UTC
Labels: Fixed in RakuAST

**Comment by ab5tract** [comment] 2024-04-21 19:42
The behavior with `EVAL` is also related to whether or not the string is stored as `MVM_STRING_GRAPHEME_32` or `MVM_STRING_GRAPHEME_8`. The examples that worked before all store the haystack as `MVM_STRING_GRAPHEME_8`. 

Not sure exactly why the presence of `"\n"` changes the storage type of the haystack to `MVM_STRING_GRAPHEME_8`. Likewise the double-quoting (but only without any whitespaces?).

**Comment by lizmat** [comment] 2024-04-22 08:46
`"\n"` is a synthetic in Raku land, to abstract the different line endings `"\r\n"`, `"\r"` and `"\n"` into a single logical line ending.   So that definitely explains the storage type change!

**Comment by lenticularis39** [comment] 2024-04-22 12:42
@ab5tract It's not the double-quoting itself, but rather the fact escape is used for `$` in the double-quoted string. Double-quoted string without escape does not trigger the different behavior:
```perl
# test1b.raku (same as above)
my $regex = /abaacab/;
sub do-nothing {
  my $random-thing = qq|"Xabddcabaacab" ~~ \$regex|;
}
say '"Xabddcabaacab" ~~ $regex'.EVAL;
# test1d.raku (same as test1b.raku, but regex without $ sigil)
my \regex = /abaacab/;
sub do-nothing {
  my $random-thing = qq|"Xabddcabaacab" ~~ regex|;
}
say '"Xabddcabaacab" ~~ regex'.EVAL;
```
```bash
$ raku test1d.raku
Nil
$ raku test1b.raku
｢abaacab｣
```

**Comment by ab5tract** [comment] 2024-04-28 16:54
@lenticularis39 I'm not clear on which is the "different" behavior here, but:

The correct response is produced when the $ is escaped in double quotes. This means that 8-bit strings are being used.

But clearly it is not simply escaping of $ that causes 8-bit strings. Otherwise the examples with spaces on both sides of the expression would have worked as well.
