### ISSUE TITLE
“MVMHash representation requires MVMString keys” rescalar regression

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2056] opened 2018-07-12 15:39 UTC
- [x] I don't have a golf of the issue, but it should be easily golfable. See https://github.com/MARTIMM/unicode-precis (it's a module without deps).

Bisected: (2018-07-09) https://github.com/rakudo/rakudo/commit/d3c5381b747169f951db578bebbfd0c5d8165116

Running this:
```bash
PERL6LIB=lib/ perl6 t/100-precis.t
```
This is the result:
```
===SORRY!===
MVMHash representation requires MVMString keys
```

With `--ll-exception`:
```
MVMHash representation requires MVMString keys
   at gen/moar/stage2/QAST.nqp:6755  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/QAST.moarvm:assemble_to_file)
 from gen/moar/stage2/NQPHLL.nqp:443  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:mbc)
 from gen/moar/stage2/NQPHLL.nqp:1825  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1861  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1864  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1850  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1548  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1805  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1728  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1654  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<entry>)

   at SETTING::src/core/Exception.pm6:57  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:throw)
 from SETTING::src/core/control.pm6:178  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:die)
 from SETTING::src/core/control.pm6:166  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:die)
 from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:293  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:precompile)
 from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:210  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:precompile)
 from SETTING::src/core/CompUnit/PrecompilationRepository.pm6:46  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:try-load)
 from SETTING::src/core/CompUnit/Repository/FileSystem.pm6:135  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/CompUnit/Repository/FileSystem.pm6:128  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/CORE.setting.moarvm:need)
 from src/Perl6/World.nqp:1274  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/World.moarvm:load_module)
 from src/Perl6/World.nqp:1202  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/World.moarvm:do_pragma_or_load_module)
 from gen/moar/Perl6-Grammar.nqp:1741  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:statement_control:sym<use>)
 from gen/moar/stage2/QRegex.nqp:1696  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:statement_control)
 from gen/moar/Perl6-Grammar.nqp:1389  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Perl6-Grammar.nqp:1317  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1107  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Perl6-Grammar.nqp:1764  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Perl6-Grammar.nqp:1281  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Perl6-Grammar.nqp:552  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2303  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1912  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1828  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1861  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1864  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1850  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1548  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1805  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1728  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1654  (/home/alex/.rakudobrew/moar-master/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/alex/.rakudobrew/moar-master/install/share/perl6/runtime/perl6.moarvm:<entry>)
```

**Comment by AlexDaniel** [comment] 2018-07-12 16:41
Found another module failing with the same bisect result. See https://github.com/IanTayler/MinG.

Fails with something like this:
```
Tried to get the result of a broken Promise
  in method parallel_run at /home/alex/git/MinG/lib/MinG/S13.pm6 (MinG::S13) line 386
  in method parallel_parse at /home/alex/git/MinG/lib/MinG/S13.pm6 (MinG::S13) line 425
  in method parse_str at /home/alex/git/MinG/lib/MinG/S13.pm6 (MinG::S13) line 496
  in method large_parse at /home/alex/git/MinG/lib/MinG/S13.pm6 (MinG::S13) line 534
  in block <unit> at t/basic.t line 70

Original exception:
    Cannot invoke this object (REPR: Null; VMNull)
      in block  at /home/alex/git/MinG/lib/MinG/S13/Logic.pm6 (MinG::S13::Logic) line 18
      in method children_with_property at /home/alex/git/MinG/lib/MinG.pm6 (MinG) line 160
      in method exps at /home/alex/git/MinG/lib/MinG/S13.pm6 (MinG::S13) line 213
      in block  at /home/alex/git/MinG/lib/MinG/S13.pm6 (MinG::S13) line 382
```

**Comment by AlexDaniel** [comment] 2018-07-13 10:10
Another module is [Spit](https://github.com/spitsh/spitsh). Output before and after: https://gist.github.com/da52e7372c313ceae57b6d0589a64afa

**Comment by jnthn** [comment] 2018-07-16 10:35
The fix in https://github.com/MoarVM/MoarVM/commit/b7c6afd929 deals with the "MVMHash representation requires MVMString keys" error. The behavior change that led to so many strings is that instead of doing some C cheating, we now `nqp::bindattr` into `Scalar`, and that makes it eligible for serialization context repossession. That is the mechanism by which `augment` works.

Given the different failure modes of the other two tests, I don't think that the MoarVM fix I just did will address them. It is, however, possible that they have changed behavior for the same underlying reason.

**Comment by jnthn** [comment] 2018-07-16 10:59
I put in a hack to never do the repossession on a `Scalar` and that didn't fix either of the other two. So the good new is that it's not due to that problem. The bad news is that it must therefore we due to some other as yet unknown problem.

**Comment by jnthn** [comment] 2018-07-16 11:02
Ah, correction. The `Scalar` repossession issue *is* the cause of the MinG regression, but not the Spit one.

**Comment by jnthn** [comment] 2018-07-16 14:04
The Spit one is fixed by 38d046fafb. A case where the new Scalar assignment code lacks a bug the previous one had, but thankfully there's a way to make fix a second bug and get it happy and passing all its tests again. So that's 2 out of 3.

**Comment by jnthn** [comment] 2018-07-16 15:08
NQP commit https://github.com/perl6/nqp/commit/1ca664ac66 deals with the MinG regression.

Verification of all of these would be very welcome.

**Comment by AlexDaniel** [comment] 2018-07-18 17:32
Looks good here!

**Comment by lizmat** [comment] 2024-10-04 18:25
closing as untestable

**Closed by lizmat** 2024-10-04 18:25 UTC
Labels: tests needed, regression, MoarVM
