### ISSUE TITLE
Enum (cont) space returns false even if it contains a space

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2604] opened 2019-01-12 19:05 UTC
## The Problem
See title.

## Expected Behavior
`enum ∋ ' '` should return `True`.

## Actual Behavior
It returns `False`.

## Steps to Reproduce

```
enum Foo «' '»;
say Foo.enums ∋ ' ';
```

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.4 GENERIC.MP#364 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.12-158-gf39be10ce built on MoarVM version 2018.12-13-g473324ee3
implementing Perl 6.d.

**Comment by lizmat** [comment] 2019-01-12 21:33
This problem is not just for homemade `enum`s or special enums like with a space.  It's for all `enum`s with a False value:

    dd Endian.enums; # Map.new((:BigEndian(2),:LittleEndian(1),:NativeEndian(0)))
    say Endian.enums (cont) NativeEndian;  # False

    enum Foo (a => "foo", b => "");
    dd Foo.enums;  # Map.new((:a("foo"),:b("")))
    say Foo.enums (cont) "a";  # True
    say Foo.enums (cont) "b";  # False

**Comment by lizmat** [comment] 2019-01-12 21:36
Actually, this has nothing to do with `enum`s:

    my %h = a => 0, b => 1;
    say "a" (elem) %h;   # False
    say "b" (elem) %h;   # True

**Comment by lizmat** [comment] 2019-01-12 21:41
And from there: this is actually not a bug, but a result of `Set` semantics: `elem` and friends apply them to their parameters.  So if you say:

    say Endian.enums (cont) NativeEndian;  # False

You are actually saying:

    say Endian.enums.Set (cont) NativeEndian;  # False

Which makes sense if you see:

    dd Endian.enums.Set; # Set.new("LittleEndian","BigEndian")

So maybe we need to document this gotcha.

**Comment by lizmat** [comment] 2019-01-13 10:05
An alternate way to check if something is in an enum, is to use `:exists`:

    enum Foo <a b c>;
    say Foo.enums<a>;              # 0
    say Foo.enums<a>:exists;   # True

**Comment by lizmat** [comment] 2019-01-13 18:35
Trap documented with https://github.com/perl6/doc/commit/ca3067e5e7 , closing now

**Closed** 2019-01-13 18:34 UTC
