### ISSUE TITLE
Raku architecture document is obsolete

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#4281] opened 2021-03-31 10:40 UTC
It even says so in the header. Shouldn't it be deleted directly? Or moved to another "archived-and-forgotten" repository...

https://github.com/rakudo/rakudo/blob/09d27c32165d939544d4030844c9477c3affdb00/docs/architecture.html#L3

(Also: might be a good idea to update it)

**Comment by lizmat** [comment] 2021-03-31 10:46
Some parts may be salvageable, that's why I didn't delete it when I added the OBSOLETE header :-)

**Comment by Altai-man** [comment] 2021-03-31 13:01
Maybe it's a good idea to just update it with fresh info rather than removing?

**Comment by MasterDuke17** [comment] 2021-04-01 08:27
https://github.com/rakudo/rakudo/blob/master/docs/compiler_overview.pod is also pretty outdated.

**Comment by lizmat** [comment] 2024-10-16 11:52
Dupe of #4245

**Closed by lizmat** 2024-10-16 11:52 UTC
Labels: docs
