### ISSUE TITLE
Decont operator is slow

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#3327] opened 2019-11-27 21:20 UTC
## The Problem

The Raku decont operator `<>` is mapped to `postcircumfix:<{ }>` which spends more than 70% of its time in `Bool`. This makes it slow.

## Expected Behavior

The decont operator `<>` should be almost as fast as `nqp::decont`.

## Actual Behavior

A non-trivial routine using a single `<>` is almost 40% slower than the same routine using `nqp::decont`.

## Environment
* Operating system: Windows 10
* Compiler version (`perl6 -v`):
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

**Comment by lizmat** [comment] 2019-11-27 22:10
The slowdown is caused by a `%hash.Bool` to check for named parameters.  Looking at making that faster now.

**Comment by lizmat** [comment] 2019-11-27 22:22
Fixed with https://github.com/rakudo/rakudo/commit/872cb7c002 .  Thanks for the headsup!

**Closed by lizmat** 2019-11-27 22:22 UTC
