### ISSUE TITLE
NativeCall JIT Bug exposed by DBIish (PostgreSQL driver)

### ISSUE THREAD

**Issue by rbt** [rakudo/rakudo#4828] opened 2022-03-23 17:56 UTC
Around the 340th record being decoded, the driver throws this error. The value being decoded has no impact on the result.

The error occurs on Linux with both moar-2022.02 and moar-2022.03 installed via rakubrew downloads. Works fine on moar-2021.12.

```
Native call expected argument 1 to reference a native integer, but got CPointer
  in sub str-to-blob at /home/rbt/work/DBIish/lib/DBDish/Pg/Native.pm6 (DBDish::Pg::Native) line 23
  in sub  at /home/rbt/work/DBIish/lib/DBDish.pm6 (DBDish) line 54
  in block  at /home/rbt/work/DBIish/lib/DBDish/Pg/StatementHandle.pm6 (DBDish::Pg::StatementHandle) line 133
  in method _row at /home/rbt/work/DBIish/lib/DBDish/Pg/StatementHandle.pm6 (DBDish::Pg::StatementHandle) line 128
  in method row at /home/rbt/work/DBIish/lib/DBDish/StatementHandle.pm6 (DBDish::StatementHandle) line 93
  in block  at /home/rbt/work/DBIish/lib/DBDish/StatementHandle.pm6 (DBDish::StatementHandle) line 132
  in block <unit> at /tmp/test.raku line 12
```

Line 23 of Native.pm6 looks like this. $elems is expected to contain the number of bytes decoded, and works as expected for the first few hundred calls.
```
    my \ptr = PQunescapeBytea($value, my size_t $elems);
```

Test file to reproduce the error.

```
use v6;
use DBIish;

my %con-parms;
# If env var set, no parameter needed.
%con-parms<database> = 'test' unless %*ENV<PGDATABASE>;
%con-parms<user> = 'test' unless %*ENV<PGUSER>;

my $dbh = DBIish.connect('Pg', |%con-parms);

my @rows = $dbh.execute(q{select ''::bytea from (SELECT * from generate_series(1, 2000)) as series(c)}).allrows;
say @rows.elems;
```

**Comment by rbt** [comment] 2022-03-23 18:03
@niner  I suspect it's related to this change in some way but did not prove it.

https://github.com/rakudo/rakudo/commit/c92833f3501edcb8e0be35a2ddb107fb7e96cf32

**Comment by jnthn** [comment] 2022-03-23 18:15
@rbt Does the bug go away with `MVM_JIT_DISABLE=1` set in the environment? That would pretty much confirm it's JIT-y.

**Comment by demanuel** [comment] 2022-03-23 18:37
@jnthn Nope:

```
$ MVM_JIT_DISABLE=1 raku bug.raku
Native call expected argument 1 to reference a native integer, but got CPointer
  in sub str-to-blob at /home/demanuel/.rakubrew/versions/moar-master/install/share/perl6/site/sources/1B6018506ABC08CD131DD147B02C370C56599B7B (DBDish::Pg::Native) line 20
  in sub  at /home/demanuel/.rakubrew/versions/moar-master/install/share/perl6/site/sources/EE48EDA05EFB5052583EACDA1ED614EFFB395FED (DBDish) line 54
  in block  at /home/demanuel/.rakubrew/versions/moar-master/install/share/perl6/site/sources/722DCB5B6813505E9834D6F0226E6E48F433B21A (DBDish::Pg::StatementHandle) line 133
  in method _row at /home/demanuel/.rakubrew/versions/moar-master/install/share/perl6/site/sources/722DCB5B6813505E9834D6F0226E6E48F433B21A (DBDish::Pg::StatementHandle) line 128
  in method row at /home/demanuel/.rakubrew/versions/moar-master/install/share/perl6/site/sources/300A6A8F69E68E61F3353B05F301E464D8E9234F (DBDish::StatementHandle) line 93
  in block  at /home/demanuel/.rakubrew/versions/moar-master/install/share/perl6/site/sources/300A6A8F69E68E61F3353B05F301E464D8E9234F (DBDish::StatementHandle) line 132
  in block <unit> at bug.raku line 4
```

**Comment by niner** [comment] 2022-03-23 19:22
What about `MVM_SPESH_DISABLE=1`?

**Comment by demanuel** [comment] 2022-03-23 19:41
@niner 

With `MVM_SPESH_DISABLE=1` works as expected:

```
$ MVM_SPESH_DISABLE=1 raku bug.raku
2000
```

**Comment by niner** [comment] 2022-03-26 11:17
This is easily reproducible in t/04-nativecall/15-rw-args.t by adding just this code and running with MVM_SPESH_BLOCKING=1:
```
my size_t $size_t;                                                                                                                                            
for ^10000 {                                                                                                                                                  
    $size_t = 0;
    SetSizeT($size_t);                                                                                                                                        
}
```

The speshed code looks like:
```
      getlexref_u       r4(2), lex(idx=0,outers=1,$size_t)
      [Annotation: Logged (bytecode offset 114)]
      # [009] dispatch not compiled: unsupported NativeCall rw type 40
      # [007] Monomorphic in the inline cache
      sp_dispatch_o     r4(5), lits(lang-call), callsite(0x7f131fafdca0, 2 arg, 2 pos, nonflattening, interned), sslot(82), litui32(12),   r2(7),   r4(2)
      [Annotation: INS Deopt One Before Instruction (idx 8 -> pc 102; line 90)]
      sp_guardobj      r2(13),   r2(7), sslot(77), litui32(8)
      sp_p6oget_o       r5(2),  r2(13), liti16(48)  # [008] emitted from dispatch program attribute load op
      [Annotation: INS Deopt Synth (idx 8)]
      [Annotation: INS Deopt One Before Instruction (idx 143 -> pc 102; line 90)]
      sp_guardobj       r5(3),   r5(2), sslot(78), litui32(143)
      [Annotation: INS Deopt Synth (idx 8)]
      [Annotation: INS Deopt One Before Instruction (idx 144 -> pc 102; line 90)]
      sp_guardconc      r4(6),   r4(2), sslot(79), litui32(144)
```
First, we cannot spesh the call to sp_runnativecall_v, because unsigned rw args are not supported (which is easily fixed and would get around this issue).
The native call actually does not have a return value, but rakudo emits a dispatch_o and NativeCall will set the return value to a type object (Mu). C.f. https://github.com/MoarVM/MoarVM/commit/768228b327d1e37d2135bb44d6cf8e96b2c2e4c3
translate_dispatch_program emits the guard on the argument after the actual call here: https://github.com/MoarVM/MoarVM/blob/master/src/spesh/disp.c#L662
Then we abort translation of the dispatch program here: https://github.com/MoarVM/MoarVM/blob/master/src/spesh/disp.c#L1253
But at this point the guard is already in place (but in the wrong one).

**Comment by niner** [comment] 2022-03-29 16:58
Will be fixed by https://github.com/MoarVM/MoarVM/pull/1695

**Closed** 2022-04-12 18:17 UTC
