### ISSUE TITLE
IO::Handle.lines assumes utf8

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3753] opened 2020-06-12 19:45 UTC
```
react whenever run("/usr/bin/find", "/mnt", :out).out.lines { say $++ }
```
dies with:
```
Died because of the exception:
    Malformed UTF-8 near bytes 47 6c 81
      in block <unit> at -e line 1
```

The bug is triggered by filenames on a btrfs what where written by samba. So this might be more common then it should.

discussion on irc:
21:32 < gfldex> Should Rakudo be able to handle malformed utf-8 that pops out of Proc::Async?
21:36 < MasterDuke> hm. or should the user be required to manually decode/encode before calling .lines?
21:36 < lizmat> perhaps it should default to utf8-c8 ?

**Comment by lizmat** [comment] 2020-06-12 19:54
`IO::Handle.lines` assumes `utf8`, and that is ok.

I guess the issue is really with `Proc` ?

**Comment by jnthn** [comment] 2020-06-12 23:01
The overhead of `utf8-c8` is pretty high (maybe a factor of 2-3 worse decoding performance). We have one case here where the default of `utf8` didn't work out so well, but of course nobody files issues to tell us about the overwhelming majority of times when it works out just fine.

I think `utf8-c8` is a pretty fine default for command line arguments, environment variables, and file names from IO stuff (like `dir`), because it makes things Just Work (with plentiful caveats, but much of the time you're either just passing those on to the file system or to a sub-process), there aren't that many of them, and you decode them once at process start and are done with it. But with processes, throughput of output matters.

I'd rather we place the burden on the handful of cases that need something else to either pass `:bin` or to pass an appropriate encoding, rather than the burden on everyone who wants things to perform decently to opt out of it.

(Also, this is shelling out to `find`, rather than using the built-in `dir`, which would not had had this problem because it does apply `utf8-c8`. I'm also a bit surprised to see a synchronous `run` being used with `react`/whenever`.)

**Comment by lizmat** [comment] 2020-07-04 11:30
So this looks like a case of DIHWIDT, so closing this issue now.  Please re-open if you disagree.

**Closed by lizmat** 2020-07-04 11:30 UTC
