### ISSUE TITLE
Rakudo build log for rakudo JVM misses spaces

### ISSUE THREAD

**Issue by melezhik** [rakudo/rakudo#5195] opened 2023-02-10 02:30 UTC
## The Problem

I am not sure, but probably output from rakudo build misses some spaces ...

## Expected Behavior

```
 => => # +++ Generating gen/jvm/stage1/NQPHLL.nqp                                                             
 => => # +++ Generating gen/jvm/stage1/JASTNodes.nqp                                                          
 => => # +++ Compiling gen/jvm/stage1/JASTNodes.jar                                                           
 => => # +++ Compiling gen/jvm/stage1/NQPHLL.jar 
```

## Actual Behavior

```
 => => # +++ Generatinggen/jvm/stage1/NQPHLL.nqp                                                             
 => => # +++ Generatinggen/jvm/stage1/JASTNodes.nqp                                                          
 => => # +++ Compilinggen/jvm/stage1/JASTNodes.jar                                                           
 => => # +++ Compilinggen/jvm/stage1/NQPHLL.jar 
```

## Steps to Reproduce

```bash
curl -sLf https://rakudo.org/dl/rakudo/rakudo-2022.12.tar.gz -o rakudo-2022.12.tar.gz
tar -xzf rakudo-2022.12.tar.gz && cd rakudo-2022.12 && \
perl Configure.pl --gen-nqp --backends=jvm && make install
```

## Environment

* Operating system:

Alpine OS

* Compiler version (`perl6 -v` or `raku -v`):

2022.12

**Comment by melezhik** [comment] 2023-02-10 02:33
To be 100% accurate I build rakudo from Dockerfile:

```Dockefile
FROM alpine:latest
ENV PATH="/home/worker/.raku/bin:/var/rakudo/rakudo-2022.12/install/bin/:${PATH}"
ENV SP6_DUMP_TASK_CODE=1
ENV SP6_FORMAT_COLOR=1
RUN apk update && apk add openssl bash curl wget perl openssl-dev sudo git
RUN apk add --no-cache bash g++ make
RUN mkdir -p /var/rakudo/ && cd /var/rakudo/ && curl -sLf https://rakudo.org/dl/rakudo/rakudo-2022.12.tar.gz -o rakudo-2022.12.tar.gz
RUN apk add openjdk9 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
RUN cd /var/rakudo/ && tar -xzf rakudo-2022.12.tar.gz && cd rakudo-2022.12 && \
perl Configure.pl --gen-nqp --backends=jvm && make install
```

**Comment by usev6** [comment] 2023-02-10 06:47
If I'm not mistaken the posted output stems from building NQP.

More specifically it seems to be from this echo commands:
* https://github.com/Raku/nqp/blob/d19ece2409/tools/lib/NQP/Config/NQP.pm#L500
* https://github.com/Raku/nqp/blob/d19ece2409/tools/lib/NQP/Config/NQP.pm#L514

Maybe you could experiment with adding some debug output to those lines.

For me it looks like the tab gets somehow lost. Do you maybe process the output of the build tools in some way? (Seeing ```SP6_FORMAT_COLOR``` makes me think in that direction.)

Anyway, I wasn't able to reproduce this with a plain build of NQP ("git clone", "perl Configure.pl --backends=jvm", "make"). Also the output of our CI builds look fine -- e.g. https://dev.azure.com/Rakudo/rakudo/_build/results?buildId=3440&view=logs&j=4b893f53-7e1e-5c61-1e1e-e4fc61ee1c48&t=819ee56f-5718-551c-ab20-4c9fdb52c66b

Btw, do you get this for ```backends=jvm``` only? If I'm not mistaken there is no difference in the format between moar and jvm.

**Comment by vrurg** [comment] 2023-02-10 14:08
> Btw, do you get this for `backends=jvm` only? If I'm not mistaken there is no difference in the format between moar and jvm.

 No, there is no difference. It's a clear case of filtered out tabs.

**Comment by melezhik** [comment] 2023-02-10 14:30
Let me rerun this command directly without Dockerfile, output might be affected by Docker build command. Yes I build for jvm only , have not checked for moar

**Comment by melezhik** [comment] 2023-02-10 16:26
Ok, looks like spaces are eaten by Docker build command, probably not rakudo installer issue?

![docker build log](https://raw.githubusercontent.com/melezhik/images/master/6AE4727C-A567-49A7-B4C2-1748CF274787.jpeg)

**Comment by usev6** [comment] 2023-02-11 08:53
Yes, this is not a problem with Rakudo. I'm closing this issue.

**Closed by usev6** 2023-02-11 08:53 UTC
