### ISSUE TITLE
NativeCall, incorrect values after call into C

### ISSUE THREAD

**Issue by loops** [rakudo/rakudo#2036] opened 2018-07-08 00:59 UTC
## The Problem

Quite often when calling into C and passing a pointer to a "uint32_t" type,
the value is lost and set to 0 upon return to perl6.  This happens if the
C code changes the pointed to value, or leaves it alone.  In either case,
the value is set to 0 once Perl6 resumes executing.

## Expected Behavior

The proper value should be available in Perl6 after calling into C.

## Actual Behavior

The value is cleared to 0.

## Steps to Reproduce

Here's a short script that exhibits the problem:

[tst.txt](https://github.com/rakudo/rakudo/files/2173236/tst.txt)

As noted in the comments, disabling the Jit makes the problem vanish.

## Environment
* Operating system:
     Fedora Linux 
* Compiler version (`perl6 -v`):
     This is Rakudo version 2018.06-82-gb236fae built on MoarVM version 2018.06-34-g411f73f
     implementing Perl 6.c.

**Comment by zoffixznet** [comment] 2018-07-08 03:11
(just copy-pasting the code from the OP's file, in case the file gets lost):

```perl6
#!/bin/env perl6
#  
#  Running the following will die 3 or 4 times out of 5.
#
#   the problem seems to be related to the "is rw" portion of the
#   "tst" spec; $x comes back as 0 from the c call sporadically 
#
#   the problem goes away when MVM_JIT_DISABLE=1 is set in the
#   environment before running the perl6 code
#

use NativeCall;
my sub tst(uint32 is rw) is native( './tst.so') { * };

for ^30_000 {
  my uint32 $x = 1;
  tst($x);
  die "$_ $x" if $x != 1;
}

# Compile tst.c with :    gcc -fPIC -shared -o tst.so tst.c
# tst.c contains :
#     #include <stdint.h>
#     void tst(uint32_t *x) { }
#
```

**Comment by loops** [comment] 2018-07-08 11:59
lizmat,

The NativeCall docs ( https://docs.perl6.org/language/nativecall#Passing_and_Returning_Values )
say:

Note that the lack of a returns trait is used to indicate void return type. Do not use the void type anywhere except in the Pointer parameterization.

But just to be sure I created a new test case with a function that returns a value.  Same problem.

**Comment by lizmat** [comment] 2018-07-08 13:00
Thank you!  :-)

**Comment by loops** [comment] 2018-07-09 18:54
Just as a data point, when doing the same thing with a CStruct, the problem does not appear.
So the following code, always works:

`use NativeCall;

class TC is repr('CStruct') {
  has uint32 $.x;
}

my sub tst(TC is rw) is native('./tst.so') { * };

for ^30_000 {
  my $tc = TC.new(:2x);
  tst($tc);
  die "$_ {$tc.x}" if $tc.x != 2;
}

# Compile tst.c with :    gcc -fPIC -shared -o tst.so tst.c
# tst.c contains :
#     #include <stdint.h>
#     typedef struct  {
#       uint32_t x;
#     } TC;
#     void tst(TC *tc) { }
#
`

**Comment by niner** [comment] 2018-07-22 19:58
Another very interesting data point. This runs for hours without breaking:
`while MVM_SPESH_BLOCKING=1 MVM_SPESH_NODELAY=1 perl6 test.pl6 ; do true ; done`
This tells me, that the code created after speshing is just fine while it's the initially compiled code that is faulty.

There are actually two rounds of JIT compilation happening for NativeCall. In the first we just compile code for doing the call with the information we got from the native sub's signature. Later on the Perl 6 wrapper sub containing the actual native call will be speshed and JIT compiled. At that point we create a new version of the calling code which can factor in the data spesh has collected at runtime. Apparently this version is safer.

Of course it's also possible, that the speshed version is just safer by accident. We could confirm that by finding some native sub that fails even with MVM_SPESH_BLOCKING=1 MVM_SPESH_NODELAY=1

**Comment by niner** [comment] 2018-07-29 08:44
Additional findings: the issue is sensitive to `MVM_SPESH_NODELAY=1`. Running with `MVM_SPESH_BLOCKING=1` makes it appear earlier, after a couple 100 iterations instead of several 1000. Also in every test run there's just a single iteration giving a wrong result.
Therefore I suspect that it's not actually the JITed native call at fault here, but some OSR issue in spesh. Maybe a mishandling of the `getarg_i` op that's used only for native calls with rw arguments.

**Comment by loops** [comment] 2018-08-12 02:56
Thank you so much for tracking down the bug and supplying a patch niner.  And thank you zoffixznet for pointing me here from irc and keeping an eye on things.

Gave the fix a try here and it's all looking good.  Can not reproduce the problem any longer.

Thanks again.

**Comment by lizmat** [comment] 2024-10-04 18:15
Closing as basically untestable

**Closed by lizmat** 2024-10-04 18:15 UTC
Labels: tests needed, NativeCall
