### ISSUE TITLE
Adding/subtracting negative values to/from Date

### ISSUE THREAD

**Issue by nwellnhof** [rakudo/rakudo#2707] opened 2019-02-19 13:18 UTC
Adding negative values to a `Date` seems buggy:

    say Date.new('2019-01-01') + -100  # 2019-01--99
    say Date.new('2019-01-01') - 100   # 2018-09-23

Subtracting negative values as well:

    say Date.new('2019-01-01') - -100  # 2019-01-101
    say Date.new('2019-01-01') + 100   # 2019-04-11

**Comment by AlexDaniel** [comment] 2019-02-19 13:20
Bisected: https://github.com/rakudo/rakudo/commit/a11d599f4b8856d78ddea6540b09e7827776db49

**Comment by lizmat** [comment] 2019-02-19 13:47
Problem was caused by an over-eager optimization not taking into account negative values.  Fixed with  91ca827523 ,

**Comment by lizmat** [comment] 2019-02-19 13:51
Tests added with https://github.com/perl6/roast/commit/67d9ff0294

**Closed by lizmat** 2019-02-19 13:51 UTC
Labels: regression, ⚠ blocker ⚠
