### ISSUE TITLE
custom prefix for List does not work with all quote constructs

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#3823] opened 2020-07-24 14:38 UTC
```
sub prefix:<px>(List:D \l) is looser(&infix:<,>) { };

px 1,2;
px<a b>;
px«/usr/bin/find /tmp»;
```
Fails with:
```
===SORRY!=== Error while compiling /home/dex/projects/raku/lib/raku-shell-piping/example/basic.raku
Two terms in a row
at /home/dex/projects/raku/lib/raku-shell-piping/example/basic.raku:118
------> px«/usr/⏏bin/find /tmp»;
    expecting any of:
        infix
        infix stopper
        statement end
        statement modifier
        statement modifier loop
```

This is inconsistent as the non-interpolating quote construct works. The error message is also misleading.

## Environment
* Operating system: Linux dexhome 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
* Compiler version (`perl6 -v` or `raku -v`):This is Rakudo version 2020.07-41-g3843a1e89 built on MoarVM version 2020.07 implementing Raku 6.d.

**Comment by pmichaud** [comment] 2020-07-24 19:23
Looking at the error message, it looks to me like it's treating the / as delimiters for the argument, so perhaps the « is being treated as a hyper-meta-op modifier to the ```px``` prefix op.  The same thing happens even for built-in prefix ops, like ```+```:

```
> say +«/usr/bin/find /tmp»; 
===SORRY!=== Error while compiling:
Two terms in a row
------> say +«/usr/⏏bin/find /tmp»;
    expecting any of:
        infix
        infix stopper
        postfix
        statement end
        statement modifier
        statement modifier loop
```

I'm inclined to say "not a bug", but others can weigh in on the interpretation.

Personally, I would be writing the expression as ```px «/usr/bin/find /tmp»```.

Pm

**Comment by vrurg** [comment] 2020-07-24 19:30
@pmichaud Looks like it's the cause. Because `px` is a prefix `«` is it's metaop then.

Closing.

**Closed by vrurg** 2020-07-24 19:30 UTC

**Comment by lizmat** [comment] 2020-07-24 20:30
I would prefer it if we give the op the option of indicating that they agree with this, and let *them* close the issue.  If you close an issue like this that is still pretty hot, it could be felt by the op that the issue was not taking seriously.
