### ISSUE TITLE
Problems with large hash definitions?

### ISSUE THREAD

**Issue by JJ** [rakudo/rakudo#3647] opened 2020-04-28 10:27 UTC
## The Problem

When hash definitions are huge (in this case, ~ 120k) they seem to silently fail when exported, or defined "our", or both.

https://github.com/JJ/raku-service-portmapping/blob/6913f6309e35938f1013a79f38c8e1ab1a0cbb99/lib/Service/PortMapping.pm6#L4

They also take a loooong time...

## Expected Behavior

Either throw an error or success.

## Steps to Reproduce

"use" that file and print any of the defined hashes.

```
use Service::PortMapping;

say %TCPPorts;
```

## Environment
* Operating system: 
* Compiler version (`perl6 -v`): 

Ubuntu 16.04, raku 2020.02

**Comment by dogbert17** [comment] 2020-10-24 18:36
I don't know if the module code has changed or if something has been fixed in Rakudo but the example given seems to work. Perhaps I have misunderstood what the problem is:

    dogbert@dogbert-VirtualBox:~/repos/raku-service-portmapping$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-92-g6e6c9e5cc.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-20-gf99bc2ce7.
    dogbert@dogbert-VirtualBox:~/repos/raku-service-portmapping$ perl6 -Ilib -e 'use Services::PortMapping; say %TCPPorts'
    "Service Name","Port Number","Transport Protocol",Description,Assignee,Contact,"Registration Date","Modification Date",Reference,"Service Code","Unauthorized Use Reported","Assignment Notes"
    {1ci-smcs => 3091, 3Com-nsd => 1742, 3com-amp3 => 629, 3com-net-mgmt => 2391, 3com-njack-1 => 5264, 3com-njack-2 => 5265, 3com-tsmux => 106, 3com-webview => 2339, 3comfaxrpc => 3446, 3comnetman => 1181, 3d-nfsd => 2323, 3ds-lm => 1538, 3exmp => 5221, 3gpp-cbsp => 48049, 3l-l1 => 1511, 3link => 15363, 3m-image-lm => 1550, 3par-evts => 5781, 3par-mgmt => 5782, 3par-mgmt-ssl => 5783, 3par-rcopy => 5785, 4-tieropmcli => 2934, 4-tieropmgw => 2933, 4talk => 3284, 5afe-dir => 23294, 802-11-iapp => 3517, 914c-g => 211, 914c/g => 211, 9pfs => 564, Apple Remote Desktop (Net Assistant) => 3283, BESApi => 3408, CAIlic => 216, CardWeb-IO => 9060, DMExpress => 32636, Escale (Newton Dock) => 3679, EtherNet-IP-1 => 2222, EtherNet-IP-2 => 44818, EtherNet/IP-1 => 2222, EtherNet/IP-2 => 44818, LiebDevMgmt-A => 3029, LiebDevMgmt-C => 3027, LiebDevMgmt-DM => 3028, LiebDevMgmt_A => 3029, LiebDevMgmt_C => 3027, LiebDevMgmt_DM => 3028, MOS-aux => 10542, MOS-lower => 10540, MOS-soap => 10543, MOS-soap-opt => 10544, MOS-upper => 10541, MaxumSP => 4179, MobilitySrv => 6997, PS-Capture-Pro => 7216, PS-Server => 7215, PowerAlert-nsa => 4150, RDCenter => 4756, SunVTS-RMI => 6483, XSIP-network => 1354, XmlIpcRegSvc => 9092, a1-bs => 5603, a1-msc => 5602, a13-an => 3125, a14 => 3597, a15 => 3598, a16-an-an => 4598, a17-an-an => 4599, a21-an-1xbs => 4597, a3-sdunode => 5604, a4-sdunode => 5605, aairnet-1 => 3618, aairnet-2 => 3619, aal-lm => 1469, aamp => 3939, aap => 2878, aas => 1601, abacus-remote => 2894, abarsd => 8402, abatemgr => 3655, abatjss => 3656, abb-escp => 6316, abb-hw => 10020, abbaccuray => 1546, abbs => 4885, abcsoftware => 3996, abcvoice-port => 3781, abr-api => 1954, abr-secure => 1955, ac-cluster => 18463, ac-tech => 2796, acap => 674, acas => 62, acc-raid => 2800, accel => 4108, accelenet => 1182, accessbuilder => 888, accessnetwork => 699, accord-mgc => 1205, acctopus-cc => 6868, accu-lmgr => 7781, accuracer => 12007, ...}

**Comment by Kaiepi** [comment] 2020-10-24 18:56
MoarVM got a new hash implementation recently, which may explain why this works now.

**Closed** 2024-10-13 11:27 UTC
