### ISSUE TITLE
sleep() after run() still has CPU usage: [SCHEDULER \d+] Per-core utilization (approx): 1.1223469876632168%

### ISSUE THREAD

**Issue by Marcool04** [rakudo/rakudo#3941] opened 2020-10-01 10:08 UTC
## The Problem
When a run() call is placed, a ThreadPoolScheduler is apparently started, which is still running even after the run() completes, and continues to even during a sleep() instruction, causing the paradoxical effect of a sleeping program using CPU. This is evidenced by setting RAKUDO_SCHEDULER_DEBUG_STATUS environmental variable and watching messages such as:
```
[SCHEDULER 7094] Per-core utilization (approx): 1.1223469876632168%
```
be spilled out continuously during the sleep phase. 

## Expected Behavior
One would expect a sleeping program with no forks or async threads to monitor to not use any CPU, except perhaps for garbage collection (so this should be one off, then usage should go to 0).

## Actual Behavior
Notice how the CPU usage increases with the length of the sleep:
```
[mark@macbookpromark ~]$ time raku -e 'run(<echo hi>); sleep 10'
[snip]
user	0m0.400s
sys	0m0.141s
[mark@macbookpromark ~]$ time raku -e 'run(<echo hi>); sleep 20'
[snip]
user	0m0.451s
sys	0m0.183s
[mark@macbookpromark ~]$ time raku -e 'run(<echo hi>); sleep 40'
[snip]
user	0m0.660s
sys	0m0.287s
```
But stays quasi-constant when no run() has been used:
```
[mark@macbookpromark ~]$ time raku -e 'say "hi"; sleep 10'
[snip]
user	0m0.360s
sys	0m0.083s
[mark@macbookpromark ~]$ time raku -e 'say "hi"; sleep 20'
[snip]
user	0m0.320s
sys	0m0.074s
[mark@macbookpromark ~]$ time raku -e 'say "hi"; sleep 40'
[snip]
user	0m0.329s
sys	0m0.095s
```

## Environment
* Operating system and compiler version:

Tested on a Macbook pro running Catalina:
```
$ uname -a 
19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
$ raku -v
This is Rakudo version 2020.07 built on MoarVM version 2020.07
implementing Raku 6.d.
```
and a Raspberrypi 4 running Arch Linux ARM:
```
$ uname -a 
5.4.65-1-ARCH #1 SMP PREEMPT Tue Sep 15 16:21:17 UTC 2020 armv7l GNU/Linux
$ raku -v
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
implementing Raku 6.d.
```

**Comment by Marcool04** [comment] 2020-10-01 10:09
For reference, see also discussion with timotimo on IRC : https://colabti.org/irclogger/irclogger_log/raku?date=2020-09-28#l250

**Comment by lizmat** [comment] 2020-10-08 19:44
Summary: the supervisor thread is started whenever something async or thready is started.  This is basically a loop that sleeps .01 second, and then goes off checking stuff that possibly needs to be done, such as starting additional threads for workers, etc. etc.  This loop has been highly optimized in the past to make sure that there are no additional allocations done.  As far as I can see, this is still the case.

Your example is a worst case scenario in that sense.  On my MBP it takes about 220 msecs CPU (for the 10 second sleep example), of which 100 msecs CPU are used in startup, so 120 msecs CPU to run the `echo hi` and then wait 10 seconds.

I've tried to make the sleep period larger if there is nothing to do, maxing out at about .64 second per supervisor check.  This brought the CPU down to about 160 msecs, so 60 msecs CPU to run `echo hi` and then wait 10 seconds.  So that saved 60 msecs of CPU.  However, this comes at the expense of needing to run one extra conditional *each* supervisor run in *normal* operation.  So that's overhead in normal operation.  **AND** this cause one spectest to fail that was using `run`.

So it looks like this is not going to be worth it, to handle this uncommon case.  Also, in some environments, such as a cro server, one wants an immediate response on a burst of request, and not potentially have to wait more than half a second before another worker thread is started.

**Comment by lizmat** [comment] 2020-10-08 19:44
The actual diff I used to test variable sleep times for the supervisor thread:

    diff --git a/src/core.c/ThreadPoolScheduler.pm6 b/src/core.c/ThreadPoolScheduler.pm6
    index fb40c5cb8..fd8044855 100644
    --- a/src/core.c/ThreadPoolScheduler.pm6
    +++ b/src/core.c/ThreadPoolScheduler.pm6
    @@ -527,10 +527,13 @@ my class ThreadPoolScheduler does Scheduler {
         # The supervisor sits in a loop, mostly sleeping. Each time it wakes up,
         # it takes stock of the current situation and decides whether or not to
         # add threads.
    -    my constant SUPERVISION_INTERVAL  = 1e-2;
    -    my constant NUM_SAMPLES           = 5;
    -    my constant NUM_SAMPLES_NUM       = 5e0;
    -    my constant EXHAUSTED_RETRY_AFTER = 100;
    +    my constant INITIAL_SUPERVISOR_SLEEP = 1e-2;  # initial sleep value
    +    my constant MAX_SUPERVISOR_SLEEP     = 0.5e0; # approx max sleep value
    +    my constant NUM_SAMPLES              = 5;     # samples for smoothing (int)
    +    my constant NUM_SAMPLES_NUM          = 5e0;   # samples for smoothing (num)
    +    my constant EXHAUSTED_RETRY_AFTER    = 100;   # retry spawning after loops
    +    my constant LOW_WATER_CPU            = 0.1e0; # low for doubling sleep
    +    my constant HIGH_WATER_CPU           = 1e0;   # high for resetting sleep
         method !maybe-start-supervisor(--> Nil) {
             unless $!supervisor.DEFINITE {
                 $!supervisor = Thread.start(:app_lifetime, :name<Supervisor>, {
    @@ -612,10 +615,10 @@ my class ThreadPoolScheduler does Scheduler {
                     my num $smooth-per-core-util = 0e0;
     
                     scheduler-debug "Supervisor thinks there are $cpu-cores CPU cores";
    +                my num $sleep = INITIAL_SUPERVISOR_SLEEP;
                     loop {
    -                    # Wait until the next time we should check how things
    -                    # are.
    -                    nqp::sleep(SUPERVISION_INTERVAL);
    +                    # Wait until the next time we should check how things are.
    +                    nqp::sleep($sleep);
     
                         # Work out the delta of CPU usage since last supervision
                         # and the time period that measurement spans.
    @@ -669,7 +672,17 @@ my class ThreadPoolScheduler does Scheduler {
                         $smooth-per-core-util += $per-core-util;
                         @last-utils.push($per-core-util);
     #?endif
    -                    scheduler-debug-status "Per-core utilization (approx): $smooth-per-core-util%"
    +                    # If CPU usage is really low, then double the sleep
    +                    # period for the supervisor.  As soon as the CPU usage
    +                    # goes up, switch back to the default sleep period.
    +                    if nqp::isgt_n($smooth-per-core-util,HIGH_WATER_CPU) {
    +                        $sleep = INITIAL_SUPERVISOR_SLEEP;
    +                    }
    +                    elsif nqp::islt_n($smooth-per-core-util,LOW_WATER_CPU) {
    +                        $sleep += $sleep
    +                          if nqp::islt_n($sleep,MAX_SUPERVISOR_SLEEP);
    +                    }
    +                    scheduler-debug-status "Per-core utilization: $smooth-per-core-util% (per $sleep secs)"
                           if $scheduler-debug-status;
     
                         # exhausted the system allotment of low level threads

**Comment by lizmat** [comment] 2020-10-08 19:45
Leaving this issue open for now.  If no further comments, I will close in a few days.

**Comment by Marcool04** [comment] 2020-10-09 10:16
Thanks @lizmat for doing research into this. I'm perfectly ok with the need to balance the fit-for-all-purposes goal and performance. You are perfectly right in saying there is probably not a very significant gain to be attained here and I also hear your argument for cases like listening servers needing to be able to sleep while also reacting as soon as possible to events.

If you'll allow me (one more) naive question:

In the [source](https://github.com/rakudo/rakudo/blob/8134470538457c68164eb64f90e8d3e946d235a0/src/core.c/Proc.pm6#L1) for `Proc` I see this:


````raku
# Proc is a wrapper around Proc::Async, providing a synchronous API atop of
# the asynchronous API.
````

This is obviously the reason the ThreadPoolScheduler is started here. Would it be unreasonable / undesirable / hard to implement, for the ThreadPoolScheduler to be stopped when the run() call terminates?

**Comment by lizmat** [comment] 2020-10-09 11:02
To be able to do that, we would need to build in a test in the supervisor loop that would need to be tested each iteration.  So that would be additional overhead, just like the "slowing down" patch would be.

But more importantly, how can we be sure that the `run` is the only thing that will be run in a program?

So I think it would be undesirable to implement, because of potential false positives.  And *if* a `run` is the only thing that runs in a program, I don't think you can actually notice the supervisor overhead, as the program won't be running long then anyway.

Finally, there's also an optimizer thread running as well.  At least a part of the CPU overhead you've seen, is caused by that thread:

    $ time raku -e ''
    real	0m0.118s
    user	0m0.109s
    sys	0m0.021s

    $ raku -e 'sleep 10'
    real	0m10.287s
    user	0m0.143s
    sys	0m0.045s

And that thread *has* to run and cannot be stopped afaik.

**Comment by AlexDaniel** [comment] 2020-10-09 17:52
Is it normal behavior in other languages?

**Comment by lizmat** [comment] 2020-10-09 17:55
And how is this important?

**Comment by niner** [comment] 2020-10-09 20:56
> And how is this important?

It may give us an idea how to improve this. Personally, I think, the Linux 
kernel could give all the inspiration we need, since it has to solve similar 
problems. It used to have a fixed interval scheduler interrupt, which wasted 
energy and made it less responsive. It did get smarter though and now only 
wakes when there will be a process to run.

**Comment by Marcool04** [comment] 2020-10-09 21:03
> To be able to do that, we would need to build in a test in the supervisor loop that would need to be tested each iteration. So that would be additional overhead, just like the "slowing down" patch would be.
> 
> But more importantly, how can we be sure that the `run` is the only thing that will be run in a program?
> 

Yes that does indeed sound like it would be over complexifying things for not much gain. I think I had something in mind like a run_sync alternative to run() that would perhaps do everything synchronously so as not to fire off the ThreadPoolScheduler… If that makes any sense :/

**Comment by lizmat** [comment] 2020-10-09 22:43
FWIW, in earlier versions of Raku, `run` was actually running synchronously.  It was deemed too much effort to maintain, as an async version also needed to be maintained.  So that's how `run` actually became a synchronous frontend to an asynchronous action.

**Comment by Marcool04** [comment] 2020-10-10 08:49
I guess my "expectations" here are shaped by the fact that I now use raku in most situations where I used to use perl, as a "glue" language for handling information from various other tools, so run() in such a case is an important part of the process, as is sleep(). Both work just fine and I don't expect any work to go into improving stuff ; thanks for all your patience here by the way.

If you could point me to the implementation of run() that was in place before the choice was made to switch to the async wrapper I'd be grateful. Maybe I can get it running again in recent versions as a separate run_sync() and experiment with that…

**Comment by lizmat** [comment] 2020-10-10 09:39
Checkout ecc7a0a614 and look at src/core/Proc.pm : that should be a good start I think

**Comment by lizmat** [comment] 2020-10-10 09:44
@niner 

> since it has to solve similar problems

Processes are not threads.  Having said that, what I think is missing, also to be able to balance work over worker threads better, is to be able to find out how much CPU each *thread* is using.  Without that information, I don't think it will be possible to get Raku much smarter than it is now.

**Closed** 2024-10-14 11:34 UTC
Labels: performance, concurrency, needs research
