### ISSUE TITLE
Array[Pair] as return constraint does not work

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2182] opened 2018-08-05 21:20 UTC
Here's the gist to reproduce the problem:
https://gist.github.com/AlexDaniel/96a813043e1a6a58fb261a688b925081

Basically it is this sub:
```perl6
sub parse-line() returns Array[Pair] is export {
    Array[Pair].new("foo" => "bar")
}
```
Which you must use from another file (no issue if it's in the same executable).

Output:
```
Type check failed for return value; expected Array[Pair] but got Array[Pair].new("foo" => "bar")
  in sub parse-line at /home/bisectable/git/whateverable/sandbox/LTSV-Parser.pm6 line 3
in block <unit> at sandbox/ltsv.p6 line 5
```

IMO the error message doesn't make much sense.

I bisected this problem to (2016-02-11) https://github.com/rakudo/rakudo/commit/22b4ef05b1f72b50d63e4599d5e037bccf1f08ed
The result does look a bit surprising, but I do recall problems when you use certain classes too early, or something like that. I think changing `my Pair @arg-help;` to just `my @arg-help;` can resolve the problem.
Proof that it is that commit: https://gist.github.com/2b52334854aee55ec4eb584c8b0c58ca

There is a module failing to pass its tests because of this: https://github.com/perl6/ecosystem-unbitrot/issues/34

**Comment by zoffixznet** [comment] 2018-08-05 21:29
Possible dupe of https://rt.perl.org/Ticket/Display.html?id=132525#ticket-history and related to https://rt.perl.org/Ticket/Display.html?id=127309

**Closed** 2024-10-06 12:33 UTC
Labels: regression
