### ISSUE TITLE
token name confilct with internal name ?

### ISSUE THREAD

**Issue by araraloren** [rakudo/rakudo#1870] opened 2018-05-26 07:07 UTC
```
my grammar Test { 
rule TOP { <CREATE> } 
token CREATE { "CREATE" }
};
say Test.parse: "CREATE"; 
```
## The Problem

Above code will raised an error that cause by the name of token CREATE(it is a internal name ?), it is work fine if we change the CREATE to something other such as CREATEX.

## Expected Behavior
```
｢CREATE｣
 CREATE => ｢CREATE｣
```
## Actual Behavior
```
Too many positionals passed; expected 1 argument but got 2
  in regex CREATE at -e line 1
  in regex TOP at -e line 1
  in block <unit> at -e line 1
```
## Environment
* Operating system:  fedora 27
* Compiler version (`perl6 -v`):  2018.04.1

**Comment by zoffixznet** [comment] 2018-05-26 11:45
This is a known limitation ([R#127945](https://rt.perl.org/Ticket/Display.html?id=127945#ticket-history)). Basically because you did not specify an Actions class, you get an empty one, but the empty one still contains all the Mu methods that get called with the match object, which is where the error you see is coming from.

You can avoid it by giving it your own Actions object with the Mu methods overridden:

```perl6
my grammar Test {
    rule TOP { <CREATE> }
    token CREATE { "CREATE" }
};
say Test.parse: "CREATE", actions => class { method CREATE($) {} }; 

# ｢CREATE｣
# CREATE => ｢CREATE｣
```

**Comment by raiph** [comment] 2018-05-27 21:19
That needs to be:

    say Test.parse: "CREATE", actions => class foo is Mu { method CREATE($) {} }; 

i.e. `class foo is Mu` rather than just `class` otherwise you'd have to override `Any` methods too.

**Comment by raiph** [comment] 2018-05-27 21:28
Maybe the appropriate relatively easy fix is to generate a class called, say, `actions` that has an empty `.^mro`.

Then ship that with Rakudo.

Then folk can define their own action classes as `class foo is actions { ... }`.

And we can make that the default actions class.

**Comment by zoffixznet** [comment] 2018-05-27 21:34
I tried that before, but if it's not a Mu it's not accepted by any parameters anywhere.

**Comment by raiph** [comment] 2018-05-27 22:05
That sucks.

Here's a horrible, horrible ugly hack idea so I can go to sleep. As before, but the generated class called `actions` is a duplicate of `Mu` but with no attributes and empty method bodies. Or perhaps method bodies that check if the caller is the Actions mechanism, and if it is, does nothing, and if it isn't, `samecall`s to invoke the underlying `Mu` method.

I hope I can sleep tonight.

**Comment by raiph** [comment] 2018-06-29 15:22
[How to create a class that doesn't inherit from any other class?](https://stackoverflow.com/questions/51031264/how-to-create-a-class-that-doesnt-inherit-from-any-other-class)

**Closed** 2023-11-11 09:18 UTC
Labels: regex
