### ISSUE TITLE
Weird issue with `zef install`

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#1413] opened 2018-01-16 14:35 UTC
When installing [X11::Xlib::Raw](https://github.com/slobo/Perl6-X11-Xlib-Raw) I get this SORRY:
```bash
zef install X11::Xlib::Raw
```
```
===> Searching for: X11::Xlib::Raw
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Testing: X11::Xlib::Raw
===> Testing [OK] for X11::Xlib::Raw
===> Installing: X11::Xlib::Raw
===> Install [FAIL] for X11::Xlib::Raw: ===SORRY!===
Cannot bind attributes in a keysym type object

===SORRY!===
Cannot bind attributes in a keysym type object

  in any  at /home/alex/.perl6/precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516101847.70846/00/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 line 1
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 581
  in any  at /home/alex/.perl6/precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516101847.70846/00/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 line 1
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 589
  in block  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 552
  in sub  at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 541
  in method install at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 633
  in sub MAIN at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/C360CEB3AF792C33F65155FA82FDB7AB4467EC82 (Zef::CLI) line 152
  in block <unit> at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/resources/1063D2A135456C8AB42D605E20DBCF9E4A1C9F3B line 3
  in sub MAIN at /home/alex/.rakudobrew/bin/../moar-master/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/alex/.rakudobrew/bin/../moar-master/install/share/perl6/site/bin/zef line 2
```

It seems that the module is installed successfully, so to reproduce again you'd have to ``zef uninstall X11::Xlib::Raw``. According to toaster results, that's a regression somewhere between 2017.12 and HEAD.

**Comment by zoffixznet** [comment] 2018-01-16 16:41
Here's the backtrace for it... Looks like `my $val := nqp::rebless(nqp::clone($value), $enum_type_obj);` in `World/create_enum_value` ends up returning a typeobject or something

```bash
~/R/rakudo/zef (master)$ perl6 --ll-exception -Ilib bin/zef install X11::Xlib::Raw
===> Searching for: X11::Xlib::Raw
===> Testing: X11::Xlib::Raw
===> Testing [OK] for X11::Xlib::Raw
===> Installing: X11::Xlib::Raw
===> Install [FAIL] for X11::Xlib::Raw: Cannot bind attributes in a keysym type object
   at src/Perl6/World.nqp:3696  (/home/zoffix/R/install/share/nqp/lib/Perl6/World.moarvm:create_enum_value)
 from gen/moar/Perl6-Actions.nqp:4769  (/home/zoffix/R/install/share/nqp/lib/Perl6/Actions.moarvm:type_declarator:sym<enum>)
 from gen/moar/stage2/QRegex.nqp:1629  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from src/Perl6/Grammar.nqp:3276  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:type_declarator:sym<enum>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:type_declarator)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term:sym<type_declarator>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:4013  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:883  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:4053  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1335  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1267  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from src/Perl6/Grammar.nqp:2571  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:package_def)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:package_declarator:sym<package>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:package_declarator)
 from src/Perl6/Grammar.nqp:2664  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:scoped)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:scope_declarator:sym<unit>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:scope_declarator)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term:sym<scope_declarator>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:4013  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:883  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:4053  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1335  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1267  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1113  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from src/Perl6/Grammar.nqp:1706  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from src/Perl6/Grammar.nqp:1231  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:comp_unit)
 from src/Perl6/Grammar.nqp:532  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2335  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1881  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1797  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1830  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1833  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1819  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1519  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1774  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1699  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/zoffix/R/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1625  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<entry>)

Cannot bind attributes in a keysym type object
   at src/Perl6/World.nqp:3696  (/home/zoffix/R/install/share/nqp/lib/Perl6/World.moarvm:create_enum_value)
 from gen/moar/Perl6-Actions.nqp:4769  (/home/zoffix/R/install/share/nqp/lib/Perl6/Actions.moarvm:type_declarator:sym<enum>)
 from gen/moar/stage2/QRegex.nqp:1629  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from src/Perl6/Grammar.nqp:3276  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:type_declarator:sym<enum>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:type_declarator)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term:sym<type_declarator>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:4013  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:883  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:4053  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1335  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1267  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from src/Perl6/Grammar.nqp:2571  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:package_def)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:package_declarator:sym<package>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:package_declarator)
 from src/Perl6/Grammar.nqp:2664  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:scoped)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:scope_declarator:sym<unit>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:scope_declarator)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term:sym<scope_declarator>)
 from gen/moar/stage2/QRegex.nqp:1726  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:4013  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:883  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:4053  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1335  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1267  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1113  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from src/Perl6/Grammar.nqp:1706  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from src/Perl6/Grammar.nqp:1231  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:comp_unit)
 from src/Perl6/Grammar.nqp:532  (/home/zoffix/R/install/share/nqp/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2335  (/home/zoffix/R/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1881  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1797  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:1830  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1833  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1819  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1519  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1774  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1699  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/zoffix/R/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1625  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<entry>)

   at SETTING::src/core/Exception.pm:57  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:throw)
 from SETTING::src/core/control.pm:178  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:die)
 from SETTING::src/core/control.pm:166  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:die)
 from SETTING::src/core/CompUnit/PrecompilationRepository.pm:293  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:precompile)
 from SETTING::src/core/CompUnit/PrecompilationRepository.pm:210  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:precompile)
 from SETTING::src/core/CompUnit/Repository/Installation.pm:317  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Any-iterable-methods.pm:634  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:sink-all)
 from SETTING::src/core/Seq.pm:136  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:sink)
 from SETTING::src/core/CompUnit/Repository/Installation.pm:307  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/CompUnit/Repository/Installation.pm:293  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Lock.pm:23  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:protect)
 from SETTING::src/core/CompUnit/Repository/Installation.pm:195  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:install)
 from SETTING::src/core/CompUnit/Repository/Installation.pm:173  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:install)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):592  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):565  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):555  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:)
 from SETTING::src/core/Any-iterable-methods.pm:895  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Any-iterable-methods.pm:423  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:push-all)
 from SETTING::src/core/Iterator.pm:69  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:push-until-lazy)
 from SETTING::src/core/List.pm:104  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:reify-until-lazy)
 from SETTING::src/core/List.pm:672  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/List.pm:670  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:push-until-lazy)
 from SETTING::src/core/Array.pm:241  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:STORE-ITERABLE)
 from SETTING::src/core/Array.pm:228  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:STORE)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):553  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:)
 from SETTING::src/core/Any-iterable-methods.pm:423  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:push-all)
 from SETTING::src/core/List.pm:148  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:reify-all)
 from SETTING::src/core/Sequence.pm:69  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:eager)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):544  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:)
 from SETTING::src/core/Seq.pm:205  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:)
 from SETTING::src/core/Seq.pm:214  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:pull-one)
 from SETTING::src/core/Iterator.pm:56  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:push-all)
 from SETTING::src/core/List.pm:148  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:reify-all)
 from SETTING::src/core/List.pm:924  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:eager)
 from SETTING::src/core/Sequence.pm:69  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:eager)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):544  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:)
 from /home/zoffix/R/rakudo/zef/lib/Zef/Client.pm6 (Zef::Client):636  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/DF/DFBCE92B48D89E35CAB1AB7A7719F84ED8D68727:install)
 from /home/zoffix/R/rakudo/zef/lib/Zef/CLI.pm6 (Zef::CLI):152  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/34/34674DE0B49051C42E89F10D51FE788C3C3A3816:MAIN)
 from /home/zoffix/R/rakudo/zef/lib/Zef/CLI.pm6 (Zef::CLI):21  (/home/zoffix/R/rakudo/zef/lib/.precomp/E28DBB8A08ADE886AEF0EDA64FDC96B5736C217D.1516113296.19328/34/34674DE0B49051C42E89F10D51FE788C3C3A3816:MAIN)
 from SETTING::src/core/Main.pm:228  (/home/zoffix/R/install/share/perl6/runtime/CORE.setting.moarvm:MAIN_HELPER)
 from bin/zef:3  (<ephemeral file>:<unit>)
 from bin/zef:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1537  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:1774  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:1699  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from src/Perl6/Compiler.nqp:42  (/home/zoffix/R/install/share/nqp/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:1625  (/home/zoffix/R/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/main.nqp:47  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/main.nqp:38  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/zoffix/R/install/share/perl6/runtime/perl6.moarvm:<entry>)

```

**Comment by zoffixznet** [comment] 2018-01-18 23:17
Got "golf" for this: https://gist.github.com/zoffixznet/f7d259acbad7e1a0e93a1e72ddde6331   It's just a single giant enum. Trimming it down a bit more makes the issue appear less often.

I traced the issue to [this MoarVM commit](https://github.com/MoarVM/MoarVM/commit/db706bb7dfa68bd025d823e3871222bf3b4afb59), specifically marking `return_o` op with `:useshll` fixed the issue.

Since [we don't wanna do that](https://irclog.perlgeek.de/perl6/2018-01-18#i_15708626), I'm leaving this for jnthn to hack on further.

**Comment by jnthn** [comment] 2018-01-19 16:40
It's still not entirely clear what's going on, but https://github.com/MoarVM/MoarVM/commit/4733449165 works around the issue without disabling the new opts. If somebody can reproduce that MoarVM HEAD fixes the issue for them also, then I think we can close this ticket, and I've made https://github.com/MoarVM/MoarVM/issues/782 in order to track looking deeper into the issue on the MoarVM side.

**Comment by jnthn** [comment] 2018-01-19 16:41
Oh, a roast test for this would also be very nice.

**Comment by AlexDaniel** [comment] 2018-01-20 17:51
OK, this is indeed fixed now! At least, I can no longer reproduce it.

**Closed** 2018-02-02 19:50 UTC
Labels: regression, testneeded
