### ISSUE TITLE
[WIP] Blin 2020.01

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3417] opened 2020-01-11 18:06 UTC
- [x] 5162e6f5a31d98bf295e706cb60c0fa8a93935dd [Format::Lisp](https://modules.raku.org/dist/Format::Lisp) – Fail, Bisected: 5162e6f5a31d98bf295e706cb60c0fa8a93935dd (path is sent)
- [x] 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17 [Object::Permission](https://modules.raku.org/dist/Object::Permission) – Fail, Bisected: 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17
- [x] 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17 [PDF](https://modules.raku.org/dist/PDF) – Fail, Bisected: 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17
- [x] 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17 [PDF::Content](https://modules.raku.org/dist/PDF::Content) – Fail, Bisected: 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17
- [x] 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17 [PDF::Lite](https://modules.raku.org/dist/PDF::Lite) – Fail, Bisected: 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17
- [x] 63f117502a93b44f12d97898eb3438417996793a [overload::constant](https://modules.raku.org/dist/overload::constant) – Fail, Bisected: 63f117502a93b44f12d97898eb3438417996793a
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [App::MoarVM::Debug](https://modules.raku.org/dist/App::MoarVM::Debug) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (tests are racey, sometimes install fine)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [Bitcoin::RPC::Client](https://modules.raku.org/dist/Bitcoin::RPC::Client) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (an odd flapper, the repo is archived)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [CCLog](https://modules.raku.org/dist/CCLog) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890  (fails on installing stage)
aa9c824d06c9f65645b35173b360c09388ab1890 CamelPub – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (the code is fragile and is broken on the previous release too, issue is created at https://nest.pijul.com/donpdonp/camelpub/discussions/1)
aa9c824d06c9f65645b35173b360c09388ab1890 DB::Xoos::Pg – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (false positive on dependency resolution, at worst a flapper)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [FileSystem::Parent](https://modules.raku.org/dist/FileSystem::Parent) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [FindBin](https://modules.raku.org/dist/FindBin) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [FindBin::libs](https://modules.raku.org/dist/FindBin::libs) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [HTTP::API::Pingdom](https://modules.raku.org/dist/HTTP::API::Pingdom) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (fails on 2019.11 as well)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [IRC::Client::Plugin::Ignore](https://modules.raku.org/dist/IRC::Client::Plugin::Ignore) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (fails on 2019.11 as well)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [MoarVM::Remote](https://modules.raku.org/dist/MoarVM::Remote) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (installs fine)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [Module::Toolkit](https://modules.raku.org/dist/Module::Toolkit) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [November](https://modules.raku.org/dist/November) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [P6W](https://modules.raku.org/dist/P6W) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [Pakku](https://modules.raku.org/dist/Pakku) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (deps are not specified, was installed fine by accident, issue at https://github.com/hythm7/Pakku/issues/5 )
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [Perl6::Ecosystem](https://modules.raku.org/dist/Perl6::Ecosystem) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (a reported module breakage)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [Rabble](https://modules.raku.org/dist/Rabble) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (https://github.com/MadcapJake/rabble/pull/3)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [TOML](https://modules.raku.org/dist/TOML) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (https://github.com/Mouq/toml-pm6/pulls)
- [x] aa9c824d06c9f65645b35173b360c09388ab1890 [Verge::RPC::Client](https://modules.raku.org/dist/Verge::RPC::Client) – Fail, Bisected: aa9c824d06c9f65645b35173b360c09388ab1890 (archived module, tests are ok, installing is broken)
- [x] add2ec0d491218e59e6c7a517e37458e1a6c3daf [ADT](https://modules.raku.org/dist/ADT) – Fail, Bisected: add2ec0d491218e59e6c7a517e37458e1a6c3daf
- [x] cddcd46a77594e1b6feb21ea705fd0f3f44eb0db [PDF::Class](https://modules.raku.org/dist/PDF::Class:cpan:WARRINGD) – Fail, Bisected: cddcd46a77594e1b6feb21ea705fd0f3f44eb0db
- [ ] 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17[PDF::Font::Loader](https://modules.raku.org/dist/PDF::Font::Loader:cpan:WARRINGD) – Fail, Bisected: 55b51a24a3f2cd6fe2bd1cddba397e84b74f2b17

**Comment by jonathanstowe** [comment] 2020-01-11 18:18
Looking at Object::Permission - I'm a bit surprised as it hasn't had to be changed for four years but I can see how the bisected change could break it.

**Comment by Altai-man** [comment] 2020-01-11 18:44
Logs: https://clbin.com/oknVY

**Comment by Altai-man** [comment] 2020-01-11 18:46
Seems like we have some false positives here.

**Comment by jonathanstowe** [comment] 2020-01-11 19:14
It seems like  Object::Permission had been on borrowed time calling `.can` directly on a type object, which was previously accidentally working.  Just fixing now.

**Comment by niner** [comment] 2020-01-11 19:55
Why should `.can` not work on a type object? Doing that seems entirely reasonable to me.

**Comment by jonathanstowe** [comment] 2020-01-11 20:03
It's `.^can`  with an alias to `.can` I think but `Object::Permission` is calling it while the type is being composed so it depends on the order of things which is asking for trouble.

**Comment by vrurg** [comment] 2020-01-11 21:23
@jonathanstowe I checked out the code where `can` is been called. There is nothing really worrisome about it (except that I don't consider the internal logic of the module). The only thing you need is a [line like this](https://github.com/vrurg/raku-AttrX-Mooish/blob/027588a88f04acf4118fbbc66927e04fd71b2efd/lib/AttrX/Mooish.pm6#L625) to be added prior to `callsame`.

**Comment by vrurg** [comment] 2020-01-11 21:35
`PDF` – bisection is coincidental. The real cause is described in #3328

**Comment by vrurg** [comment] 2020-01-11 22:40
Outcome of testing under a Linux VM against rakudo master:

`PDF`, `PDF::Content`, `PDF::Lite`, `PDF::Class` are installing ok.

`PDF::Font::Loader` cannot be tested as its dependency, `Font::FreeType` test fails with:

```
Must specify something as a path: did you mean '.' for the current directory?
  in sub guess_library_name at /home/vrurg/raku/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 225
  in method setup at /home/vrurg/raku/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 285
  in block  at /home/vrurg/raku/share/perl6/core/sources/947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 594
  in method bitmap at /home/vrurg/src/Raku/Font-FreeType-p6/lib/Font/FreeType/Native.pm (Font::FreeType::Native) line 235
  in method bitmap at /home/vrurg/src/Raku/Font-FreeType-p6/lib/Font/FreeType/GlyphImage.pm (Font::FreeType::GlyphImage) line 83
  in block  at t/20bitmap.t line 48
  in block  at t/20bitmap.t line 27
  in block <unit> at t/20bitmap.t line 16
```

Most likely it is caused by it failing to load libfreetype6, but I have no idea what's going on there. Otherwise, I would presume that `PDF::Font::Loader` failure was caused by the same cause as for `PDF`.

**Comment by Altai-man** [comment] 2020-01-12 10:55
lizmat++ has fixed Lisp::Format with https://github.com/drforr/perl6-Format-Lisp/pull/1, removing the blocker status.

**Comment by Altai-man** [comment] 2020-01-12 11:40
FindBin, FindBin::libs, FileSystem::Parent seem to rely on each other and in fact are not installable on 2019.11 as well on my system.

**Comment by lizmat** [comment] 2020-01-12 11:44
confirmed

**Comment by Altai-man** [comment] 2020-01-12 12:48
I have checked ones which are false positives for various reasons (see comments). Ones that _do_ need a solution are:

- [ ] Object::Permission
- [ ] overload::constant
- [ ] Module::Toolkit
- [ ] November
- [ ] ADT

**Comment by jonathanstowe** [comment] 2020-01-12 14:28
I've uploaded a new Object::Permission which works against head, dunno how long it takes until zef picks up the new version.

**Comment by Altai-man** [comment] 2020-01-13 15:19
Module::Toolkit is broken for long time (ugexe++), so striking it out, as well as November module.
Only odd `overload::constant` regression and `ADT` module are left.

**Comment by Xliff** [comment] 2020-01-15 18:27
Isn't fixing `ADT` just a matter of replacing `perl` with `raku`?

**Comment by AlexDaniel** [comment] 2020-01-15 18:39
@Xliff I tried that and it makes no difference. Maybe I'm doing something wrong.

**Comment by lizmat** [comment] 2020-01-15 19:06
> Isn't fixing ADT just a matter of replacing perl with raku?

That should *NOT* be necessary.  If that would be the fix, there is something seriously wrong.

**Comment by Altai-man** [comment] 2020-01-19 11:11
Closing the ticket as no more relevant.

**Closed by Altai-man** 2020-01-19 11:11 UTC
Labels: BLOCKER
