### ISSUE TITLE
"raku -n" is almost two times slower than manual iteration

### ISSUE THREAD

**Issue by bbkr** [rakudo/rakudo#3545] opened 2020-03-12 12:14 UTC
Test file has 30M lines, 1.2GB size.
I've noticed big performance drop while processing lines of such file using `-n` option:

```
$ time cat big_file.txt | raku -ne ''
real    0m34.407s
```

```
$ time raku -e 'for "big_file.txt".IO.lines { }'
real    0m18.893s
```
Is there something more going on under the hood while using `-n` ?
I would expect those two approaches to have very similar timings.

## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2020.02 built on MoarVM version 2020.02

**Comment by lizmat** [comment] 2020-03-12 13:02
Did you notice drop after a recent Rakudo change, or has it "always" been this way ?

**Comment by bbkr** [comment] 2020-03-12 13:34
I haven't tested historical versions. Just saw this suspicious difference on 2020.02.

**Comment by jnthn** [comment] 2020-03-12 19:28
There's some overhead given this form goes through `lines()`, which I think uses the argfiles mechanism. But that isn't the whole answer:

```
$ time perl6 -e 'for "longfile".IO.lines {}'
real	0m0.895s
user	0m0.876s
sys	0m0.064s

$ time cat longfile | perl6 -ne ''
real	0m1.246s
user	0m1.144s
sys	0m0.140s

$ time cat longfile | perl6 -e 'for lines() {}'
real	0m0.947s
user	0m0.840s
sys	0m0.164s
```

We'd at least expect `-ne` to match with `for lines() {}`. I wondered if it was because the `-ne` code-gen produced a sunk map call rather than `p6forstmt`. Alas, changing that gave very little difference either.

Then I took a closer look. It turns out that, since you can mutate the line, it actually takes `$_ is copy`, and if we do that:

```
$ time cat longfile | perl6 -e 'for lines() -> $_ is copy {}'
real	0m1.265s
user	0m1.172s
sys	0m0.140s
```

Then we get to the `-ne` time. In short, it's slower primarily because of `is copy`.

End of story?

Well, not quite, because then I decided to look at what we're compiling an `is copy` of a scalar parameter into. The answer? Something that doesn't actually use the MoarVM spesh plugin for assignment. Hmm, could that help? It turns out that yes, it does:

```
$ time cat longfile | perl6 -e 'for lines() -> $_ is copy {}'
real	0m0.985s
user	0m0.892s
sys	0m0.152s

$ time cat longfile | perl6 -ne ''
real	0m0.987s
user	0m0.884s
sys	0m0.136s
```

Except that we've improved every `is copy`, not just improved `-ne`. Committed in 5cad8feee4, and I put in the switch to compile to a simple loop, not a `map`, in be9c139fd4 too given I've written the code and it almost certainly saves a tiny something.

Disclaimer: I didn't check what the escape analyzer is doing, but it's possible it's entirely tossing out the allocation in this rather synthetic case, and it can't in a more general one, so this may overstate the gain in real code.

**Comment by bbkr** [comment] 2020-03-13 07:36
Wow! Thanks @jnthn for resolving this issue sooo fast.

What is the policy of closing such issues? Should this change be tested somehow (I don't see a way to make such performance test that will be reliable) or can it just be closed after ecosystem  tests are ran without sign of regression?

**Comment by jnthn** [comment] 2020-03-13 11:35
> What is the policy of closing such issues?

I wanted to hear that the effect was visible to somebody other than me. Given your comment, I guess that's the case. :-)

> Should this change be tested somehow (I don't see a way to make such performance test that will be reliable)

Performance tests have mostly made a nuisance of themselves. I'd like at some point to have a way to run a bunch of benchmarks against every commit, so we can monitor for changes, rather than have them as tests.

In the meantime, I don't think there's much point leaving this open if the issue is addressed. We already have quite enough tickets... :-)

**Closed by jnthn** 2020-03-13 11:35 UTC
Labels: performance
