### ISSUE TITLE
multis are sometimes not shown when introspecting methods

### ISSUE THREAD

**Issue by bduggan** [rakudo/rakudo#3323] opened 2019-11-26 13:04 UTC
## The Problem

When a class is declared in a separate file, introspection does not list the multi methods.

## Expected Behavior

`multi`s should be listed

## Actual Behavior

They are not

## Steps to Reproduce

in X.pm6
```
class X {
  multi method y { }
  method z { }
}
```

Then in another file
```
use lib '.';
use X;
say X.^methods;
```

output:
```
(z AUTOGEN BUILDALL)
```

i.e. `y` is missing.  It works if the class is declared in the same file, so I guess this is a precompilation issue.

## Environment
* Operating system:  OS/X
* Compiler version (`perl6 -v`): `This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.`

**Comment by jnthn** [comment] 2019-11-26 13:07
> y is missing

The `AUTOGEN` is the auto-generated `proto` for `y`, so the issue isn't that it's missing, but that it's lost its name change.

**Comment by lizmat** [comment] 2019-11-26 14:12
As a temporary workaround:

    class X {
      proto method y(|) {*}
      multi method y { }
      method z { }
    }

appears to solve the problem.

**Comment by jnthn** [comment] 2020-02-05 15:52
This needs a spectest before we can close it.

**Closed** 2020-08-20 14:51 UTC
Labels: dispatching, tests needed
