### ISSUE TITLE
Rakudo Star no longer builds on FreeBSD

### ISSUE THREAD

**Issue by pprocacci** [rakudo/rakudo#3559] opened 2020-03-20 18:38 UTC
## The Problem
Following the instructions here: https://www.raku.org/downloads/
rakudo no longer builds on FreeBSD

## Actual Behavior
Creating Makefile ...
Cleaning up ...
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 27: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 29: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 307: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 309: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 311: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 426: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 428: Need an operator
make[1]: "/root/rakudo-star-2020.01/nqp/Makefile" line 430: Need an operator
make[1]: Fatal errors encountered -- cannot continue== Configuring and building Rakudo
cd rakudo && /usr/local/bin/perl Configure.pl  --prefix="/opt" --backends=moar && make
Using /opt/bin/nqp-m (version 2020.01 / MoarVM 2020.01.1).
Cleaning up ...

You can now use '/usr/local/bin/gmake' to build Rakudo.
After that, '/usr/local/bin/gmake test' will run some tests and
'/usr/local/bin/gmake install' will install Rakudo.
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 13: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 15: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 281: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 283: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 284: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 286: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 288: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 290: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 291: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 293: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 294: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 296: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 626: Need an operator
make[1]: "/root/rakudo-star-2020.01/rakudo/Makefile" line 628: Need an operator
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /root/rakudo-star-2020.01/rakudo
*** Error code 1

## Steps to Reproduce
Follow the instructions on your own website doing so on FreeBSD.

## Environment
# uname -a
FreeBSD workvm 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

**Comment by patrickbkr** [comment] 2020-03-20 19:26
Can you nopaste the rakudo and nqp Makefile here?

**Comment by usev6** [comment] 2020-03-20 20:33
Also, the instruction talks about ```gmake``` (```You can now use '/usr/local/bin/gmake' to build Rakudo.```). Did you try to substitute make with ```gmake```? I'm regularly building on FreeBSD (11), but I'm using ```gmake``` instead of ```make```.

My guess at what happens would be: [The code from nqp-configure](https://github.com/Raku/nqp-configure/blob/326895a2e4/lib/NQP/Config.pm#L231-L238) finds your ```gmake``` and decides to produce a Makefile for ```gmake```. Unfortunately, at some point ```make``` is called.

Probably the installation instructions are not spot on, since they refer to ```make``` only.

If no-one beats me to it I'll try to take a closer look.

**Comment by usev6** [comment] 2020-03-20 20:44
Sorry, didn't want to close this.

Taking a second look it might really only be the installation instructions to be wrong ...

**Comment by pprocacci** [comment] 2020-03-20 20:44
Why close this if you are going to take a closer look?
It should be left open until someone actually does take a look.

It's worked in the past.  Why not now?

I don't use gmake.  Never have, and never needed to.
I'd suggest sticking with a build system that works everywhere (like it has in the past) ..
... instead of tailoring it to gnu specific utilities only.

Barring that, if the intention is to tailor the installation of raku to gnu specific utilities, instructions must be included to ensure those utilities exist prior to their attempted execution.

**Comment by pprocacci** [comment] 2020-03-20 20:45
Our comments crossed paths ... disregard the "why close this"

**Comment by pprocacci** [comment] 2020-03-20 20:47
On another note, I do have gmake installed.
The raku build system is failing to execute it (/usr/local/bin/gmake) and instead is executing the make that comes w/ FreeBSD /usr/bin/make

**Comment by usev6** [comment] 2020-03-20 23:23
Just two more data points:

On a clean machine with FreeBSD 11.3 (no ```gmake``` installed) following the build instructions from https://www.raku.org/downloads/ worked just fine.
```
# wget https://rakudo.org/downloads/star/rakudo-star-2020.01.tar.gz
# tar xfz rakudo-star-2020.01.tar.gz
# cd rakudo-star-2020.01
# perl Configure.pl --gen-moar --make-install --prefix ~/rakudo
[...]
NQP has been built and installed.
Using /root/rakudo/bin/nqp-m (version 2020.01 / MoarVM 2020.01.1).

Creating Makefile ...
Cleaning up ...
== Configuring and building Rakudo
cd rakudo && /usr/local/bin/perl Configure.pl  --prefix="/root/rakudo" --backends=moar && make
Using /root/rakudo/bin/nqp-m (version 2020.01 / MoarVM 2020.01.1).
Cleaning up ...

You can now use 'make' to build Rakudo.
After that, 'make test' will run some tests and
'make install' will install Rakudo.
+++ Checking for moar NQP version
+++ Expanding	gen/moar/main-version.nqp
[...]
```
There was no error during make. (I didn't wait for the compilation of Rakudo to finish, but that's not relevant here.)

After that I removed the extracted sources and the installed executables and tried again from scratch -- but with ```gmake``` installed:
```
# pkg install gmake
# tar xfz rakudo-star-2020.01.tar.gz
# cd rakudo-star-2020.01
# perl Configure.pl --gen-moar --make-install --prefix ~/rakudo
```
That command successfully built moar and NQP, but then died with the same error @pprocacci  reported:
```
[...]
NQP has been built and installed.
Using /root/rakudo/bin/nqp-m (version 2020.01 / MoarVM 2020.01.1).

Creating Makefile ...
Cleaning up ...
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 27: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 29: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 307: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 309: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 311: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 426: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 428: Need an operator
make[1]: "/opt/rakudo-star-2020.01/nqp/Makefile" line 430: Need an operator
make[1]: Fatal errors encountered -- cannot continue== Configuring and building Rakudo
cd rakudo && /usr/local/bin/perl Configure.pl  --prefix="/root/rakudo" --backends=moar && make
Using /root/rakudo/bin/nqp-m (version 2020.01 / MoarVM 2020.01.1).
Cleaning up ...

You can now use '/usr/local/bin/gmake' to build Rakudo.
After that, '/usr/local/bin/gmake test' will run some tests and
'/usr/local/bin/gmake install' will install Rakudo.
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 13: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 15: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 281: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 283: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 284: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 286: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 288: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 290: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 291: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 293: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 294: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 296: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 626: Need an operator
make[1]: "/opt/rakudo-star-2020.01/rakudo/Makefile" line 628: Need an operator
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /opt/rakudo-star-2020.01/rakudo
*** Error code 1

Stop.
make: stopped in /opt/rakudo-star-2020.01
Command failed (status 256): make
```

AFAICS the problem is that Rakudo Star's own build system only uses ```make``` (https://github.com/rakudo/star/blob/65f8cd4611/bundle/Configure.pl#L172 and https://github.com/rakudo/star/blob/65f8cd4611/tools/build/Makefile.in#L42), whereas the Makefile that is generated by Rakudo's Configure.pl uses the recently overhauled build system and prefers ```gmake``` if it can find it.

So it looks like the build system for Rakudo Star needs some updates.

The other question is, whether we are good with trying to prefer to use ```gmake``` and only use BSD's ```make``` as a fallback. That's how @vrurg++ implemented it in the last year(?). I guess there won't be many people who volunteer to touch the build system again.

**Comment by Kaiepi** [comment] 2020-03-21 02:14
> The other question is, whether we are good with trying to prefer to use gmake and only use BSD's make as a fallback. 

I wasn't much of a fan of there still being a dependency on `gmake` in certain cases on the *BSDs back then, and still am not now. This was a compromise, but I don't remember the specifics of why it was made.

**Comment by usev6** [comment] 2020-03-21 11:53
FWIW, this is a problem specific to Rakudo Star. Rakudo *does* build on FreeBSD. I've changed the title of the bug report accordingly.

**Comment by hankache** [comment] 2020-03-21 20:04
Maybe @Tyil would be able to help?

**Comment by hankache** [comment] 2020-03-21 20:19
Can you please transfer this issue to https://github.com/rakudo/star ?

**Comment by vrurg** [comment] 2020-03-22 23:26
Following the discussion, I can conclude that the problem comes from unsynced decisions made by Rakudo and Rakudo Start configure scripts. Whereas Rakudo chooses gmake to maintain maximum possible consistency in builds across different platforms, Star seemingly defaults to old plain make executable which is GNU Make on Linux and BSD Make on *BSD. There two solutions to the issue:

1. Rakudo might choose BSD make as the default on *BSD. I don't see a reason why should it do so if gmake is available which is the de-facto standard.
2. Rakudo Star incorporates nqp-configure framework and starts making same decisions as Rakudo does.

My personal preference is apparently 2. First, I already mentioned the consistency. Second, it's Rakudo Star to follow Rakudo, not the vice versa. We should not adapt the core project to an auxiliary one.

Unfortunately, I cannot take care of Rakudo Star currently both due to the lack of time and primarily because I don't use it and thus not well known with the demands implied. But I would assuredly assist as much as possible to anybody willing to re-implement Star's build subsystem around nqp-configure.

**Comment by Tyil** [comment] 2020-03-23 13:18
> Maybe @Tyil would be able to help?

I'm currently working on new scripts to handle Rakudo Star installation, but I
haven't tested anything on (Free)BSD yet. I have as much understanding of the
Makefile based approach that is in the current Rakudo Star codebase as anyone
else, sadly, and found it to be easier to just rewrite things as I go on.

FreeBSD is a target on my list of things to test for, as I use FreeBSD on some
machines myself, and also found that the latest Rakudo Star didn't play nice
anymore.

If you're interested in helping out in this endeavour (or just keeping track),
the repository in which I keep this experiment contained is on my own cgit
frontend: https://home.tyil.nl/git/rakudo-star-2.0/about/.

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

social: https://soc.fglt.nl/tyil
git:    https://home.tyil.nl/git

**Comment by Tyil** [comment] 2020-03-25 15:08
I've created an `alpha1` distribution that uses the new Bash based installation scripts, and made it available on https://dist.tyil.nl. I've created a vm with FreeBSD 12.1, using 2048mb memory and 2 cores. I've installed Rakudo Star using the following commands:

    pkg install ca_root_nss bash perl5 gcc
    fetch https://dist.tyil.nl/raku/rakudo-star/rakudo-star-2020.03-alpha1.tar.gz
    tar xzf rakudo-star-2020.03-alpha1.tar.gz
    cd rakudo-star-2020.03
    ./bin/rstar install

It installed in just over 6 minutes, and running `./bin/rakudo` gives me a REPL where Raku code seems to work. Installation of community modules seems to have failed, but I think I know how to fix it.

*Don't let the name fool you, `rakudo-star-2020.03-alpha1` uses MoarVM, NQP and Rakudo 2020.01! This alpha release is only to test the new Bash installer.*

**Comment by Altai-man** [comment] 2020-03-25 16:52
@Tyil does it mean a new Rakudo Star can be built and shipped with (presumably) 2020.03 release and this ticket can be closed?

**Comment by vrurg** [comment] 2020-03-25 17:07
@Tyil did you try it with gmake installed?

**Comment by Tyil** [comment] 2020-03-25 19:09
@Altai-man I can update it to use the 2020.03 components (moarvm/nqp/rakudo) and then we do have a release, though I am planning to do that in 2020.04 (release cycle is every 3 months). I made this alpha release in order to test for FreeBSD, and so @pprocacci can at least update their Rakudo Star installation if they need the updated version for any reason.

I'm mostly hesitant to just release a proper 2020.03 because while I tested it on a FreeBSD vm, I didn't test it for OpenBSD or various GNU+Linux distros, and there's currently no support *at all* for Windows or Mac builds. There needs to be at least something in place for those, but I'm unsure if @hankache has time to look into the Windows aspect, and I don't know who could assist for the Mac aspect.

@vrurg It's been a while ago since I tested it, but I'm sure I had `gmake` installed on the machine I tried it with. Regardless of that, I would still be mostly unfamiliar with the Makefile based approach, meaning I can't properly support it if people come around with issues.

**Comment by Altai-man** [comment] 2020-03-25 19:48
>I'm mostly hesitant to just release a proper 2020.03 because reasons

Sure, releasing it FreeBSD _only_ is not the best solution. I think having tested support for everything by 2020.03 (or a bit later) would be rather nice, but maybe out of our hands giving the time constraints.

Anyway, I am still a bit hesitant on this, but considering this is a rakudo star ticket and if we will be able to pull implementing&testing&releasing star off quickly, the issue will resolve itself, and if not it can be argued to not block rakudo release process.

**Comment by Tyil** [comment] 2020-03-25 22:40
@hankache already requested it to be moved to the rakudo/star repo for that reason, it's not an issue in Rakudo itself.

**Comment by hankache** [comment] 2020-03-26 16:36
@Tyil Actually the last Rakudo Star for Windows was built using https://github.com/hankache/rakudo-star-win. The build system of https://github.com/rakudo/star was not longer usable on Windows (this happened after Rakudo's build was overhauled with nqp configure, etc.) and I had to patch up something quick to produce an msi.

Since then I modified the scripts a bit and introduced a couple of enhancements that are Windows specific.

The repo can be used to build Rakudo Star on Windows pretty easily going forward. So making a 2020.03 release is very possible.

On the other hand I'd like to solicit some guidance for the Rakudo Star build process:
1) Should we keep the build separate (Windows and Linux/BSD/macOS) or should we try to unify them?
2) The https://github.com/rakudo/star repo is pretty useless at the moment.
Windows is being built using: https://github.com/hankache/rakudo-star-win
Linux/BSD/macOS is being built using:  https://home.tyil.nl/git/rakudo-star-2.0/about/
What should we do in terms of repo ownership? Should we moved them to the rakudo org? As new repo? as a branch of Rakudo/Star? etc.

**Comment by Tyil** [comment] 2020-03-26 20:02
1) I would *like* to see it unified, but I'm unsure if it's easy to do. If it's more cumbersome to combine everything, it's best we don't. I'm not very familiar with PowerShell, so I'm also unsure how hard it would be to port that script to bash. However, it's easy to put that script in the `lib` directory and just `exec` to PowerShell for Windows builds. We'll just say PowerShell is a dependency for Windows maintainers. I believe all (supported) Windows versions have it by default anyway, so it's not a big deal.

2) I'm personally not a fan of using GitHub, which is why I keep my repositories at my own location. However, I do understand people see value in using it, and we could make use of CI systems supported by GitHub if someone were to write the scripts for them. Besides, `git` is inherently decentralized, it's an easy job for me to simply push to two remotes for a release. We could also mirror it on GitLab if that would make contributions easier for interested people.

As for the location of the repository, I'm not part of the Rakudo team, and I'm unsure if you are. If neither of us are, I think the Rakudo organisation is an odd place for us to do work. We can place it in the Raku organisation, which could also more accurately signify it is not just Rakudo thing, but bigger than that.

**Comment by Tyil** [comment] 2020-04-06 16:40
@hankache Any thoughts on my reply?

---

I've continued with testing in the past week, and the scripts seem to work for FreeBSD, OpenBSD and the following GNU+Linux distributions:

- Fedora
- Archlinux
- CentOS
- Voidlinux
- Alpine
- Debian
- Ubuntu
- Gentoo

If anyone has suggestions for distributions that are commonly used that I should explicitly test for, let me know, so I can check it out. I'm testing these by running a Docker image of these distributions, and running the commands laid out in the README.md. FreeBSD and OpenBSD were tested in a VM.

jjatria is working on integrating building Docker images into the repository, but if I don't need to do much additional testing, I may try my hand at writing something up myself later this week.

**Comment by hankache** [comment] 2020-04-19 10:18
@Tyil sorry for the late answer, I did miss your reply.
Well done testing on Linux and BSDs!

Regarding your previous points:
1) PowerShell is native to Windows whereas Bash is not. Hence the transition to Bash would not be really helpful in this case. IMHO the only way to "unify" both builds is to use Make. Nevertheless I've thought about it for a bit and I think that keeping them separate would be beneficial in the long run. The Windows build has the potential to evolve into something much bigger _a la_ Strawberry Perl. It could possibly bundle GCC and Git so that users are not expected to install anything else on their machines as a prerequisite. GCC and Git are most probably present on all *nix machines but on Windows these have to be installed separately.
2) GitHub is where most of the Raku community collaborate hence my preference. I believe hosting these repositories on GH makes it easier for people to collaborate, open issues, send PRs, etc. But at the end of the day it's really your call, this is volunteer work so do as you please. When it comes to the windows build, it's currently hosted on GH under my handle, I would gladly move it to the rakudo org if necessary but unfortunately I do not have the required authorizations.

**Comment by Tyil** [comment] 2020-04-21 10:11
On Sun, Apr 19, 2020 at 03:18:28AM -0700, Naoum Hankache wrote:
> @Tyil sorry for the late answer, I did miss your reply.
> Well done testing on Linux and BSDs!
> 
> Regarding your previous points:
> 1) PowerShell is native to Windows whereas Bash is not. Hence the transition to Bash would not be really helpful in this case. IMHO the only way to "unify" both builds is to use Make. Nevertheless I've thought about it for a bit and I think that keeping them separate would be beneficial in the long run. The Windows build has the potential to evolve into something much bigger _a la_ Strawberry Perl. It could possibly bundle GCC and Git so that users are not expected to install anything else on their machines as a prerequisite. GCC and Git are most probably present on all *nix machines but on Windows these have to be installed separately.

In my experience, any build system that incorporates Windows support becomes a
pain to maintain, so I am not opposed to keeping the two seperate. So long as
we can get the Windows .msi packages available on the same downloads page, I
don't think it'll cause much confusion for end-users either.

I will update the README in my repository to be clear that Windows support is
handled by your repository, in case anyone finds a bug.

If there's anything I can tweak on my end to make it easier for you to keep
up-to-date with changes (such as version bumps, ecosystem module changes, ...),
please let me know, so I can look into it. I'm trying to keep most information
in simple text files, but it's easy to miss out on something.

> 2) GitHub is where most of the Raku community collaborate hence my preference. I believe hosting these repositories on GH makes it easier for people to collaborate, open issues, send PRs, etc. But at the end of the day it's really your call, this is volunteer work so do as you please. When it comes to the windows build, it's currently hosted on GH under my handle, I would gladly move it to the rakudo org if necessary but unfortunately I do not have the required authorizations.

I do not follow that belief, but again, it is trivial for me to push to
multiple repositories. I already use two mirrors at this point in time, adding
a third one on GitHub is not a big deal.

If none of the Raku project members oppose it, I will create a rakudo-star
repository in the Raku namespace, and start pushing updates there as well.

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

social: https://soc.fglt.nl/tyil
git:    https://home.tyil.nl/git

**Comment by dufresnep** [comment] 2023-02-27 04:15
I just successfully build rakudo on:
[paul@dufresnep ~/mymoar/MoarVM/install/bin]$ uname -a
FreeBSD dufresnep.ca 13.2-BETA3 FreeBSD 13.2-BETA3 releng/13.2-n254537-d0e8ce556627 GENERIC amd64
[paul@dufresnep ~/mymoar/MoarVM/install/bin]$ ls -lh
total 1283
-rwxr-xr-x  1 paul  paul    81K Feb 26 22:42 moar
-rwxr-xr-x  1 paul  paul    81K Feb 26 22:52 nqp
-rwxr-xr-x  1 paul  paul    81K Feb 26 22:52 nqp-m
-rwxr-xr-x  1 paul  paul    85K Feb 26 23:01 perl6
-rwxr-xr-x  1 paul  paul    86K Feb 26 23:01 perl6-debug
-rwxr-xr-x  1 paul  paul    86K Feb 26 23:01 perl6-debug-m
-rwxr-xr-x  1 paul  paul   1.9K Feb 26 23:01 perl6-gdb-m
-rwxr-xr-x  1 paul  paul   1.7K Feb 26 23:01 perl6-lldb-m
-rwxr-xr-x  1 paul  paul    85K Feb 26 23:01 perl6-m
-rwxr-xr-x  1 paul  paul   1.6K Feb 26 23:01 perl6-valgrind-m
lrwxr-xr-x  1 paul  paul     6B Feb 26 23:01 raku -> rakudo
lrwxr-xr-x  1 paul  paul    12B Feb 26 23:01 raku-debug -> rakudo-debug
-rwxr-xr-x  1 paul  paul    85K Feb 26 23:01 rakudo
-rwxr-xr-x  1 paul  paul    86K Feb 26 23:01 rakudo-debug
-rwxr-xr-x  1 paul  paul    86K Feb 26 23:01 rakudo-debug-m
-rwxr-xr-x  1 paul  paul   1.9K Feb 26 23:01 rakudo-gdb-m
-rwxr-xr-x  1 paul  paul   1.7K Feb 26 23:01 rakudo-lldb-m
-rwxr-xr-x  1 paul  paul    85K Feb 26 23:01 rakudo-m
-rwxr-xr-x  1 paul  paul   1.6K Feb 26 23:01 rakudo-valgrind-m
[paul@dufresnep ~/mymoar/MoarVM/install/bin]$ 

Was blindly following instructions from:
https://github.com/MoarVM/MoarVM

gmake test said all tests passed.

After gmake install:
[paul@dufresnep ~/mymoar/MoarVM/install/bin]$ ./rakudo
Welcome to Rakudo™ v2023.02.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.02.

**Closed** 2024-10-12 15:47 UTC
Labels: regression
