### ISSUE TITLE
“Cannot call method 'typed_panic' on a null object” when trying to use v6.e or v6.e.PREVIEW

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2783] opened 2019-03-22 23:12 UTC
```perl6
use v6.e.PREVIEW
```
or
```perl6
use v6.e
```

Output:
```
===SORRY!===
Cannot call method 'typed_panic' on a null object
```

**Comment by AlexDaniel** [comment] 2019-03-22 23:40
This commit should have enough clues on how to add v6.e.PREVIEW support: https://github.com/rakudo/rakudo/commit/46ef0ea08cae96db25c7b5a9543ba696034408c8

That said, versions beyond 6.e shouldn't have weird issues with null objects.

**Comment by vrurg** [comment] 2019-03-24 00:25
The implementation of `load-lang-ver` looks like a quick hack to enable `6.d` only. 

Correct me if I'm wrong, but for `6.e+` core setting must be loaded for 'd', 'e', etc. Correspondingly, the settings must be built for each version too.

**Comment by vrurg** [comment] 2019-03-25 22:26
I spent some of my spare time looking into the ways of adding 'e' to the list of versions. Here is what I came up with.

Do we really need `.PREVIEW` version? What real difference does it make to just `v6.X`? As I see a version life cycle, at some point a new letter pops up in the master branch while its predecessor is been kept as the default. So, anyone willing to test, say, `.e` simply does `use v6.e;`. Then it takes over as the default when the language is ready.

Next. The built subsystem is better be redone. It was hacked to incorporate `6.d` stuff. Adding `e` and further versions would require some handwork and copy-paste. Not that I'd be happy spending time on this, but it's beyond my patience to see chunks of make files being just copied over with just one char changing. I'd like to reduce the amount of changes to as much as adding the new letter somewhere in a file, creating necessary directories – and then have everything else be done automatically.

With regard to the NQP code – besides of 46ef0ea there is 4a6d91083 too.

**Comment by vrurg** [comment] 2019-03-25 22:28
And, BTW. The more I think of it the more it looks like consensus is required on how exactly the versions are to be handled. Perhaps one more issue for problem solving?

**Comment by ugexe** [comment] 2019-03-25 22:30
> Do we really need .PREVIEW version?

Yes, it would be a regression to remove it since there are lots of slide (and potentially live code) that have `use v6.d.PREVIEW`

**Comment by vrurg** [comment] 2019-03-25 22:32
I'm not proposing removing `v6.d.PREVIEW`. But is there reason to have it with `v6.e`?

**Comment by ugexe** [comment] 2019-03-25 22:37
Code using `.PREVIEW` is accepting that something might change in the new spec. If I'm a new user and I don't know that `6.e` is in testing and `use v6.e` works then I'm liable to write code that may break when upgrading rakudo.

**Comment by vrurg** [comment] 2019-03-25 22:47
Ok. Not sure how helpful is this, but the point is taken. Thanks!

**Comment by AlexDaniel** [comment] 2019-03-25 23:35
@vrurg well, what's the other option? We can't make `use v6.e` available if it's not released yet. That's just not right.

FWIW there are [11 modules that still use v6.d.PREVIEW](https://gist.github.com/Whateverable/239ab1d53f43662673188cf0bd4df1fc). One even declares it in META6.json. It's an interesting problem, maybe there's a better solution. For example, one alternative is to have `use PREVIEW` or something similar, so that it always uses the latest version. That's not better, I think, but I just wanna say that there are options.

**Comment by vrurg** [comment] 2019-03-26 16:50
The thing which confuses me is that internally rakudo doesn't make difference between `6.d` and `6.d.PREVIEW`. So, it's just a political decision as it seems. From that point of view I really don't see a difference between `v6.e` and `v6.e.PREVIEW` when running the `master`. Though what would make difference to me is a warning message on use of `PREVIEW` after the language is released because that'd be a signature of non-production code.

Just to make it clear: I'm not objecting but trying to gain more understanding.

**Comment by ugexe** [comment] 2019-03-26 17:17
I can only reiterate what I've stated:

Leading up to `6.d` it was desired to show off the schematics, and those schematics could still change until the `6.d` release. During this period of time one would have to write code using `use v6.d.PREVIEW` to use the new features. Because of the `.PREVIEW` the module author is almost certainly aware that functionality may change from underneath them in the future, and so is anyone reading the code. If instead we allowed people to `use v6.d` to test new features that may change then we have to make a huge point that anyone using e.g. `use v6.d` is NOT using a stable version until some arbitrary date is reached.

So it doesn't matter if we break someones code that is using `.PREVIEW` because they have explicitly opted into this situation. The person doing `use v6.d;` is almost certainly unaware if they are using a stable version or not unless explicitly told by someone in the know.

> The thing which confuses me is that internally rakudo doesn't make difference between 6.d and 6.d.PREVIEW

Once `6.d.` got released there is no difference. Up until `6.d.` was released there was a difference -- one had to opt into the possibly changing schematics via `use v6.d.PREVIEW`. They couldnt write code using `use v6.d` that WOULD NOT work on the actual `v6.d` release.

**Comment by vrurg** [comment] 2019-03-26 17:50
> > The thing which confuses me is that internally rakudo doesn't make difference between 6.d and 6.d.PREVIEW
> 
> Once `6.d.` got released there is no difference. Up until `6.d.` was released there was a difference -- one had to opt into the possibly changing schematics via `use v6.d.PREVIEW`. They couldnt write code using `use v6.d` that WOULD NOT work on the actual `v6.d` release.

This is external, not internal difference. Technically, rakudo core doesn't differentiate between the two. This is what primarily matter to me now because I'm currently working on the build process and on adding `.e`.

Considering all the points sounded here, I would conclude that the right thing would be to:

- don't allow `v6.X` prior to its release. Require `v6.X.PREVIEW` instead for early testers
- perhaps there must be a point in time of stable pre-release which is transitional time allowing both versions to be used but pushing towards the `v6.X` but not making it the default yet.
- release disables `.PREVIEW` altogether?

Just my thoughts.

Anyway, more important questions are outspoken in rakudo/rakudo#1289. I wish they had more focus, though not in this thread.

**Comment by niner** [comment] 2019-03-26 18:49
The plan was to remove support for .PREVIEW at some point after the release of the new language version. That would be a good point for the user to check if the released language actually conforms to how the PREVIEW version behaved or if the user's code needs adaptions.

However, after release of 6.d there was no pressure and therefore no consensus to actually disable support for 6.d.PREVIEW.

**Comment by vrurg** [comment] 2019-04-17 23:58
While awaiting for my build revamp work to be merged, I got time to continue solving this issue.

46ef0ea isn't the only commit related, there is also 4a6d910839f9c9acee768bccfd4882626ff3e1d8. I have certain doubts about it. On the first glance it's done so as to allow `6.d` to arise but without a thought about the next releases. When it initiates loading of `CORE` setting instead of `NULL.d` it's ok. But I have a strong feeling that for `6.e` `CORE.d` must be loaded, and so on.

If I'm right, it's not a big deal to get fixed. What I'm not exactly sure about is if loading `CORE.d` automatically pulls `CORE`? Considering that `CORE` is set as outer context for `CORE.d` I guess it should.

**Comment by vrurg** [comment] 2019-04-18 03:02
I've got a [branch](https://github.com/vrurg/rakudo/tree/add_version_6e) with a fix for `typed_panic` and specification `e` added. Though it is based on #2816 and thus is not ready for PR yet.

**Closed** 2019-05-31 00:42 UTC
Labels: 6.e
