### ISSUE TITLE
<1/3>.base(10, *) hangs/timeout

### ISSUE THREAD

**Issue by lucasbuchala** [rakudo/rakudo#1872] opened 2018-05-26 14:47 UTC
```
> say <1/2>.base(10, 5)
0.50000

> say <1/3>.base(10, 5)
0.33333

> say <1/2>.base(10, *)
0.5

> say <1/3>.base(10, *)
(Program hangs)
```

This is Rakudo version 2018.05 built on MoarVM version 2018.05 implementing Perl 6.c.

**Comment by zoffixznet** [comment] 2018-05-26 18:17
This seems to be [as-documented](For Rationals, the Whatever indicates that you wish all of the possible digits of the fractional part, but use caution: since there's no detection of repeating fractional parts (the algorithm will eventually stop after generating 2**63 digits)):

> For Rationals, the Whatever indicates that you wish all of the possible digits of the fractional part, but use caution: since there's no detection of repeating fractional parts (the algorithm will eventually stop after generating 2**63 digits).

Fixing this is blocked by the Halting Problem, isn't it?

**Comment by zoffixznet** [comment] 2018-05-26 20:43
Ah right. Some googlefoo for possible solutions: https://softwareengineering.stackexchange.com/a/192077

**Comment by AlexDaniel** [comment] 2018-05-26 20:46
But what's the expected behavior? (assuming we can detect this)

**Comment by zoffixznet** [comment] 2018-05-26 20:58
> But what's the expected behavior? (assuming we can detect this)

From that link:

> The number of digits in the repeating portion of the decimal expansion of a rational number can also be found directly from the multiplicative order of its denominator.

How about full non-repeating decimal + 1 instance of repeating portion? We probably have the algo in `.base-repeating` already, no?

```
$ perl6 -e 'use MONKEY; augment class Rat { method non-hang-base (\b, \p) { 
    self.base: b, p unless p.WHAT =:= Whatever; 
    self.base-repeating(b).join.Numeric } 
};  say .non-hang-base: 10, * for ½, ⅓, <1/19>'
0.5
0.3
0.052631578947368421
```

**Comment by zoffixznet** [comment] 2018-05-26 20:59
> 1 instance of repeating portion?

Hm, maybe something a bit smarter than that, since `⅓ -> 0.3` loses quite a bit of precision.

**Comment by colomon** [comment] 2018-05-26 21:18
Is there some fancy Unicode trick we could use to mark repeating digits?

**Comment by zoffixznet** [comment] 2018-05-26 21:35
I'd expect the resultant string to be numifiable:

```
<Zoffix_> m: say +"5.81̅4̅4̅"
<camelia> rakudo-moar 01a373649: OUTPUT: «Cannot convert string to number: trailing characters after number in '5.8⏏1̅4̅4̅' (indicated by ⏏)␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by lizmat** [comment] 2020-01-10 10:58
I think this is a DIHWIDT case, as it is documented to be hanging when the value can not be easily represented.  With https://github.com/rakudo/rakudo/commit/97e7cdbd54 I've added a `:no-trailing-zeroes` option so that you *can* specify a large number for the precision *and* still have it remove trailing zeroes (which previously was impossible, and one of the reasons the `Whatever` parameter exists).  Therefore closing this issue.

**Closed by lizmat** 2020-01-10 10:58 UTC
Labels: rationals, stringification
