### ISSUE TITLE
In signature, a Mu/Any typed positional codegens a read-only container, other types do not

### ISSUE THREAD

**Issue by dakkar** [rakudo/rakudo#3387] opened 2019-12-28 17:59 UTC
## The Problem

```perl6
use v6.d;
use Test;

subtest 'untyped parameters' => {
    my BagHash $foo;

    sub count($a,$b) {
        $foo{$a=>$b}+=1;
    }

    count('a','b');
    count('a','b');

    is-deeply(
        $foo.keys,
        @( 'a'=>'b' ),
        'should have 1 key',
    )
}

subtest 'typed parameters' => {
    my BagHash $foo;

    sub count(Str $a, Str $b) {
        $foo{$a=>$b}+=1;
    }

    count('a','b');
    count('a','b');

    is-deeply(
        $foo.keys,
        @( 'a'=>'b' ),
        'should have 1 key',
    )
}

done-testing;
```

## Expected Behavior

Test pass.

## Actual Behavior

```
    not ok 1 - should have 1 key
    # Failed test 'should have 1 key'
    # at p.p6 line 14
    # expected: $(:a("b"),)
    #      got: $(:a("b"), :a("b"))
    1..1
    # You failed 1 test of 1
not ok 1 - untyped parameters
# Failed test 'untyped parameters'
# at p.p6 line 4
    ok 1 - should have 1 key
    1..1
ok 2 - typed parameters
    ok 1 - should have 1 key
    1..1
ok 3 - constructor
1..3
# You failed 1 test of 3
```
## Environment
* Operating system: Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1

**Comment by lizmat** [comment] 2019-12-28 19:19
This is weird

**Comment by lizmat** [comment] 2019-12-28 19:24
Ok, it *does* count them correctly, but somehow in the first case, the two pairs have different `.WHICH`es

**Comment by dakkar** [comment] 2019-12-28 19:35
ah, yes, I should have noticed!

so, smaller test:
```perl6
use v6.d;
use Test;

subtest 'untyped parameters' => {
    sub mk($a,$b) {
        return $a=>$b;
    }

    is mk('a','b').WHICH,mk('a','b').WHICH;
}

subtest 'typed parameters' => {
    sub mk(Str $a, Str $b) {
        return $a=>$b;
    }

    is mk('a','b').WHICH,mk('a','b').WHICH;
}

done-testing;
```

**Comment by lizmat** [comment] 2019-12-28 19:37
Ok, the underlying issue is indeed in the signature.  Observe:

    $ raku -e 'use nqp; sub a($a) { nqp::iscont($a) }; dd a "foo"'
    1
    $ raku -e 'use nqp; sub a(Str $a) { nqp::iscont($a) }; dd a "foo"'
    0

A `Pair` will only be a value type when created without any containers.  So in the first case, it won't be a value type, so each `Pair` will be different from any other `Pair` (even if they have the same value).  In the second case, there are no containers, so that `Pair` *does* become a value type, so the two `Pair`s *will* be seen as identical.

Note that it is not the absence of the type, but the fact that it is `Any` (which is the default):

    $ raku -e 'use nqp; sub a(Any $a) { nqp::iscont($a) }; dd a "foo"'
    1

Renaming the issue accordingly.

**Comment by lizmat** [comment] 2019-12-28 19:44
@dakkar: thanks for the test, but I think that's testing the derived issue with `Pair`.  The issue is really why there is a container for the `Mu/Any` case, and not for other cases.  Pretty sure the container in the first case, is not needed, and may actually improve performance if we can get rid of it.

**Comment by dakkar** [comment] 2019-12-28 19:49
I agree, your test (checking`nqp::iscont`) is simpler and more focused!

**Comment by jnthn** [comment] 2020-02-11 16:30
When the incoming argument is typed such to something that is not `Iterable`, the code-gen omits the container. This optimization saves an *enormous* number of `Scalar` allocations. In the case of `Any` / `Mu` we conservatively wrap the value (same if you were to write `Array $foo`).

**Comment by dakkar** [comment] 2020-02-11 16:38
@jnthn I'm not sure what the implication of your comments are… should code assume that all argumens have containers? If that's the case, how do I write a sub that produces `Pair`s with stable `WHICH`?

**Comment by dakkar** [comment] 2020-03-05 20:22
More testing:
```perl6
sub test(Callable $c) {
    say "using {$c.name}";
    my $a='a';my $b='b';
    my $p1=$c($a,$b);
    my $a2='a';my $b2='b';
    my $p2=$c($a2,$b2);
    say "{$p1.WHICH} =?= {$p2.WHICH} >> { $p1.WHICH eq $p2.WHICH }";
}

test sub pair-sigilless(\a,\b) { return Pair.new(a,b) }
test sub pair-any($a,$b) { return Pair.new($a,$b) }
test sub pair-str(Str $a, Str $b) { return Pair.new($a,$b) }
test sub pair-str-raw(Str $a is raw, Str $b is raw) { return Pair.new($a,$b) }
test sub pair-raw($a is raw, $b is raw) { return Pair.new($a,$b) }
test sub pair-decont($a, $b) { return Pair.new($a<>,$b<>) }
```
produces:
```
using pair-sigilless
Pair|94276172318512 =?= Pair|94276172318568 >> False
using pair-any
Pair|94276172320080 =?= Pair|94276172320136 >> False
using pair-str
Pair|47AA52B211B8C79C5A2F59FE5EA3CF9519225499 =?= Pair|47AA52B211B8C79C5A2F59FE5EA3CF9519225499 >> True
using pair-str-raw
Pair|94276172506136 =?= Pair|94276172506192 >> False
using pair-raw
Pair|94276172506248 =?= Pair|94276172506304 >> False
using pair-decont
Pair|47AA52B211B8C79C5A2F59FE5EA3CF9519225499 =?= Pair|47AA52B211B8C79C5A2F59FE5EA3CF9519225499 >> True
```

Is this behaviour desired? I see two pieces that need either documentation, or spectests:
* a Pair will only create a value-type when created without containers
    * the docs for Pair mention `.freeze` and de-containerising, but don't mention that they're needed to get value-type pairs
* sometimes calling a sub creates containers, sometimes it doesn't
    * we may decide that this is implementation-defined, but should be documented

**Comment by lizmat** [comment] 2024-10-12 14:59
`Pair` can never be a ValueType anymore, so closing

**Closed by lizmat** 2024-10-12 14:59 UTC
