### ISSUE TITLE
Some sort of regression in Red module

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2640] opened 2019-01-24 05:53 UTC
https://github.com/FCO/Red

```output
# Failed test at t/04-blog.t line 46
# Something went wrong in (NoMatch)
# Failed test 'The object is-a 'Post''
# at t/04-blog.t line 47
# Actual type: Any
No such method 'author-id' for invocant of type 'Any'
  in block <unit> at t/04-blog.t line 48
```

Bisected: any of 4bb5c33c72c53914c6e8676d17c35be66fc2efc9 e87b7afb0d23b50bc5c2cf14572a3aee511b40fd, but I'm not 100% confident

Note that if you run all tests (not just `t/04-blog.t`) you will probably see this also:
```
MoarVM panic: Trying to unwind over wrong handler

…

Test Summary Report
-------------------
t/06-better-map.t                (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
```

I *think* it is a different unrelated bug.

:pancakes:

**Comment by jonathanstowe** [comment] 2019-01-24 07:16
The MoarVM panic was seen in https://github.com/FCO/Red/pull/92# too.

**Comment by jonathanstowe** [comment] 2019-01-24 09:37
Removing the ```lives-ok``` from two lines above in the test the actual Exception is:

```
Died with X::Multi::NoMatch
  in method translate at /home/jns/me/Red/lib/Red/Driver/CommonSQL.pm6 (Red::Driver::CommonSQL) line 1
  in block  at /home/jns/me/Red/lib/Red/Driver/CommonSQL.pm6 (Red::Driver::CommonSQL) line 307
  in method translate at /home/jns/me/Red/lib/Red/Driver/CommonSQL.pm6 (Red::Driver::CommonSQL) line 302
  in method prepare at /home/jns/me/Red/lib/Red/Driver/SQLite.pm6 (Red::Driver::SQLite) line 26
  in method execute at /home/jns/me/Red/lib/Red/Driver.pm6 (Red::Driver) line 25
  in method save at /home/jns/me/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 212
  in method create at /home/jns/me/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 225
  in method create at /home/jns/me/Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 274
  in block <unit> at t/04-blog.t line 47

```

This does seem to be caused by some change in Rakudo though, but just to be on the safe side I'll stick a ticket on Red (@FCO is in the process of  moving at the moment AFAIK.)

**Comment by jonathanstowe** [comment] 2019-01-24 09:42
Also it seems from inserting some diagnostics into the code it could indeed be related to the commits you bisected to as something is winding up as a 'set' at that point.

**Comment by jonathanstowe** [comment] 2019-01-24 11:16
Ah, golfed it:

```
perl6 -e 'Set.HOW ~~ Metamodel::EnumHOW'
Died with X::Multi::NoMatch
  in block <unit> at -e line 1
```

So that'll definitely be a regression in Rakudo then.

**Comment by FCO** [comment] 2019-01-24 17:14
I think the problem is with `Set.HOW`:

https://colabti.org/irclogger/irclogger_log/perl6?date=2019-01-24#l343

**Comment by jonathanstowe** [comment] 2019-01-24 19:20
Yeah, the ```Set.HOW``` appears to have an anonymous role applied to it,  but the commits above appear to only apply a mixin when the ```Set``` is parameterized and nothing that would break the ```ACCEPTS```` anyway.  I'm a bit confused.

**Comment by lizmat** [comment] 2019-01-24 22:42
Further golfed to:

    $ perl6 -e 'Mu.ACCEPTS(Set.HOW)'
    Cannot resolve caller ACCEPTS(Mu:U: Perl6::Metamodel::ClassHOW+{<anon>}); none of these signatures match:
        (Mu:U: \topic, *%_)
        (Mu:U: Mu:U \topic, *%_)

So apparently `Set.HOW` is not a `Mu`, and `Metamodel::EnumHOW` **is**?

**Comment by FCO** [comment] 2019-01-25 02:35
I think Set is not being composed:
https://colabti.org/irclogger/irclogger_log/perl6?date=2019-01-25#l124

**Comment by lizmat** [comment] 2019-01-25 10:38
FWIW, this also happens with other classes that have a `^parameterize` method:

    $ perl6 -e 'say Array.HOW ~~ Metamodel::EnumHOW'
    Cannot resolve caller ACCEPTS(Perl6::Metamodel::EnumHOW:U: Perl6::Metamodel::ClassHOW+{<anon>}); none of these signatures match:
    ....

**Comment by lizmat** [comment] 2019-01-25 21:35
Temporary fix committed with 71a19c61a2

**Comment by AlexDaniel** [comment] 2019-01-25 22:12
OK, blocker label removed. If there's still an issue I'll see in during the next run of Blin.

I added `rerevert` label because there's no other label… Maybe `rerevert` should be called `fix properly` or something like that.

**Comment by lizmat** [comment] 2019-11-30 16:09
Reverted the temporary fix with https://github.com/rakudo/rakudo/commit/1d8d62d46d  Leaving it up to @FCO to close this ticket.

**Closed** 2020-03-13 15:20 UTC
Labels: rerevert
