### ISSUE TITLE
Using a hash variable in a regex should give a better error message

### ISSUE THREAD

**Issue by moritz** [rakudo/rakudo#1367] opened 2018-01-05 21:13 UTC
## The Problem

    < moritz> m: my %h = a => 'b'; say 'b' ~~ / %h /
    <+camelia> rakudo-moar 8023d2129: OUTPUT: «P6opaque: no such attribute 
                 '$!reified' on type List in a Seq when trying to get a value␤  
                 in block <unit> at <tmp> line 1␤␤»

This is, of course, not a good error message

## Expected Behavior

S05 speculates:

> The use of a hash variable in patterns is reserved.

So a nice, compile-time error message would be better

## Environment
* Operating system: Ubuntu Linux (but should be independent)
* Compiler version (`perl6 -v`): This is Rakudo version 2017.12-98-gffabfdb built on MoarVM version 2017.12-20-g5710340
implementing Perl 6.c.

**Comment by zoffixznet** [comment] 2018-01-05 22:17
Dupe of [RT#131243](https://rt.perl.org/Ticket/Display.html?id=131243#ticket-history). Closing that one in favour of this ticket.

**Comment by lizmat** [comment] 2018-01-05 23:13
Hmmm.. I guess we need to reference the issue in the first line?

**Comment by zoffixznet** [comment] 2018-01-05 23:32
> I guess we need to reference the issue in the first line?

Any mention of the full URL or the number with a hash (#1367) adds an automatic reference and prefixing that with "Fixes" or "Closes" (and [a bunch of other variations](https://help.github.com/articles/closing-issues-using-keywords/)) will automatically close the Issue, when the commit is comes into the master branch.

The full-URL reference works even across different repos (with auto-close done if you have the commit bit)

**Closed** 2018-01-06 00:20 UTC
Labels: testneeded
