### ISSUE TITLE
some typed Arrays don't match same-typed Positionals

### ISSUE THREAD

**Issue by dakkar** [rakudo/rakudo#3383] opened 2019-12-26 21:41 UTC
## The Problem

```perl6
use Test;

ok(Array ~~ Positional);
ok(Array[Str] ~~ Positional);
ok(Array[Str] ~~ Positional[Str]);
ok(Array[Str:D] ~~ Positional);
ok(Array[Str:D] ~~ Positional[Str]);
ok(Array[Str:D] ~~ Positional[Str:D]);
done-testing;
```

## Expected Behavior

All tests pass.

## Actual Behavior

`Array[Str:D] ~~ Positional[Str:D]` fails

## Environment
* Operating system: linux
* Compiler version (`perl6 -v`): This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1

**Comment by vrurg** [comment] 2019-12-27 14:47
This is actually by design. Simply consider `Str:D ~~ Str:D`. `Str:D` can only accept defined strings whereas `Str:D` itself isn't. `Str:D =:= Str:D` or `Str:D === Str:D` do the right thing, but that's not a solution to your case. So far, the closest thing I came up with is:

```
Positional[Str:D] ~~ any Array[Str:D].^roles # True
```

**Comment by dakkar** [comment] 2019-12-27 15:10
If true, that's quite annoying.
The context I initially encontered the problem in, was in a sub return type, something like:
```perl6
sub foo(--> Positional[Str:D]) { return my Str:D @ = qw[a b c] }
```
and it fails type-checking the return value.

Is there any way to declare (to the compiler, and callers) that a sub will return guaranteed-defined strings? (let's ignore for the moment the weird syntax that seems to be required to even have a typed literal)

**Comment by vrurg** [comment] 2019-12-27 18:00
Unfortunately, not yet. Though there is a workaround. But first I wonder what do you need the return constraint of this form for? `Str:D` in array declaration does the job for you already anyway.

Potentially, something like this would do the job:

```
sub foo(--> Positional where *.values».defined.all) { ... }
```

But this form is not implemented yet. However, we have subsets!

```
subset PosStrD of Positional where *.values».defined.all;
sub foo ( --> PosStrD ) { my Str @ = ["A", Str] } # Type check failed for return value; expected DP but got Array[Str] (Array[Str].new("AA", Str))
```

Note though that this has a performance tag attached.

**Comment by dakkar** [comment] 2019-12-27 18:28
«what do you need the return constraint of this form for?»
Because I want to guarantee to the caller (and the compiler, and the optimiser) that there won't be any undefined values in there.

But if this is not a valid use of Raku's type system, I'll just have to do without.

**Comment by vrurg** [comment] 2019-12-27 18:54
Depending on the complexity of your function or method, constraining an array that you're returning could be somewhat more efficient from performance point of view. At least for now.

If you're not trying to squeeze out a couple of CPU cycles, then the subset solution would be quite the thing to have.

Unfortunately, for the moment I don't see other solutions as this is how smartmatch works.

**Comment by vrurg** [comment] 2019-12-28 01:55
It turns out there is a solution for this problem. So, I re-open for a while.

**Comment by vrurg** [comment] 2019-12-28 03:42
#3385 fixes this. Closing.

**Closed by vrurg** 2019-12-28 03:42 UTC
Labels: parameters/arguments, roles, smartmatch

**Comment by dakkar** [comment] 2019-12-28 13:48
thank you! you've made the type system more useful and more intuitive!
