### ISSUE TITLE
Using `done` in a tap outside react / supply is not caught properly

### ISSUE THREAD

**Issue by demanuel** [rakudo/rakudo#5330] opened 2023-08-01 13:25 UTC
## The Problem

I was playing with "interval" and wrote the following one liner:

[0] > Supply.interval(1).tap({.say; done if $_ == 10})
0
Tap.new
[1] > 1
2
3
4
5
6
7
8
9
10
No exception handler located for catch
   at SETTING::src/core.c/Supply-factories.pm6:64  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Supply-factories.pm6:64  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from <unknown>:1  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Exception.pm6:65  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/Exception.pm6:625  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:print_control)
 from SETTING::src/core.c/Exception.pm6:644  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:<anon>)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:256  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:254  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:253  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/control.pm6:20  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:THROW-NIL)
 from SETTING::src/core.c/control.pm6:236  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:done)
 from <unknown file>:1  (<ephemeral file>:)
 from SETTING::src/core.c/Supply-factories.pm6:65  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Lock/Async.pm6:132  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:protect)
 from SETTING::src/core.c/Supply-factories.pm6:65  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:266  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:247  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:244  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:run-one)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:295  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Thread.pm6:69  (/usr/share/perl6/runtime/CORE.c.setting.moarvm:THREAD-ENTRY)

## Expected Behavior
To not die

## Environment
* Operating system: 
```
$ uname -a
Linux archlinux 6.4.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 27 Jul 2023 22:02:18 +0000 x86_64 GNU/Linux
``` 
* Compiler version (`perl6 -v` or `raku -v`):
```
raku -v
Welcome to Rakudo™ v2023.06-121-g947b49c90.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.06-1-g63af27399.
```

**Comment by lizmat** [comment] 2023-08-01 14:44
The problem is really that `done` is only legal within a `supply` or `react` block, and that the error telling you that, aka `X::ControlFlow.new(illegal => "done", enclosing => "supply or react")` (or as text "done without supply or react"), is somehow caught incorrectly.

The correct way of using `done`:
````raku
react whenever Supply.interval(1) { .say; done if $_ == 10 }
````

**Comment by lizmat** [comment] 2023-08-01 14:51
Leaving the issue open because of the LTA error message

**Comment by demanuel** [comment] 2023-08-01 15:00
@lizmat indeed. The error message is wrong, but it shouldn't kill the raku process as well.

**Comment by vrurg** [comment] 2023-08-01 15:03
An unhandled exception must kill a process.

**Comment by demanuel** [comment] 2023-08-01 15:08
@vrurg right, but i don't remember any time where i wrote bad code in the python REPL and it died... Maybe i'm wrong.

**Comment by lizmat** [comment] 2023-08-01 15:10
@demanuel And that is indeed the problem.  The outer `CATCH` reports this error and then has no other option than to kill the process.  There should be an inner `CATCH` that should have caught the error and reported it.

**Comment by vrurg** [comment] 2023-08-01 15:22
To be precise, the error message comes from the backend which can't find an exception handler installed by the code. Most likely, this is caused by an independent thread and, if memory serves me right, we don't install handlers in threads. Perhaps because they're supposed to be started via `Promise` which does the handling.

**Comment by lizmat** [comment] 2024-10-20 12:48
Closing because even *if* we would create a better error message, it would still not have any other option but to exit the process (as it runs in a completely different thread from the REPL's thread, and there is no way that the exception handler can relate that back to the REPL).

**Closed by lizmat** 2024-10-20 12:48 UTC
Labels: LTA, REPL
