### ISSUE TITLE
v6.d fails to buffer large inputs 

### ISSUE THREAD

**Issue by lembark** [rakudo/rakudo#3086] opened 2019-07-29 01:48 UTC
Reading a large file published by NCBI and available at 
[ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz](ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz)
This is in FASTA format:

  >header information\n   <--- newline separator
  sequence\n                   <--- newline embedded in sequence
  more seq\n
  > next header\n             <--- next entry begins with a leading '>'
  sequence
  EOF                              <--- EOF may leave last sequence w/o newline.

The leading '>' starts an entry, header is separated from the sequence by a newline. The header
is not published without a sequence, so even on EOF there should be at least one newline in
each entry separating the header and sequene.

In this case the headers and sequences are often hundreds of KB, up to MB.

My expected behavior is:
```

with $*IN
{
  .nl-in( '>' );

  .lines
  .skip(1)
  .map( { my $i = .index( "\n" ) // die "Missing newline..."; Empty } )
}
```

should read the entire input without any errors, processing chunks delimited by '>', allocating memory as necessary to  accommodate the input, with a least one newline found within $_
after the header. After skipping the leading (empty) string the '> will behave as post-
delimiters.

## Actual Behavior

Simple reader using nl-in = '>':
https://pastebin.com/ei2LCs2G

Feeding it the current nr.gz file leaves me with repeatable errors:
https://pastebin.com/TGF7QKV6

The same input fed via gzip -dc < nr.gz | ./pass1 or prior-unzip with direct input (i.e., avoiding the pipe) yields identical results; reading un-zipped copy of the nr file reading from tmpfs to avoid any disk I/O issues gets identical results.

## Environment

* Operating system: 
(1) Thinkpad w/ 4GiB RAM, Intel(R) Core(TM) i7-7500U CPU:
Linux steamer 5.1.7-gentoo.at #1 SMP Fri Jun 7 17:04:25 CDT 2019 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux 
(2) SuperMicro 128GiB RAM, AMD Opteron(tm) Processor 6172
Linux dizzy 5.1.15-gentoo.domu-ac #2 SMP Tue Jul 9 23:16:28 CDT 2019 x86_64 AMD Opteron(tm) Processor 6172 AuthenticAMD GNU/Linux

* Compiler version (`perl6 -v`): 
Both systems:
This is Rakudo version 2019.03.1-585-gb8669fe6f built on MoarVM version 2019.05-49-gfbb1ddd8e
implementing Perl 6.d.

* If it matters:
gcc (Gentoo 9.1.0-r1 p1.1) 9.1.0

**Comment by AlexDaniel** [comment] 2019-07-29 05:35
If someone can come up with a way to generate the data instead of downloading a 48.6 GB file I'd highly appreciate it.

**Comment by AlexDaniel** [comment] 2019-07-29 05:38
Also, what are the errors exactly? I looked at https://pastebin.com/TGF7QKV6 but it seems to be outputting some data without errors? Should it output something different? If yes, what should it be?

**Comment by pprocacci** [comment] 2019-08-25 08:52
I was playing around with this myself just to see if I could figure it out.
The problem isn't with large inputs.  The problem is something else.

I've cut out all the cruft in the example file provided by the submitter to a single lined entry (delimited by '>').  See attached.

In the working example, there is no output as the buffer contains a newline '\n'.
In the non-working example, there is output as there was no newline found.


[3086-broken.txt](https://github.com/rakudo/rakudo/files/3537958/3086-broken.txt)
[3086-working.txt](https://github.com/rakudo/rakudo/files/3537959/3086-working.txt)

**Comment by lembark** [comment] 2019-09-11 16:30
Using index to find the newlines and greater-than symbols the sequence for nr.gz is correct (see below, thankfully Perl6 looks pretty much like C when we need it to :-).

Using Perl6 generating sufficient data to reasonably mimic the structure takes longer than just 
downloading nr.gz in the background. 

```
with open './data/input.p', :r, :enc('ascii') -> $input   
{
    # no typed state vars, put these out here.

    my atomicint $n = 0;
    my atomicint $m = 0;

    sub process-chunk
    (
        Str:D   $chunk
        --> Nil
    )
    {
        my $i   = 0;
        my $j   = 0;

        while 
            $i = $chunk.index( "\n", $j )
            and
            $j = $chunk.index( '>',  $i )
        {
            use Digest::SHA256::Native;

            my $seq = $chunk.substr( $i, $j - $i ).subst( "\n", '', :g );
            my $dig = sha256-hex $seq;

            my $rec = atomic-inc-fetch $n;

            $dig_out.say( $rec , ',' , $seq.chars , ',' , qq{"$dig"}  );
            $seq_out.say( $rec,  ',' , qq{"$seq"}                     );
        }
    }

    sub read-chunk
    (
        --> Str
    )
    {
        state   $next   = '';
        state   $start  = now;

        my  $chunk  = $next;
        my  $i      = 0;

        # i.e., keep reading until searching for a '>' at 
        # a 1 CHUNK offset yields something; give up at EOF.

        until $i = $chunk.index( '>', CHUNK )
        {
            ( my $buff = $input.read ).bytes
            or last;

            $chunk  ~= $buff.decode( 'ascii' );
        }

        # at this point $chunk contains more than a CHUNK
        # of input with a known record boundary -- or EOF.

        atomic-inc-fetch( $m ) % INTERVAL   
        or do
        {
            state $last_rec = 0;
            state $last_tm  = $start;

            my $recs    = $n - $last_rec;
            my $time    = now - $last_tm;
            my $rate    = ( $recs / $time ).Int;
            my $mrec    = ( $recs / 1_000_000 ).Int;

            print-stats label => "$m chunks, $mrec Mseq ($rate Hz)";

            $last_rec   = $n;
            $last_tm    = now;
        };

        # add artificial terminator after EOF.

        $next   = $chunk.substr( ++$i );
        
        $i
        ?? $chunk.substr( 0, $i )
        !! $chunk ~ '>'
    }

    my @chunked-input  
    = lazy gather loop
    {
        my $chunk   = read-chunk()
        or last;

        take $chunk;
    };

    print-stats label => $*PROGRAM;

    # sink, Nil, Empty avoid memory leaks due to 
    # leftover chunks of data.

    @chunked-input
    .race( degree => THREADS, batch => 1 )
    .map( { sink process-chunk $_; $_ = Nil; Empty } )
    ;

    print-stats :final, label => "Total Records: $n";
}
```

**Comment by lembark** [comment] 2020-05-14 03:23
Apologies, personal issues kept me away from all of this for a while.
Finally back to reality. I'll be able to test this now.

**Comment by lembark** [comment] 2020-05-14 03:35
Still seems broken. Using the current 6.d I get the NIL:

$ /opt/bin/rakudo -V | grep '^Raku'
Raku::can-language-versions=6.c 6.c 6.d 6.d.PREVIEW 6.d.TEST 6.d.TESTDEPR 6.e 6.e.PREVIEW
Raku::codename=
Raku::implementation=Rakudo
Raku::language-revisions=c      mods
Raku::language-version=6.d
Raku::prefix=/opt/rakudo
Raku::release-number=
Raku::source-digest=fd2b1400b53970fa090ed746dc3bfc57c1aef38f
Raku::static-nqp-home=
Raku::static-rakudo-home=/opt/rakudo/share/perl6
Raku::version=2020.05.1-57-ga317f538d

Pasted the code below into ./test-read with "#!/opt/bin/rakudo":

$ gzip -dc < data.gz | ./test-read
Use of Nil in numeric context
  in block  at ./test-read line 17
543     65366944        374208
WP_000783428.1 MULTI...rotein F component -

**Comment by MasterDuke17** [comment] 2020-06-29 22:44
@lembark I just watched your talk and thought I'd try to repro the failed read, but the code you have above can't be run as-is (complains about 'undeclared routine print-stats', etc. Do you have some example code that fails with the smaller data.gz?

**Comment by lembark** [comment] 2020-09-14 11:54
#!/usr/bin/env raku

with $*IN
{
    my $rec     = 0;
    my $read    = 0;

    .nl-in  = '>';

    .lines
    .skip( 1 )
    .map:
       {
            my $i   = $_.index( "\n" );

            if $i > 0 
            {
                $read   += $_.chars;
                my $seq = $_.substr( $i + 1 ).subst( "\n", '', :g );

                say "Sequence: {++$rec} +$i\t'{$_.substr($i-10, 20).subst( "\n", "\t")}'";
            }
            else
            {
                say "\n\nEntry lacks newline:\n\n", $_;
                die "Runt read at record $rec offset $read.\n";
            }

            Empty
        } 
    ;
}

Blows up with:
xzcat ../data/nr.xz | ./pass1;
Sequence: 1 +75 'ia brevis]     MAWTRQLVP'
Sequence: 2 +123        'bacterium]     MITPVSEEG'
Sequence: 3 +119        'elezensis]     MTDQVRCAV'
Sequence: 4 +60 'us cereus]     MSQQPKGKK'
<snip>
Sequence: 13276 +462    'nfluenzae]     MRDLVRSGK'
Sequence: 13277 +133    'paradoxus]     MLSTRAIRA'


Entry lacks newline:

XP_023404962.1 LOW QUALITY PROTEIN: putative C-
  in block  at ./pass1 line 16
Runt read at record 13277 offset 6930879.

  in block  at ./pass1 line 26
  in block <unit> at ./pass1 line 3

**Comment by pprocacci** [comment] 2020-11-10 17:52
@lembark - I'm back to believing this isn't a bug.
The nr data contains several records in the following format:

>XP_023404962.1 LOW QUALITY PROTEIN: putative C->U-editing enzyme APOBEC-4 [Loxodonta africana]

I've wrote a very small C program which closely resembles your raku program and it fails at the exact same spot:

###############################################
#include <unistd.h>
#include <stdio.h>
#include <string.h>

int main(void)
{
        ssize_t r;
        char *linep = 0;
        size_t linecapp = 0;
        int skip = 0;

        while( (r = getdelim(&linep, &linecapp, '>', stdin)) > 0) {
                if(!skip) { ++skip; continue; }
                if(!memchr(linep, '\n', r)) { printf("%s\n", linep); _exit(111); }
        }

        _exit(0);
}
###############################################

C Program:
gunzip -c nr.gz | ./test
XP_023404962.1 LOW QUALITY PROTEIN: putative C->

Raku Program:
gunzip -c nr.gz | ./test.pl6
XP_023404962.1 LOW QUALITY PROTEIN: putative C-


To put this another way ... encountering a '>' character doesn't always indicate the beginning of a record.

**Comment by pprocacci** [comment] 2020-11-10 18:53
Working raku program:

```#!/usr/bin/env raku

# Read very first '>' character and discard it
$*IN.nl-in = '>';
$*IN.read;

with $*IN
{

my $rec = 0;
my $read = 0;

.nl-in = "\n>";
.lines
.skip(1)
.map:
{
        my $i   = $_.index( "\n" );

        if $i > 0
        {
            $read   += $_.chars;
            my $seq = $_.substr( $i + 1 ).subst( "\n", '', :g );

            say "Sequence: {++$rec} +$i\t'{$_.substr($i-10, 20).subst( "\n", "\t")}'";
        }
        else
        {
            say "\n\nEntry lacks newline:\n\n", $_;
            die "Runt read at record $rec offset $read with i $i.\n";
        }

        Empty
};
}
```

**Comment by lizmat** [comment] 2024-10-10 19:00
Closing as not reproducoible

**Closed by lizmat** 2024-10-10 19:00 UTC
Labels: edge cases
