### ISSUE TITLE
Make test fails on OSX Apple M1 architecture

### ISSUE THREAD

**Issue by Zer0-Tolerance** [rakudo/rakudo#4394] opened 2021-06-07 07:55 UTC
## The Problem
I've built from source the latest Raku 2021.05 but the make test fails to pass even with libffi installed using brew. This is related to #4364. 
```
+++ Checking for moar NQP version
'/Users/xxx/perl5/perlbrew/perls/perl-5.24.4/bin/perl' -I'/Users/xxx/install/raku/rakudo-2021.05/tools/lib' -I'/Users/xxx/install/raku/rakudo-2021.05/3rdparty/nqp-configure/lib' t/harness5 --moar t/01-sanity t/02-rakudo t/04-nativecall t/05-messages t/06-telemetry t/07-pod-to-text t/08-performance t/10-qast t/09-moar
t/01-sanity/03-op-logic.t ....................................... ok
t/01-sanity/02-op-math.t ........................................ ok
t/01-sanity/04-op-cmp.t ......................................... ok
t/01-sanity/01-literals.t ....................................... ok
t/01-sanity/05-var.t ............................................ ok
t/01-sanity/06-op-inplace.t ..................................... ok
t/01-sanity/09-end-blocks.t ..................................... ok
t/01-sanity/12-counter.t ........................................ ok
t/01-sanity/11-tap.t ............................................ ok
t/01-sanity/10-regex.t .......................................... ok
t/01-sanity/08-var-array.t ...................................... ok
t/01-sanity/13-equal.t .......................................... ok
t/01-sanity/07-op-string.t ...................................... ok
t/01-sanity/15-sub.t ............................................ ok
t/01-sanity/17-isa.t ............................................ ok
t/01-sanity/16-eqv.t ............................................ ok
t/01-sanity/19-say.t ............................................ ok
t/01-sanity/21-try.t ............................................ ok
t/01-sanity/20-defined.t ........................................ ok
t/01-sanity/18-simple-multisubs.t ............................... ok
t/01-sanity/14-if.t ............................................. ok
t/01-sanity/98-test-deprecated.t ................................ ok
t/01-sanity/53-transpose.t ...................................... ok
t/02-rakudo/01-is_approx.t ...................................... ok
t/01-sanity/56-use-isms.t ....................................... ok
t/01-sanity/55-use-trace.t ...................................... ok
t/01-sanity/99-test-basic.t ..................................... ok
t/02-rakudo/03-corekeys-6d.t .................................... ok
t/02-rakudo/03-corekeys.t ....................................... ok
t/02-rakudo/03-corekeys-6c.t .................................... ok
t/02-rakudo/03-corekeys-6e.t .................................... ok
t/02-rakudo/04-diag.t ........................................... ok
t/02-rakudo/04-settingkeys-6d.t ................................. ok
t/02-rakudo/05-range-in-range.t ................................. ok
t/02-rakudo/06-is.t ............................................. ok
t/02-rakudo/07-implementation-detail-6.c.t ...................... ok
t/02-rakudo/07-implementation-detail-6.d.t ...................... ok
t/02-rakudo/04-settingkeys-6e.t ................................. ok
t/02-rakudo/04-settingkeys-6c.t ................................. ok
t/02-rakudo/07-implementation-detail-6.e.t ...................... ok
t/02-rakudo/08-repeat.t ......................................... ok
t/02-rakudo/08-inline-native-arith.t ............................ ok
t/02-rakudo/09-thread-id-after-await.t .......................... ok
t/02-rakudo/10-nqp-ops.t ........................................ ok
t/02-rakudo/13-exceptions.t ..................................... ok
t/02-rakudo/11-deprecated.t ..................................... ok
t/02-rakudo/08-slangs.t ......................................... ok
t/02-rakudo/12-proto-arity-count.t .............................. ok
t/02-rakudo/17-cli.t ............................................ ok
t/02-rakudo/18-pseudostash.t .................................... ok
t/02-rakudo/dd.t ................................................ ok
t/02-rakudo/dump.t .............................................. ok
t/02-rakudo/14-revisions.t ...................................... ok
t/02-rakudo/03-cmp-ok.t ......................................... ok
t/02-rakudo/99-misc.t ........................................... ok
t/02-rakudo/v6.d-tests/01-deprecations.t ........................ ok
t/02-rakudo/16-begin-time-eval.t ................................ ok
t/02-rakudo/15-gh_1202.t ........................................ ok
t/04-nativecall/01-argless.t .................................... ok
t/04-nativecall/00-misc.t ....................................... ok
t/04-nativecall/03-simple-returns.t ............................. ok
t/04-nativecall/02-simple-args.t ................................ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/14 subtests
	(less 1 skipped subtest: 12 okay)
t/04-nativecall/04-pointers.t ................................... ok
t/04-nativecall/07-writebarrier.t ............................... ok
t/02-rakudo/repl.t .............................................. ok
t/04-nativecall/08-callbacks.t .................................. ok
t/04-nativecall/05-arrays.t ..................................... ok
t/04-nativecall/06-struct.t ..................................... ok
t/04-nativecall/10-cglobals.t ................................... ok
t/04-nativecall/09-nativecast.t ................................. ok
t/04-nativecall/11-cpp.t ........................................ ok
t/04-nativecall/14-rw-attrs.t ................................... ok
t/02-rakudo/reproducible-builds.t ............................... ok
t/04-nativecall/13-union.t ...................................... ok
t/04-nativecall/16-rt125408.t ................................... ok
t/04-nativecall/12-sizeof.t ..................................... ok
t/04-nativecall/16-rt125729.t ................................... ok
t/04-nativecall/17-libnames.t ................................... ok
t/04-nativecall/19-function-pointers.t .......................... ok
t/04-nativecall/13-cpp-mangling.t ............................... ok
t/04-nativecall/21-callback-other-thread.t ...................... ok
t/04-nativecall/20-concurrent.t ................................. ok
t/04-nativecall/23-incomplete-types.t ........................... ok
t/04-nativecall/18-routine-sig-sanity.t ......................... ok
t/04-nativecall/22-method.t ..................................... ok
t/05-messages/11-overflow.t ..................................... ok
t/05-messages/moar/01-errors.t .................................. ok
t/04-nativecall/15-rw-args.t .................................... ok
t/05-messages/v6.d-tests/01-errors.t ............................ ok
t/05-messages/03-errors.t ....................................... ok
t/05-messages/10-warnings.t ..................................... ok
t/06-telemetry/03-thread.t ...................................... ok
t/06-telemetry/02-usage.t ....................................... ok
t/06-telemetry/04-threadpool.t .................................. ok
t/08-performance/01-iterators.t ................................. ok
t/07-pod-to-text/02-input-output.t .............................. ok
t/07-pod-to-text/01-whitespace.t ................................ ok
t/08-performance/05-processkeys.t ............................... ok
t/08-performance/99-misc.t ...................................... ok
t/05-messages/01-errors.t ....................................... ok
t/08-performance/02-qast-rewrites.t ............................. ok
t/05-messages/02-errors.t ....................................... ok
t/09-moar/00-misc.t ............................................. ok
t/09-moar/01-profilers.t ........................................ ok
t/10-qast/00-misc.t ............................................. ok
t/09-moar/Line_Break__LineBreak.t ............................... ok
t/09-moar/General_Category__UnicodeData__2.t .................... ok
t/09-moar/NAME__UnicodeData.t ................................... ok
t/09-moar/General_Category__extracted-DerivedGeneralCategory.t .. ok
t/06-telemetry/01-basic.t ....................................... ok

Test Summary Report
-------------------
t/04-nativecall/02-simple-args.t                              (Wstat: 256 Tests: 14 Failed: 1)
  Failed test:  10
  Non-zero exit status: 1
Files=110, Tests=1842, 28 wallclock secs ( 0.34 usr  0.16 sys + 162.31 cusr 13.54 csys = 176.35 CPU)
Result: FAIL
make: *** [m-coretest5] Error 1
```
## Expected Behavior
Make test should pass without modification on M1 Macs

## Actual Behavior
make test fails **t/04-nativecall/02-simple-args.t** 
## Steps to Reproduce

1. `export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"; export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"`
2. `./Configure.pl --gen-moar --gen-nqp --moar-option="--has-libffi"`
2. `make`
3. `make test`
## Environment
* Operating system: `Darwin XXX 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64`
* Compiler version (`perl6 -v` or `raku -v`): `Welcome to Rakudo(tm) v2021.05.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.`

**Comment by lizmat** [comment] 2021-06-11 14:48
A dupe of #4341 ?

**Comment by tony-o** [comment] 2021-06-12 00:28
The test is already skipped on `macosx`.  Current master skips this test for `macosx` and M1 arch identifies as `macos`.  The PR skips this test for both.

```
$ raku -v
Welcome to Rakudo(tm) v2021.05-12-g9433d0f93.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05-14-g0a62f0c6a.
$ raku -e 'say $*DISTRO.name'
macos
```

**Comment by Zer0-Tolerance** [comment] 2021-06-12 16:00
> A dupe of #4341 ?

yes probably but I was asked to open an issue so I did :)

**Comment by coke** [comment] 2022-10-14 14:48
> > A dupe of #4341 ?
> 
> yes probably but I was asked to open an issue so I did :)

And that issue is closed, closing this one as well.

**Closed by coke** 2022-10-14 14:48 UTC
