### ISSUE TITLE
RFE: please consider a better error message for start-with and index

### ISSUE THREAD

**Issue by ToddAndMargo** [rakudo/rakudo#3736] opened 2020-06-02 05:31 UTC
Dear Raku Developers,

K:\Windows\NtUtil>raku -v
This is Rakudo version 2020.05.1 built on MoarVM version
2020.05 implementing Raku 6.d.

https://docs.raku.org/routine/starts-with
multi method starts-with(Str:D: Str(Cool) $needle, :i(:$ignorecase), :m(:$ignoremark) --> Bool:D)

This applies to “index” as well.

The following has a deliberate error in it.  I am sending it an undefined Haystack (invocant) variable.  This I found out the hard way, which is a story for another day:

#!/usr/bin/env raku
my Str $x;
if $x.starts-with( "[" )  &&   $x.contains( "]" )
{ say "Passed"; } else { say "Failed"; }

K:\Windows\NtUtil>raku Contains.Test.pl6
Cannot resolve caller starts-with(Str:U: Str:D); none of these signatures match

    (Cool:D: Cool:D $needle, :i(:$ignorecase)!, :m(:$ignoremark), *%_ --> Bool)
    (Cool:D: Cool:D $needle, :m(:$ignoremark)!, *%_ --> Bool)
    (Cool:D: Cool:D $needle, *%_ --> Bool)
    (Str:D: Str:D $needle, :i(:$ignorecase)!, :m(:$ignoremark), *%_ --> Bool)
    (Str:D: Str:D $needle, :m(:$ignoremark)!, *%_ --> Bool)
    (Str:D: Str:D $needle, *%_ --> Bool)
in block <unit> at Contains.Test.pl6 line 3

Instead of telling me what I did wrong, which was to violating the requirement that the Haystack (invocant) be a defined string (Str:D), it told me everything I could not do.

Saying that it was confusing to troubleshoot is an understatement.

Would you please consider telling me what I did wrong, instead of what I can not do?  The following would be a lovely error message:

     starts-with's Haystack (invocant) requires a defined value (Str:D)

And since you already check for the sun, the moon, and the stars (list of what I can’t do), adding a check for “defined” should be pretty easy.

Many thanks,
-T

**Comment by JJ** [comment] 2020-06-02 06:36
I'm afraid the message is totally correct. The "undefined" you mention contains, actually, Str:U. What it's saying is that there's no multi that works with that as an invocant. If you want to really make the default value of a container something like Null or whatever, you need to define it that way via "is default" 
For Rakudo, it's impossible to know if you assigned an Str:U deliberately or it's the default value, and it's like that by design. So it says what it knows: I was expecting a Cool:D or somesuch here, this is not what I find, it's a Str:U. Totally fine, and I'm closing this issue.

**Closed by JJ** 2020-06-02 06:36 UTC

**Comment by ToddAndMargo** [comment] 2020-06-03 01:52
Hi JJ,
Let me make user I completely understand your reasoning.  The spec say is required a `Str:D` meaning a defined string, but you say is okay to violate the requirement because raku does not know why a Str:U would be sent to it: it could be on purpose.  Seems to me, if I am not misunderstanding you, that the spec needs to be updated to match your reasoning: a Str:D is not actually required.  If this is the case, would you like me to open a trouble ticket on the documentation page to remove the Str:D requirement?
-T

**Comment by JJ** [comment] 2020-06-03 06:19
No, that's not what I'm saying. Please read again.

**Comment by ToddAndMargo** [comment] 2020-06-03 08:00
Hi JJ,

Reread it several more times. I still comes to the same apparent misunderstanding.  The error message that comes back lists all the things it is not (a flood of sentences which have to be read over in a process of elimination), rather than simply getting straight to the point and stating that you have violated the requirement.  You "seems" to be saying that it is somehow okay to violate the rules.  

If, as you stated, "it's impossible to know if you assigned an Str:U deliberately or it's the default value", then the rules should state such.  And since when does Raku care why you screw up?  Raku is a machine not a psychologist.

Not sure why the following needs to be replaced with something so confusing:

> my Str $Haystack; 
> if not $Haystack.defined {say "starts-with's Haystack (invocant) requires a defined value (Str:D)"}

Gets straight to the point.  You messed up, verses sentence after sentence after sentence of thrashing around the perturbation of the shrubbery.

Please straighten me out.

Many thanks,
-T

**Comment by JJ** [comment] 2020-06-03 08:35
Do you understand that there's no such thing as an undefined value? First, there isn't; there's no such thing as an "Undefined" you can smartmatch to a value (and thus it can't be used in error messages). Then, there's this

    my $foo = Any; my $bar; say $foo eqv $bar # True

Since you can assign types to variables, and the default value of a variable is a type, you can't say if a container has a defined value (and is a type), or if it's got no value at all. You can check for definedness with .defined, but  that checks if it's a type value or a value:

    my $foo = Any; my $bar; say $foo.defined, $bar.defined # FalseFalse

But also:

    my $foo = Str; say $foo.defined # False

"Undefined", in this context, is not a value, but a quality that says it does not have a concrete value (a :D) but a type value (an :U).

That said, signatures can make :D apart from :U. But nothing more. 

   sub foo( Str:U $ ) { "Undefined string" }; my $bar; say foo($bar)
   # Type check failed in binding to parameter '<anon>'; expected Str but got Any (Any)

`$bar` will contain the default value for that kind of container, `Any`, which matches `Any:U`. Gotcha! They you can check for undefinedness that way, right?

    sub foo( Any:U $ ) { "Undefined suff" }; my $bar; say foo($bar) # "Undefined stuff"
    sub foo( Cool:U $ ) { "Undefined suff" }; my Str $bar; say foo($bar) # Undefined stuff

Wrong. This only works one way up the hierarchy, not down the hierarchy. A Str is Cool, but not the other way round.

    sub foo( Str:U $ ) { "Undefined suff" }; my Cool $bar; say foo($bar)
    # Type check failed in binding to parameter '<anon>'; expected Str but got Cool (Cool)

So you are still stuck with the undefinedness of undefined, or the strict way it's defined in Raku. Thus, no better error messages are possible, because of the strict type checking, and default values in Raku. 

Read about how to obtain [default values for several containers here](https://docs.raku.org/routine/default), [how to force all variables to be definite via a pragma](https://docs.raku.org/language/variables#Default_defined_variables_pragma), [how to assign default values to containers when they are defined](https://docs.raku.org/language/variables#Type_constraints_and_initialization), and, finally, about [type smileys](https://docs.raku.org/type/Signature#Constraining_argument_definiteness)

**Comment by ToddAndMargo** [comment] 2020-06-03 21:48
Hi JJ,
I think I am wrapping my mind around what you are trying to say.  Maybe if you were to consider giving the same error as sending an undefined variable as the needle, it would make both of us happy:
```
> my $needle
(Any)
> say "abc".starts-with($needle);
Cannot resolve caller starts-with(Str:D: Any:U);

```
Here "any:U" is a great tip off as to what you did wrong.

-T

**Comment by JJ** [comment] 2020-06-04 06:45
I would be happy if you read what I posted before and stopped talking about "undefined" variables. There's no such thing. There are containers that contain a definite value, such as 7, and containers that contain undefinite value (not undefined), such as Any or Str. That error is exactly the same as the one you've mentioned before, except the invocant is known (because it's definite) and then it does not need to present all the possibilities for it (Str:D; Cool:D). This error message you like is *exactly the same* as the one you hate.

    Cannot resolve caller starts-with(Str:D: Any:U);

vs

    Cannot resolve caller starts-with(Str:U: Str:D); none of these signatures match

except for the position (invocant -- before the colon) or argument and the fact that it's presenting several possible alternatives. So the error message is perfectly fine. Even if you don't understand, or care to understand, the underlying concepts.

**Comment by ToddAndMargo** [comment] 2020-06-07 01:41
On 2020-06-03 23:45, Juan Julián Merelo Guervós wrote:
> I would be happy if you read what I posted before and stopped talking 
> about "undefined" variables. There's no such thing. 

https://docs.raku.org/type/Mu#method_defined

Shall I put in a bug report on it based on your explanation
above?

> There are containers 
> that contain a definite value, such as 7, and containers that contain 
> undefinite value (not undefined), such as Any or Str. That error is 
> exactly the same as the one you've mentioned before, except the invocant 
> is known (because it's definite) and then it does not need to present 
> all the possibilities for it (Str:D; Cool:D). This error message you 
> like is /exactly the same/ as the one you hate.
> 
> |Cannot resolve caller starts-with(Str:D: Any:U); |
> 
> vs
> 
> |Cannot resolve caller starts-with(Str:U: Str:D); none of these 
> signatures match |

Again, you are violating the documentation:

https://docs.raku.org/routine/starts-with
multi method starts-with(Str:D: Str(Cool) $needle, :i(:$ignorecase), 
:m(:$ignoremark) --> Bool:D)

It clearly states `Str:D:`, not `Str:` or `Str:U:`

If you send it a `Str:U:`, state CLEARLY that you have
violated the requirements.  No trashing about the
Protuberance of the Shrubbery.  Leave that kind of
speak to politicians.

> except for the position (invocant -- before the colon) or argument and 
> the fact that it's presenting several possible alternatives. So the 
> error message is perfectly fine. 

Q: Is a "cow" a "Plant"

A: A cow is not an onion
A: A cow is not an carrot
A: A cow is not an turnip
A: <ad nauseam>

Preferred answer:
A: No

Indeed the error messages above are absolutely correct.
And they are also perfectly useless.

    A cow is not a potato
    (Cool:D: Cool:D $needle, :i(:$ignorecase)!, :m(:$ignoremark), *%_ 
--> Bool)
    (Cool:D: Cool:D $needle, :m(:$ignoremark)!, *%_ --> Bool)
    (Cool:D: Cool:D $needle, *%_ --> Bool)
(Str:D: Str:D $needle, :i(:$ignorecase)!, :m(:$ignoremark), *%_ --> Bool)
    (Str:D: Str:D $needle, :m(:$ignoremark)!, *%_ --> Bool)
    (Str:D: Str:D $needle, *%_ --> Bool)
    A cow is not a tomato


It would not kill anyone to just answer the question directly.

I am not asking you to correct an incorrect answer.  The
message that comes back is absolutely correct.  Confusing
as all the dickens, but absolutely correct.

I am asking for a simple straight forward message.  The
requirements for the Haystack (invocant) have been
violated.

"starts-with's Haystack (invocant) requires a defined value (Str:D)". 
(I don't care if you change the wording as long
as it says the same thing.)

No one would pull their hair out.  No one would be would
be confused.  No "what the h***" momenbts.  No need to
plead with JJ.

> Even if you don't understand, or care 
> to understand, the underlying concepts.

Perhaps.  But I can only go on the requirements stated
documentations.

And since you are in charge of the documentation, you could
always modify starts-with and defined to match your above
explanation.  Remove the "D" from start-with's invocant and
change the name and description of defined.

-T

**Comment by niner** [comment] 2020-06-07 07:37
This bug report has nothing to do with `start-with` or `index`. It's about our 
reporting of failed multi dispatch in general.

The reported multi candidates in the example given have 3 things in common: 
they require a defined invocant, a defined first argument and will all return 
a Bool. These commonalities could be used to create a more helpful error 
message that points out the probable mistake more directly. Indeed, it doesn't 
matter that much, what candidates for a defined we have, since they all fail 
to match for the same reason.

It would be cute if we e.g. find the candidate with most matching arguments 
and in the error message mark the matching arguments green and the violating 
arguments red.

Since it's very common for methods to only work on concrete objects and not 
classes, we could even special case this and tell the user that they called 
the method on a class, but it really needs an object to work.

I would still display the full list of candidates though, but after the more 
directed error message.

@ToddAndMargo: can you please have a go at implementing such improved error 
reporting and open a PR?

**Comment by ToddAndMargo** [comment] 2020-06-07 07:58
Hi Niner,

Love your analysis.  

> @ToddAndMargo: can you please have a go at implementing such improved error
reporting and open a PR?

Love to.  What is a PR and where is it?  (Me dumb dumb.)

**Comment by niner** [comment] 2020-06-07 08:23
On Sonntag, 7. Juni 2020 09:58:59 CEST ToddAndMargo wrote:

> Love to.  What is a PR and where is it?  (Me dumb dumb.)

A Pull Request:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/
about-pull-requests

**Comment by ToddAndMargo** [comment] 2020-06-08 02:21
> A Pull Request: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/ about-pull-requests

Where is the proper place to create this Raku pull request?  (I always put them in the wrong place.)

**Comment by niner** [comment] 2020-06-08 06:44
> Where is the proper place to create this Raku pull request?  (I always put
> them in the wrong place.)

You fork https://github.com/rakudo/rakudo, push your fixes into your fork and 
press the Create pull request button when you're done.

I'd start with a simple script outside rakudo though. That makes it mach 
easier and faster to experiment.
The code for creating the error message is in:
https://github.com/rakudo/rakudo/blob/master/src/core.c/Exception.pm6#L2730
It basically needs a Capture with the supplied arguments and the proto of the 
method you try to call. Try to extend it to give you the desired error 
message.

**Comment by JJ** [comment] 2020-06-08 07:37
A

> Hi Niner,
> 
> Love your analysis.
> 
> > @ToddAndMargo: can you please have a go at implementing such improved error
> > reporting and open a PR?
> 
> Love to. What is a PR and where is it? (Me dumb dumb.)

Maybe, when you get around to it, you can read [this perl6-users thread](https://www.mail-archive.com/search?l=perl6-users%40perl.org&q=subject:%22GIT+PR+Help%22&o=newest&f=1) where, 5 months ago, @treyharris explained what was a pull request and how to do it in this or other cases.

**Comment by tbrowder** [comment] 2020-06-08 10:21
On Mon, Jun 8, 2020 at 2:37 AM Juan Julián Merelo Guervós
<notifications@github.com> wrote:
...

And where I posted this (recommended to be somewhere on our Raku site):

   https://github.com/tbrowder/tidbits/blob/master/Contributing-PRs.md

which is referenced in this:

    https://github.com/Raku/doc/blob/master/CONTRIBUTING.md#contributing-pull-requests

-Tom
