### ISSUE TITLE
gmake fails on windows

### ISSUE THREAD

**Issue by dumarchie** [rakudo/rakudo#4009] opened 2020-11-07 07:30 UTC
## The Problem

After building and installing NQP, `gmake` fails:

```
c:\raku\rakudo>gmake
+++ Checking for moar NQP version
+++ Expanding   gen\moar\main-version.nqp
+++ Generating  gen\moar\rakudo.nqp
+++ Generating  gen\moar\Grammar.nqp
+++ Generating  gen\moar\World.nqp
+++ Generating  gen\moar\ModuleLoader.nqp
+++ Compiling   blib\Perl6\ModuleLoader.moarvm
+++ Generating  gen\moar\Ops.nqp
+++ Compiling   dynext\perl6_ops_moar.dll
+++ Compiling   blib\Perl6\Ops.moarvm
+++ Generating  gen\moar\Pod.nqp
+++ Compiling   blib\Perl6\Pod.moarvm
+++ Compiling   blib\Perl6\World.moarvm
+++ Generating  gen\moar\Actions.nqp
+++ Compiling   blib\Perl6\Actions.moarvm
+++ Compiling   blib\Perl6\Grammar.moarvm
+++ Generating  gen\moar\Compiler.nqp
+++ Generating  gen\moar\Optimizer.nqp
+++ Compiling   blib\Perl6\Optimizer.moarvm
+++ Compiling   blib\Perl6\Compiler.moarvm
+++ Generating  gen\moar\SysConfig.nqp
+++ Compiling   blib\Perl6\SysConfig.moarvm
+++ Compiling   rakudo.moarvm
+++ Generating  gen\moar\BOOTSTRAP\v6c.nqp
+++ Generating  gen\moar\Metamodel.nqp
+++ Compiling   blib\Perl6\Metamodel.moarvm
+++ Compiling   blib\Perl6\BOOTSTRAP\v6c.moarvm
+++ Compiling   blib\CORE.c.setting.moarvm
The following step can take a long time, please be patient.
Stage start      :   0.000
Stage parse      :  69.092
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :   7.257
Stage mast       :  14.755
Stage mbc        :   9.321
+++ Generating  gen\moar\BOOTSTRAP\v6d.nqp
+++ Compiling   blib\Perl6\BOOTSTRAP\v6d.moarvm
+++ Compiling   blib\CORE.d.setting.moarvm
The following step can take a long time, please be patient.
Stage start      :   0.000
Stage parse      :   0.409
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :   0.021
Stage mast       :   0.066
Stage mbc        :   0.028
+++ Generating  gen\moar\BOOTSTRAP\v6e.nqp
+++ Compiling   blib\Perl6\BOOTSTRAP\v6e.moarvm
+++ Compiling   blib\CORE.e.setting.moarvm
The following step can take a long time, please be patient.
Stage start      :   0.000
Stage parse      :   1.634
Stage syntaxcheck:   0.000
Stage ast        :   0.000
Stage optimize   :   0.150
Stage mast       :   0.328
Stage mbc        :   0.033
+++ Generating  rakudo-m.exe
+++ Generating  gen\moar\rakudo-debug.nqp
+++ Compiling   rakudo-debug.moarvm
+++ Compiling   inst-rakudo.exe
+++ Compiling   inst-rakudo-debug.exe
+++ Compiling   inst-rakudo-m.exe
+++ Compiling   inst-rakudo-debug-m.exe
+++ Compiling   inst-rakudow.exe
gcc: error: unrecognized command line option '--subsystem=windows'; did you mean '--machine=windows'?
gmake: *** [Makefile:1323: inst-rakudow.exe] Error 1
```

Line 1323 in the *Makefile* is:

```
	$(NOECHO)$(M_CC) -c -DSTATIC_EXEC_PATH="C:\\raku\\rakudo\\install\\bin\\$(M_RAKUDOW)" -DSTATIC_NQP_HOME="C:\\raku\\rakudo\\install\\share\\nqp" -DSTATIC_RAKUDO_HOME="C:\\raku\\rakudo\\install\\share\\perl6"  -DSUBSYSTEM_WINDOWS $(M_CFLAGS) $(M_MOAR_INC_PATHS) -o $(M_INST_RAKUDOW).o src\vm\moar\runner\main.c
```

## Environment
* Operating system: Windows 10
* Compiler version (`install\bin\moar.exe --version`): This is MoarVM version 2020.10-31-gb13f6a24c built with JIT support

**Comment by Altai-man** [comment] 2020-11-07 11:07
Hi. Is it a regression? I remember discussion we only support msvc these days, but maybe I am wrong.

**Comment by dumarchie** [comment] 2020-11-08 05:54
Merging MoarVM/MoarVM/pull/1377 made it possible to build MoarVM with `gcc` again, so why would we only support a proprietary compiler?

**Comment by Altai-man** [comment] 2020-11-08 09:51
>Resolving MoarVM/MoarVM/issues/1345 made it possible to build MoarVM with

Oh, so this is a legitimate bug then.

**Comment by patrickbkr** [comment] 2020-11-08 10:40
Just to give some background. We never intended to drop support for mingw. But two events might have given that impression:

1. The pthread bug that recently got fixed.
2. The decision that the binary release builds will use msvc for now.

I know what's wrong here. The new `rakuw.exe` launchers need to have a different subsystem set. It seems the compiler flag to do so on gcc is wrong. I'll have a look.

**Comment by dumarchie** [comment] 2020-11-08 11:07
@patrickbkr, did you mean that msvc was to be used as long as mingw was not supported, or are there additional reasons to prefer msvc?

**Comment by patrickbkr** [comment] 2020-11-08 12:43
@dumarchie No, that decision was taken at a time when mingw was still working. There were long discussions on what compiler to use for the binary builds (the ones offered on rakudo.org). I don't remember the exact reasons, library compatibility might have been one. Maybe @ugexe can remember details. But the decision on what compiler to use is not such an important one. We could start offering builds with both compilers as soon as someone is willing to invest the time to adapt the scripts that do the build accordingly. (They are created with [our Azure CI build pipeline](https://github.com/rakudo/rakudo/blob/master/azure-pipelines.yml#L226).)

**Comment by patrickbkr** [comment] 2020-11-18 13:35
@Altai-man: Just wondering, why is this a blocker? The build on MinGW has been broken for many releases...

**Comment by Altai-man** [comment] 2020-11-18 13:47
https://github.com/rakudo/rakudo/issues/4009#issuecomment-723534832 said it was possible to build with gcc (essentially MinGW) on Windows. The issue is dated September. Given this issue was reported in November, it is wise to fix it now, add a CI test, just the time. Am I misunderstanding something?

More generally, I just really, really don't like "It cannot be built at all" type of issues issues, they are always blockers except for a very rare exceptions IMO.

**Comment by patrickbkr** [comment] 2020-11-18 13:58
It's been broken since 2020.07, so already four releases. But I just created a PR with a fix for this last problem. :-)
Maybe I can manage to create a CI config in the evening as well.

**Comment by Altai-man** [comment] 2020-11-18 17:16
This should not be closed until we have CI for it.

**Comment by Altai-man** [comment] 2021-04-29 08:24
Closed as we have tests now. Thanks!

**Closed by Altai-man** 2021-04-29 08:24 UTC
Labels: BLOCKER, Windows, build, tests needed
