### ISSUE TITLE
Are CI builds with nqp-master or moar-master needed?

### ISSUE THREAD

**Issue by patrickbkr** [rakudo/rakudo#3700] opened 2020-05-17 21:50 UTC
A process of unifying our CI testing infrastructure where testing happens only on AzureCI instead of CircleCI + AppVeyor + Travis is in progress. An AzureCI configuration is already in place that tests all the build combinations that the other three CI platforms provided.

In the context of that migration the question [came up on IRC](https://colabti.org/irclogger/irclogger_log/raku?date=2020-05-17#l493) what's the worth of testing builds of:

- rakudo + nqp master branch (+ moar via the revision given in nqp)
- rakudo + nqp master branch + moar master branch

These combinations cause "false positives" with changes that span more than one of those three repos and that depend on each other.

What is the reason for testing those build combinations?

Ping @Altai-man @jnthn @lizmat @ugexe

**Comment by Altai-man** [comment] 2020-05-17 22:02
Now that I think about, I wrote some nonsense on irc about them not being helpful.

I suppose it might help to spot regressions up the stack earlier and allows to test smaller chunks of changes (e.g. there might be 20 commits between bumps and if you find there is a failure after making a bump you likely don't want to check all those commits).

But now we have another question: what's the merit of testing some specific revision each commit if we strive for having all three pieces to be always clean? It's like you do a bump each commit, then why re-test some of them over and over?

Anyway, it would be very helpful to get feedback on this to know if we can reduce complexity of our checks making them easier to look at, while not sacrificing anything even a little important.

**Comment by AlexDaniel** [comment] 2020-05-17 22:20
> Now that I think about, I wrote some nonsense on irc about them not being helpful.

I like this attitude :)

Anyway, I have an idea. What if we make a single configuration that runs all tests with one provided moar-nqp-rakudo combo, and then use it for all three repos? For example, I'm suggesting to run moarvm, nqp and rakudo tests for each *MoarVM* commit. This way any MoarVM PR will trigger tests that show if it is going to break NQP and Rakudo. It also means that, for example, “rakudo + nqp master branch + moar master branch” combo will be part of NQP repo, so that new NQP commits will correctly trigger the tests we need, instead of doing it asswards and waiting for Rakudo CI to turn red for new commits. Let me know if it's unclear and I should describe it a bit more.

**Comment by patrickbkr** [comment] 2020-05-17 22:24
Do I understand correctly?:
Rakudo repo CI: Test rakudo master + NQP (via NQP_REV) + Moar (via MOAR_REV)
NQP repo CI: Test Rakudo master + NQP master + Moar (via MOAR_REV)
Moar repo CI: Test Rakudo master + NQP master + Moar master

**Comment by AlexDaniel** [comment] 2020-05-17 22:30
@patrickbkr correct!

**Comment by patrickbkr** [comment] 2020-05-17 22:31
I think I'll need to ponder this some more, but seems sensible on first sight. Should also be easy to do and simplify our CI landscape even more!

**Comment by AlexDaniel** [comment] 2020-05-17 22:37
> Should also be easy to do and simplify our CI landscape even more!

Yep, that's what I'm thinking. That said, with this approach new issues in Rakudo will propagate to MoarVM CI status, so some can possibly argue that *this* is asswards, but I think that in all practical aspects we will benefit from this inversion. For example, CI status of MoarVM will always be showing whether it is safe to commit bumps, something you had to test yourself previously.

**Comment by AlexDaniel** [comment] 2020-05-17 22:42
@patrickbkr while you're working on it and while I'm here, do you have any thoughts on running roast tests for CI? I think all the solutions out there have limits that make it impossible to use long-running tests, but can't we use our own servers for that? Talk to @rba, they'll tell you if we have something suitable.

**Comment by jnthn** [comment] 2020-05-17 23:11
> Do I understand correctly?:
> Rakudo repo CI: Test rakudo master + NQP (via NQP_REV) + Moar (via MOAR_REV)
> NQP repo CI: Test Rakudo master + NQP master + Moar (via MOAR_REV)
> Moar repo CI: Test Rakudo master + NQP master + Moar master

This makes sense to me, in so far as a change in Moar that breaks things in NQP or Rakudo will be reported primarily against the MoarVM commit, rather than the situation now where one would have to look at Rakudo's CI results to know if that happened.

I don't think it helps the situation where changes need to be coordinated over multiple repos, but I'm not sure it makes it worse either...

**Comment by AlexDaniel** [comment] 2020-05-17 23:36
> I don't think it helps the situation where changes need to be coordinated over multiple repos, but I'm not sure it makes it worse either...

Oh, I have an idea for that too. By any chance can we make it so that it will attempt to use the same branch (a branch with the same name) from other repos, and if there's no branch with that name then just use master? So that:

* Rakudo repo CI: Test rakudo **(given branch)** + NQP (via NQP_REV) + Moar (via MOAR_REV)
* NQP repo CI: Test Rakudo **(given branch or master)** + NQP **(given branch)** + Moar (via MOAR_REV)
* Moar repo CI: Test Rakudo **(given branch or master)** + NQP master **(given branch or master)** + Moar **(given branch)**

I guess it won't help forks but for core development it'll make some things easier. For example, if you have `rakuast` branches in all three repos, then committing to MoarVM will work fine instead of showing red status (it'll use nqp and rakudo checked out at respective `rakuast` branches), but in nqp and rakudo you'll need bumps (which is actually correct because merging a branch without a bump will result in broken state at the merge commit, and having more than one bump in a branch is actually good for bisectability).

**Comment by patrickbkr** [comment] 2020-05-20 21:16
> @patrickbkr while you're working on it and while I'm here, do you have any thoughts on running roast tests for CI? I think all the solutions out there have limits that make it impossible to use long-running tests, but can't we use our own servers for that? Talk to @rba, they'll tell you if we have something suitable.

@AlexDaniel

I see two possible ways to do this.
1. Just run the spec tests on AzureCI. The maximum runtime for a single job is 6 hours for public repos. That should be more than enough.
2. AzureCI supports adding self-hosted worker machines to run jobs on. Those can do whatever we want. (I've been pondering the idea to add two Raspies as build hosts so we can have precompiled arm releases for quite a while now.)

**Comment by AlexDaniel** [comment] 2020-05-20 21:48
Ah, I see. ① should be OK actually.

**Comment by patrickbkr** [comment] 2020-05-21 08:40
In what constellations do we want to run spectest?
On every commit or only releases / when triggered?
On all three platforms or only Linux/MoarVM?
Only the rakudo repo or all three rakudo, nqp, moar?

**Comment by patrickbkr** [comment] 2020-05-21 11:39
Depends on #3705

**Comment by patrickbkr** [comment] 2020-06-24 15:38
I just want to give a short report of how far this progressed:

AzureCI is set up and active in Rakudo, NQP and MoarVM. Both PRs and commits are tested. The combinations as discussed above are implemented in the respective repositories.

MoarVM Travis has a set of other builds that test combinations of different compilers and libraries. All of those have been converted faithfully. Only exception is a build that does a coverage report using clang and uploads the result to a server. That build has been broken on Travis for years.

Open points:

- There is a mysterious failure where a git reference was not found in the git repo that was cloned. I only saw it once and have no real lead of how to hunt this down should it appear again. I will ignore this until it reappears.
- There are occasional segfaults in test runs. They are not reproducible. Rerunning a segfaulting build job will usually succeed. It's difficult to judge whether these are legitimate errors or whether the CI is at fault. Help on how to approach hunting this down appreciated!
- Spec tests are not yet run.
- Precomiled builds similar to our precomp release builds are not run on every commit.
- There is no IRC reporter bot.
- The other CI toolchains are still active. I'm unsure when the best point to turn it of is reached.

I plan to work on the recomp builds for every commit next. And then work toward disabling all other CI toolchains.

**Comment by Altai-man** [comment] 2020-06-24 16:10
@patrickbkr 
Can I ask you to arrange some work towards coverage of different test cases rather than going for nightly we can not hurry too much?

Particular ones I am thinking about immediately:
1)Older GCC which was caught by CircleCI but not by Azure. We can't drop it until this case is ported.
2)https://github.com/rakudo/rakudo/issues/1257 seems related.
3)Do we have an Azure check for musl/alpine?

**Comment by Altai-man** [comment] 2020-06-24 16:14
>There is no IRC reporter bot.

I don't think there is a need for it until devs can trust the builds are reliable. Let's strive for at least a couple of months without false positives and then having a bot is cool.

>The other CI toolchains are still active. I'm unsure when the best point to turn it of is reached.

As was noted in previous comment, CircleCI setup with older GCC is not ported. Once we have that we probably can disable them (not completely removing the config code) and see.

>Spec tests are not yet run.

Those contain flappers (I know it sucks, but) and devs are running them pretty often. There is 6.c and 6.d, but I'll let it be my headache, I guess.

>There are occasional segfaults in test runs

This sounds like a legitimate bug for moarvm folks to resolve once there are any evidences, I guess.

**Comment by AlexDaniel** [comment] 2020-06-24 17:32
> Those contain flappers (I know it sucks, but) and devs are running them pretty often. There is 6.c and 6.d, but I'll let it be my headache, I guess.

Just mark these as blockers. Seriously. The amount of time they waste is incredible, especially for release managers. When you use the sakefile, it runs the spectest several times until it succeeds, which is why you have to wait so long for it to actually finish and produce the tars. We just got used to them and also got used to not caring. Let's reverse that.

**Comment by ugexe** [comment] 2020-06-24 17:35
A question to put things into perspective: what was the last non-bugfix feature/change that we absolutely could not wait e.g. 24 hours (for automated spec tests, review, whatever) before merging into master? I cannot think of a single one.

**Comment by patrickbkr** [comment] 2020-06-24 17:48
Running the precomp build toolchain will test running on CentOS6 which will (implicitly) test if older GCCs work. This is a good test as it will ensure the precomp builds that are part of the release process will work.


Testing more platforms is a different topic.

As already stated in [problem-solving#206](https://github.com/Raku/problem-solving/issues/206#issuecomment-647366052) we need to evaluate what platforms we want to support / test on. Some might be available on AzureCI directly, some we can pull in via Docker, for some we might even have to set up our own hardware infrastructure. Integrating external hardware into Azure is possible.

But the first step is to put a list together of which platforms we want to support. Without that we'll end up in a "add whatever platform we can find - the more the better" frenzy. That won't help stability and reliability of or CI toolchain.

So before I start working on a test setup that tests lots of different environments (that haven't been tested before already) I'd like to have a clear goal set.

**Comment by patrickbkr** [comment] 2020-08-18 07:33
The AzureCI pipeline has been running basically unchanged since 10th of June and is duplicating the environments the other CI pipelines test on.

Are there any reasons to keep the other pipelines running? If no, then I'd like to disable Travis, Circle-CI and AppVeyor in the Rakudo, NQP and MoarVM repositories soon.

@Altai-man @ugexe @niner @AlexDaniel @lizmat

**Comment by MasterDuke17** [comment] 2020-08-18 07:40
Can everybody with a commit bit to the repos restart a failed test?

**Comment by patrickbkr** [comment] 2020-08-18 08:09
@MasterDuke17 I have just tried doing so on AzureCI. When trying to restart a failed build on the AzureCI website it requires login to Azure. But when trying to re-run a failed build using the `re-run` button on the left of the GitHub Actions page (That's GitHub page one is forwarded to when clicking on CI jobs in PRs or commits.) the builds are re-run without the need for an AzureCI login. It does seem to have its problems with re-running PRs though (it seems to fail accessing the correct commit). Do you see this as a precondition to disabling the other CIs?

**Closed** 2024-10-13 11:59 UTC
