### ISSUE TITLE
routine 'say' can not print large data

### ISSUE THREAD

**Issue by vnluc** [rakudo/rakudo#1945] opened 2018-06-21 17:07 UTC
## The Problem
routine say I use to print a string about 100KB and it get error

```
Failed to write bytes to filehandle: Not enough space
  in block <unit> at lim.p6 line 5
```
## Expected Behavior
say should work fine,

## Steps to Reproduce

Run this code with file cafef.html  big size (my test 137,146 bytes).

```
use v6;

my $x = slurp "cafef.html";
say $x;

```

will got errror:
```
Failed to write bytes to filehandle: Not enough space
  in block <unit> at lim.p6 line 5
```
## Environment
* Operating system: Windows 7 x64
* Compiler version (`perl6 -v`):  
This is Rakudo version 2018.05 built on MoarVM version 2018.05

**Comment by lizmat** [comment] 2018-06-21 17:11
FWIW, I cannot reproduce this on MacOS, not even with a 1M file

**Comment by vnluc** [comment] 2018-06-21 17:15
I am on Windows7. I am not sure which option can affect this.

**Comment by jnthn** [comment] 2018-06-21 17:16
Does it work if the output is redirected to a file (e.g. `> foo`)?

**Comment by jnthn** [comment] 2018-06-21 17:20
We needed [this workaround](https://github.com/MoarVM/MoarVM/blob/master/src/io/syncfile.c#L134) for reading input from the Windows console, and it may be that there's some similar kind of limitation on output. Though `write` would be expected to normally write what it can and tell us how much it wrote, and then we call it again, and we're handling that already.

**Comment by jnthn** [comment] 2018-06-21 17:29
OK, probably we need to throw in a similar isatty check and then just do our own write-a-bit-at-a-time logic.

**Comment by lizmat** [comment] 2024-10-04 12:17
Assuming this is no longer an issue on more modern Windows versions, so closing

**Closed by lizmat** 2024-10-04 12:17 UTC
Labels: Windows
