### ISSUE TITLE
segfaults raised when trying with this code.

### ISSUE THREAD

**Issue by xinminglai** [rakudo/rakudo#2147] opened 2018-07-29 20:20 UTC
## The Problem
Segfault will be raised when try with this test scripts.

## Expected Behavior
Should run smooth without any problem.

## Actual Behavior
rakudo compiler segfaults.

## Steps to Reproduce
#----- file main.p6
```
#!env perl6

use lib '.';
use A;
use B;
my %cfg = ({});
```

#----- file A.pm6
```
use B;
```

#----- file B.pm6
```
multi infix:['|+|'] (Any, $arg) is export { }
multi infix:['|+|'] (Int \o, $t) is export { }
```

Save these 3 files to same directly, and run perl6 main.p6

## Environment
* Operating system: Gentoo Base System release 2.4.1
* Compiler version (`perl6 -v`): This is Rakudo version 2018.06-265-gb7379a804 built on MoarVM version 2018.06-314-g4199a9564

**Comment by zoffixznet** [comment] 2018-07-29 20:21
Bisects to https://github.com/rakudo/rakudo/commit/722d8711b359a1e5b9f21c3d2a954f18074bffd8 that brought NQP https://github.com/perl6/nqp/compare/2017.09-40-ga6a1aa0...2017.09-59-g60f79d3 and MoarVM https://github.com/MoarVM/MoarVM/compare/2017.09.1-553-ga4fef0b...2017.09.1-575-gd4e230a

**Comment by taboege** [comment] 2018-11-13 12:49
I stumbled on this too today. Here is a repository for reproducing the problem https://github.com/taboege/rakudo-segv -- at least I think that it is the same. It seems to be caused by two (not one; see the README) operators being `use`d multiple times.

It *does* segfault here under valgrind, so maybe that allows progress to be made. Even though the backtrace in gdb seems to disagree:
```
Thread 1 "moar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a03e73 in MVM_interp_run () from //home/tab/src/perl6/rakudo/install/lib/libmoar.so
(gdb) bt
#0  0x00007ffff7a03e73 in MVM_interp_run () from //home/tab/src/perl6/rakudo/install/lib/libmoar.so
#1  0x00007ffff7afd755 in MVM_vm_run_file () from //home/tab/src/perl6/rakudo/install/lib/libmoar.so
#2  0x0000555555555630 in main ()
```
the valgrind output suggests that the stack is exhausted, because manually running `valgrind --main-stacksize=$N` always leads to a segfault with `The main thread stack size used in this run was {$N ± a bit}.` Or maybe I'm misinterpreting that.

My version: `This is Rakudo version 2018.10 built on MoarVM version 2018.10`. Let me know if there is anything more I can do.

**Comment by dogbert17** [comment] 2020-10-22 16:30
Ran it several times without any problems. Some bisectable wizardry is needed in order to figure out which commit fixed this.

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-82-gb30fa3a71.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.

**Comment by lizmat** [comment] 2024-10-05 13:22
closing as untestable

**Closed by lizmat** 2024-10-05 13:22 UTC
Labels: severe, SEGV
