### ISSUE TITLE
set op(s?) do(es?)n't preserve class inheritance

### ISSUE THREAD

**Issue by grondilu** [rakudo/rakudo#5190] opened 2023-02-06 12:55 UTC
## The Problem

set union operator `(+)` does not preserve inheritance from Bag.

## Steps to Reproduce

```raku
use Test;
plan 1;

class Foo is Bag {}
isa-ok Foo.new("a") (+) Foo.new("b"), Foo, "union of two Foo instances should be a Foo instance";
```

## Environment
* Operating system: fedora 37
* Compiler version: Rakudo™ v2022.12-1118-g03b3b13db

**Comment by lizmat** [comment] 2023-02-06 13:03
I think the problem is broader, and probably applies to *all* set operators.

**Comment by lizmat** [comment] 2023-02-06 18:25
Added test with https://github.com/Raku/roast/commit/a647a0ecae  I think all set ops are covered now.  So closing.  Please re-open if I missed something  :-)

**Closed by lizmat** 2023-02-06 18:25 UTC
