### ISSUE TITLE
Creating a lot of PseudoHashes in a loop sometimes hangs

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#1835] opened 2018-05-17 05:11 UTC
`my $a; $a = PseudoStash.new for ^9999; say $a` (almost?) always hangs and pegs the cpu. However, with MVM_SPESH_DISABLE=1, MVM_SPESH_OSR_DISABLE=1, and MVM_SPESH_INLINE_DISABLE=1 it's fine, but not with MVM_JIT_DISABLE=1.

```
[00:44] <AlexDaniel> bisect: my $a; $a = PseudoStash.new for ^9999; say $a
[00:45] <+bisectable6> AlexDaniel, Bisecting by exit signal (old=2015.12 new=b8318b8). Old exit signal: 0 (None)
[00:46] <+bisectable6> AlexDaniel, bisect log: https://gist.github.com/e3cb6a0d63e4d77af2068587d75f5ff1
[00:46] <+bisectable6> AlexDaniel, (2017-08-11) https://github.com/rakudo/rakudo/commit/76af17a8b1dc79f8923109bbd284afed2e2fe011
```
Bisected: (2017-08-11) https://github.com/rakudo/rakudo/commit/76af17a8b1dc79f8923109bbd284afed2e2fe011

**Comment by MasterDuke17** [comment] 2018-05-17 11:16
Interestingly, `my $a; for ^10_000 { $a = PseudoStash.new for ^1_000 }; say $a;` works just fine.

**Comment by timo** [comment] 2018-05-25 17:13
it's infinitely recursing when printing out the pseudostash, because it finds itself in there after the loop body has been inlined, i.e. $a looks kind of like PseudoStash.new( a => PseudoStash.new( a => PseudoStash.new( a => … ) ) )

and gistseen isn't filtering it out for some reason.

**Comment by lizmat** [comment] 2018-07-26 20:49
I can't reproduce this anymore.  Perhaps this got fixed with the last round of @jnthn's refactoring?

**Comment by AlexDaniel** [comment] 2018-07-26 22:19
@lizmat so what do you get exactly?

Output from committable:
```
¦«2016.01.1,2016.02,2016.03,2016.04,2016.05,2016.06,2016.07.1,2016.08.1,
  2016.09,2016.10,2016.11,2016.12,2017.01,2017.02,2017.03,2017.04.3,
  2017.05,2017.06,2017.07»:
PseudoStash.new(("\$_" => 9998))

¦«2017.08,2017.09,2017.10,2017.11,2017.12,2018.01,2018.02.1,2018.03,
  2018.04.1,2018.05,2018.06»:
«timed out after 10 seconds» «exit signal = SIGHUP (1)»
¦«HEAD(08b449e)»:
unknown lexical type encountered when bulding context hash
  in block <unit> at /tmp/wchCWz55D5 line 1

«exit code = 1»
```
Does not look fixed to me.

**Comment by jnthn** [comment] 2018-07-26 22:50
Yes, the case that is fixed is the *sensible* one where you acquire a PseudoStash and then actually do a lookup. The case where you acquire it and then use it some arbitrary time later is the outstanding one (and I've by now concluded there's no way to do that except forcing a full stack deopt of the thread where it takes place).

**Comment by jnthn** [comment] 2018-07-26 22:51
>  forcing a full stack deopt of the thread where it takes place

Oh, and to add to that - possibly forbidding any frame that's implicated from doing OSR, but I'm hoping I might be able to avoid that restriction.

**Comment by lizmat** [comment] 2024-10-04 09:54
Added test with https://github.com/rakudo/rakudo/commit/25640772f7

**Closed by lizmat** 2024-10-04 09:54 UTC
Labels: regression, MoarVM

**Comment by lizmat** [comment] 2025-06-14 09:22
This issue appears to have re-surfaced in 6.e:
```
$ raku -e 'use v6.*; my $a; $a = PseudoStash.new for ^9999; $a.gist'
```
