### ISSUE TITLE
fp numbers with outside-range chars hang

### ISSUE THREAD

**Issue by llelf** [rakudo/rakudo#1624] opened 2018-03-18 20:17 UTC
E. g.

    :10<1.a>
    :16<0.G>

(just eval in repl)

This is Rakudo version 2018.02.1-175-gb75d9b1e14 built on MoarVM version 2018.02-171-geee5be412
implementing Perl 6.c.

**Comment by lizmat** [comment] 2018-03-18 22:16
This appears to happen at compile time:

$ perl6 -e ':10<1.a>; BEGIN say “compiling”'
^C
$

**Comment by AlexDaniel** [comment] 2018-03-18 22:29
This is a regression after (2018-02-28) https://github.com/rakudo/rakudo/commit/7835652d54f6538337b694f03e936a4814bec925

**Comment by AlexDaniel** [comment] 2018-03-18 23:08
Tests.

**Comment by lizmat** [comment] 2018-03-18 23:08
Was caused by infinilooping in the error message creation.  Fixed with 15ccfd3331 , tests may still be needed outside of an EVAL string.

**Closed** 2018-03-18 23:20 UTC
Labels: regression
