### ISSUE TITLE
leaking BOOTStr

### ISSUE THREAD

**Issue by gfldex** [rakudo/rakudo#1800] opened 2018-05-06 09:26 UTC
BOOTStr seams to be leaking into Perl 6 land. The following example is as golfed as I could get it. Surprisingly the lookup hash is required to trigger this bug.

```
my regex suffix { <[dhms]> };

my %unit-multipliers = 's' => 1;

put <s>»\
    .match(/<suffix>/)».hash\
    .map(-> % ( Str(Any) :$suffix ) { %unit-multipliers{$suffix} });
```

## Expected Behavior

I would expect BOOTStr not to be there or at least be able to coerce to Str.

## Actual Behavior

```
Type check failed in binding to parameter '<anon>'; expected Any but got BOOTStr (?)
  in block <unit> at /home/dex/projects/perl6/rakudobug/BOOTStr-leakage.p6 line 7
```
## Environment
```
This is Rakudo version 2018.04-21-g24a907747 built on MoarVM version 2018.04-34-g25f165ad7
implementing Perl 6.c.
```

make clean and rm-ing .precache did not help.

**Comment by Digicrat** [comment] 2019-02-28 06:25
The same bug exists when using action classes with Grammars.  I found a temporary workaround using the .subst method.  Other attempts to coerce it into a string, even sprintf, failed.

An abbreviated example, where this method is part of a Grammar action class:

```
has Set $.list; # Set in constructor
method word($in) {
     say $in.^name; # Says name of Grammar class
     say $.mnemonics{$in}; # Always False - this is not what I expect
     # my $tmp = sprintf("%s", $in); # dies with "This representation (Null) doe snot support elems (for type VMNull)
     say $.mnemonics{ $in.subst(/@/,"") }; # True (/w correct input).  This subst has no effect, since @ symbol it not a valid character in my grammar.
}
```

An earlier test case within this function (which I neglected to save) gave the exact same type check error as in the original issue here -- searching on that error is what led me to this page.

**Comment by vrurg** [comment] 2020-11-30 00:00
Fixed alongside with the new coercion semantics. A coercion method was indeed returning a `BOOTStr`.

**Comment by Altai-man** [comment] 2020-11-30 10:57
@vrurg is there a test?

**Comment by vrurg** [comment] 2020-11-30 14:17
@Altai-man Rakudo build itself serves as a test.

**Comment by Altai-man** [comment] 2020-11-30 14:24
Erm, so Rakudo was impossible to build due to this, until 2020.10 release where the coercion protocol was implemented? I am clearly lack details here, sorry for being incompetent while pedantic.

**Comment by vrurg** [comment] 2020-11-30 14:58
@Altai-man being pedantic is the quality I often miss. :) The new coercions doesn't allow a coercion method to return something what doesn't match the target type. So, something like `method Str { nqp::join(...) }` became unacceptable and started causing problems. Unfortunately, I don't remember when exactly `Match` returning `BOOTStr` started causing issues, but I'm most certain that 4efcdba2b4 is what fixed this issue.

**Comment by Altai-man** [comment] 2020-11-30 15:32
@vrurg in OP there is a clear golfed code to reproduce. I can reproduce it as well on 2020.10:

```
➜  ~ raku --version
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.10.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.10.
➜  ~ raku foo.raku
Type check failed in binding to parameter '<anon>'; expected Any but got BOOTStr (BOOTStr)
  in block <unit> at foo.raku line 7
```

So I am sure we can add this golf to roast and close it. :)

**Comment by vrurg** [comment] 2020-11-30 15:40
Sorry, no idea what OP means here. Anyway, if somebody makes a test I can review it. But otherwise, frankly saying, I need some rest of anything related to coercions.

**Comment by Altai-man** [comment] 2020-11-30 16:31
You sure deserve some.

My point is that we need to add somewhere in roast a test to ensure this:

```
➜  ~ raku --version
Welcome to Rakudo(tm) v2020.11.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.11.
➜  ~ cat foo.raku
my regex suffix { <[dhms]> };

my %unit-multipliers = 's' => 1;

put <s>»\
    .match(/<suffix>/)».hash\
    .map(-> % ( Str(Any) :$suffix ) { %unit-multipliers{$suffix} });

➜  ~ raku foo.raku
1
➜  ~ rakubrew switch moar-2020.10
Switching to moar-2020.10
➜  ~ raku foo.raku
Type check failed in binding to parameter '<anon>'; expected Any but got BOOTStr (BOOTStr)
  in block <unit> at foo.raku line 7

➜  ~
```

**Comment by patrickbkr** [comment] 2020-11-30 16:33
Just to clear this up: OP == original poster, referring to the person that started a thread.

**Comment by ab5tract** [comment] 2024-05-25 20:53
The test from this issue report has been added to roast in [288cd5b](https://github.com/Raku/roast/commit/288cd5b89a5801f6507f84a13a668d3f7c876bd8).

**Closed by ab5tract** 2024-05-25 20:53 UTC
