### ISSUE TITLE
`say` optimization breaks Test::Output

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2751] opened 2019-03-08 08:58 UTC
```bash
PERL6LIB=lib bin/blin.p6 --old=2018.12 --new=HEAD Test::Output
```

Test::Output – Fail, Bisected: 9770c1aa15fff0f54df2af0291be2c07c0de486e

Originally reported on IRC and on https://github.com/perl6-community-modules/perl6-Test-Output/issues/3.

**Comment by AlexDaniel** [comment] 2019-03-08 09:00
Obligatory pings: @scovit, @lizmat

**Comment by scovit** [comment] 2019-03-08 10:25
The module declare an IO::Handle class and do not define the method say

**Comment by scovit** [comment] 2019-03-08 11:37
Can I allow myself a comment on the style? I find the two tags with urgency banners as aggressive, and the term obligatory as extremely rude.
That said, to me the bug seems to be that it is possible to create wrong code that still works but then breaks, I don't know if this bug can be fixed..

**Comment by JJ** [comment] 2019-03-09 08:05
OK, let's see if we can fix that "wrong code" on the other side.

**Comment by scovit** [comment] 2019-03-09 08:34
Thank you JJ, I'm sorry but I am in a personal condition right now, and even this message is typed on a cellphone, otherwise I would have been glad to help

**Comment by JJ** [comment] 2019-03-09 08:35
@scovit no problem. Working on it right now. Best of luck.

**Comment by JJ** [comment] 2019-03-09 09:28
The exception is in this line:

        $PROCESS::ERR = $err;

Really have no idea why.

**Comment by JJ** [comment] 2019-03-09 10:37
Looks like I managed to fix it. A new release has been made. It does not seem to be a Rakudo error, unless you consider as such a LTA error message . Main problem was that it was not using WRITE for the IO::Handle that was defined, and then that said Handle didn't use UTF8 encoding.

**Comment by AlexDaniel** [comment] 2019-03-09 13:37
> Can I allow myself a comment on the style? I find the two tags with urgency banners as aggressive, and the term obligatory as extremely rude.

That's not the intent, sorry. When I was the release manager, my understanding was that we shouldn't be breaking modules on a whim. When I see a commit that makes things faster but doesn't have a written justification for breaking things, I file a bug report. `blocker` label was added because this is something we definitely want to figure out (one way or another) before the release. `regression` label in this case is perhaps not necessary, but the issue didn't exist before (and was bisected), so technically it's right. Authors are pinged because IMO they need to know that there is an issue. Obligatory in a sense that I'm pinging you because that's the process, not because you have to drop all things and fix that issue asap.

Does that make sense? Maybe we should have a written document about it somewhere. Maybe on https://github.com/perl6/problem-solving.

@kawaii

**Comment by AlexDaniel** [comment] 2019-04-15 13:36
I don't remember the status of this why it still has a label.

**Comment by kawaii** [comment] 2019-04-21 11:31
@AlexDaniel it doesn't seem like too much of a priority right now regardless of the status, so I'll remove the blocker label from it.

**Comment by JJ** [comment] 2022-01-09 08:59
Is this still blocking anything?

**Comment by niner** [comment] 2022-01-09 09:38
Reading up on this issue and the linked one in Test::Output I'm stumped about why we've not yet reverted the broken change. Breaking modules for some optimizations in Rakudo is not OK unless those modules did something that was clearly wrong. The latter has not been discussed at all, neither here, nor in the other issue.

**Comment by lizmat** [comment] 2022-01-09 10:25
`sub say` has evolved since then.  It is now basically a modern version of the original:
````raku
    $_ := $*OUT;
    .print: nqp::concat(x.gist,.nl-out)
````
So I'm unsure how https://github.com/rakudo/rakudo/commit/9770c1aa15fff0f54df2af0291be2c07c0de486e can still be the issue here?

**Comment by niner** [comment] 2022-01-09 10:45
Is the bug actually still present? Unfortunately neither bug report actually 
mentions what was wrong. Many of the links don't work anymore either. That's 
why it's so important to always include all the relevant information and e.g. 
commit messages like "Fix GH issue 1234" are no use at all.

**Comment by jonathanstowe** [comment] 2022-01-09 10:53
If there was a test failure, there isn't now:

```
===> Testing: Test::Output:ver<1.001002>
[Test::Output] t/00-use.t ...... ok
[Test::Output] t/01-capture.t .. ok
[Test::Output] t/02-Test.pm.t .. ok
[Test::Output] All tests successful.
[Test::Output] Files=3, Tests=11,  1 wallclock secs
[Test::Output] Result: PASS
===> Testing [OK] for Test::Output:ver<1.001002>
```

**Comment by JJ** [comment] 2022-01-09 11:53
Actually, that was due to a [workaround](https://github.com/raku-community-modules/Test-Output/commit/44566cca4f8029d686e18181b4c7c3544e80f907), mainly upgrading to 6.d. It's probably still present in 6.c

**Comment by niner** [comment] 2022-01-09 12:16
> It's probably still present in 6.c

So what is "it"?

**Comment by JJ** [comment] 2022-01-09 12:22
Sorry, the bug. Answering to @jnthn in that comment.

**Comment by jonathanstowe** [comment] 2022-01-09 12:29
Right, but I can't find anywhere that says explicitly what that was just that there was a test failure. Maybe I'm not looking hard enough, but a reproduction with the actual error might be useful to save us going round in circles.

**Comment by JJ** [comment] 2022-01-09 12:44
Trying to reproduce it [here](https://github.com/raku-community-modules/Test-Output/tree/task/reproduce-error), lowering the version to 6.c, but no go. I would say it's fixed. Closing.

**Closed by JJ** 2022-01-09 12:44 UTC
Labels: regression, ecosystem modules
