### ISSUE TITLE
.index complains needlessly, .indices silently doesn't work

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2743] opened 2019-03-05 05:41 UTC
```perl6
say "banana".index("ana", -0.9)
```
```
1
```
```perl6
say "banana".index("ana", -1)
```
```
Position in index out of range. Is: -1, should be in 0..6
  in block <unit> at -e line 1
```
So it says it needs to be in 0..6 range, yet -0.9 is fine. Let's crosscheck against .indices:
```perl6
say "banana".indices("ana", -0.9)
```
```
(1)
```
```perl6
say "banana".indices("ana", -1)
```
```
()
```
No exception. Inconsistent.

**Comment by lizmat** [comment] 2024-10-09 12:29
This is caused by the `.Int` behaviour on `-0.9`
```raku
say (-0.9).Int;  # 0
```
Since the `Cool` args are coerced to `Int`, this is what you get.

Considering this a case of DIHWIDT, so closing

**Closed by lizmat** 2024-10-09 12:29 UTC
Labels: edge cases
