### ISSUE TITLE
Compiler error when using ::?CLASS probably a bit too much

### ISSUE THREAD

**Issue by Altreus** [rakudo/rakudo#3483] opened 2020-02-14 22:10 UTC
## The Problem

An unlikely combination of four things causes an unintelligible error.

* A Role with a multi method
* One part of which is unimplemented (`...`)
* Using  `::?CLASS` to define the invocant
* Using `returns ::?CLASS` as well

Causes the compilation error:

`No such method 'raku' for invocant of type '::?CLASS'`

Any of these not being the case allows compilation with no problem.

The rationale behind these four aspects of the role is to allow a method with a class-level implementation as well as an object-level one. Any class consuming the role gets a default behaviour for the class-level implementation, which is to instantiate an object and run the other one.

Strictly, it is not necessary to use `returns ::?CLASS` but I wanted to be specific that they should both return an object of the consuming class's type.

[Example](https://github.com/shuppet/p6-api-discord/blob/8cc714c8ae9d905d35d2c76005312a17a7563874/lib/API/Discord/HTTPResource.pm6#L33):

```raku
role JSONy {
    multi method from-json (::?CLASS:U: $json) returns ::?CLASS {
        self.new.from-json($json);
    }

    multi method from-json (::?CLASS:D: $json) returns ::?CLASS { ... }
}
```

```
> class A does JSONy {}
===SORRY!=== Error while compiling:
No such method 'raku' for invocant of type '::?CLASS'
```

## Environment
```
$ raku -v
This is Rakudo version 2020.01 built on MoarVM version 2020.01.1
implementing Perl 6.d.

$ uname -a
Linux adouglas 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
```

**Comment by Altreus** [comment] 2020-02-14 22:12
I also tried `returns ::?CLASS:D` since that's more specifically what I wanted; same error.

**Comment by vrurg** [comment] 2020-02-14 23:43
Actually, use of `::?CLASS` in a role not such a good idea in general because when a role is being defined the symbol is generic any any kind of issues are possible when the role is being introspected. Such as in this case, the actual error comes from an attempt to report another error where exception text is being formed using stringification of method's signature.

The immediate workaround would be to use `::?ROLE` instead.

**Comment by Altreus** [comment] 2020-02-15 12:27
I was expecting `::?CLASS` to resolve to the class that consumed it. However, the error makes it clear that it's resolved to the role name anyway:

`Multi method 'from-json' with signature :(API::Discord::JSONy:D: $json, *%_) must be implemented`

Is there no symbol, then, that I can use in a role that resolves at time of composition to the consuming class? My only goal is to be as explicit as possible to help the compiler, VM, and developer to understand the semantics.

**Comment by Altreus** [comment] 2020-02-15 12:49
Apparently it's more complicated than my above comment. I'm currently trying to work out what caused the above message; all my simple experiments so far have provided the consuming class in the error message, not the role name.

**Comment by vrurg** [comment] 2020-02-15 22:05
@Altreus I guess somehow you've got your role puned. So far, that's the only way I can think of. In any other case your `::?CLASS` has no value until the role is applied, and it's not applied yet because the error raised while application is in progress.

I played a bit with the error message in order to prevent the secondary exception caused by calling `raku` method on a generic type. There're two ways to handle the situation. In first you get this:

```
Multi method 'from-json' with signature :(Foo:D: $json, *%_ --> ::?CLASS) must be implemented by Foo because it is required by a role
```

The problem with this approach is that `::?CLASS:D` would still be reported as `::?CLASS` and it might be confusing.

In another the return type is not reported at all. This way is even worse.

**Comment by vrurg** [comment] 2020-02-16 00:57
The rabbit hole is apparently deeper than it seemed. As a matter of fact, signature parameters are getting instantiated by the time of the error is thrown. But the return value is not. That fact I should've spotted when played with the error message because the type of `self` is reported as `Foo:D` whereas the return type remains `::?CLASS`. This actually has another implication: such method prototype cannot be fulfilled because no type can match a generic, even the generic itself. So, adding a method with identical signature to the class fails as if there is no method at all.

I've produced a fix for both problems. Will merge if it passes tests. But there is one problem remains: for `::?CLASS:D` in a return value `:D` is stripped of silently. So, for `method foo(--> ::?CLASS:D) {...}` a `method foo(--> ::?CLASS) { }` would be a match. @lizmat, do you have an idea how to get this straighten out?

**Comment by vrurg** [comment] 2020-02-17 19:28
Closing via merge of #3484

**Comment by vrurg** [comment] 2020-02-17 20:51
Oops, forgot about tests...

**Closed** 2022-05-01 22:42 UTC
Labels: tests needed, LTA
