### ISSUE TITLE
Flopping test: 99-misc.t (2019.07)

### ISSUE THREAD

**Issue by nxadm** [rakudo/rakudo#3065] opened 2019-07-18 16:28 UTC
## The Problem
This test fails a lot on Travis and sometime on my home machine. It looks like it more likely to fail when the resources are limited.
 t/08-performance/99-misc.t  ...................................... Dubious, test returned 1 (wstat 256, 0x100)

## Expected Behavior

Test should pass.

## Actual Behavior

Test fails often.

## Steps to Reproduce

Make test
## Environment
* Operating system: ubuntu 16.04, 18.04, 18.10 both amd64 and i386
* Compiler version (`perl6 -v`): NA

**Comment by lizmat** [comment] 2019-07-18 16:32
Perhaps an empty loop gauging the performance of the system in question, and then adapt the tests according to that ??

**Comment by AlexDaniel** [comment] 2019-07-18 16:57
The problem is that it tests for performance difference of 2x which is right on the edge of what the actual performance difference is. Just bump it to several times like 5x or whatever, and it'll stop flapping for most people.

**Comment by nxadm** [comment] 2019-07-18 17:50
Yeah, on Travis I need to build some pkgs 4 times on a row (so far) to get a run without an error. 2 is indeed way to limited. I wonder if resource dependant tests make sense, maybe only for the release manager?

**Comment by AlexDaniel** [comment] 2019-07-18 17:52
Yeah but that's what RAKUDO_SKIP_TIMING_TESTS is for, right? I don't think there's a huge problem with that test, it's just that the margin is *way* too small.

**Comment by nxadm** [comment] 2019-07-18 17:57
If possible I prefer not to skip test, so rakudo-pkg can be an additional canary (at least for me).

**Comment by nxadm** [comment] 2019-07-18 18:18
For the record, it looks like i386 are more impacted (they seem to fail a lot more).

**Comment by KrisShannon** [comment] 2019-07-18 23:21
Maybe just skip those timing tests for the actual deployment builds?

It looks like you generally are running the tests on master and then when you're happy you create the release tag.

That means the deployment builds have already had the tests run on them in master,  so skipping those tests which can temporarily fail due to resource constraints in Travis can avoid failed deployments.

```$ENV{RAKUDO_SKIP_TIMING_TESTS} = 1 if '' ne ($ENV{TRAVIS_TAG} // '');```

**Comment by nxadm** [comment] 2019-07-19 06:47
@KrisShannon I think the changes proposed by @AlexDaniel will solve the problem. The changes can be of course removing at the deployment builds, but in fact master and feature branches are run a lot more, and the problem happens there too of course.

**Comment by AlexDaniel** [comment] 2019-07-27 06:13
I simply bumped the limit. The commit that does it is currently on the release branch and it'll land on master soon.

**Comment by AlexDaniel** [comment] 2019-07-27 06:13
I simply bumped the limit. The commit that does it is currently on the release branch and it'll land on master soon.

**Comment by nxadm** [comment] 2019-08-02 16:47
I am not able to reopen this issue, but I raised the threshold again because while the changed helped eliminated fails on 64-bit builds, 32-bit still hit it. PR sent.

**Comment by AlexDaniel** [comment] 2019-08-02 17:36
Ah, already merged. OK for now, I guess.

**Comment by CurtTilmes** [comment] 2020-04-09 20:57
This is failing for `2020.02.1` in my alpine distribution for architecture `ppc64`:
https://gitlab.alpinelinux.org/ctilmes/aports/-/jobs/89046#L1914
```
t/08-performance/99-misc.t ...................................... 
 Dubious, test returned 1 (wstat 256, 0x100)
 Failed 1/3 subtests 
[...]
 Test Summary Report
 -------------------
 t/08-performance/99-misc.t                                    (Wstat: 256 Tests: 3 Failed: 1)
   Failed test:  3
   Non-zero exit status: 1
 Files=103, Tests=1793, 97 wallclock secs ( 0.83 usr  0.13 sys + 674.23 cusr 15.45 csys = 690.64 CPU)
 Result: FAIL
```

**Comment by lizmat** [comment] 2020-04-09 21:12
Perhaps we should run this test with `RAKUDO_SKIP_TIMING_TESTS` on any non-Intel hardware, as that does not have a JIT.  Or maybe make a function that indicates whether a JIT is available and active, and decide to run that test only when there's a JIT running?

**Comment by CurtTilmes** [comment] 2020-04-09 22:26
It currently runs `make RAKUDO_SKIP_TIMING_TESTS=1 test`.
That is what fails.

Here's the whole setup: 
https://gitlab.alpinelinux.org/ctilmes/aports/-/blob/rakudo-2020.02.1/testing/rakudo/APKBUILD

For reference, here's what I'm using for moarvm and nqp:
https://gitlab.alpinelinux.org/ctilmes/aports/-/blob/rakudo-2020.02.1/testing/moarvm/APKBUILD
https://gitlab.alpinelinux.org/ctilmes/aports/-/blob/rakudo-2020.02.1/testing/nqp/APKBUILD

Suggestions for improvement welcome!  I'm neither an Alpine nor a Rakudo expert.

**Comment by niner** [comment] 2020-04-19 11:51
I would really like us to change these tests to opt-in instead of opt-out. We know pretty much every developer who can benefit from these tests but we don't know who might have to set RAKUDO_SKIP_TIMING_TESTS. It'd be much easier for us to add a `export RAKUDO_RUN_TIMING_TESTS=1` to our .profile

**Comment by jnthn** [comment] 2020-04-19 14:11
> I would really like us to change these tests to opt-in instead of opt-out. We know pretty much every developer who can benefit from these tests but we don't know who might have to set RAKUDO_SKIP_TIMING_TESTS. It'd be much easier for us to add a export RAKUDO_RUN_TIMING_TESTS=1 to our .profile

Yes, I agree with this.

**Comment by Altai-man** [comment] 2020-05-01 13:14
This test attempts to test performance, which behaves differently depending on various circumstances, but, if I am not mistaken, does not relate to actual sanity of the rakudo.
While we surely want to make those tests opt-in as suggested above, this is not a blocker.

**Comment by AlexDaniel** [comment] 2020-05-02 06:43
@Altai-man but failing tests affect all packagers (e.g. Debian).

**Comment by Altai-man** [comment] 2020-05-02 08:19
Is there anything preventing core devs from excluding them and making opt-in?

**Comment by AlexDaniel** [comment] 2020-05-02 08:49
@Altai-man no, it's just that somebody has to do it.

**Closed** 2020-05-02 10:35 UTC
Labels: intermittent, severe
