### ISSUE TITLE
"Cannot modify an immutable Match" after matching junction against m//

### ISSUE THREAD

**Issue by stuart-little** [rakudo/rakudo#4002] opened 2020-11-02 19:17 UTC
## The Problem

Matching a junction against `m/<blah>/` will set `$/` to a junction whose eigenstates are immutable. This then results in the error in the title whenever `m//` is called, until `$/` is reset (e.g. directly or with an `rx//` match).

First:

```
> any('a','b') ~~ m/./
False
```
Then:

```
> 'x' ~~ m/./
Cannot modify an immutable Match (｢a｣)
  in block <unit> at <unknown file> line 1
```
## Expected Behavior

First, I'd expect `any('a','b') ~~ m/./` to return `True`. Secondly, I would expect

```
> 'x' ~~ m/./
｢x｣
```

## Actual Behavior

First, `any('a','b') ~~ m/./` returns false. Secondly, one gets

```
> 'x' ~~ m/./
Cannot modify an immutable Match (｢a｣)
  in block <unit> at <unknown file> line 1
```
immediately after that first match, apparently due to `$/` being set to the junction `any(｢a｣, ｢b｣)` with the `｢a｣` eigenstate immutable.

## Steps to Reproduce

The relevant REPL commands are all provided above: run

```
any('a','b') ~~ m/./
```
and

```
'x' ~~ m/./
```
in immediate succession in the REPL.

## Environment
* Operating system: multiple Linux and Linux-like (Ubuntu 20.04, Arch, Android 10 with the [termux](https://termux.com/) terminal emulator)
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo(tm) v2020.10-13-g39c515957.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.10.
```

## Additional info
There is also [an SO question](https://stackoverflow.com/questions/64650122/matching-a-junction-makes-match-immutable-in-raku?noredirect=1#comment114312788_64650122) on the matter.

**Comment by raiph** [comment] 2020-11-02 20:14
My analysis:

The `False` is correct. The `~~` sets `$_` to `any('a','b')`. Then it evaluates `m/./`. The result is `any(｢a｣, ｢b｣)`, and `$/` set to the same value. Then the `~~` calls `.ACCEPTS` on that value, i.e. it does the same as `any('a','b') ~~ any(｢a｣, ｢b｣)`. That evaluates to `False`.

----

The subsequent problem golfs down to having set `$/` to a junction:
```
$/ = any 42;
$_ = 'x';
m/./
```
displays `Cannot modify an immutable Int (42)`.

In your case you get `Cannot modify an immutable Match` because `$/` has been set to `any(｢a｣, ｢b｣)`.

----

The issue is presumably that some code in the matching logic doesn't expect `$/` be set to a `Junction`.

It seems that just adding an empty code block, anywhere in the regex, makes the bug go away:

```
$/ = any 42;
$_ = 'x';
m/ . {} /
```

**Comment by stuart-little** [comment] 2020-11-02 20:29
@raiph Thank you: I was pkaying around with `.ACCEPTS` too, but did not, apparently, push the analysis to its conclusion.

All sorts of fun can be had with the seemingly-paradoxical conclusions:

```
> all('a','b') ~~ m/x/
True
```
because, by the same logic, that's the same as
```
all('a','b') ~~ all((Any), (Any))
```
(given that `$/` gets set to the latter). Fascinating :)..

**Comment by raiph** [comment] 2020-11-02 20:52
While the overall smartmatch design is a great thing imo, the behaviors of some individual types is <strike>mental</strike> emmental due to lack of tuits in both design terms (stuff not properly/fully specified) and implementation (bugs).

The same is true of junctions.

Put the two together and...

**Comment by stuart-little** [comment] 2020-11-02 21:23
Re: the nit: yes, I mis-"spoke" (though I understood the distinction at the time); It's not the setting, it's the returning. 

Re: the mind-bending quality of junctions: I could not find a reference to quantum mechanics on the `Raku` [documentation page](https://docs.raku.org/type.html), but I think it's a fair assumption the phrase [eigenstate](https://docs.raku.org/language/faq#How_can_I_extract_the_values_from_a_Junction?) for the inner components `'a'` and `'b'` of a junction like `any('a','b')` is a nod to the living/dead [Schrodinger-cat](https://en.wikipedia.org/wiki/Schr%C3%B6dinger's_cat) alternative. There too, the specific states among the achievable possibilities for a quantum system are, mathematically, [eigenstates](https://en.wikipedia.org/wiki/Introduction_to_eigenstates) ([eigenvectors](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors) of certain linear operators). 

I actually hadn't made that connection until just now; apologies for overindulging in this message if it was well-known to insiders :).

**Comment by lizmat** [comment] 2020-11-02 21:34
Fixed with https://github.com/rakudo/rakudo/commit/5b3691817a

**Comment by stuart-little** [comment] 2020-11-02 21:53
For what it's worth, the problem I reported seems to have disappeared after building just now, with https://github.com/rakudo/rakudo/commit/5b3691817a:

```
> any('a','b') ~~ m/./
False
> 'x' ~~ m/./
｢x｣
``` 
(so no error there, as previously).

**Comment by melezhik** [comment] 2020-11-17 19:37
I've added rkp test for this if it helps - http://rakudist.raku.org/sparky/report/RakuPlay-1/1214

**Closed** 2020-11-18 23:01 UTC
Labels: tests needed
