### ISSUE TITLE
Regression in Cro (fetching a json file eats RAM)

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3223] opened 2019-10-09 20:41 UTC
Script:
```perl6
#!/usr/bin/env perl6

use Cro::HTTP::Client;

use Telemetry;

start loop {
    exit 42 if T<max-rss> > 2_000_000; # the amount of RAM it is allowed to eat is limited here
    sleep 0.5;
}

my $url = ‘https://modules.perl6.org/search.json’;

my $resp = await Cro::HTTP::Client.get: $url,
      headers => [
          User-Agent => ‘perl6 ecosystem unbitrot’,
      ],
;
my $x = await $resp.body;
```

If you run it on newer-ish rakudo it'll eat your RAM. This wasn't the case before. Bug confirmed: https://colabti.org/irclogger/irclogger_log/perl6?date=2019-10-09#l679

The code comes from a [real script](https://github.com/perl6/ecosystem-unbitrot/blob/e919c8cba58231c12a75e7473fc8f5f96f677735/lib/Unbitrot/Utils.pm6#L13-L17) that I use for [ecosystem-unbitrot](https://github.com/perl6/ecosystem-unbitrot) repo.

Bisected with [Blin](https://github.com/perl6/Blin):
```bash
bin/blin.p6 --old=2018.11 --new=HEAD --custom-script=croregression.p6 Cro::HTTP::Client
```

* croregression.p6 – Fail, Bisected: 541a4f1628e4e156f6eefc547938746f7b736104

**Comment by jnthn** [comment] 2019-10-10 14:58
Does it do this at HEAD of `Cro::HTTP::Client`?

**Comment by AlexDaniel** [comment] 2019-10-10 15:07
The HEAD version requires Log::Timeline which doesn't pass tests:
```
===> Testing: Log::Timeline:ver<0.3>
# Failed test 'Log file has expected number of lines'
# at t/output-json-lines.t line 30
# expected: '6'
#      got: '42'
reached end of string when looking for something
```

Otherwise it works fine, indeed!

**Comment by AlexDaniel** [comment] 2019-10-10 15:36
Hmm that's weird. Log::Timeline is clean in Blin, but it wasn't when I was trying to install it myself.

**Comment by jnthn** [comment] 2019-10-10 15:38
I believe there was a `JSON::Fast` version released at some point with a regression, iirc that led to `:!pretty` leaving newlines in, and we relied on it not doing that in order to produce JSONLines format. It's possible Blin runs the latest `JSON::Fast` without that.

**Comment by niner** [comment] 2019-10-20 11:07
On HEAD the script uses 1.2 GB RSS. That's kinda much, but it stays there for a while until it finishes. With Cro::HTTP 0.8.1 the script bails out when reaching 2GB

**Comment by niner** [comment] 2019-10-20 11:14
It's indeed Cro::HTTP commit 02d8c3a21f4271956df2c5f214dce2dda881fb47 that fixes this issue. The commit message fits and it explains why it's triggered by a change in rakudo:

    "Fix a memory leak in FrameParser
    Timotimo++ for helping with identifying a source of the leak.
    It seems we previously relied on a rakudo bug that terminated loop
    after `when` branch executing, as it seems to be fixed now, we were
    appending an unchanging $data to $buffer in a loop which caused a
    severe memory leak. Adding an explicit `last` fixes it."

I guess it's time for a Cro::HTTP release :) Closing this issue as it's not rakudo's fault.

**Closed by niner** 2019-10-20 11:14 UTC
Labels: BLOCKER, regression
