### ISSUE TITLE
Make Deprecations skip core locations by default

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1362] opened 2018-01-04 02:24 UTC
It's kinda hard to get the position right using it. For `:buffer` deprecation, looks like it prints right location when used as a method, but when as sub is used (that uses the method), the deprecation references core source code instead of user's code and [that caused user confusion](https://irclog.perlgeek.de/perl6/2018-01-04#i_15649320) and rogue code hunt :(

```
2017.12.11 zoffix@VirtualBox~$ perl6 -e '$*OUT.open: :buffer'
Saw 1 occurrence of deprecated code.
================================================================================
Method open (from IO::Handle) seen at:
  -e, line 1
Deprecated since v2017.09.455.g.2.fba.0.ba.0.d, will be removed with release v2018.01!
Please use :out-buffer argument to control handle buffering instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
2017.12.11 zoffix@VirtualBox~$ perl6 -e 'open "-", :buffer'                                                                                                                                                                                                    
Saw 1 occurrence of deprecated code.
================================================================================
Method open (from IO::Handle) seen at:
  SETTING::src/core/io_operators.pm, line 93
Deprecated since v2017.09.455.g.2.fba.0.ba.0.d, will be removed with release v2018.01!
Please use :out-buffer argument to control handle buffering instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
2017.12.11 zoffix@VirtualBox~$ perl6 -v
This is Rakudo version 2017.12-11-g2a8287c built on MoarVM version 2017.12-1-g912f967
implementing Perl 6.c.
2017.12.11 zoffix@VirtualBox~$ 
```

**Comment by lizmat** [comment] 2024-10-01 16:26
Closing as I cannot reproduce

**Closed by lizmat** 2024-10-01 16:26 UTC
