### ISSUE TITLE
perl6 --target=parse hanging

### ISSUE THREAD

**Issue by cognominal** [rakudo/rakudo#2905] opened 2019-05-17 16:02 UTC
--target=parse hanging on simple cases where --target=ast works fine
  $ perl6 --target=parse -e 'grammar A {}'

 
* Operating system: : MacOS Mojave 
* Compiler version (`perl6 -v`): 
This is Rakudo version 2018.12-245-g94995d60e built on MoarVM version 2018.12-35-gc001ce23c
implementing Perl 6.d.

**Comment by vrurg** [comment] 2019-05-17 16:28
Duplicate of #2827

**Closed** 2019-05-17 18:43 UTC
