### ISSUE TITLE
Build fails when BSD make is used

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3190] opened 2019-09-16 21:20 UTC
## The Problem
When the configuration script detects that BSD make should be used, it doesn't output a Makefile that can actually be used with BSD make.

## Expected Behavior
The build should succeed.

## Actual Behavior
This happens:

```
bastille% make
+++ Checking for moar NQP version
+++ Expanding   gen/moar/main-version.nqp
===WARNING===
  /home/morfent/.perl6/bin/nqp-m version 2019.07.1-97-g00eaa35e8 is outdated, 2019.07.1-100-gf1ab9a56f expected.
+++ Generating  gen/moar/perl6.nqp
+++ Generating  gen/moar/Grammar.nqp
+++ Generating  gen/moar/World.nqp
+++ Generating  gen/moar/ModuleLoader.nqp
+++ Compiling   blib/Perl6/ModuleLoader.moarvm
Bad modifier: [1]}
>
```

The part make has an issue with is `${>:[1]}`, which is what nqp-configure outputs when selecting the first prerequisite. This is not the syntax you use for modifiers and `1` isn't a valid modifier in the first place.

One way to fix this would be to use `.SUFFIXES` and specify the first prerequisite using `$<` in a suffix rule. Another way would be to use the `:M` modifier to match only the first prerequisite's filename. I'm not comfortable doing either myself though since they both would require some refactoring and I don't have the time to look into how the build system works enough to do that at the moment.

## Steps to Reproduce

Run `./Configure.pl` on a *BSD system without `gmake` installed, then run `make`.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.6 GENERIC.MP#253 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.07.1-313-ga08dcf0036 built on MoarVM version 2019.07.1-198-gafc4be154
implementing Perl 6.d.

**Comment by Leont** [comment] 2019-09-16 23:34
bsdmake can also be used on Linux, it's usually called `bmake`. I assume it can be reproduced that way on Linux as well.

**Comment by vrurg** [comment] 2019-09-16 23:36
It would require additional changes to Configure to support bmake. But I see no use for that. Anyway, I have a FreeBSD VM and a bunch of servers around. Still wonder what's went wrong with this.

**Comment by vrurg** [comment] 2019-09-16 23:45
OpenBSD. Again... :( Huston, we have a problem...

`${>:[1]}` selects the first prerequisite. Where it's being used only the first one is needed, the rest are there to indicate if rebuild is required.

Suffix rules cannot be used because they don't play well with multi-directory build. They don't play with it whatsoever. We generate `.moarvm` in a couple of dirs.

With `:M` I don't see how it could extract exactly one first prereq. It turns out I don't know how to do it with OpenBSD make.  

*Leaving in despair for deep googling...*

**Comment by Kaiepi** [comment] 2019-09-17 13:58
>With :M I don't see how it could extract exactly one first prereq. It turns out I don't know how to do it with OpenBSD make.

The rule for building `$(PERL6_ML_MOAR)` looks like this at the moment:

```
$(PERL6_ML_MOAR): 	$(M_BUILD_DIR)/ModuleLoader.nqp gen/nqp-version
	@echo '+++ Compiling	$@'
	@$(M_NQP) $(M_NQP_FLAGS) --target=mbc --output=$@ ${>:[1]}
```

This is how it'd look with `:M` to work with OpenBSD make:

```
$(PERL6_ML_MOAR): 	$(M_BUILD_DIR)/ModuleLoader.nqp gen/nqp-version
	@echo '+++ Compiling	$@'
	@$(M_NQP) $(M_NQP_FLAGS) --target=mbc --output=$@ $>:M$(M_BUILD_DIR)/ModuleLoader.nqp
```

**Comment by vrurg** [comment] 2019-09-17 17:20
But then I don't need $> (or whichever variable is used by a particular make) in first place! The whole point of using the first prerequisite in the build is to have one common receipe for all targets. And that was allowing for using single template for all of them. Now, to take care of OpenBSD lazy approach I'd need to rework this part and do more manual stuff... I'd prefer stick to gmake and work on something more productive. :(

*NB* I'm really, really confused by their approach. `make` is not a security threat. What holds them back from upgrading it to some later version of it??

**Comment by vrurg** [comment] 2019-09-19 17:00
While reworking NQP makefiles I have developed a workaround for this stupid problem. Can't promise to incorporate the change into rakudo soon – not before the rework is done. But it's on the way.

**Comment by vrurg** [comment] 2019-09-23 19:16
@Kaiepi pls, re-open and ping please if it still fails on OpenBSD. But since it's not using the first prereq variable anymore everything should be fine.

**Comment by Kaiepi** [comment] 2019-10-11 22:27
My bad, I didn't catch the notification for this until now.

@vrurg, the build still fails. MoarVM and nqp seem to work fine, but this happens when I try to run `perl6` after installing Rakudo:
```
bastille% perl6 -e 'say 1'
Unhandled exception: While looking for '/home/morfent/.perl6/share/perl6/runtime/perl6.moarvm': no such file or directory
```

**Comment by vrurg** [comment] 2019-10-11 22:59
@Kaiepi could you please check if your `perl6` is the compiled version? What's in your Makefile? Especially `PERL6_HOME` content. Do you use `DESTDIR`?

In the `Makefile` check the `m-install-main` rule, it must have a line like:

```
        @$(CP) $(PERL6_MOAR) $(PERL6_DEBUG_MOAR) '$(DESTDIR)$(PERL6_HOME)/runtime'
```

**Comment by Kaiepi** [comment] 2019-10-11 23:12
> @Kaiepi could you please check if your perl6 is the compiled version?

`perl6` appears to be the runner Rakudo compiles.

> Especially PERL6_HOME content. 
```
PERL6_HOME = /home/morfent/.perl6/share/perl6
```

> Do you use `DESTDIR`?

Not sure what you mean. I passed `--prefix=$HOME/.perl6` to `./Configure.pl`, in case that's related, but `DESTDIR` is used in the Makefile and there isn't any kind of assignment to it in the file.

`m-install-main` has the rule you're talking about.

**Comment by vrurg** [comment] 2019-10-21 01:00
Closing via #3255

@Kaiepi would it be in my power, I'd discourage people from using OpenBSD make. In the following rule:

```
m-install:: m-all m-install-pre m-install-main m-install-post
```

it somehow manages to execute `m-install-main` preprequisites prior to `m-install-pre` prereqs! Ok, there could be a race condition but `.NOTPARALLEL` is active. Still, it found the way to first install new files and them call the rule which removes old ones!

**Closed by vrurg** 2019-10-21 01:00 UTC
Labels: BLOCKER, build

**Comment by Leont** [comment] 2019-10-22 19:11
> it somehow manages to execute m-install-main preprequisites prior to m-install-pre prereqs!

To be fair, that is entirely legal if `m-install-main` doesn't depend on `m-install-pre`
