### ISSUE TITLE
Coercion puns target roles

### ISSUE THREAD

**Issue by Leont** [rakudo/rakudo#5034] opened 2022-08-19 19:37 UTC
## The Problem
```
class Foo::Bar { ... }
role Foo {
  method foo { ... }
  method COERCE($in) {
    return Foo::Bar.new
  }
}
class Foo::Bar does Foo {
  method foo {}
}
my Foo(Any) $foo = 1;
```

## Expected Behavior
`$foo` will contain a `Foo::Bar` object, as it would if `Foo` doesn't contain an unimplemented method.

## Actual Behavior
Error: `Method 'foo' must be implemented by Foo because it is required by roles: Foo.`

## Environment
* Compiler version (`perl6 -v` or `raku -v`):
```
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
```

**Comment by vrurg** [comment] 2022-08-19 20:16
While this particular example looks rather clear, but the problem is more complex in general and, I'm afraid, doesn't have a good solution.

First of all, invoking a method on a role results in pun. This is the general principle. Because this case of coercion is just a syntax sugar for `Foo.COERCE(1)`, the error is apparently inevitable.

I think a better solution would be to split the role in two with the coercing one to be punnable.

**Comment by Leont** [comment] 2022-08-20 01:29
> First of all, invoking a method on a role results in pun. This is the general principle.

Right, I guess I'm barking at the wrong tree then.

> I think a better solution would be to split the role in two with the coercing one to be punnable.

I don't see how that could workable TBH.

**Comment by vrurg** [comment] 2022-08-20 01:38
I don't know the exact requirements of your original task, but something like this:

```raku
role R1 {
    method COERCE($) { Foo::Bar.new }
}
role R2 does R1 {
    method foo {...}
}
class Foo::Bar does R2 { method foo { } }
```

**Comment by vrurg** [comment] 2022-08-25 15:12
@Leont Can we close this one?

**Closed** 2022-08-25 19:23 UTC
