### ISSUE TITLE
Non-void $i++ is somehow 13% faster than ++$i

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1491] opened 2018-02-07 02:43 UTC
Was working on my postfix-to-prefix optimizations today and noticed my tricks were 25% slower where at worst I expected the opt to do no benefit.

Turns out, even without my optimizations postfix ++ is somehow faster than prefix++:

```
<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + $i++ }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «2.05785717␤»
<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + $i++ }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «1.9331361␤»
<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + $i++ }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «1.9125183␤»

<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + ++$i }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «2.1624072␤»
<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + ++$i }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «2.1104659␤»
<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + ++$i }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «2.14803603␤»

<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { $z = 1 + $i++ }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «1.92103945␤»

<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «0.5950968␤»
<Zoffix__> m: my $i = 1; my $z; { for ^10000_000 { }; say now - ENTER now }
<camelia> rakudo-moar 052a0bbef: OUTPUT: «0.58464195␤»


<Zoffix__> m: say (2.1-.59)/(1.92-.59)
<camelia> rakudo-moar 052a0bbef: OUTPUT: «1.135338␤»
```

Currently going to comment out the optimization.

Also: https://irclog.perlgeek.de/perl6/2018-02-07#i_15786774

**Comment by zoffixznet** [comment] 2018-09-24 17:30
Another weird case with native type being slower than non-native one. Don't see why it'd be boxing anywhere in the code and [there is a native candidate](https://github.com/rakudo/rakudo/blob/2bdf2b35a/src/core/Int.pm6#L246)

```
+leont │ m: my int $x; {for ^2000_000 { $x++ }; say now - ENTER now}                                                                                         
1325   +camelia │ rakudo-moar 2bdf2b35a: OUTPUT: «0.26520674␤»                                                                                                        
1325     +leont │ m: my Int $x; {for ^2000_000 { $x++ }; say now - ENTER now}                                                                                         
1325   +camelia │ rakudo-moar 2bdf2b35a: OUTPUT: «0.15650947␤»
```

**Comment by Leont** [comment] 2018-09-26 20:52
>Another weird case with native type being slower than non-native one. Don't see why it'd be boxing anywhere in the code and there is a native candidate

Spesh not picking it up perhaps?

**Comment by jnthn** [comment] 2018-09-26 20:58
Much of the problem is that spesh understands native references pretty poorly so far (and we conservatively take references in case the target parameter `is rw`). A similar pattern to the spesh box/unbox elimination can probably be applied to eliminate quite a few of the unrequired native reference takes (at least, that's the direction I'd planned to explore in), and some better static analysis can get rid of more of them even before we reach spesh too.

**Comment by dogbert17** [comment] 2020-10-21 16:32
Looks more reasonable now I think:

    dogbert@dogbert-VirtualBox:~$ perl6 -v
    Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.09-82-gb30fa3a71.
    Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
    Built on MoarVM version 2020.09-15-g4b06df1a6.
    dogbert@dogbert-VirtualBox:~$ perl6 -e 'my int $x; {for ^2000_000 { $x++ }; say now - ENTER now}'
    0.019414
    dogbert@dogbert-VirtualBox:~$ perl6 -e 'my Int $x; {for ^2000_000 { $x++ }; say now - ENTER now}'
    0.0733987

**Comment by lizmat** [comment] 2024-10-02 10:13
Closing as the world has changed

**Closed by lizmat** 2024-10-02 10:13 UTC
Labels: performance, weird
