### ISSUE TITLE
qqx tries to run the module, not the sub inside the module

### ISSUE THREAD

**Issue by ToddAndMargo** [rakudo/rakudo#5120] opened 2022-12-06 16:01 UTC
qqx tries to run the module, not the sub inside the module:

Windows 10 Pro 21H2
Windows 11 Pro 22H2

https://rakudo.org/dl/rakudo/rakudo-moar-2022.07-01-win-x86_64-msvc.msi

When you run this sub inside your program, there is no issue.

If you put the sub into a module, then qqx tries to
run the module itself, not the batch file this sub
creates:

```
<RunCmdModule.pm6>
## unit module RunCmdModule;
## RunCmdModule.pm6


sub RunCmd( Str $CommandStr, Bool $EchoOff = False ) returns Str is export( :RunCmd )  {
   my $PathIAm          = $?FILE;
   my Str $BatFile = $PathIAm ~ ".bat";
   ## print "$BatFile\n";   
   my Str $RtnStr;
   my Str $CmdStr = "";  
   
   if $EchoOff  { $CmdStr = Q[@echo off] ~ "\n"; }
   $CmdStr = $CmdStr ~ $CommandStr ~ "\n";  
   ## print "$CmdStr";

   spurt( $BatFile, $CmdStr );
   ## print "$RtnStr\n";
   $RtnStr = qqx { $BatFile };
}
</RunCmdModule.pm6>
```

Test one liner (run in the same directory as the module):
     raku -e "use lib '.'; use RunCmdModule :RunCmd; say RunCmd(Q[ls]);

Result: qqx tries to run the .pm6 file, not the .bat file
   https://imgur.com/q7NzxIil.png

**Comment by raiph** [comment] 2022-12-06 18:15
For Help on using GitHub (GH) when at an issues page, click the icon at the top right of the page. You should see a drop down menu, with "Signed in as Todd" or similar at the top, followed by a list of menu options. Near the end of the list, above "Settings" and "Sign out", is "Help". Click that to get started with Help about GH.

The main Help page has a search field at its top right. I entered "formatting" and the first page listed is [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

There's stuff there about `#`s, but I'd say the bit you need to apply starts:

> To format code or text into its own distinct block, use triple backticks.

That way `#` will be formatted like all the rest of the text (code) within that block.

**Comment by ToddAndMargo** [comment] 2022-12-06 23:51
> I took the liberty of wrapping your code in backticks (edit and look at the source to see where). Please update the position as needed, and check out @raiph's notes.

Thank you.  Much prettier!

**Comment by ToddAndMargo** [comment] 2022-12-07 08:50
If you want to have some fun with this bug, register .pm6 extension to notepad like I did for easy editing.    Run run the example.  Notepad will open up with the contents of the pm6 module.  Drove me nuts until I realized what was happening.

**Comment by raiph** [comment] 2022-12-07 10:29
Hi @ToddAndMargo,

> If you want to have some fun ... Drove me nuts until I realized what was happening.

Are you saying that:

A) This issue should be closed?

or merely:

B) Contra the issue's title, `qqx` does NOT try to run the module.

C) This issue is impacted by what you realized, but the issue should remain open, and the title unchanged.

If A) applies, please click one of the buttons for closing this issue and close it. If B) applies, please edit the issue title. If C) applies, please note that. Thx.

**Comment by ToddAndMargo** [comment] 2022-12-07 11:38
> I'd imagine that the reason for what you _think_ is happening, is that when `$?FILE` is in a _module_ it is will actually be something like `/path/to/module/RunCmdModule.pm6 (RunCmdModule)` and not just the path to the file, that is it has the name of the module in parentheses after the path.
> 
> I guess you could do something like `$?FILE.split(' ')[0]` to get the actual path.

If you take out the comment marks, you can see what is going on.  You can also see the .bat file being created and where.  And a quick look at the batch file and you will also see it is in the same directory as the current working directory.  Please do run the sample I posted.  Also note that I have used this sub for years without problem.  This problem occurred when I moved the sub to a module.

**Comment by jonathanstowe** [comment] 2022-12-07 13:09
I *did* run the sample, that's how I could see what was happening.

**Comment by ugexe** [comment] 2022-12-07 14:07
@jonathanstowe is correct. @ToddAndMargo you seem to be confused at how spaces work in the shell i.e. `qqx{...}` - I would suggest taking the advice you are given with more than a grain of salt before suggesting others aren't understanding.

**Comment by ToddAndMargo** [comment] 2022-12-07 15:32
On 12/7/22 06:07, Nick Logan wrote:
> @jonathanstowe <https://github.com/jonathanstowe> is correct. 
> @ToddAndMargo <https://github.com/ToddAndMargo> you seem to be confused 
> at how spaces work in the shell i.e. |qqx{...}| - I would suggest taking 
> the advice you are given with more than a grain of salt before 
> suggesting others aren't understanding.

Nick,

1) Why does this sub work perfectly when not
in a module?

2) did you run teh sample with "raku" as the first parameter?
(the results are different if you use the registry.)

2) Were the test you ran on Windows 10 or 11?

3) why is the .bat file perfectly created (Test 4 below)?

4) why is the .bat file NOT being run (it is missing in
tests 1,2,3)?

Spaces in a Windows shell commands are a known issue:
https://github.com/Raku/problem-solving/issues/166

This is one of the reasons I created this sub.
(The other is its ease of use.)

Please show me the space issue with this example?
```
#!/usr/bin/raku
# NativeWinUtilsTest.pl6

use lib '.';
use NativeWinUtils :RunCmd;

print ( RunCmd
     "@ echo off\nrem test for NativeUtils :RunCmd\ndir *.bat\n" ) ~
     "\n";
```

Test 1:
raku NativeWinUtilsTest.pl6
This is the result.  *.pm6 is registered to Notepad,
so qqx opens notepad with the module's
(NativeWinUtils.pm6) source code:

https://imgur.com/ESthQjrl.png


Test2:
In this test, the registry is used to find raku:

NativeWinUtilsTest.pl6
https://imgur.com/pawIOjol.png

Notice the difference?  This time qqx is opening up
source (NativeWinUtilsTest.pl6) of the pl6.  I
also have *.pl6 registered to Notepad.


Now for another example.  This time with the sub inside

```
#!/usr/bin/raku
# NativeWinUtilsTest2.pl6

sub RunCmd( Str $CommandStr, Bool $EchoOff = False ) returns Str  {
    my $PathIAm          = $?FILE;
    my Str $BatFile = $PathIAm ~ ".bat";
    # print "$BatFile\n";
    my Str $RtnStr;
    my Str $CmdStr = "";

    if $EchoOff  { $CmdStr = ***@***.*** off] ~ "\n"; }
    $CmdStr = $CmdStr ~ $CommandStr ~ "\n";
    # print "$CmdStr";

    spurt( $BatFile, $CmdStr );
    $RtnStr = qqx { $BatFile };
    # print "$RtnStr\n";
}

print ( RunCmd
     "@ echo off\nrem test for NativeUtils :RunCmd\ndir *.bat\n" ) ~
     "\n";
```

Test 3:
This is the result of running with raku found by
the registry.  Notice that it again open up the
source code (NativeWinUtilsTest2.pl6):

https://imgur.com/mpvITygl.png

So same problem.


Test 4
BUTTTTTTTT, if we do not let the registry open
the file NativeWinUtilsTest2.pl6, we get the
following:

https://imgur.com/KhG47gMl.png

It works!


And look here. from Test 4
K:\Windows\NtUtil>dir *.bat | grep -i NativeWinUtilsTest
12/07/2022  06:57 AM  55 NativeWinUtilsTest2.pl6.bat

There are no spaces in the .bat file name.


I am also seeing no difference in the way I am
accessing $?FILE

print "\$\?FILE; = <" ~ $?FILE ~ ">\n";
$?FILE; = <K:\Windows\NtUtil/NativeWinUtilsTest2.pl6>

print "\$\?FILE.split(' ')[0] = <" ~ $?FILE.split(' ')[0] ~ ">\n";
$?FILE.split(' ')[0] = <K:\Windows\NtUtil/NativeWinUtilsTest2.pl6>


Now I have noticed that only Test 4 creates
the .bat file and only Test 4 will respond
to the "print" debug statements when the
comments are removed.

So, qqx may not be the culprit.  But something is
and it is not the way I am handling $?FILE

**Comment by ugexe** [comment] 2022-12-07 15:49
> Why does this sub work perfectly when not in a module?

see the earlier comment answering this by @jonathanstowe - what part about it are you confused about? Please be explicit when answering this, and avoid asking more questions in an attempt to answer it.

> Were the test you ran on Windows 10 or 11?

The version of windows doesn't matter - the behavior you are complaining about will occur regardless of the OS involved. That you seem to think the OS is relevant kind of shows that you might be confused about the nature of the problem (which again others have clarified and I think you should give a second thought to)

> why is the .bat file perfectly created (Test 4 below)?

Because you aren't creating the bat file via a shell command. `"a path with spaces.txt".spurt("foo")` will work despite the fact there are spaces in the path, yet a shell command such as  `touch a path with spaces.txt` unsurprisingly doesn't create a single file named "a path with spaces.txt" whereas `touch "a path with spaces.txt"`

> why is the .bat file NOT being run (it is missing in tests 1,2,3)?

As mentioned above, you are using a shell command. Part of the shell command includes a path with spaces. Therefore the shell command is using the part of the path up to the space (which does not include the `.bat`). 

> Please show me the space issue with this example?

Again, please read the earlier comments. Specifically `when $?FILE is in a module it is will actually be something like /path/to/module/RunCmdModule.pm6 (RunCmdModule)`

**Comment by jonathanstowe** [comment] 2022-12-07 15:51
> 1) Why does this sub work perfectly when not in a module?

Because `$?FILE`  has `(ModuleName)` appended when it is in 'module' - that is when you have included the file by `use` or `require`.

As an example, create a `Module.pm6` with just:

```
say $?FILE;
```

Then `use` it like:

```
raku -e 'use lib "."; use Module'
```
I get:

```
/home/jonathan/devel/raku/rc/Module.pm6 (Module)
```

You will get something that reflects your path.

Then *run* it with :

```
raku Module.pm6
```

I get:

```
/home/jonathan/devel/raku/rc/Module.pm6
```

**Comment by ToddAndMargo** [comment] 2022-12-07 16:08
Windows only cares about the last extension which is ".bat".  It does not matter what the rest of the name is.  IT DOES NOT MATTER if the file name has a pm/pm6 in it as long as it is not the extension.

```
my $PathIAm          = $?FILE;
my Str $BatFile = $PathIAm ~ ".bat";
```

And in the module (Test 1)  the first print debug statement is not being seen:
```
   my $PathIAm          = $?FILE;
   my Str $BatFile = $PathIAm ~ ".bat";
   print "$BatFile\n";   
 ```

Also Windows has a lot of bugs in it and acts differently than Linux.  Please only give me examples in Windows.  And do not trouble shoot my code in Linux either.  (Yes, Linux quality spoils me too, but I have to support Windows as well.  There is no bug 166 in Linux.)

```
>raku -e "use lib '.'; NativeWinUtils"
===SORRY!=== Error while compiling -e
Undeclared name:
    NativeWinUtils used at line 1

```

**Comment by ToddAndMargo** [comment] 2022-12-07 16:25
On 12/7/22 07:49, Nick Logan wrote:
> Because you aren't creating the bat file via a shell command. |"a path 
> with spaces.txt".spurt("foo")| will work despite the fact there are 
> spaces in the path, yet a shell command such as |touch a path with 
> spaces.txt| unsurprisingly doesn't create a single file named "a path 
> with spaces.txt" whereas |touch "a path with spaces.txt"|


The symptom is the same whether there are spaces in
the name or not.

**Comment by ugexe** [comment] 2022-12-07 16:31
I think you're the only one confused about this behavior; the reason its acting this way has been explained to you by multiple people. Most of the things you are saying suggest you are not taking the advice you are given seriously, instead deciding that advice/information must be wrong simply because *you* do not understand it. I'd ask you to step back and ask yourself why you seem to be the only one left confused. That being said, I'm afraid I can't make things any clearer for you and wish you luck in drawing whatever conclusion you are looking for.

**Comment by ToddAndMargo** [comment] 2022-12-07 16:38
On 12/7/22 07:49, Nick Logan wrote:
> Again, please read the earlier comments. Specifically |when $?FILE is in 
> a module it is will actually be something like 
> /path/to/module/RunCmdModule.pm6 (RunCmdModule)|


I changed the bat file name to MickyMouse.bat
and you guys were right all along.

This is another manifstation of

qqx not picking up quotes in Windows 7
https://github.com/Raku/problem-solving/issues/166
Posted Feb 26, 2020

Does it always take this long to fix these kind of bugs?

Please close this as a duplicate of issue 166

A special thank to everyone's patience with this.

**Comment by ToddAndMargo** [comment] 2022-12-07 16:41
On 12/7/22 07:51, Jonathan Stowe wrote:
>      1. Why does this sub work perfectly when not in a module?
> 
> Because |$?FILE| has |(ModuleName)| appended when it is in 'module' - 
> that is when you have included the file by |use| or |require|.

Now that I know this is bug 166, it sound like a job for regex.

$BatFile ~~ s/ $( Q[.pm] .* /.bat/;

**Comment by coke** [comment] 2024-03-25 23:09
Duplicate of #166 (per @ToddAndMargo)

**Closed by coke** 2024-03-25 23:09 UTC
