### ISSUE TITLE
Cannot run installations of the JVM

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#3842] opened 2020-08-07 09:28 UTC
## The Problem
I can't run this with an installation of Rakudo on the JVM in my `$PATH`:
```
$ rakudo-j -e 'say 1'
```

## Expected Behavior
This should output `1`.

## Actual Behavior
An error gets thrown:
```
bastille% rakudo-j -e 'say 1'
Error: Could not find or load main class perl6
Caused by: java.lang.ClassNotFoundException: perl6
```

## Steps to Reproduce

Install Rakudo on the JVM and run the test command.

## Environment
* Operating system:
OpenBSD bastille.kennel.qt 6.7 GENERIC.MP#7 amd64
* Compiler version (`perl6 -v` or `raku -v`):
Can't tell because the same error gets thrown. This is a build of Rakudo on the JVM on a branch forked some point after v2020.07 was released.

**Comment by Altai-man** [comment] 2020-08-07 09:30
Can you check if the regression was present in 2020.07 or not?

**Comment by Kaiepi** [comment] 2020-08-07 09:31
I can in a minute. FTR, the `rakudo-j` binary in the `rakudo` directory from `make` works alright.

**Comment by Kaiepi** [comment] 2020-08-07 10:28
The regression isn't present in 2020.07.

**Comment by patrickbkr** [comment] 2020-08-11 12:35
@Kaiepi Can you re-test this on latest master? There were some significant changes in the parts of the code that seem to have caused this regression.

**Comment by patrickbkr** [comment] 2020-08-14 14:08
I tried to reproduce this on latest master (rakudo commit [9d6d8d](https://github.com/rakudo/rakudo/commit/9d6d8dd7a72aed698e30b6fe4b8eea62642c62c6)) as well as the commit prior to merging my SysConfig changes ([798614c](https://github.com/rakudo/rakudo/commit/798614cb788ff80cea6dd92cb05d61af95ae8304)). I could not reproduce the error in any case.

My test environment:

- Java 11
- Fedora Linux
- testing both the installed `rakudo-j` as well as the executable in the build directory
- always adding the installation directory to the path, switching to some other folder and then calling `rakudo-j -e 'say 1'`

Maybe this is OpenBSD specific? I'll try to get my OpenBSD VM up.

**Comment by patrickbkr** [comment] 2020-08-16 22:07
I now also tried to reproduce this on OpenBSD. Results are similar. Both, current master branch and the commit prior to my SysConfig changes are working.

My test environment:

- Java 11
- OpenBSD 6.5 GENERIC#809 amd64
- testing the installed `rakudo-j`
- adding the installation directory to the path, switching to some other folder and then calling `rakudo-j -e 'say 1'`

@Kaiepi Can you provide more details about how you compiled and set things up?

**Comment by Kaiepi** [comment] 2020-08-18 07:35
It was still happening on the branch I'm working on, even though I rebased it on master a few days ago. I figured out this was happening because I never renamed `PERL6_HOME` to `RAKUDO_HOME` in my `.zshenv`. With that set, `$ rakudo-j -e 'say 1'` works fine.

**Comment by patrickbkr** [comment] 2020-08-18 07:50
There is a fallback in [src/Perl6/SysConfig.nqp](https://github.com/rakudo/rakudo/blob/master/src/Perl6/SysConfig.nqp#L21) to fall back to `PERL6_HOME` should `RAKUDO_HOME` be undefined. So it should still work with only `PERL6_HOME` set. I'll investigate.

Out of curiosity: Why do you need to set `RAKUDO_HOME` explicitly in your setup? In a normal setup (not moving the install directory after installation) it shouldn't be necessary to set `RAKUDO_HOME`.

**Comment by Kaiepi** [comment] 2020-08-20 13:10
Ah, I didn't know that.

**Comment by Altai-man** [comment] 2020-08-24 09:31
@patrickbkr hi! The fix can be merged if it's clean, I think.

**Closed** 2020-08-24 20:34 UTC
Labels: BLOCKER

**Comment by sammysheep** [comment] 2020-09-27 03:57
# Environment
This is Rakudo version 2020.09-3-gf74950c51 built on JVM
implementing Raku 6.d.

MacOS Mojave.

openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

# Code
File *hello.pl*:
`say "Hello world!"`

# Build

`./rakudo --target=jar --output=hello.jar hello.pl`

# Outcome

```{shell}
$ java -jar hello.jar 
no main manifest attribute, in hello.jar
```

# Working through the problem a little more..
Opened with vim and added a Main-Class attribute to the manifest manually. The jar contains something like:

```{bash}
META-INF/MANIFEST.MF
D5625B53FBA625BE7327B00E93C45B4AF87A2617.class
D5625B53FBA625BE7327B00E93C45B4AF87A2617.serialized
```

I added the second line to the manifest:
```{bash}
Manifest-Version: 1.0
Main-Class: D5625B53FBA625BE7327B00E93C45B4AF87A2617
```

Now I get a new error, likely because there is still an issue with the manifest or the java class path:
```{bash}
Error: Could not find or load main class D5625B53FBA625BE7327B00E93C45B4AF87A2617
Caused by: java.lang.NoClassDefFoundError: org/raku/nqp/runtime/CompilationUnit
```

**Comment by sammysheep** [comment] 2020-09-27 04:00
Ignore deleted post, wrong thread.
