### ISSUE TITLE
Intermittent wrong response when using IO::Path.relative and Promise

### ISSUE THREAD

**Issue by FCO** [rakudo/rakudo#3959] opened 2020-10-15 15:20 UTC
## The Problem
When using `IO::Path.relative($base)` inside a start block, some times it returns the wrong value:

```
raku -e '
my $path = "/etc";
multi a($_) {
   start {
      when .d { await do for .dir -> $f { a $f } }
      default { my $a = .relative: $path; say "wrong: $_\n\t$a\n\t{ .relative: $path }" if $a eq "." || $a.starts-with: "../" }
   }
}


await a $path.IO
'
wrong: /etc/postfix/transport
	.
	postfix/transport
wrong: /etc/openldap/slapd.conf.default
	../slapd.conf.default
	openldap/slapd.conf.default
wrong: /etc/cups/snmp.conf.default
	.
	cups/snmp.conf.default
wrong: /etc/apache2/extra/httpd-multilang-errordoc.conf
	.
	apache2/extra/httpd-multilang-errordoc.conf
wrong: /etc/openldap/schema/fmserver.schema
	../fmserver.schema
	openldap/schema/fmserver.schema
An operation first awaited:
  in block  at -e line 5

Died with the exception:
    Failed to get the directory contents of '/etc/cups/certs': Failed to open dir: Permission denied
      in block  at -e line 5
      in block  at -e line 5

```

(please ignore the "Permission denied" exception)

It some times thinks the relative path for a file is ".", or a path starting with "../" where it shouldn't be needed. And if you "ask". again it gives you the right answer.

another example:

https://colabti.org/irclogger/irclogger_log/raku?date=2020-10-15#l173

## Expected Behavior

It should always return the right path relative to the passed base

## Actual Behavior

It sometimes return the wrong value.

## Steps to Reproduce

Just run the code above several times'

## Environment

I've tested it on Mac, on debian docker image with camelia and evalable6

**Comment by FCO** [comment] 2020-10-15 15:23
it seems to happen without specifying a base as well:

```
raku -e '
sub a($_) { start { when .d { await do for .dir -> $f { a $f } }; default { my $a = .relative; say "wrong: $_\n\t$a\n\t{ .relative }" if $a eq "." || $a.starts-with: "../" } } }; await a ".".IO
'
wrong: rpc
	.
	rpc
wrong: asl/com.apple.mkb.internal
	../com.apple.mkb.internal
	asl/com.apple.mkb.internal
wrong: asl/com.apple.callhistory.asl.conf
	.
	asl/com.apple.callhistory.asl.conf
wrong: cups/cups-files.conf
	.
	cups/cups-files.conf
wrong: openldap/schema/corba.ldif
	../corba.ldif
	openldap/schema/corba.ldif
wrong: openldap/schema/ppolicy.ldif
	.
	openldap/schema/ppolicy.ldif
An operation first awaited:
  in block  at -e line 2

Died with the exception:
    Failed to get the directory contents of '/private/etc/cups/certs': Failed to open dir: Permission denied
      in block  at -e line 2
      in block  at -e line 2
```

**Comment by FCO** [comment] 2020-10-15 15:32
It seems it does not need recursive starts:

```
raku -e '
sub a($_) { start { when .f { my $a = .relative; die "wrong: $_\n\t$a\n\t{ .relative }" if $a eq "." || $a.starts-with: "../" } } }; await do for |".".IO.dir xx 10000 { .&a }
'
An operation first awaited:
  in block <unit> at -e line 2

Died with the exception:
    wrong: rc.common
	    ../rc.common
	    rc.common
      in block  at -e line 2
```

**Comment by Altreus** [comment] 2021-09-20 09:18
I can reproduce this with @FCO's last comment, but I can't offer any further insight. It can take a few tries and the file in question is different each time, and there's nothing special about the files it chooses to die on.

**Comment by Altreus** [comment] 2021-09-20 12:17
I adapted it to `my $a = .relative ~ " $*CWD";` and by the time `$*CWD` is evaluated here it is correct. This doesn't imply it was correct when `.relative` was evaluated, however...

**Comment by lizmat** [comment] 2024-10-14 14:17
This was probably due to dynamic variables not being handled correctly in start blocks.

Closing assuming this has been fixed, please re-open if his assumption was faulty

**Closed by lizmat** 2024-10-14 14:17 UTC
