### ISSUE TITLE
Bogus "emit without supply or react" when using hyper

### ISSUE THREAD

**Issue by niner** [rakudo/rakudo#4410] opened 2021-06-17 10:03 UTC
## The Problem

Using `.hyper` when processing an array leads to an occasional "emit without supply or react" error in a worker. This can be trivially reproduced with:

```
> rakudo -e 'my @a; loop { @a.hyper[0] }'
A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at -e line 1
  in block <unit> at -e line 1

Died at:
    emit without supply or react
      in block <unit> at -e line 1
      in block <unit> at -e line 1
```

Tested on Rakudo commit 28ff12a8b884ac01044e4c3ecd07feeab8e2b73f

**Comment by lizmat** [comment] 2021-06-17 10:08
Confirmed on MacOS.

**Comment by niner** [comment] 2021-06-17 10:12
It's *not* a spesh issue. Can reproduce it with MVM_SPESH_DISABLE=1 set, but it takes longer to fail.
It's also *not* caused by commit 6f42d19eb0. I suspected that one but reverting it also turned out to just defer the inevitable.

**Comment by niner** [comment] 2021-06-17 10:28
@dogbert17 noted some suspicious tsan output: https://gist.github.com/dogbert17/dea0a2c20be1826851615980be3b1710
I'm skeptical about a data race though. AFAICT cache_node_head can only ever change from NULL to a valid pointer, but not back, so I don't think this can cause any issues.

**Comment by lizmat** [comment] 2021-06-17 10:56
A full stack traces, just in case

```
$ rl 'my @a; loop { @a.hyper[0] }'
emit without supply or react
   at SETTING::src/core.c/Exception.pm6:62  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/Exception.pm6:569  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:print_control)
 from SETTING::src/core.c/Exception.pm6:591  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:<anon>)
 from gen/moar/stage2/NQPHLL.nqp:2094  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/nqp/lib/NQPHLL.moarvm:)
 from SETTING::src/core.c/control.pm6:198  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from SETTING::src/core.c/Mu.pm6:63  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from SETTING::src/core.c/Supplier.pm6:55  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from SETTING::src/core.c/Supplier.pm6:104  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from SETTING::src/core.c/Channel.pm6:42  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:send)
 from SETTING::src/core.c/Rakudo/Internals/HyperWorkStage.pm6:43  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:batch-used)
 from SETTING::src/core.c/Rakudo/Internals/HyperToIterator.pm6:51  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:pull-one)
 from SETTING::src/core.c/Iterator.pm6:28  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:push-exactly)
 from SETTING::src/core.c/Iterator.pm6:45  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:push-at-least)
 from SETTING::src/core.c/List.pm6:40  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:reify-at-least)
 from SETTING::src/core.c/List.pm6:479  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:AT_POS_SLOW)
 from SETTING::src/core.c/Sequence.pm6:56  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:AT-POS)
 from -e:1  (<ephemeral file>:<unit>)
```

**Comment by niner** [comment] 2021-06-17 20:47
This patch apparently fixes the issue, but I have no idea why:
```
diff --git a/src/core.c/Supplier.pm6 b/src/core.c/Supplier.pm6
index ab2b6424d..f80d7bf0e 100644
--- a/src/core.c/Supplier.pm6
+++ b/src/core.c/Supplier.pm6
@@ -17,6 +17,8 @@ my class Supplier {
         # need lock on modification).
         has Mu $!tappers;
 
+        submethod BUILD() { $!tappers := Mu; }
+
         method tap(&emit, &done, &quit, &tap) {
             my $tle := TapListEntry.new(:&emit, :&done, :&quit);
             # Since we run `tap` before adding, there's a small chance of
```

The same is true for this patch. It also fixes the issue but I can't see how $!tappers could be not concrete when $added is True:

```
diff --git a/src/core.c/Supplier.pm6 b/src/core.c/Supplier.pm6
index ab2b6424d..fc6057d65 100644
--- a/src/core.c/Supplier.pm6
+++ b/src/core.c/Supplier.pm6
@@ -29,8 +29,10 @@ my class Supplier {
                 $!lock.protect({
                     if $added {
                         my Mu $update := nqp::list();
-                        for nqp::hllize($!tappers) -> \entry {
-                            nqp::push($update, entry) unless entry =:= $tle;
+                        if nqp::isconcrete($!tappers) {
+                            for nqp::hllize($!tappers) -> \entry {
+                                nqp::push($update, entry) unless entry =:= $tle;
+                            }
                         }
                         $!tappers := $update;
                     }
```

Since we've got state spread across multiple variables, I figured that it might be a memory write order issue. But even generous sprinkling of nqp::barrierfull in TapList's tap method did not help.

**Comment by melezhik** [comment] 2021-06-17 21:44
formally speaking,  what output should be when the bug is fixed? different versions or rakudo yield different results

```
[root@5168af46f232 r3tool]# tomty --color --env=4f61a108b1e717a8e05ee861738a412d55be6ed4  4410
load configuration from /root/projects/r3tool/.tomty/env/config.4f61a108b1e717a8e05ee861738a412d55be6ed4.pl6
[repository] :: index updated from file:///root/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/4410]
==================================================

[4410] :: cat $root_dir/task.bash
[4410] ::
[4410] :: $raku -v
[4410] ::
[4410] :: $raku -e 'my @a; loop { @a.hyper[0] }'
[4410] :: Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.05-23-g4f61a108b.
[4410] :: Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
[4410] :: Built on MoarVM version 2021.05-14-g0a62f0c6a.
[4410] :: stderr: A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at -e line 1
  in block <unit> at -e line 1

[4410] :: stderr: Died at:
    emit without supply or react
      in block <unit> at -e line 1
      in block <unit> at -e line 1

[4410] :: task exit status: 1
[4410] :: task 4410 FAILED
```
```
[root@5168af46f232 r3tool]# tomty --color   4410
load configuration from /root/projects/r3tool/.tomty/env/config.pl6
[repository] :: index updated from file:///root/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/4410]
==================================================

[4410] :: cat $root_dir/task.bash
[4410] ::
[4410] :: $raku -v
[4410] ::
[4410] :: $raku -e 'my @a; loop { @a.hyper[0] }'
[4410] :: Welcome to Rakudo(tm) v2021.05.
[4410] :: Implementing the Raku(tm) programming language v6.d.
[4410] :: Built on MoarVM version 2021.05.
[4410] :: stderr: A worker in a parallel iteration (hyper or race) initiated here:
  in block <unit> at -e line 1
  in block <unit> at -e line 1

[4410] :: stderr: Died at:
    emit without supply or react
      in block <unit> at -e line 1
      in block <unit> at -e line 1

[4410] :: task exit status: 1
[4410] :: task 4410 FAILED

**Comment by melezhik** [comment] 2021-06-17 21:46
sorry, the output for 2 versions seems identical ... so this should not fail or?

**Comment by jnthn** [comment] 2021-06-17 22:08
@niner Ah bother, I think I know what that is, and I ran into likely the same when I was implementing various of the lock-free data structures. Scalar containers in object containers get vivified lazily at the moment. This isn't so much an optimization (it actually sucks for escape analysis purposes), but because we rely on a C-ish `NULL` in the slot to signal that the attribute was never touched during `BUILD` time, and so should have its attribute default run. (I dearly wanted to kill this all off when doing the EA work. It'd make our JIT output smaller and less branchy too. But figuring out how to do the attribute default decision making is awkward. You can't just go on if the attribute has a defined value, for example, because assigning a type object should also suppress using the attribute default value.)

**Comment by moon-chilled** [comment] 2021-06-18 07:11
@melezhik presumably it should simply loop forever

**Comment by niner** [comment] 2021-06-18 07:23
@melezhik @moon-chilled Indeed. It should just keep on looping without any output at all.

**Comment by melezhik** [comment] 2021-06-18 22:55
Now, I can confirm it's fixed for ca8dea277aa93be11b34a4b3847d5501f05cb067

[r3 tool](https://github.com/melezhik/r3tool) report:

```
[r3@6523d917496c r3tool]$ tomty 4410
[repository] :: index updated from file:///home/r3/repo/api/v1/index
==================================================
[https://github.com/rakudo/rakudo/issues/4410]
==================================================

[4410] :: cat $root_dir/task.bash
[4410] ::
[4410] :: $RAKUBIN -v
[4410] ::
[4410] :: timeout 30 $RAKUBIN -e 'my @a; loop { @a.hyper[0] }'
[4410] ::
[4410] :: echo exit_status: [$?]
[4410] :: Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.05-37-gca8dea277.
[4410] :: Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
[4410] :: Built on MoarVM version 2021.05-16-gb015e1a46.
[4410] :: exit_status: [124]
[task check] stdout match <exit_status: [124]> True
```

**Comment by Altai-man** [comment] 2021-06-19 15:40
Closing as the fix was commited and checked. Re-open if disagree.

**Closed by Altai-man** 2021-06-19 15:40 UTC

**Comment by melezhik** [comment] 2022-06-09 21:20
sorry for the noise, looks like false negative, docker container was terminated, not killed by timeout
