### ISSUE TITLE
Cannot load modules from a directory which contains a META6.json without a provides key indicating the location of files.

### ISSUE THREAD

**Issue by raydiak** [rakudo/rakudo#3787] opened 2020-07-12 03:46 UTC
Don't know if this is intentional behavior or not, but nobody on IRC at the time could answer that, and at the least it felt a bit spooky to me.

$ mkdir foo
$ cd foo
$ echo '{"name":""}' > META6.json # without valid JSON content rakudo throws an error, and without a defined name it throws a warning
$ touch Foo.rakumod

$ raku --ll-exception -I. -e 'use Foo; say "success";'
Could not find Foo in:
    file#/home/x/data/projects/raku/Inline-Lua-test/foo
    inst#/home/x/.raku
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/site
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/vendor
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/core
    ap#
    nqp#
    perl5#
   at SETTING::src/core.c/Exception.pm6:62  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/CompUnit/Repository/Perl5.pm6:35  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/NQP.pm6:19  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/AbsolutePath.pm6:8  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/FileSystem.pm6:101  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from gen/moar/World.nqp:1490  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/World.moarvm:load_module)
 from gen/moar/World.nqp:1440  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/World.moarvm:do_pragma_or_load_module)
 from gen/moar/Grammar.nqp:1316  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control:sym<use>)
 from gen/moar/stage2/QRegex.nqp:1695  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statement_control)
 from gen/moar/Grammar.nqp:964  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statement)
 from gen/moar/Grammar.nqp:892  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1464  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from gen/moar/Grammar.nqp:1344  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from gen/moar/Grammar.nqp:840  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:comp_unit)
 from gen/moar/Grammar.nqp:555  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2258  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2299  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:2215  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:execute_stage)
 from gen/moar/stage2/NQPHLL.nqp:2250  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:2246  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2242  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from gen/moar/stage2/NQPHLL.nqp:1917  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2057  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2112  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2037  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:128  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:93  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<entry>)

$ raku --ll-exception -I. -e 'require Foo; say "success";'
Could not find Foo in:
    file#/home/x/data/projects/raku/Inline-Lua-test/foo
    inst#/home/x/.raku
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/site
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/vendor
    inst#/home/x/.rakubrew/versions/moar-blead/install/share/perl6/core
    ap#
    nqp#
    perl5#
   at SETTING::src/core.c/Exception.pm6:62  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/CompUnit/Repository/Perl5.pm6:35  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/NQP.pm6:19  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/AbsolutePath.pm6:8  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/Installation.pm6:586  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from SETTING::src/core.c/CompUnit/Repository/FileSystem.pm6:101  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/CORE.c.setting.moarvm:need)
 from -e:1  (<ephemeral file>:<unit>)
 from -e:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1947  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2057  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:2112  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:55  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2037  (/home/x/.rakubrew/versions/moar-blead/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:128  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:93  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/x/.rakubrew/versions/moar-blead/install/share/perl6/runtime/perl6.moarvm:<entry>)

$ raku --ll-exception -I. -e 'require "Foo.rakumod"; say "success";'
success

$ raku -v
This is Rakudo version 2020.06-65-g90f86d4c9 built on MoarVM version 2020.06-22-gaf5b89b64
implementing Raku 6.d.

$ uname -a
Linux prism 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/debian_version 
bullseye/sid

**Comment by JJ** [comment] 2020-07-12 06:37
Not sure I understand this properly. What I got is: if there's a module _and_ a copy of META6.json in the same directory, you can't "use" it, is that correct?
In that case, I can't reproduce it:
```
✗cp META6.json lib/Grammar/Common
✗ raku -Ilib -e "use Grammar::Common; say 'foo'";
foo
✗ ls lib/Grammar/Common
Expression  META6.json  Text.pm6
✗ raku -Ilib -e "use Grammar::Common::Text; say 'foo'";
foo
```

Could it be some other reason?

**Comment by niner** [comment] 2020-07-12 07:33
This is entirely intentional and should be mentioned in the documentation. If we find a META6.json in a file system module repository, we consider it to be authoritative with regards to the modules we find in that repository and don't look through the file system any more. The main benefit is that this way you notice right away if you miss something in the `provides` section of your META6.json instead of having to install the distribution first. With the recommended structure of a distribution directory containing a `lib` directory, you still got the choice of using `raku -Ilib` vs. `raku -I.`

**Comment by JJ** [comment] 2020-07-12 09:52
The error message shows that it's actually looking for Foo in the directory where it is:
```
Could not find Foo in:
file#/home/x/data/projects/raku/Inline-Lua-test/foo
```
So let me see if I got this right. This is saying actually that it's not finding a "provides" key in META6.json. If we change the META6.json to

```
{"name":"",
 "provides": { "Foo": "Foo.rakumod" }
}
```
it works. So, while agreeing documentation could be improved, could this also be a case of LTA?

**Comment by lizmat** [comment] 2020-07-12 10:16
Well, It just occurred to me that reading a `META6.json` file is usually *not* in the directory in which loadable module files exist.  So this also feels a bit like a DIHWIDT.  When a directory structure is set up correctly, with a correct `META6.json` file, you can do either `-I.` or `-Ilib`.  Take for example my recent `Game::Covid19` module:

    $ cd Game-Covid19
    $ raku -I. -MGame::Covid19 -e 'play(age => 64)'
    You're moderately ill.
    You'll need 6 weeks for recovery.
    You've permanently lost 1% of your constitution.
    $ raku -Ilib -MGame::Covid19 -e 'play(age => 84)'
    You're seriously ill.
    You'll need 6 months for recovery.
    You've permanently lost 8% of your constitution.

**Comment by raydiak** [comment] 2020-07-12 11:06
Agreed this is arguably understandable behavior, I get where it's coming from. At the very least, telling me it searched in the directory I specified and didn't find the file which does exist in the specified search directories is very LTA. When I was around 5 years ago, rakudo had nothing to do with META6.json, that was only for package managers. Now the contents of that file throw warnings and/or errors in rakudo, and have definite immediate impacts on functionality. I spent hours narrowing this down. So at the least, some sort of indication of what's going on beyond "not found" when I've complied with the documented processes, would be very helpful in these scenarios. Telling me "then don't do that" seems like a cop out. It's an unusual scenario, but obviously one someone could stumble upon, because I just did.

**Comment by lizmat** [comment] 2020-07-12 11:26
Part of the problem is that path resolution is really a chain of Repo objects deciding for themselves they cannot resolve the given path, calls the next Repo and returns whatever it finds.  If nothing can be found then the final one giving up by throwing an exception.  Perhaps that should just return a `Failure`.

Investigating...

**Comment by raydiak** [comment] 2020-07-12 11:31
The behavior you describe is entirely undocumented in the main source of documentation. Perhaps that is the only problem here? This is the first I've heard of Repo objects...

**Comment by lizmat** [comment] 2020-07-12 11:38
This appears to be underdocumented.  Only https://docs.raku.org/type/CompUnit::Repository::FileSystem and https://docs.raku.org/type/CompUnit::Repository::Installation appear to have some documentation  :-(

Also, https://docs.raku.org/language/variables#index-entry-$*REPO could use some improvements.  Perhaps we need some tutorial on that.

**Comment by raydiak** [comment] 2020-07-12 11:48
I suppose that explains the unsettling experience. A person reads the docs and feels like they have this nice clear, concise understanding of how modules are found and loaded. And then they bump into something like this, and find out the truth is (by necessity) more complicated than they were told. More central points like https://docs.raku.org/language/modules should reflect the whole story, IMO.

**Comment by ugexe** [comment] 2020-07-12 13:21
META6.json is the authority where it exists, not the file system. It’s really quite simple and desirable... It would be worrisome if you could have a META6.json setup somewhere that you have properly declared all the code you expect to exist upon a typical installation, but it happily loads whatever at runtime when used through a CURFS.

**Comment by lizmat** [comment] 2020-07-12 13:55
Fixed with https://github.com/rakudo/rakudo/commit/2f6677b2d1  Please close this ticket if you agree.

**Comment by raydiak** [comment] 2020-07-13 08:49
I can certainly see where you're coming from. It still feels a bit odd that you put one file in a directory and all of a sudden the entire semantics of how modules are looked up changes. Not saying it's incorrect now that I understand the behavior, just that it might be nice if this were a little more explicit to the user.

Besides more clearly documenting, could we at least get some sort of indication of this in the error message? Perhaps the word "file" in "file#/home/x/data/projects/raku/Inline-Lua-test/foo" should say something else when a META6.json is controlling the lookup, like "json", "meta", "dist" or something along those lines? Would it make sense to split these two behaviors into two different types of Repo? It's clearly not searching the filesystem any more, we kind of have two different behaviors packed into one Repo type.

If none of that makes sense, perhaps we could check for the presence of the requested module even if it's not in META6.json and report that as a warning before continuing down the chain of Repos? Or else somehow add that information to the error message when the final repo gives up, even though that information would most likely be coming from an earlier repo in the chain?

**Comment by ugexe** [comment] 2020-07-13 12:08
> we kind of have two different behaviors packed into one Repo type.

I actually brought up turning CURFS into two different CURs before. But any solution I came up with was flawed... I think a big problem was only a single repo can be the default when no spec is passed — file#/foo is treated the same as /foo — which repo gets to then have the expected behavior?

**Comment by raydiak** [comment] 2020-07-13 21:06
Fair enough, that was the part I wasn't sure about. I can imagine a few possibilities, but they're all as complicated/messy as you're saying:

-Dynamically changing the repo chain from within a CUR which looks for a META6.json
-From the META6 CUR, calling the other one that isn't explicitly in the Repo chain itself
-One CUR in the Repo chain responsible for calling either of the two actual implementations, neither of which would be explicitly in the chain themselves
-A way in rakudo for a CUR to specify another CUR as a fallback in case of an error, then making the META6.json CUR throw an error when there is no valid META6.json, triggering rakudo to try the other CUR

All of them do sound pretty inelegant one way or another, just to be able to ignore META6.json with something like 'dir#./foo' for a fairly rare case. Arguably this is even a good thing to not allow, e.g. it forced me to move Math::ThreeD's build scripts into a 'tools' directory instead of having them lying around messily in the root as they were before. And if you REALLY REALLY needed this for some bizarre reason, you can still write your own CUR to replicate the old behavior That might be easier if CURFS!dist-from-ls() were public instead so you could call it from your own implementation, but again there's probably little to no actual reason to want to make this easier.

Thanks for leading me through that little thought exercise. It does indeed appear that the only sensible path forward is just improving the error and docs.

**Closed** 2020-09-05 10:41 UTC
Labels: docs
