### ISSUE TITLE
Odd behavior when invoking run of script with #!/usr/local/bin/perl6 shbang

### ISSUE THREAD

**Issue by zostay** [rakudo/rakudo#3023] opened 2019-06-26 16:50 UTC
## The Problem

Running with direct shbang causes odd behavior when invoked via `run()`. It appears that using `run` in this way results in the script being sent to bash rather than perl6.

## Expected Behavior

I expect a shbang line to be honored as usual to select the interpreter and not have bash parse and try to run Perl 6 code.

## Actual Behavior

When I create a script with the shbang line set to `#!/usr/local/bin/perl6` and then run the program using the `run()` subroutine, the code returns bash parsing errors for the script and runs the commands bash can parse and interpret.

## Steps to Reproduce

I can reproduce it on my Mac OS X laptop running Rakudo 2019.03 installed using Homebrew.

Create a file named `one.p6`:

```
#!/usr/local/bin/perl6
use v6;

say 'one';
run './two.p6';
```

Create another file named `two.p6`:

```
#!/usr/local/bin/perl6
use v6;

say 'two';
```

Make these programs executable and run `one.p6`:

```
% chmod a+x one.p6 two.p6
% ./one.p6
one
./two.p6: line 2: use: command not found
```

On my laptop, this will actually invoke the `say` command, resulting in the text-to-speech engine saying the word "two". That's slightly disturbing, but makes sense if bash is executing the script the way it normally would try to do so.

## Workaround

The workaround is to write the scripts using a shbang line of `#!/usr/bin/env perl6` which just works.

## Environment
* Operating system
    * (`uname -v`): Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 
    * (About dialog): macOS Mojave Version 10.14.5
* Compiler version (`perl6 -v`): This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03 implementing Perl 6.d.

Perl 6 has been installed in /usr/local/bin/perl6 by homebrew, in case that make any difference.

**Comment by lizmat** [comment] 2019-06-26 17:15
FWIW, I cannot reproduce this problem with bleed rakudo on MacOS

**Comment by jnthn** [comment] 2019-06-26 17:23
Could this be the problem caused by us previously using a shell script for `perl6`, and resolved by bleed using a real executable now?

**Comment by vrurg** [comment] 2019-06-26 19:04
It looks like @jnthn assumption make sense. I tested on my `rakudobrew` installation of `2019.03.01`. `/bin/sh` on macOS fails to interpret `one.p6`'s shebang properly and treats the script as a shell script in first place. 

@zostay can you try `master` and confirm it's ok for you too?

**Comment by zostay** [comment] 2019-06-27 15:57
I'd have to hack the homebrew recipe to do it definitively. But I installed moar-2019.03.1 and moar-master with rakudobrew and @jnthn's theory seems confirmed. Since I couldn't use the perl6 executable directly as a shbang for `one.p6` in 2019.03.1 in this particular case, it doesn't behave exactly like my homebrew install. That's probably just a similar error showing up in a different place here, but why it wouldn't for homebrew, I don't know. 

Here's a transcript of my session:

```
% cat one.p6
#!/Users/sterling/.rakudobrew/versions/moar-master/install/bin/perl6
use v6;

say "one";
run "./two.p6";
% cat two.p6
#!/Users/sterling/.rakudobrew/versions/moar-master/install/bin/perl6
use v6;

say "two";
% ./one.p6
one
two
% perl -pi -e 's/moar-master/moar-2019.03.1/' one.p6 two.p6
% cat one.p6
#!/Users/sterling/.rakudobrew/versions/moar-2019.03.1/install/bin/perl6
use v6;

say "one";
run "./two.p6";
% cat two.p6
#!/Users/sterling/.rakudobrew/versions/moar-2019.03.1/install/bin/perl6
use v6;

say "two";
% ./one.p6
zsh: exec format error: ./one.p6
% perl -pi -e 's/moar-2019.03.1/moar-master/' one.p6
% ./one.p6
one
./two.p6: line 2: use: command not found
% ./one.p6
one
./two.p6: line 2: use: command not found
```

As with before the voice synthesizer says "two" aloud. :-p

**Comment by vrurg** [comment] 2019-06-27 18:00
It was talking to me too. ;)

Ok, closing as it is not relevant in HEAD. Thanks @zostay!

**Closed by vrurg** 2019-06-27 18:00 UTC
