### ISSUE TITLE
`+=` meta op with FatRat typeobject LHS uses incorrect type

### ISSUE THREAD

**Issue by zoffixznet** [rakudo/rakudo#1830] opened 2018-05-14 23:35 UTC
This was originally found [when a fudged test was changed](https://github.com/perl6/roast/commit/14f5138f07) to no longer trigger this issue and this probably affects all other ops like `-=` and `*=`.

The expansion of the op ends up using zero-arg version of the meta-ed op, which in the case of `infix:<+>`  returns in a `0` of type `Int`. 

This results in failure to promote the result to correct infectiousness of the arguments involved. A `Rat + Int => Rat`, but here the result is an `Int`:

```
<Zoffix_> m: my Rat $x; $x += 1;
<camelia> rakudo-moar 20e2f1d20: OUTPUT: «Type check failed in assignment to $x; expected Rat but got Int (1)␤  in block <unit> at <tmp> line 1␤␤»
```

Not sure if this can be elegantly solved. Maybe coercing the zero-arg result of the op to the type of the variable?

Technically, the direct expansion of this construct crashes as `infix:<+>` does not work with type objects, so perhaps leaving infectiousness different is acceptable?

```
<Zoffix_> m: my FatRat $a; $a = $a + .1
<camelia> rakudo-moar 20e2f1d20: OUTPUT: «Cannot look up attributes in a FatRat type object␤  in block <unit> at <tmp> line 1␤␤»
```

**Comment by thundergnat** [comment] 2018-05-15 00:41
(Duplicate of comment on original commit)

Yes but there is no mechanism to add a Rat to an uninitialized FatRat type. Once it is initialized, you can do arithmetic operations with Rationals or Ints and it will stay a FatRat, but it needs to be an instance first.

The only way I could see around that is to either add endless multis that will work with :U arguments (ugh...) or to automatically initialize constrained containers to their identity value. (Can no longer have :U typed containers.) Neither of which seem to be a good option. Really the best way forward looks to me to be documenting "You can't do arithmetic operations on an unitialized constrained container unless that operation specifically result in a value of the constrained type." Which is pretty much what we have. (except for the documentation part.)

**Comment by zoffixznet** [comment] 2018-05-15 02:50
>  And it didn't end up a Rat, it failed trying to add a Rat to an uninitialized FatRat type

That's not what the error says:

```
<Zoffix_> m: my FatRat $a; dd $a += .1
<camelia> rakudo-moar 20e2f1d20: OUTPUT: «Type check failed in assignment to $a; expected FatRat but got Rat (0.1)␤  in block <unit> at <tmp> line 1␤␤»
```

Nor is it what the QAST says:
```
- QAST::Op(assign) <sunk> +=
  - QAST::Var(lexical $a) <wanted> $a
  - QAST::Op(callstatic &infix:<+>) 
    - QAST::Op(if) 
      - QAST::Op(p6definite) 
        - QAST::Var(lexical $a) <wanted> $a
      - QAST::Var(lexical $a) <wanted> $a
      - QAST::Want 
        - QAST::WVal(Int) 
        - Ii
        - QAST::IVal(0) 
    - QAST::WVal(Rat) <wanted> 1.0
```

You can see there's an `Int` `0` being added, which will result in `Rat` object, which will then fail the typecheck on assignment. And that `Int` `0` is from zero-arg `infix:<+>` that's being called when `$a` contains a typeobject.

> add endless multis that will work with :U arguments

That won't help (without further codegen changes) as the `Int` value comes from zero-arg `infix:<+>` call.

> initialize the FatRat

That'd just sweep the problem under the rug, the same as this commit did. Yes, `infix:<+>` and other ops don't have `:U` candidates, but we still use a default value with unintialized variables automatically in many cases, which is especially handy with anon state vars:

```
<Zoffix_> m: my $a; $a += 42; say $a; my $b; $b++; say $b;   say ++$
<camelia> rakudo-moar 20e2f1d20: OUTPUT: «42␤1␤1␤»
```

The problem lies in the fact that we always use an `Int` with uninitialized variables,, thus never gaining the infectiousness of the original type object.

**Comment by thundergnat** [comment] 2018-05-15 10:11
I see your point and I don't disagree. It is LTA a bit, but it isn't just FatRats that exhibit that behaviour. Every Numeric type complains if the initial value is not of the constrained type.

    perl6 -e'my Rat $r; dd $r += 1'
    Type check failed in assignment to $r; expected Rat but got Int (1) in block <unit> at -e line 1

    perl6 -e'my Num $n; dd $n += .1'
    Type check failed in assignment to $n; expected Num but got Rat (0.1) in block <unit> at -e line 1

Maybe they are all wrong, but they are consistent.

**Comment by zoffixznet** [comment] 2018-05-15 17:27
> but they are consistent

Consistently unusable isn't a good thing. I also fail to see consistency in `my Int $x; $x += 42` working fine, but `my Rat $x; $x += 42` failing; in `my Int $x; $x++` working fine, but `my Rat $x; $x++` failing.

> Maybe coercing the zero-arg result of the op to the type of the variable?

That will fail in cases like this, since `Int` won't know how to coerce to a custom class.

```
class MyRat is Rat {}
my MyRat $x; $x++;
```

We could go the opposite way: make all `Numeric`s' `.new` be able to take another `Numeric` as intializer value, `.Bridge`ing any non-core `Numeric`.

**Comment by zoffixznet** [comment] 2018-05-15 17:32
> make all Numerics' .new be able to take another Numeric as intializer

And then [this](https://github.com/rakudo/rakudo/blob/5ce24929f5bdbcb64a99beeec148ecdc7d24efd8/src/core/metaops.pm6#L3) and related metas would need to be a multi that differentiates on `Numeric` and does `arg.WHAT.new: op.()`

**Comment by zoffixznet** [comment] 2018-05-15 17:41
Though the issue exists beyond `Numeric`s:

```
m: my Buf $x ~= Buf.new
rakudo-moar 5ce24929f: OUTPUT: «Cannot use a Buf as a string, but you called the Stringy method on it␤  in block <unit> at <tmp> line 1␤␤»
```
```
$ perl6 -e 'my $x = Bag.new ⊖ Set.new; dd $x'
Bag $x = bag()

$ perl6 -e 'my Bag $x ⊖= Set.new; dd $x'
Type check failed in assignment to $x; expected Bag but got Set (().Set)
  in block <unit> at -e line 1
```

**Closed** 2024-10-04 09:46 UTC
Labels: math, rationals, metaop
