### ISSUE TITLE
REPL: can't bind variables to other variables

### ISSUE THREAD

**Issue by Prince213** [rakudo/rakudo#3297] opened 2019-11-11 12:17 UTC
## The Problem
Can't bind variables to other variables
## Actual Behavior
```
===SORRY!=== Error while compiling:
Cannot use bind operator with this left-hand side
------> $a := $b<HERE>;
```
## Steps to Reproduce
Run this code(from https://docs.perl6.org/language/containers#Binding)
```
my $a = 0;
my $b = 0;
$a := $b;
```

## Environment
* Operating system: Windows 10 64bit
* Compiler version (`perl6 -v`): 
```
This is Rakudo version 2019.07.1-469-g1c5d010f8 built on MoarVM version 2019.07.1-309-g48491b896
implementing Perl 6.d.
```

**Comment by lizmat** [comment] 2019-11-11 12:55
FWIW, on HEAD on MacOS:

    my $a = 0; my $b = 42; $a := $b; say $a;   # 42

**Comment by AlexDaniel** [comment] 2019-11-11 13:07
Yeah, I'm a bit confused too.

> \<AlexDaniel\> 6c: my $a = 0; my $b = 0; $a := $b;
> \<committable6\> AlexDaniel, ¦6c (39 commits): «»

**Comment by Prince213** [comment] 2019-11-11 14:13
@lizmat please try this in REPL
```
my $a = 0;
my $b = 0;
$a := $b;
```

**Comment by lizmat** [comment] 2019-11-11 16:37
Ah, indeed.  I'm afraid this is an artefact of using the REPL, which cuts a number of corners to make it work interactively.  I don't see a quick solution for this.

**Comment by lizmat** [comment] 2024-11-24 13:44
Closing as dupe of https://github.com/rakudo/rakudo/issues/1565

**Closed by lizmat** 2024-11-24 13:44 UTC
Labels: LTA, REPL
