### ISSUE TITLE
LTA error message when calling `split()` with an empty regex

### ISSUE THREAD

**Issue by jeffgazso** [rakudo/rakudo#5319] opened 2023-07-24 17:26 UTC
## The Problem

When attempting to split a scalar into a sequential array of characters, programmers coming from *many* other languages instinctively reach for `.split()`. To cite a Perlish example: `my @arr = split(//, $scalar)` is an idiomatic way of performing this task in Perl 5. Unfortunately, it's invalid Raku and the error message that results is LTA:

```
===SORRY!=== Error while compiling:
Null regex not allowed
------> @arr = split(//⏏,$scalar);
```
Given the prevalence of this idiom in other programming languages it's reasonable to infer what the programmer is attempting to do. The error message should reflect this.

## Expected Behavior

The error message should include the following:

1. Inform the programmer that `$scalar.comb` is the equivalent Raku idiom for splitting a scalar into an array of individual Unicode graphemes. This is most likely what they're after.
2. It's probably a good idea to explain the reason for the design decision in some small way that emphasizes the problems this approach avoids compared to splitting on a null regex. This will help them get better acquainted with the Raku way of doing things.

**Comment by lizmat** [comment] 2023-07-24 19:31
The problem with providing a better error, is that `.split` is not the cause, but `//` is.
````
$ raku -e '//'
===SORRY!=== Error while compiling -e
Null regex not allowed
````

**Comment by lizmat** [comment] 2023-07-24 19:39
I've changed the error message a bit, so now it will say:
````
$ rakue -e '//'                          
===SORRY!=== Error while compiling -e
Null regex not allowed.  Please use .comb if you wanted to produce a
sequence of characters from a string.
````
Commit: https://github.com/rakudo/rakudo/commit/1919197153

Please close this issue if you're happy with the result.  And thanks for bringing this up!

**Comment by jeffgazso** [comment] 2023-07-24 19:45
Wow, that was fast. Thanks!

**Comment by jeffgazso** [comment] 2023-07-24 19:45
Resolved.

**Closed** 2023-07-24 19:45 UTC
