### ISSUE TITLE
Performance regression with loop() in a class sub

### ISSUE THREAD

**Issue by MasterDuke17** [rakudo/rakudo#3560] opened 2020-03-20 23:27 UTC
This code: 
```perl6
class FOO {
	our proto sub foo($) {*};
	multi sub foo(Int $n) {
		my @a = ^$n;
		my $b;
		loop (my $i = 0; $i < $n; $i++) {
			$b = @a[$i]
		}
		$b
	}
	multi sub foo(Str $s) {
		foo($s.Int)
	}
}

say FOO::foo(1_000_000);
say now - INIT now
```
used to take ~1.3s, but after 48ce47e takes ~2.1s. This was discovered when benchmarking some changes to String::CRC32. The sample code `use String::CRC32; say String::CRC32::crc32("abcdefghijklmnopqrstuvwxyz0123456789~!#^_+;:./>?" x 100_000)`, using https://github.com/cosimo/perl6-string-crc32/pull/12, caused 4.8 million calls each to `MVM_frame_find_lexical_by_name` for `&postfix:<++>` and `&infix:«<»`.

**Comment by MasterDuke17** [comment] 2020-03-20 23:28
https://gist.github.com/Whateverable/7e08b6856f9aa8c20358e7370961d1cb has the timings for releases.

**Comment by MasterDuke17** [comment] 2020-03-21 00:08
https://gist.github.com/MasterDuke17/ece191957c1ee47136650926da661c75 has the output of `MVM_dump_bytecode(tc)` at the top of `MVM_frame_find_lexical_by_name` when `name` is '&postfix:<++>'.

**Comment by jnthn** [comment] 2020-03-25 11:14
It seems it produces nicely optimized code...but then never manages to complete OSR and use it.

**Comment by jnthn** [comment] 2020-03-25 11:32
It's still not clear how this ever worked (and it might have done so accidentally...) but the problem is that a `proto` invokes the body with `invokewithcapture`, and OSR doesn't know how to find the args and callsite for doing an arg guard test.

**Comment by MasterDuke17** [comment] 2020-03-25 11:57
Think this is something I could fix with a pointer to where OSR is failing?

**Comment by jnthn** [comment] 2020-03-25 12:05
I already have a patch that helps (the time it outputs goes from 3.76 to 0.70 on my slow home VM); just been checking it doesn't knock off OSR otherwise (seems not) and spectesting it.

**Comment by jnthn** [comment] 2020-03-25 12:22
Fixed with https://github.com/MoarVM/MoarVM/commit/f2a52cf5d7.

**Closed by jnthn** 2020-03-25 12:22 UTC
Labels: performance
