### ISSUE TITLE
t/02-rakudo/08-repeat.t on rakudo 2017.12 on Linux

### ISSUE THREAD

**Issue by nxadm** [rakudo/rakudo#1377] opened 2018-01-08 18:19 UTC
Build fails on Travis and on my local machine with an out of memory. It may be related to a higher default ulimit on Linux compared to MacOS where the test passes.

Build on all the Linux distributions supported by rakudo-pkg:
https://travis-ci.org/nxadm/rakudo-pkg/builds/321564136

Verbose output of test (on a machine with 16GB of ram):
```
bologna:~/tmp/rakudo/rakudo-2017.12$ ./perl6 -Ilib t/02-rakudo/08-repeat.t
1..5
MoarVM panic: Memory allocation failed; could not allocate 8589934592 bytes
```
Issue tracked on https://github.com/nxadm/rakudo-pkg/issues/29

**Comment by lizmat** [comment] 2018-01-08 19:47
FWIW, building rakudo on MacOS creates a process that grows to 1.17GB, at the moment.

**Comment by AlexDaniel** [comment] 2018-01-08 20:03
FWIW whateverables are still struggling with memory leaks. Perhaps if that is fixed the memory usage will go down.

**Comment by nxadm** [comment] 2018-01-08 20:08
I tried playing with ulimit on MacOS, but it seems "open files" can be changed to default Linux values, "max user processes" is stuck to max 1064 on MacOS, while it's 63536 on my Linux machines.

I suspect that if that could be changed, the out-of-memory would also apply to MacOs.

The question that I have is if I can ignore the test and release 2017.12 rakudo packages, or if the test fail for a good reason and Linux users should stick to 2017.11.

C.

**Comment by AlexDaniel** [comment] 2018-01-08 21:21
Pretty sure 2017.12 was fine on linux. Releasable just doesn't produce tars if tests don't pass (although it tries to pass tests very hard, by running the stresstest several times in case there are flappers).

**Comment by nxadm** [comment] 2018-01-08 21:58
@AlexDaniel,

I don't understand how the test in question passed on Linux@releasable when *all* (15) Linux distributions/releases fail on Travis. 

How does releasable release tars? And is what ends in the tar tested or a certain git commit/tag? Seen the failures on Travis, I suspect it's not built there and the released tars are not used. Is it a dev VM with non-standard defaults? On a non-Linux OS?

**Comment by AlexDaniel** [comment] 2018-01-08 22:26
@nxadm releasable makes bump commits (to nqp and moar) locally, then runs the tests. If everything is OK, then tars are created from the tagged commits. Then I check everything manually just in case, and with a final command it pushes the commits, tags and tars to the public. Basically it follows [nqp](https://github.com/perl6/nqp/blob/master/docs/release_guide.pod) and [rakudo](https://github.com/rakudo/rakudo/blob/master/docs/release_guide.pod) release guides. The code for all that is not public I think (yet).

This time the tests were run on a debian distro, with plenty of ram available. Though now that you are saying that, I'll go run the tests once again…

**Comment by AlexDaniel** [comment] 2018-01-08 22:44
Ah, I think I know. So here is my hypothesis while the tests are crunching. I think you're trying to run tests with roast@HEAD, which rakudo 2017.12 does not pass. This is not surprising, because as soon as we nail some bugs in rakudo, we add tests to roast. So previous versions of rakudo are not really supposed to pass with the most recent roast. I think if you try with roast at 6a027d36c587511f29ddf3eb8923da695dc45c93 (which is around the time of the release, but I'd have to check the logs for the actual sha), then it will succeed.

**Comment by AlexDaniel** [comment] 2018-01-08 23:00
Pft. Now that I reread the ticket, it is complaining about rakudo tests… Then I don't know. Everything is clean here.

**Comment by AlexDaniel** [comment] 2018-01-08 23:10
Also, it never flaps (``while ./perl6 -Ilib t/02-rakudo/08-repeat.t; do :; done``).

FWIW, this ticket shouldn't be closed until the issue is resolved. Making a point release won't make sense, but we definitely want to get it fixed for 2018.01 (even if it's a limitation of travis, we definitely want this thing to be green).

**Comment by AlexDaniel** [comment] 2018-01-09 00:04
https://twitter.com/travisci/status/950463103464067073 ?

**Comment by nxadm** [comment] 2018-01-09 07:32
Thx @lizmat and @AlexDaniel for looking at this ticket. Just to be clear:

The fails are *not* Travis or Docker specific:
- I run the test on my local machine (Ubuntu 17.10 amd64, 16gb RAM, i7, SSD) without Docker (my Travis setup uses Docker): it fails with the same error.
- The Travis branch can be rebuilt at will and it fails every time with identical results, i.e. not related to their downtime.

In short, I would be baffled if people Linux's installation pass this test while it fails on my local machine (Ubuntu 17.10) and on Travis (Ubuntu, Debian, Centos, Fedora, Alpine running on top of a Ubuntu 14.04 kernel).

Furthermore, I am not sure this fail is as innocent as we may suspect. In opposition to what I believed, the test was already there on the 2017.11 release (and it passed). That's why I hesitate to release 2017.12 packages. A lot of people seem to use the packages by now, and making packages available that have known memory allocation errors will harm that trust. We must remember that Linux is without doubt the main platform for deployment.

C.

**Comment by nxadm** [comment] 2018-01-09 07:35
@AlexDaniel,

About roast: I am running the tests in the released tar-ball (as run by 'make test'), not using HEAD or specific commits. Therefore, I don't thing it's a out-of-sync or racing condition between tests and code.

C.

**Comment by AlexDaniel** [comment] 2018-01-09 10:43
@nxadm OK. Can you bisect it? That'd give the answer right away, possibly.

**Comment by nxadm** [comment] 2018-01-09 12:58
Hi,

If you or someone else can direct me to the bisecting docs, I'll certainly try it. In the meantime, I did some testing with interesting results confirming what I thought about why it this specific test failed on Travis and on my setup, but not on the setup of some rakudo devs. 

In summary, it's because I am using the released tarballs of moarvm, nqp and rakudo:
```
$ cd ~/tmp/MoarVM-2017.12
$ perl ./Configure.pl --prefix=/home/claudio/tmp/separated && make && make install
$ cd ~/tmp/nqp-2017.12
$ perl ./Configure.pl --prefix=/home/claudio/tmp/separated --backends=moar && make && make test && make install
$ cd ~/tmp/rakudo-2017.12
$ perl ./Configure.pl --prefix=/home/claudio/tmp/separated --backends=moar && make && make test
```
This results in a faling t/02-rakudo/08-repeat.t

However, when using --gen-moar and --gen-nqp, the test passes because it uses git commits:
```
$ cd ~/tmp/rakudo-2017.12
$ perl ./Configure.pl --prefix=/home/claudio/tmp/separated --gen-moar --gen-nqp && make && make test
```

This looks to me to an out-of-sync bug between what's on github and what's been released. If you want or need reproducible builds (like Debian requires) the random git cloning is not an option.

C.

**Comment by CurtTilmes** [comment] 2018-01-09 15:32
_This looks to me to an out-of-sync bug between what's on github and what's been released._

I think you are correct.

This exhibits the failure:
```
curl -L https://www.moarvm.org/releases/MoarVM-2017.12.tar.gz | tar xzvf -
cd MoarVM-2017.12 && perl Configure.pl --prefix=/tmp/rak && make && make install
cd ..
curl -L https://github.com/perl6/nqp/archive/2017.12.tar.gz | tar xzvf -
cd nqp-2017.12 && perl Configure.pl --prefix=/tmp/rak --backends=moar && make && make test && make install
cd ..
curl -L https://github.com/rakudo/rakudo/archive/2017.12.tar.gz | tar xzvf -
cd rakudo-2017.12 && perl Configure.pl --prefix=/tmp/rak --backends=moar && make && make test
```

But this works perfectly:
```
git clone git@github.com:MoarVM/MoarVM.git
cd MoarVM
git checkout tags/2017.12 -b working
perl Configure.pl --prefix=/tmp/rak && make && make install
cd ..
git clone git@github.com:perl6/nqp.git
cd nqp
git checkout tags/2017.12 -b working
perl Configure.pl --prefix=/tmp/rak --backends=moar && make && make test && make install
cd ..
git clone git@github.com:rakudo/rakudo.git
cd rakudo
git checkout tags/2017.12 -b working
perl Configure.pl --prefix=/tmp/rak --backends=moar && make && make test && make install
```

This file seems to be the difference:
```
diff MoarVM/src/strings/ops.h MoarVM-2017.12/src/strings/ops.h
117,118c117,118
<  * If it is different debug information will be printed out.
< #define MVM_DEBUG_NFG 1 */
---
>  * If it is different debug information will be printed out. */
> #define MVM_DEBUG_NFG 1
120,121c120,121
<  * always checks every grapheme manually. Slower. (requires MVM_DEBUG_NFG)
< #define MVM_DEBUG_NFG_STRICT 0 */
---
>  * always checks every grapheme manually. Slower. (requires MVM_DEBUG_NFG) */
> #define MVM_DEBUG_NFG_STRICT 1
```

That file is different between the MoarVM released tar file and the git repository tag.
If I patch that file in to the tar releases, it works fine too.

**Comment by CurtTilmes** [comment] 2018-01-09 15:47
The github release tar.gz is fine (`https://github.com/MoarVM/MoarVM/archive/2017.12.tar.gz`)

The moarvm.org release tar.gz (`http://moarvm.org/releases/MoarVM-2017.12.tar.gz` which bundles in extra 3rdparty stuff) has the different `src/strings/ops.h`.

**Comment by nxadm** [comment] 2018-01-09 16:26
So, the solution could be:
1. Wait for a fixed 2018.01 and act like 2017.12 never existed (no Linux packages).
2. Release a moarvm patch release (2017.12.1) and release 2017.12 Linux packages automatically.
3. Patching the source manually and release 2017.12 Linux packages. A hassle because everything is set up automatically, but doable.

I prefer option 2, but I can live with all options.

C.

**Comment by AlexDaniel** [comment] 2018-01-09 17:29
OK, so. The problem is with a particular tarball, so that's not a blocker for anything. After [some discussion](https://irclog.perlgeek.de/moarvm/2018-01-09#i_15669831) it seems that MoarVM will have a 2017.12.1 release. IMO just fixing the tar is less painful, but I kinda agree that we shouldn't be setting a precedent of changing published tars.

Therefore, no ｢blocker｣ label.

To track progress on 2017.12.1, see https://github.com/MoarVM/MoarVM/issues/778.

Now, how do we make it not happen again?
* Relatively soon I'll write a bot that would check stuff like this. Track the progress on that: https://github.com/perl6/whateverable/issues/273
* Releasable will soon learn to cut moarvm releases. Most likely it won't be ready before 2018.01, but once it is done, the releases will be done in a consistent way, so issues like this won't happen. Track progress on this here: https://github.com/perl6/whateverable/issues/274

I think with this list of open issues it is fair to close this ticket. Thanks to everyone for your effort!

**Closed by AlexDaniel** 2018-01-09 17:29 UTC
Labels: ⚠ blocker ⚠

**Comment by AlexDaniel** [comment] 2018-01-09 17:34
Ah, also. As of this minute the decision is to *not* make a 2017.12.1 release of **rakudo** (meaning moarvm point release only). This means that the VERSION file of rakudo 2017.12 will show that it is supposed to work with moarvm 2017.12 and not 2017.12.1, and that is totally alright if you're letting `make` to build moarvm (as it does not use the tarballs but checkout-s the right revision). If that is not OK for someone, please let me know and we'll rethink that.

**Comment by nxadm** [comment] 2018-01-09 17:55
This is a good solution for me. This is just changing the MOARVM_VERSION variable on the .travis.yml of the rakudo-pkg repo.

Greatly appreciated.

C.
