### ISSUE TITLE
Too few positionals passed; expected 2 arguments but got 1 (with HTTP::UserAgent)

### ISSUE THREAD

**Issue by hstejas** [rakudo/rakudo#1442] opened 2018-01-25 08:11 UTC
## The Problem
    perl6 -e 'use HTTP::UserAgent;for 1..300 { say "try >> $_"; my $res = HTTP::UserAgent.new.get("http://perl6.org"); say $res.status-line; }'

This one liner always crashes with this callstack, and its usually with try 102 or 103
```
Too few positionals passed; expected 2 arguments but got 1
  in method get-proxy at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 368
  in method get-proxy at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 368
  in method get-connection at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 328
  in method request at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 156
  in method request at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 176
  in method get at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 102
  in method get at /home/user/rep/perl6/rakudo/install/share/perl6/site/sources/FD28A8E22DFE16B70B757D9981C7B6C25543060C (HTTP::UserAgent) line 105
in block <unit> at -e line 1
```

I have tried different variations like 

    perl6 -e 'use HTTP::UserAgent;my $ua = HTTP::UserAgent.new(:useragent<mozilla_linux>); for 1..300 { say "try >> $_"; my $res = $ua.get("google.com"); say $res.status-line; sleep 10; }'

## Actual Behavior

The odd thing is that the call stack is `get-proxy` is called in only once but the stack mentions it twice
(src: https://github.com/sergot/http-useragent/blob/master/lib/HTTP/UserAgent.pm6)

## Steps to Reproduce

Run the script mentioned above

## Environment
* Operating system: Ubuntu 17.10 (Linux Ubuntu 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

* Compiler version (`perl6 -v`): 
This is Rakudo version 2017.12 built on MoarVM version 2017.12
implementing Perl 6.c.

HTTP::UserAgent:ver<1.1.36>:auth<github:sergot>
zef:ver<0.1.29>:auth<github:ugexe>

Relevant discussion at http://colabti.org/irclogger/irclogger_log/perl6?date=2018-01-25#l212

**Comment by jnthn** [comment] 2018-03-16 20:57
This is a dupe of #1573, which I fixed earlier today.

**Closed by jnthn** 2018-03-16 20:57 UTC
