### ISSUE TITLE
Writing to multiple Proc::Async children throws exception after a few succeed

### ISSUE THREAD

**Issue by japhb** [rakudo/rakudo#2847] opened 2019-04-17 22:56 UTC
## The Problem

Writing to multiple Proc::Async children using the technique in https://stackoverflow.com/a/55691418 quickly fails claiming either a broken pipe or a non-writeable subprocess.

## Expected Behavior

All children execute and accept input successfully at chosen parallelism.

## Actual Behavior

After a few children run, the parent eventually crashes with either:

```
A react block:
  in sub MAIN at golfed.pl6 line 8
  in block <unit> at golfed.pl6 line 1

Died because of the exception:
    broken pipe
      in sub MAIN at golfed.pl6 line 8
      in block <unit> at golfed.pl6 line 1
```

or:

```
A react block:
  in sub MAIN at golfed.pl6 line 8
  in block <unit> at golfed.pl6 line 1

Died because of the exception:
    This process is not opened for write
      in sub MAIN at golfed.pl6 line 8
      in block <unit> at golfed.pl6 line 1
```

## Steps to Reproduce

```
$ cat > golfed.p6
#!/usr/bin/env perl6

#| Test parallel Proc::Async writeable children
sub MAIN(Int :$parallel = 4  #= Maximum degree of parallelism
        ) {
    my @children = ^1000;

    react {
        sub run-one {
            my $i = @children.shift // return;
            my $proc = Proc::Async.new: :w, << echo Child $i running. >>;
            my $finished = $proc.start;

            whenever $proc.print('Test input') {
                $proc.close-stdin;
            }
            whenever $finished {
                say "Child $i finished.";
                run-one;
            }
        }
        run-one for ^$parallel;
    }

    say "All children completed!";
}
^D
$ perl6 golfed.p6
Child 0 running.
Child 1 running.
Child 2 running.
Child 3 running.
Child 0 finished.
Child 4 running.
Child 1 finished.
Child 2 finished.
Child 5 running.
Child 3 finished.
Child 6 running.
Child 7 running.
A react block:
  in sub MAIN at golfed.pl6 line 8
  in block <unit> at golfed.pl6 line 1

Died because of the exception:
    broken pipe
      in sub MAIN at golfed.pl6 line 8
      in block <unit> at golfed.pl6 line 1

```

(The number of children that run before the exception is triggered varies from run to run.)

## Environment
* Operating system: Debian Testing on x86-64
* Compiler version (`perl6 -v`):
This is Rakudo version 2019.03.1-213-g7ee08bb10 built on MoarVM version 2019.03-76-gc10fee65c

**Comment by b2gills** [comment] 2019-04-19 17:26
It sometimes complains about about the pipe not being opened for write.

```
A react block:
  in sub MAIN at ./test.p6 line 11
  in block <unit> at ./test.p6 line 1

Died because of the exception:
    This process is not opened for write
      in sub MAIN at ./test.p6 line 11
      in block <unit> at ./test.p6 line 1
```

I think what is happening is either `echo` is closing its STDIN or finishing entirely before Perl6 gets a chance to write to it.

If you swap it out for `<< cat >>` it works just fine. (`cat` waits for STDIN or STDOUT to close before it terminates.)

---

It seems like `$proc.print` may be returning a Promise as intended, but it is throwing an error instead of breaking the Promise.

There is a possibility that it isn't even given a chance to return the Promise before the error is thrown.

**Comment by jnthn** [comment] 2019-04-26 16:54
> It seems like $proc.print may be returning a Promise as intended, but it is throwing an error instead of breaking the Promise.

It does break the `Promise`; add a `QUIT` block inside of the `whenever $proc.print('Test input') {...}` block will catch it. A `react` block as a whole is terminated by unhandled asynchronous errors.

> I think what is happening is either echo is closing its STDIN or finishing entirely before Perl6 gets a chance to write to it.

Yes, I believe so too. About the two failure modes:

* One was "broken pipe": in this case we issued the write before the process termination event, but the write errored out. Passing along the OS error in that case is probably as sensible as we can do.
* The other was confusing: "This process is not opened for write". MoarVM didn't do quite enough here to make a distinction between a process that was opened for write but then either the handle was closed and the process terminated, or that was never opened for write in the first place. I put in [a patch](https://github.com/MoarVM/MoarVM/commit/741779ac4e7fa1419b80152e4738cc2fe84b4a1c) to distinguish the various cases, and now this error is the less confusing `Cannot write to process that has already terminated` (there's a separate error for if we already called `close-stdin` too).

That improved error aside, is there anything that can be done here? It feels like if you are trying to write to a process that might close its stdin or terminate unexpectedly, then there's an inherent race there, that will produce errors.

**Comment by japhb** [comment] 2019-04-26 17:26
Thank you for that patch.  The use of `echo` was just to golf the real child process to something that would "do no harm" whatever its arguments and input might be, and that probably existed on every system.  The real child process should actually read and process its stdin until the parent closes it, but it's possible I accidentally fed it garbage and it exited early.

Why does the `QUIT` block need to be inside the `whenever`?  Is it just so that each `whenever` could have its own error handling?  Or would it not work to just have a `QUIT` directly inside the `react` block as a catch-all for async errors?

**Closed** 2024-10-09 16:23 UTC
