### ISSUE TITLE
BUILD, TWEAK not invoked on Hash subclass stantiation

### ISSUE THREAD

**Issue by dwarring** [rakudo/rakudo#2716] opened 2019-02-22 20:47 UTC
## The Problem

BUILD and TWEAK methods are not called when stantiating classes that sub-class Hash. Consider:
```
use Test;
my $built;
my $tweaked;
class H is Hash {
    submethod BUILD { $built = True }
    submethod TWEAK { $tweaked = True }
}
my %h := H.new;
plan 2;
ok $built, 'BUILD invocation';
ok $tweaked, 'TWEAK invocation';
```

## Expected Behavior

I'd expected the above test to pass.

## Actual Behavior
```
$ perl6 /tmp/hash.p6 
1..2
not ok 1 - BUILD invocation
# Failed test 'BUILD invocation'
# at /tmp/hash.p6 line 11
not ok 2 - TWEAK invocation
# Failed test 'TWEAK invocation'
# at /tmp/hash.p6 line 12
# Looks like you failed 2 tests of 2
```
## Environment
* Operating system: Linux toshiba 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Compiler version (`perl6 -v`): This is Rakudo version 2018.12-311-gd6563816e built on MoarVM version 2018.12-110-g04982f6e9 implementing Perl 6.d.

**Comment by vrurg** [comment] 2019-02-26 03:37
This is intended behavior to make initialization like:

```
Hash.new(a=>1, b=>2);
```

possible. You would have to define your own `new` method in a child class and get this fixed on your own. The easiest way would be to qualify-call `self.Mu::new`.

**Comment by lizmat** [comment] 2019-02-26 09:17
> On 26 Feb 2019, at 04:37, Vadim Belman <notifications@github.com> wrote:
> 
> This is intended behavior to make initialization like:
> 
> Hash.new(a=>1, b=>2);
> 
> possible. You would have to define your own new method in a child class and get this fixed on your own. The easiest way would be to qualify-call self.Mu::new.

self.bless(named params) in that case would also do the trick.  It exists for that very reason so that you can have your own .new, and still reap the benefits of standard object initialization of attributes, BUILD and TWEAK.

**Comment by lizmat** [comment] 2020-11-16 16:31
@dwarring what do you expect `TWEAK` and `BUILD` to be called with?  The Hash itself?  Because any named parameters will have been absorbed already by that time?

**Comment by dwarring** [comment] 2020-11-23 17:25
@lizmat.
Thanks for reminding me. Revisiting this I notice this does work with bless (and did at the time I raised this).

The following passes:
```
use Test;
my $built;
my $tweaked;
class H is Hash {
    submethod BUILD { $built = True }
    submethod TWEAK(*%v) {
        self = %v;
        $tweaked = True;
    }
}
my $h := H.bless: :x(42), :y(99);
plan 3;
ok $built, 'BUILD invocation';
ok $tweaked, 'TWEAK invocation';
is $h<x>, 42;
```
That's looks good enough for my purposes (PDF::COS::Dict in PDF module which is already uses bless.

**Closed** 2020-11-23 17:35 UTC
Labels: data types, objects
