### ISSUE TITLE
Regression: No such method 'op_props' for invocant of type 'Block'

### ISSUE THREAD

**Issue by cfa** [rakudo/rakudo#5221] opened 2023-02-27 20:17 UTC
## The Problem
The following example [from the documentation](https://docs.raku.org/language/js-nutshell.html#Custom_operators_and_operator_overloading) fails to compile in 2023.02 (and the current HEAD),

```raku
multi sub infix:<||=>($a, $b) is equiv(&infix:<+=>) { $a || $b }
 
my $foo = 0;
$foo ||= 1;
say $foo; # OUTPUT: 1 
```

with the following error

```
===SORRY!=== Error while compiling /Users/cfa/tmp/fail.raku
No such method 'op_props' for invocant of type 'Block'
at /Users/cfa/tmp/fail.raku:1
```

## Expected Behavior
Compilation without error.

Relatedly, the documentation expects `$foo` to be `1` but bisection indicates that when this compiled (≤2022.12), the result was consistently `0`.

A few relevant bisection logs,

- https://gist.github.com/76206dee2e26324b4b0b30ccad04701e
- https://gist.github.com/9516f200dc2befcf57d085c3743e9935
- https://gist.github.com/Whateverable/eb01bf61dcb88f5a7a0eab9425b60cc8

## Environment
* Operating system: macOS 13.2.1
* Compiler version (`perl6 -v` or `raku -v`): 2023.12

**Comment by thundergnat** [comment] 2023-02-28 00:08
Seems to me there are two separate issues in play with this.

First: ```+=``` is a synthetic operator. It is not explicitly present in the grammar so the precedence level needs to be derived separately. That seems to have broken with commit https://github.com/rakudo/rakudo/commit/a7ccfc6f808f2d45fff4993917dc93cbbf8694a6 "Move .prec from Routine to Code " That's definitely a regression.

Second: I don't see how that ever would have returned 1. Since the equal sign is part of the operator, there is no synthetic assignment operator, and there is no assignment within the operator routine, so the value 1 would never have been assigned to $foo. It will still be 0. And it is.

Leaving aside the problem with the precedence of synthetic operators, (just use <+> for now), I would expect that to be written something like:
```
multi sub infix:<||=>($a is raw, $b) is equiv(&infix:<+>) { $a = ($a || $b) }

my $foo = 0;
$foo ||= 1;
say $foo; # OUTPUT: 1
```

So regression _and_ bad example.

**Comment by cfa** [comment] 2023-02-28 00:52
Thanks @thundergnat.

Regarding the example, should the [documentation](https://github.com/Raku/doc/blob/main/doc/Language/js-nutshell.pod6#L358) be updated to use your amended version? If so, would you like to make the change?

**Comment by 2colours** [comment] 2023-02-28 08:31
That example is really bad anyway - `||=` does exist by default, what value does it add to re-implement it badly? That's surely not "making your own operator"... I'd change that (and if nobody objects, I will) to something like `|-|` for distance (absolute value of difference).

By the way: if https://github.com/rakudo/rakudo/commit/a7ccfc6f808f2d45fff4993917dc93cbbf8694a6 broke the precedence, how come the regression only happened more than 5 years later? That's surely not the whole story - although it's good to know that apparently the issue affects precedence derivation of synthetic operators, thank you.

**Comment by cfa** [comment] 2023-02-28 15:25
Thanks @2colours.

**Closed** 2024-10-20 10:10 UTC
