### ISSUE TITLE
Does Rakudo allow named parameters with the same name but within different nested blocks?

### ISSUE THREAD

**Issue by melezhik** [rakudo/rakudo#5423] opened 2023-10-16 12:00 UTC
## The Problem

```
raku -e 'sub foo (:%netsted ( :$foo ), :%netsted2 ( :$foo ) ) {} '
```

## Expected Behavior
No errors

## Actual Behavior

error:

```
users-MacBook-Pro:sparky user$ raku -e 'sub foo (:%netsted ( :$foo ), :%netsted2 ( :$foo ) ) {} '
===SORRY!=== Error while compiling -e
Redeclaration of symbol '$foo'.
at -e:1
------> (:%netsted ( :$foo ), :%netsted2 ( :$foo⏏ ) ) {} 
    expecting any of:
        shape declaration
```

## Steps to Reproduce

 run the code above

## Environment

* Operating system:

Mac os

* Compiler version (`rakudo -v` or `raku -v`):

```
$ raku -v
Welcome to Rakudo™ v2023.04.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.04.
```

**Comment by vrurg** [comment] 2023-10-16 13:23
In brief, how do you plan to distinguish one `$foo` from another lexically? Remember, it's the same lexical context.

If you don't plan to use them then better use `:foo($)` syntax for validation.

**Comment by melezhik** [comment] 2023-10-16 13:51
> In brief, how do you plan to distinguish one `$foo` from another lexically? Remember, it's the same lexical context.
> 
> If you don't plan to use them then better use `:foo($)` syntax for validation.

not sure if I follow, this is how I'd use them:

```
foo(:nested({ :foo<A>}));
foo(:nested2({ :foo<B>}));

# with foo function
I'd distinguish as 

%nested<foo>;
%nested2<foo>;

```

**Comment by vrurg** [comment] 2023-10-16 23:10
You clearly doesn't follow because the matter is not about the outside use (relative to the sub), but to the inside, i.e. to the lexical scope of the function. `$foo` of both sub-signatures are actually lexically local to the routine's body.

Then, again, I see that you just need to validate hash keys. Therefore your solution would be to use anonymous paramters:

```raku
sub foo(:%nest1 (:foo($)), :%nest(:foo($))) {...}
```

Otherwise I'm closing this issue as a no-error case.

**Closed by vrurg** 2023-10-16 23:10 UTC

**Comment by melezhik** [comment] 2023-10-17 05:40
@vrurg  with all my respect to you, I don’t really like the way you handle this … try not jump into conclusions about what people follow and what not , without give it a time 

I don’t need to validate hash keys, I need to validated nested named parameters ( if such exist )

Again if I don’t understand the whole concepts I am ok with with that, but please don’t just “shut the door” without giving a clear explanation

**Comment by melezhik** [comment] 2023-10-17 05:56
Maybe this is also a good ticket for documenting tins ? I have not found any documentation on the official doc site on named arguments  , https://docs.raku.org/language/functions does not cover that topic at least

**Comment by vrurg** [comment] 2023-10-17 13:30
> try not jump into conclusions about what people follow and what not , without give it a time

Sorry, but it was you guess about it. I just confirmed that you guessed it right. 😉 Absolutely no offense.

Speaking of me closing the ticket – I'll try to explain that it's not a mistake. But if you have questions (and you definitely have) – feel free to ask, ticket status doesn't prevent that. So, it's not shutting the door, it's just turning off the alarm sign above it.

On the technical side. There is no difference between saying 'hash validation' and 'nested parameter validation' in the context of your case. Because on the top level you have two named parameters `%nested*`. But both of them are hashes where nested named parameters are, eventually, just keys on `%nested` hashes. 

To see why there is no error in this behavior, let's unwrap your subsignatures into a pseudo-code. Normally, `:%foo ( :$key )` can be stated as:

```raku
sub foo(:%foo) {
    my $key = %foo<key>;
    ...
    bar($key);
}
```

Apparently, I omit all checks here. OK, then what happens when you have two nameds with identical subsignatures?

```raku
sub foo(:%n1, :%n2) {
    my $key = %n1<key>;
    my $key = %n2<key>; # This is where the error comes from
}
```

Hopefully, it's better this way.

**Comment by melezhik** [comment] 2023-10-18 05:33
Yes, thanks for clarifying, it’s more clearer now. 

So, in case I use nameds, lexical variables generated and in case we have have 2 identical “ids” ( well two identical variables ) Rakudo errors with redefinition attempt, right ? 

I wonder then (a bit off topic) why named  variables exists  in Raku, if they have those limitations, and we can always use (nested) hashes instead ? What is the benefit of having nested named arguments ?

**Comment by vrurg** [comment] 2023-10-18 21:48
> So, in case I use nameds, lexical variables generated and in case we have have 2 identical “ids” ( well two identical variables ) Rakudo errors with redefinition attempt, right ?

Absolutely.

> I wonder then (a bit off topic) why named variables exists in Raku, if they have those limitations, and we can always use (nested) hashes instead ? What is the benefit of having nested named arguments ?

First of all, it is not so often one has more than one hashy named parameter, as in your example. 

See:

- accessing a hash is rather slow, slower than accessing a lexical
- validating hash content manually could be a tedious boilerplate
- and so on

BTW, we must not talk about "nested named arguments". I gave it a little bit of easing, but it's wrong terminology here. What we deal with is "parameter of a sub-signature". Otherwise it is "destructuring". 

It may have many uses. For example, just now I'm using a construct like this:

```raku
```
