### ISSUE TITLE
Rakudo no longer builds properly on OpenBSD

### ISSUE THREAD

**Issue by Kaiepi** [rakudo/rakudo#2904] opened 2019-05-17 10:51 UTC
## The Problem
The new build scripts try to build a relocatable executable by default on OpenBSD when that doesn't work.

## Expected Behavior
They should build a non-relocatable executable.

## Actual Behavior
They don't. Passing `--no-relocatable` also doesn't work without manually editing the makefile since it gets passed to it as `--no-relocatable="1"` when it doesn't take a value, making one of the scripts called by `make` throw. Also, `Configure.pl` incorrectly states that you should use `gmake` instead of `make`.

## Steps to Reproduce

Run `./Configure.pl && make install`, then try to run `perl6`.

## Environment
* Operating system: 
OpenBSD bastille.kennel.qt 6.5 GENERIC.MP#8 amd64
* Compiler version (`perl6 -v`): 
This is Rakudo version 2019.03.1-405-g7a7a23df6a built on MoarVM version 2019.03-111-g24b3ef1ad
implementing Perl 6.d.

**Comment by vrurg** [comment] 2019-05-17 13:47
With regard to gmake – do you have it in your path? If so, then this is the recommended make to use. But if you don't then this is a problem.

**Comment by vrurg** [comment] 2019-05-17 14:07
I'm installing openBSD in a VM. Meanwhile may I ask for the output of the failing script?

**Comment by Kaiepi** [comment] 2019-05-17 14:11
> With regard to gmake – do you have it in your path? If so, then this is the recommended make to use. But if you don't then this is a problem.

I do. I don't think it should be the recommended make on *BSD though since it's not installed by default.

> I'm installing openBSD in a VM. Meanwhile may I ask for the output of the failing script?

```
bastille% ./Configure.pl --backends=moar --prefix=$HOME/.perl6 --no-relocatable
Using /home/morfent/.perl6/bin/nqp-m (version 2019.03-83-g0adfd6ada / MoarVM 2019.03-111-g24b3ef1ad).
Cleaning up ...

You can now use '/usr/local/bin/gmake' to build Rakudo.
After that, '/usr/local/bin/gmake test' will run some tests and
'/usr/local/bin/gmake install' will install Rakudo.
bastille% make                                                                 
'perl' -I'/home/morfent/Documents/perl6/rakudo/tools/lib' -I'/home/morfent/Documents/perl6/rakudo/3rdparty/nqp-configure/lib' '/home/morfent/Documents/perl6/rakudo/tools/build/check-nqp-version.pl' '/home/morfent/.perl6/bin/nqp-m'
'perl' -I'/home/morfent/Documents/perl6/rakudo/tools/lib' -I'/home/morfent/Documents/perl6/rakudo/3rdparty/nqp-configure/lib' '/home/morfent/Documents/perl6/rakudo/Configure.pl' --no-relocatable="1" --prefix="/home/morfent/.perl6" --backends=moar --expand main-version --out 'gen/moar/main-version.nqp'
Option no-relocatable does not take an argument
Configure.pl - Rakudo Configure

General Options:
    --help             Show this text
    --prefix=<path>    Install files in dir; also look for executables there
    --libdir=<path>    Install architecture-specific files in dir; Perl6 modules
                       included
    --no-relocatable
                       Create a perl6 with a fixed NQP and Perl6 home dir
                       instead of dynamically identifying it (On AIX MoarVM is
                       always built non-relocatable, since AIX misses
                       a necessary mechanism.)
    --sdkroot=<path>   When given, use for searching build tools here, e.g.
                       nqp, java, node etc.
    --sysroot=<path>   When given, use for searching runtime components here
    --backends=jvm,moar,js
                       Which backend(s) to use (or ALL for all of them)
    --gen-nqp[=branch]
                       Download, build, and install a copy of NQP before writing
                       the Makefile
    --gen-moar[=branch]
                       Download, build, and install a copy of MoarVM to use
                       before writing the Makefile
    --with-nqp=<path>
                       Provide path to already installed nqp
    --make-install     Install Rakudo after configuration is done
    --moar-option='--option=value'
                       Options to pass to MoarVM's Configure.pl
                       For example: --moar-option='--compiler=clang'
    --github-user=<user>
                       Fetch all repositories (rakudo, nqp, roast, MoarVM) from
                       this github user. Note that the user must have all
                       required repos forked from the originals.
    --rakudo-repo=<url>
    --nqp-repo=<url>
    --moar-repo=<url>
    --roast-repo=<url>
                       User-defined URL to fetch corresponding components
                       from. The URL will also be used to setup git push.
    --git-protocol={ssh,https,git}
                       Protocol used for cloning git repos
    --git-depth=<number>
                       Use the --git-depth option for git clone with parameter number
    --git-reference=<path>
                       Use --git-reference option to identify local path where git repositories are stored
                       For example: --git-reference=/home/user/repo/for_perl6
                       Folders 'nqp' and 'MoarVM' with corresponding git repos should be in for_perl6 folder
    --makefile-timing  Enable timing of individual makefile commands
    --no-clean         Skip cleanup before installation
    --ignore-errors    Ignore errors (such as the version of NQP)
    --expand=<template>
                       Expand template file. With this option Makefile is not
                       generated. The result is send to stdout unless --out
                       specified.
    --out=<file>       Filename to send output of --expand into.
    --set-var="config_variable=value"
                       Sets a config_variable to "value". Can be used multiple
                       times.

Please note that the --gen-moar and --gen-nqp options are there for convenience
only and will actually immediately - at Configure time - compile and install
moar and nqp respectively. They will live under the path given to --prefix,
unless other targeting options are used. To configure how MoarVM should be
compiled, use the --moar-option flag and view MoarVM's Configure.pl for more
information on its configuration options.

Configure.pl also reads options from 'config.default' in the current directory.
*** Error 1 in /home/morfent/Documents/perl6/rakudo (Makefile:534 'gen/moar/main-version.nqp')
```

**Comment by vrurg** [comment] 2019-05-17 14:15
`gmake` won't be recommended if not found on PATH. The logic is to detect a `make` and then inform the user about the found one. Unfortunately, BSD makes doesn't identify themselves in their output making it impossible to make sure what exact `make` family we have at our hands. For this reason I choose the one I would be sure about.

**Comment by vrurg** [comment] 2019-05-17 14:17
Thanks for the output! I know what to do about it. You say openBSD won't build relocatable binary no matter what? Maybe there is a workaround?

**Comment by Kaiepi** [comment] 2019-05-17 14:19
> Thanks for the output! I know what to do about it. You say openBSD won't build relocatable binary no matter what? Maybe there is a workaround?

The workaround is to call `Configure.pl` with `--no-relocatable`, then manually edit `CONFIGURE` in the makefile to contain `--no-relocatable` instead of `--no-relocatable="1"`.

**Comment by patzim** [comment] 2019-05-17 14:20
@vrurg: During my relocatable work me and Kaiepi already fought the relocatable on OpenBSD battle and lost. Hard. The best we can do at the moment is keep OpenBSD non-relocatable.

**Comment by Kaiepi** [comment] 2019-05-17 14:20
I can't read. There is no workaround; `$ORIGIN` doesn't work on OpenBSD, making it impossible for relocatable executables to work.

**Comment by ugexe** [comment] 2019-05-17 14:29
> Unfortunately, BSD makes doesn't identify themselves in their output making it impossible to make sure what exact `make` family we have at our hands. For this reason I choose the one I would be sure about.

What about creating a temp file `GNUmakefile` and seeing if `make` runs it? Kind of sloppy, but seems like it would work.

**Comment by Kaiepi** [comment] 2019-05-17 14:34
> What about creating a temp file GNUmakefile and seeing if make runs it? Kind of sloppy, but seems like it would work.

A better approach would be running `make -v`. `-v` is unsupported on BSD make, while it is on GNU make.

**Comment by vrurg** [comment] 2019-05-17 14:39
@ugexe BSDmakefile for that matter would be better.

@Kaiepi I'm coming from the times when it was possible to have like 4-5 different make flavors around. Wouldn't take proof by contradiction for granted.

In either case, I'll take care of `no-relocatable` option and will force-enable it for OpenBSD.

**Comment by vrurg** [comment] 2019-05-17 16:59
@Kaiepi you could try  the above PRs while I'm awaiting for travis/appveyor tests passing.

**Comment by vrurg** [comment] 2019-05-17 17:46
On my test OpenBSD everything works until the installation phase:

```
'/home/vrurg/rakudo/perl6-m' '/home/vrurg/rakudo/tools/build/install-core-dist.p6' '/home/vrurg/rakudo/install/share/perl6'
===SORRY!===
no such file or directory
```

Not sure if I'll have time today to look into it.

**Comment by vrurg** [comment] 2019-05-18 03:46
@Kaiepi My lates changes from #2906 seemingly allows to install on OpenBSD. Have no time today for more testing.

**Comment by Benabik** [comment] 2019-05-20 13:23
I'm hitting this same problem on macOS, which does use GNU make.  Can confirm #2906 fixes the problem for me.

**Comment by vrurg** [comment] 2019-05-20 14:25
I'm somewhat hesitate about merging #2906 yet. But will likely merge it later today as the problems I encountered are seemingly not related to the changes.

**Comment by vrurg** [comment] 2019-05-20 22:34
@Kaiepi could you please confirm if the build is working for you now?

**Comment by Kaiepi** [comment] 2019-05-21 12:43
I can't get `Configure.pl` to run:
```
bastille% ./Configure.pl --gen-nqp --backends=moar --prefix=$HOME/.perl6
HEAD is now at 637207789 Bump Moar to get the latest goodies
Can't locate object method "make_option" via package "NQP::Config::Rakudo" at /home/morfent/Documents/perl6/rakudo/tools/lib/NQP/Config/Rakudo.pm line 429.
 at /home/morfent/Documents/perl6/rakudo/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
	NQP::Config::__ANON__("Can't locate object method \"make_option\" via package \"NQP::Co"...) called at /home/morfent/Documents/perl6/rakudo/tools/lib/NQP/Config/Rakudo.pm line 429
	NQP::Config::Rakudo::gen_nqp(NQP::Config::Rakudo=HASH(0x1ef02a8316d0)) called at ./Configure.pl line 98
```

**Comment by vrurg** [comment] 2019-05-21 13:32
You need to `git submodule update`. Or, considering recent migration of `nqp-configure` submodule under `perl6` ownership, you can either:

```
git submodule sync
git submodule update --init --recursive --remote
```

or re-clone rakudo from scratch.

**Comment by Kaiepi** [comment] 2019-05-21 18:13
The build works.

**Comment by Kaiepi** [comment] 2019-05-21 18:21
However one of the commits caused a regression:
```
bastille% perl6 --ll-exception -e 'say $*EXECUTABLE'
"--ll-exception".IO
```
`$*EXECUTABLE` and `$*EXECUTABLE-NAME` still need special cases for OpenBSD.

**Comment by vrurg** [comment] 2019-05-21 19:06
Ah, different handling is perhaps needed for different scenarios. I'll have a look into what can be done to this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by javan-z** [comment] 2019-05-21 21:11
I'm on OpenBSD 6.5, rakudo builds with clang from ports on my box, but when I run the executable(perl6) I get : Unhandled exception: Malformed UTF-8 at line 1 col 85

**Comment by vrurg** [comment] 2019-05-22 17:53
@Kaiepi I finally got a bit of time to look into it. Seems like it's to be fixed in moar because if it can't determine correct executable then `nqp::execname()` must return an empty one.

@javan-z I will try to build with llvm from ports, but it doesn't look like it belongs here. A separate ticket would be needed.

**Comment by vrurg** [comment] 2019-05-22 18:04
@javan-z My build has completed with clang from ports and everything seems to be ok.

**Comment by vrurg** [comment] 2019-05-23 00:29
@Kaiepi #2915 should be the fix.

**Comment by javan-z** [comment] 2019-05-23 18:56
Works beautifully, Thanks

**Comment by vrurg** [comment] 2019-06-01 01:03
Closed via #2915

**Comment by Kaiepi** [comment] 2019-06-05 18:46
The build works fine, but instead of `$*EXECUTABLE` being the absolute path to the perl6 binary, I get this:
```
bastille% perl6 -e 'say $*EXECUTABLE'
"perl6".IO
bastille% perl6 --ll-exception -e 'say $*EXECUTABLE'
"perl6".IO
```
This makes it impossible to run any modules.

**Comment by vrurg** [comment] 2019-06-05 21:42
Did you expect `$*EXECUTABLE` to be a string? Because this is what I get on macOS with 2019.03:

```
"/Users/vrurg/.rakudobrew/bin/../versions/moar-2019.03.1/install/bin/perl6".IO
```

With regard to the full path – I didn't find a way to get it. It's OpenBSD, after all. 😉

**Comment by ugexe** [comment] 2019-06-05 21:49
The problem is `$*EXECUTABLE.absolute` should work. `"perl6".IO.absolute` will only every be right when a perl6 binary resides in cwd.

https://github.com/rakudo/rakudo/blob/32d480aba043245d380ae1d2f089c9bb76412d01/src/core/CompUnit/PrecompilationRepository.pm6#L252

If the above did not call `.absolute` then when manually running `/home/alt/perl6` (not in PATH) it might precompile things with the perl6 in my path at `/home/ugexe/perl6`.

**Comment by vrurg** [comment] 2019-06-06 03:09
`.absolute` doesn't provide the right path. The problem is that OpenBSD doesn't let a process to know the full path of its executable. And as far as I know there is no way to resolve this. I found [a StackOverflow topic](https://stackoverflow.com/questions/31494901/how-to-get-the-executable-path-on-openbsd) where they cite Theo de Raadt saying: _Quite expensive, for such a small need._

For now I don't see a good solution for this. Perhaps the least painful one would be macro expansion of runner's C source and manual insertion of the full path as defined in the `Makefile` – similar to how scripted runners are being generated.

**Comment by patzim** [comment] 2019-06-06 08:24
I'll have a look at this. I think I know what's to do.

**Comment by patzim** [comment] 2019-06-06 08:28
I think we might be able to remove all the OpenBSD special casing when we set the executable path statically in the non-relocatable case. That's basically what @vrurg proposed.
@vrurg Are you ok with me taking this ticket? Would you prefer another `-Dvar=value` C compiler variable to pass the executable name into the C runner or turning it into a template?

**Comment by vrurg** [comment] 2019-06-06 13:26
@patzim you're welcome! It's really closer to your specialization. `-D` is really much better solution than templating in this case.

**Closed** 2019-06-12 23:33 UTC
