### ISSUE TITLE
`MAIN(Str :$a, :@b)` fails on `--a=foo, --b=bar` because of `Str` constraint

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#2797] opened 2019-03-25 22:35 UTC
Code:
```
sub MAIN(:@foo) { say @foo }
```

Run it with **no** arguments (this is OK):
```bash
foo.p6
```
```
[]
```
Run it with **two** arguments (this is OK):
```bash
foo.p6 --foo=42 --foo=50
```
```
[42 50]
```

Run it with **one** argument (this is the problem):
```bash
foo.p6 --foo=42
```
```
Usage:
  -e '...' [--foo=<Positional>]
```

As far as I can tell, this is not a regression: https://gist.github.com/cb75c1c12429ba312cac4b7f6b6fe291

**Comment by lizmat** [comment] 2019-03-26 18:10
Fixed with 87d219ee68 .  This makes one todo test pass: S06-other/main-usage.t 36  .  Unfudged that with  https://github.com/perl6/roast/commit/472bc003f0

**Comment by nxadm** [comment] 2020-05-03 11:31
I just hit this bug with the latest released (2020.02.1):
```shell
$ raku -v
This is Rakudo version 2020.02.1 built on MoarVM version 2020.02.1
```
My sample code is pretty identical to @AlexDaniel's so no point adding the gist here.

**Comment by lizmat** [comment] 2020-05-03 11:40
I'm not sure I see the problem:

    $ raku -e 'sub MAIN(:@foo) { say @foo }' --foo=42
    [42]

In other words, I can *not* reproduce the issue (on MacOS at least)

**Comment by nxadm** [comment] 2020-05-03 11:59
Passes:
```
$ echo 'sub MAIN(:$name!, :@foo) { say @foo }' > test.raku; chmod +x test.raku ; raku test.raku -name=n --foo=1 --foo=2; raku test.raku --name=n --foo=1
[1 2]
[1]
```

Fails:
```
$ echo 'sub MAIN(Str :$name!, :@foo) { say @foo }' > test.raku; chmod +x test.raku ; raku test.raku -name=n --foo=1 --foo=2; raku test.raku --name=n --foo=1
[1 2]
Usage:
  test.raku --name=<Str> [--foo=<Any> ...]
```

It's the type of :$name that makes :@foo break.

**Comment by lizmat** [comment] 2020-05-03 12:01
Golfed to:

    $ raku -e 'BEGIN @*ARGS = <--name=n --foo-1>; sub MAIN(Str :$name!, :@foo) { say @foo }'
    Usage:
      -e '...' --name=<Str> [--foo=<Any> ...]

Looks like the `Str` constraint is messing up things

**Comment by lizmat** [comment] 2024-10-27 11:36
Golfed the issue to:
```
% raku -e 'sub a(:$name!) { dd $name }; a :name<n b>'                                  
$("n", "b")
% raku -e 'sub a(Str :$name!) { dd $name }; a :name<n b>'
Type check failed in binding to parameter '$name'; expected Str but got List (("n", "b"))
```
The trick that the `MAIN` handling uses to handle the one command line argument case of `:@foo`, is to convert all of the named arguments into one-element lists and then try dispatch again.

This works ok if there are no constraints on the named argument: a `List` is an `Any` as much as a `Str` is.  However, if there **is** a `Str` constraint, the dispatch of the one-element list will fail.

And that is what's breaking:
```
% raku -e 'BEGIN @*ARGS = <--name=n --foo=1>; sub MAIN(Str :$name, :@foo) { say @foo }'
Usage:
  -e '...' --name=<Str> [--foo=<Any> ...]
```
Solution: don't specify the `Str` constraint.

**Comment by lizmat** [comment] 2024-10-27 11:47
I basically see two possible solutions:

1. Introduce a slurpy named argument syntax: `:*@foo`

Disadvantages: apart from the grammar work, this would also need quite a bit of work in the binder.  And the user would need to know to specify `:*@foo` instead of `:@foo`.

Advantages: would be generally useful, and would allow the 'adapt the `Capture` hack in `MAIN` handling to be removed.

2. Change the hack in MAIN so that it would create a `Junction` of Captures with each possible combination of arrayifying the named arguments.

Disadvantages: hack upon hack so less maintainable, possible performance issues on starting of each script.

Advantage: would make the example work as expected

**Comment by lizmat** [comment] 2024-10-27 12:00
Closing in light of https://github.com/Raku/problem-solving/issues/452

**Closed by lizmat** 2024-10-27 12:00 UTC
Labels: CLI
