### ISSUE TITLE
High CPU utilization in idle state

### ISSUE THREAD

**Issue by DavidTurny** [rakudo/rakudo#5136] opened 2022-12-14 19:21 UTC
## The Problem
I noticed that Rakudo REPL process use huge amount of CPU in idle state as you can see on this image:

![raku_cpu_usage](https://user-images.githubusercontent.com/114754950/207692616-03994b62-189b-4780-a68b-0b8715e86317.png)

## Expected Behavior
In idle state the CPU utilization should be very low.

## Actual Behavior
On a AMD Athlon X4 880K Quad Core CPU it utilizes 28%.

## Steps to Reproduce

Just start it from the start menu.

## Environment
* Operating system:
Win10
* Compiler version (`perl6 -v` or `raku -v`): 
Welcome to RakudoΓäó v2022.12.
Implementing the Raku┬« Programming Language v6.d.
Built on MoarVM version 2022.12.
(for some reason it has problem with character encoding)

**Comment by lizmat** [comment] 2022-12-14 19:30
FWIW, this appears to be a Windows related issue.  Cannot reproduce this on Linux or MacOS.

**Comment by lizmat** [comment] 2024-10-19 18:55
Is this still an issue?

**Comment by lizmat** [comment] 2024-10-20 12:02
Closing in light of #5276

**Closed by lizmat** 2024-10-20 12:02 UTC
Labels: Windows
